### ISSUE TITLE
Upgrading to latest from 8.9.4

### ISSUE THREAD

**Issue by korejan** [mikepenz/AboutLibraries#1002]
Hi, I'm updating project files, the code using AboutLibraries was written by another developer and I have no familiarity with it. The only issue I had is `LibsBuilder().withFields` no longer exists, I removed the call and I didn't notice any issues but I wanted to double check and ask if there is meant to be new way to do this in 11.2.2  that I should be doing rather than only deleting the old code?

again I haven't noticed anything different with the results but just wanted to make sure.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Good day @korejan 

This is correct the `withFields` was removed and is no longer required. 
The API and plugin were significantly refactored since v8.9, and work very differently. 

E.g. now a json file is build and included as resource which the lib will parse and display.

**Comment by korejan** [comment]
Thanks!
