### ISSUE TITLE
OFL not found

### ISSUE THREAD

**Issue by ferhatozcelik** [mikepenz/AboutLibraries#1005]
SIL OPEN FONT LICENSE
not found

OFL-1.1
https://opensource.org/license/OFL-1.1

aboutLibraries {
    allowedLicenses = ["OFL-1.0", "https://opensource.org/licenses/OFL-1.1"]
}

[## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [x] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)
](https://opensource.org/license/OFL-1.1)

**Comment by mikepenz** [comment]
Can you please provide more information. What is not found?

**Comment by ferhatozcelik** [comment]
> OFL-1.1 https://opensource.org/license/OFL-1.1
> 
> aboutLibraries { allowedLicenses = ["OFL-1.0", "https://opensource.org/licenses/OFL-1.1"] }

OFL-1.1
https://opensource.org/license/OFL-1.1

aboutLibraries {
allowedLicenses = ["OFL-1.0", "https://opensource.org/licenses/OFL-1.1"]
}
When I add it this way, it is not added to the licenses.

**Comment by mikepenz** [comment]
This configuration will allow the given license to be used by libraries, however, it won't add it. 
This is only effective when the strict mode is enabled:

```
    // Define the strict mode, will fail if the project uses licenses not allowed
    // - This will only automatically fail for Android projects which have `registerAndroidTasks` enabled
    // For non Android projects, execute `exportLibraryDefinitions`
    strictMode = com.mikepenz.aboutlibraries.plugin.StrictMode.FAIL
    // Allowed set of licenses, this project will be able to use without build failure
    allowedLicenses = ["Apache-2.0", "asdkl"]
```
