### ISSUE TITLE
The plugin returns "${extension.name} API" as library name for "Javax annotation API" Library

### ISSUE THREAD

**Issue by sergio-sastre** [mikepenz/AboutLibraries#1006]
## About this issue
While adding the [Javax annotation API](https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api) library
This plugin returns as library name the following placeholder instead of the library name:
"${extension.name} API"

## Details
- [ 11.2.2] Used library version

**Comment by mikepenz** [comment]
@sergio-sastre unfortunately that is wrong information in the libraries `pom` file.

See the same report here: https://github.com/mikepenz/AboutLibraries/issues/998

You can overwrite the respective name for such situations

**Comment by mikepenz** [comment]
See `Gradle Plugin Configuration` in the README for more details
