### ISSUE TITLE
[Feature Request] Configure library name substitutions 

### ISSUE THREAD

**Issue by dgmltn** [mikepenz/AboutLibraries#1012]
Consider the attached library. I'd like it to display a better name. It would be nice to override the name with a custom name in my gradle config.

```json
    {
      "artifactVersion": "1.3.2",
      "description": "Common Annotations for the JavaTM Platform API",
      "developers": [
        {
          "name": "Linda De Michiel"
        }
      ],
      "funding": [],
      "licenses": [
        "9be0c4d7964ad9a68deb2e9706266b8c"
      ],
      "name": "${extension.name} API",
      "organization": {
        "name": "GlassFish Community",
        "url": "https://javaee.github.io/glassfish"
      },
      "scm": {
        "connection": "scm:git:https://github.com/javaee/javax.annotation.git",
        "developerConnection": "scm:git:git@github.com:javaee/javax.annotation.git",
        "url": "https://github.com/javaee/javax.annotation"
      },
      "uniqueId": "javax.annotation:javax.annotation-api",
      "website": "http://jcp.org/en/jsr/detail?id=250"
    },
```

What if I could override the library name like:
```
aboutLibraries {
    nameOverrides = mapOf(
        "javax.annotation:javax.annotation-api" to "javax.annotation API"
    )
}
```

**Comment by mikepenz** [comment]
Good day. 

While not possible directly in the gradle, it is possible to do this with config files you can provide. You can see this being done in the sample app:
- https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L94
<img width="623" alt="Screenshot 2024-08-16 at 19 11 46" src="https://github.com/user-attachments/assets/1fc24cac-24c5-43a1-8f55-9b82450597ba">

That way you can provide new ones not detected, but also overwrite existing ones via their unique id:
- https://github.com/mikepenz/AboutLibraries/blob/develop/config/libraries/lib_merge_material_drawer.json#L2

**Comment by dgmltn** [comment]
That works for me, thanks!
