### ISSUE TITLE
Unable to make AboutLibraries work

### ISSUE THREAD

**Issue by alghe-global** [mikepenz/AboutLibraries#1013]
I'm running Android Studio latest version with Jetpack Compose latest version and Kaitlin 2.0. I'm using the root Gradle (kts) implementation of the library as well as app level core and M3 Compose library. 

I'm using LibraryContainer however my app crashes complaining I haven't supplied the data to it. I'm wondering from where to get this data? The build doesn't generate any JSON.

**Comment by alghe-global** [comment]
Do I've to specify the plugin in app's build.gradle.kts?

**Comment by alghe-global** [comment]
Have placed `aboutLibraries` in the app build.gradle.kts file, though upon build I get Unresolved reference error:

```
e: .../app/build.gradle.kts:41:1: Unresolved reference: aboutLibraries
```

in `build.gradle.kts` (app) I've:

```
/** AboutLibraries dependency */
    implementation(libs.aboutlibraries.core)
    implementation(libs.aboutlibraries.compose.m3)
```

and in `build.gradle.kts` (root), I've:

```
/** Dependency for AboutLibraries plugin */
    id("com.mikepenz.aboutlibraries.plugin") version "11.2.2" apply false
```

is KTS not supported?

**Comment by mikepenz** [comment]
Good day. 

You want to apply the plugin to the module you are gonna use it in. And yes the plugin is supported for normal groovy based gradle files as well as kts ones. 

1)
- https://github.com/mikepenz/HypnoticCanvas/blob/dev/sample/build.gradle.kts#L10
2)
- https://github.com/mikepenz/HypnoticCanvas/blob/dev/sample/build.gradle.kts



You can define it in the root:
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/build.gradle.kts#L9
But also have to define it in the actual module:
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/app-wasm/build.gradle.kts#L7
And the optional config block:
- https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/app-wasm/build.gradle.kts#L51




Please remember, the plugin only links with the android build tasks (which can be disabled) for any other platforms you want to execute the task when you need the file generated:
- https://github.com/mikepenz/AboutLibraries?tab=readme-ov-file#enterprise

**Comment by alghe-global** [comment]
Adding in the `plugins` section of app's `build.gradle.kts` did the job.

Thanks so much and great work!
