### ISSUE TITLE
Provide an option to not write the `"generated"` metadata property in Json output

### ISSUE THREAD

**Issue by opatry** [mikepenz/AboutLibraries#1022]
## About this issue

Would be nice to have an option to prevent generating `"generated": "2024-10-02T19:12:47.617Z"` (or all `metadata` section maybe?).

This could ease automation of diffing the output between SCM state & freshly generated file in the context of a commit hook or a CI job for instance.

## Details
- [x] Used library version `11.2.3`
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
It is possible to exclude various fields from the output file using the `excludeFields` config:

https://github.com/mikepenz/AboutLibraries/blob/e8a4fe3aa5b963205c986d1e0f768ca96ede3c86/app/build.gradle#L105-L106

The README has a few examples: 

```
    // Allows to exclude some fields from the generated meta data field.
    // If the class name is specified, the field is only excluded for that class; without a class name, the exclusion is global.
    excludeFields = ["License.name", "developers", "funding"]
```

Without testing it myself right now. you should be able to remove the `generated` by excluding `MetaData.generated`

**Comment by opatry** [comment]
Oh, great, I thought it was only for `License` fields.

Both `"MetaData.generated"` (with uppercase `D` 😅) and `"metadata"` for the whole metadata section (depending on your need) work.

Thanks.
