### ISSUE TITLE
Manually add licenses

### ISSUE THREAD

**Issue by adrcotfas** [mikepenz/AboutLibraries#1024]
## About this issue

Hey there,
In older versions of the library I think it was possible to manually add licenses if I remember correctly. Is this still possible?
The use case is copy pasted source code not imported as a gradle dependency.

**Comment by mikepenz** [comment]
Yes you can still add libraries via the config folder like shown here in your project:
- https://github.com/mikepenz/AboutLibraries/tree/develop/config/libraries
- https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L94
