### ISSUE TITLE
Colon in generated json filename causes problem in windows

### ISSUE THREAD

**Issue by sunragav** [mikepenz/AboutLibraries#1026]
## About this issue

- The files generated have : (colon) in their filenames, example: org.koin:koin-android.json
This works fine in mac as it is Unix based and the colon is legal character in filenames. But it is creating problems when the code is checked out in windows. Is there a way in the config to generate filenames that are windows friendly? Is there any other way to solve this problem?
It is an android project so that plugin is automatically executed.
I just add the plugin dependency in the root project and configure in my app module's build.gradle.kts file.

libs.versions.toml
```
[versions]
aboutLibraryVerison = "11.2.2"

[libraries]
mikepenz-aboutlibraries-compose-m3 = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutLibraryVerison" }

[plugins]
aboutLibrary = {id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraryVerison"}
```
Root build.gradle.kts:

```
alias(libs.plugins.aboutLibrary) apply false
```

app module build.gradle.kts
```
plugins {
    alias(libs.plugins.datadog.agp)
     alias(libs.plugins.android.application)
  alias(libs.plugins.aboutLibrary
}

aboutLibraries {
    registerAndroidTasks = false
    configPath = "config"
}
```
When generated via mac and pushed to github, it looks like this in github (With mac having no problem):

![image](https://github.com/user-attachments/assets/1414a78c-7b80-4531-9998-166dcc577c73)

But in windows the same files create problems. Also some new empty files are generated as you can see in the unresolved section:
![git-changes-in-widnows](https://github.com/user-attachments/assets/d4d46c6a-7570-4679-91f2-8429eb114e71)

## Details
- [x] Used library version - "11.2.2"
- [ ] Used support library version - NA
- [x] Used gradle build tools version - "8.3.2"
- [x] Used tooling / Android Studio version - Android Studio Ladybug | 2024.2.1 Patch 1
- [ ] Other used libraries, potential conflicting libraries - NA

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Can you for completeness of the ticket please also add the details on the command you used to generate those files?

**Comment by sunragav** [comment]
@mikepenz Sorry I misunderstood that the json files in config folder are auto-generated by the tool, but they file naming convention used by one of the team members. I will close this issue.
