### ISSUE TITLE
Help required configuring the plugin in a convetion plugin

### ISSUE THREAD

**Issue by sunragav** [mikepenz/AboutLibraries#1027]
## About this issue
I am trying to create convention plugin for about libraries in my project.
Trying to do something like this:
https://blog.kotlin-academy.com/detekt-gradle-configuration-guide-d6d2301b823a
Is there a gradle plugin lilb dependency I could add to my convention plugin?
So that I could configure the plugin with the aboutLibraries block.

I mean I want to do something like this:

```kotlin
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.getByType
import com.mikepenz.aboutlibraries.plugin.AboutLibrariesExtension
import java.util.regex.Pattern

class AboutLibrariesConventionPlugin : Plugin<Project> {

    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply("com.mikepenz.aboutlibraries.plugin")

            val extension = extensions.getByType<AboutLibrariesExtension>()
            extension.apply{
                registerAndroidTasks = false
                exclusionPatterns = listOf("com\\.salesforce\\..*").map { Pattern.compile(it) }
                configPath = "config"
            }
            dependencies {
                add("implementation", libs.findLibrary("mikepenz-fastadapter").get())
                add("implementation", libs.findLibrary("mikepenz-fastadapter-ext-binding").get())
                add("implementation", libs.findLibrary("mikepenz-fastadapter-ext-expandable").get())
                add("implementation", libs.findLibrary("mikepenz-aboutlibraries-compose-m3").get())
            }
        }
    }
}
```
I am not sure what lib dependency should I add for this in the build.gradle.kts of my convention plugin.
```kotlin
dependencies {
    compileOnly(libs.android.gradlePlugin)
    compileOnly(libs.detekt.gradlePlugin)
    compileOnly(libs.dd.sdk.android.gradle.plugin)
    compileOnly(libs.compose.compiler.gradle.plugin)
    compileOnly(libs.firebase.crashlytics.gradlePlugin)
    compileOnly(libs.firebase.performance.gradlePlugin)
    compileOnly(libs.kotlin.gradlePlugin)
    compileOnly(libs.ksp.gradlePlugin)
    compileOnly(libs.room.gradlePlugin)
    //implementation(libs.aboutLibrary.gradlePlugin)
    implementation(libs.truth)
}
```

## Details
- [x] Used library version - "11.2.2"
- [ ] Used support library version - NA
- [x] Used gradle build tools version - "8.3.2"
- [x] Used tooling / Android Studio version - Android Studio Ladybug | 2024.2.1 Patch 1
- [ ] Other used libraries, potential conflicting libraries - NA

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I assume you are looking for:

```
  dependencies {
    classpath("com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:11.2.3")
  }
```

You generally can find those on the gradle plugin portal: 

https://plugins.gradle.org/plugin/com.mikepenz.aboutlibraries.plugin

**Comment by sunragav** [comment]
Thanks. Figured it out myself. It was silly, I was missing gradlePluginPortal in my settings.gradle of my convention plugin. 
```gradle

@file:Suppress("UnstableApiUsage")

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal() <--------------
    }
    versionCatalogs {
        create("libs") {
            from(files("../gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = "build-logic"
include(":convention")

```

**Comment by sunragav** [comment]
Thanks
