### ISSUE TITLE
Documentation link points to an online version of the Desktop example

### ISSUE THREAD

**Issue by Varbin** [mikepenz/AboutLibraries#1029]
## About this issue

The [SDK docs link](https://mikepenz.github.io/AboutLibraries/) used to point to a documentation page - it now displays the Desktop example.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] ~~Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)~~
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thanks for the report. removed those links as they were not up2date anymore for quite some time. 
All docs are now in the README
