### ISSUE TITLE
Discrepancies between list of dependencies found by AboutLibrary and the dependencies task

### ISSUE THREAD

**Issue by redwarp** [mikepenz/AboutLibraries#1039]
### Briefly describe the issue
I've noticed that some libraries, that are reported by gradle when running `./gradlew app:dependencies --configuration debugRuntimeClasspath` are missing from the report 

### How can the issue be reproduced / sample code
I'm joining a minimal sample project to reproduce:
[MissingLib.zip](https://github.com/user-attachments/files/17870927/MissingLib.zip)
It's an app that does nothing but display the list of dependencies using AboutLibraries.

1. Within the sample project, run `./gradlew app:dependencies --configuration debugRuntimeClasspath`
2. Notice that there are 3 `androidx.annotation:annotation` libraries:
   - androidx.annotation:annotation
   - androidx.annotation:annotation-jvm
   - androidx.annotation:annotation-experimental
3. Run `./gradlew app:findLibraries`
4. Notice that there are only 2 of the `androidx.annotation:annotation` libraries:
   - androidx.annotation:annotation-jvm
   - androidx.annotation:annotation-experimental

## Potential fix
I experimented with the plugin, and what should fix it is to modify this line: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt#L129

From:
```
  else -> {
    if (LOGGER.isDebugEnabled) LOGGER.debug("retrieve allModuleArtifacts from artifact")
    resolvedDependency.allModuleArtifacts
}
```
to
```
  else -> {
    if (LOGGER.isDebugEnabled) LOGGER.debug("retrieve allModuleArtifacts from artifact")
    resolvedDependency.allModuleArtifacts + resolvedDependency.toResolvedBomArtifact()
}
```

It doesn't seem to have any negative side effect to do so, but maybe I'm missing something?

Let me know if I can/should open a merge request.

## Details
- [x] Used library version: 11.2.3, 12.3.0-rc01
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you very much for the report. 

Please open a PR for this adjustment
