### ISSUE TITLE
long click listener

### ISSUE THREAD

**Issue by stleusc** [mikepenz/AboutLibraries#116]
It seems like there is no way to override the default long press behavior.
Also, can't the library just use the current default theme that my app uses? Why would I have to define a theme?

**Comment by mikepenz** [comment]
@stleusc this are 2 different topics. 


about the theme. no a library can'T just use the theme of another app. you will have to provide the specified attrs so the theme is working. if you set them in your theme it's fine. https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/styles.xml#L13
Still this is not as easy as it seems :D

**Comment by stleusc** [comment]
Sweet... thanks!
