### ISSUE TITLE
Gradle Setup for com.fima.cardsui

### ISSUE THREAD

**Issue by jayakanthang** [mikepenz/AboutLibraries#121]
Hi , If I need to use your lib in my app, it shows error in com.fima.cardsui. This library has documentation how to include their lib in gradle. can you please advise?

Thanks.
Jaya

**Comment by mikepenz** [comment]
@jayakanthang this library does not contain the com.fima.cardsui project. just the sample project.
it seems you did not setup the lib with the gradle dependency for your project?

**Comment by jayakanthang** [comment]
Hi, What should I do if I want to include this lib as gradle dependency?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/AboutLibraries#using-maven
