### ISSUE TITLE
Question: Display/include License (e.g. Apache 2.0)

### ISSUE THREAD

**Issue by andreaszielke** [mikepenz/AboutLibraries#124]
Hi Mike,

first of all - thanks for this supplying this great library :+1: 

I just started to play around with it in a project using Butterknife and my first question is: you don't seem to display the actual license text to the end user. I always assumed that 4a of the Apache 2.0 license requires this - but IANAL and not a native speaker.

Does the AboutLibraries activity supply a way to display the license, or is my assumption false?

All the best
Andreas

**Comment by mikepenz** [comment]
@andreaszielke if you click on the license name inside the AboutLibraries library it will display the license text. is this false?

**Comment by andreaszielke** [comment]
Hmm - I'm running the demo app on my Kitkat Device and I don't see the
license name.

@andreaszielke <https://github.com/andreaszielke> if you click on the
license name inside the AboutLibraries library it will display the license
text. is this false?

—
Reply to this email directly or view it on GitHub
<https://github.com/mikepenz/AboutLibraries/issues/124#issuecomment-122275750>
.

**Comment by mikepenz** [comment]
it is a property and has to be activated separately

You can find it in the Manifest Activity

**Comment by andreaszielke** [comment]
Ah, cool. Thanks for your guidance.
Am 17.07.2015 20:01 schrieb "Mike Penz" <notifications@github.com>:

**Comment by yuvraazjang** [comment]
hi Mike,
First of all thanks a lot for your library contribution for android.and for we like android learner it is really helpfull. i am trying to clone wallsplash (https://github.com/mikepenz/wallsplash-android)project but 
 compile 'com.gu:option:1.3' cannot be add can you please let me know what may be the probelm?
