### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by Mek0n** [mikepenz/AboutLibraries#125]
When manually creating library entries within values these entries appear fine if proguard is not used, if proguard is used then they do not appear.

Many thanks for a great library btw
Mek0n

**Comment by mikepenz** [comment]
@Mek0n i can not automatically detect libs via the Classpath autodetector if the packagename's and classes are altered. It will work for libraries which contain the definition file in it. but this is not the case for most libraries. 

So as an alternative fix you just can define which libraries to show. but you will have to do this manually.

**Comment by Mek0n** [comment]
Thanks for the quick response, I may have not made myself clear enough...

For example I am using PDFJet within my app so I create the following in values.

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="define_PDFJet"/>
    
    <string name="library_PDFJet_author">Innovatics Inc.</string>
    <string name="library_PDFJet_authorWebsite">http://pdfjet.com/</string>
    
    <string name="library_PDFJet_libraryName">PDFJet</string>
    <string name="library_PDFJet_libraryDescription">The Premier Cloud and Mobile PDF library for Java and .NET</string>
    <string name="library_PDFJet_libraryWebsite">http://pdfjet.com/</string>
    <string name="library_PDFJet_libraryVersion">5.51</string>
    
    <string name="library_PDFJet_isOpenSource">true</string>
    <string name="library_PDFJet_repositoryLink">http://pdfjet.com/</string>
    
    <string name="library_PDFJet_licenseId">bsd_3</string>
    
</resources>

when proguard is Not enable it shows fine, if it is the this library is not displayed.

Many thanks

**Comment by mikepenz** [comment]
@Mek0n i can't prove it but i have the feeling the empty `<string name="define_PDFJet"/>` is removed by proguard. Can you try to just add some content to it?

**Comment by Mek0n** [comment]
@mikepenz  I changed it to `<string name="define_PDFJet">PDFJet</string>` and it still does not show.

**Comment by mikepenz** [comment]
@Mek0n can you add it manually via code to make sure it is in and it just can't find it via the normal way?

**Comment by Mek0n** [comment]
@mikepenz I tried that to no avail, however I should have thought of this front the start (so sorry about all the noise)  in adding `-keep class com.mikepenz.aboutlibraries.** { *; }` to the proguard config, that resolves my issue.

Many thanks for your help and great library.

**Comment by mikepenz** [comment]
@Mek0n thanks :)
