### ISSUE TITLE
AboutSpecial open a website

### ISSUE THREAD

**Issue by JordanGout** [mikepenz/AboutLibraries#126]
is it possible to open a website with AboutSpecial button ?

thanks

**Comment by mikepenz** [comment]
@JordanGout you can hook in any functionality you want. 

There is the LibsConfiguration which allows you to set any listener for it:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java

Use it like:
```java
LibsConfiguration.getInstance().setListener(...)
```

You are looking for this: `onExtraClicked`. Return `false` if you have consumed the event

**Comment by JordanGout** [comment]
I missed this event on the listener. Thank You.

**Comment by mikepenz** [comment]
@JordanGout no problem ;)
