### ISSUE TITLE
HelloCharts isn't auto detected

### ISSUE THREAD

**Issue by bauerj** [mikepenz/AboutLibraries#133]
Hi there,

I'm including `com.github.lecho:hellocharts-android:v1.5.5` in my app and I do use classes like `lecho.lib.hellocharts.view.LineChartView` from it.

Despite HelloCharts being supported, it is missing from the overview.

**Comment by mikepenz** [comment]
@bauerj which version of the AboutLibraries do you use? Do you use proguard?

**Comment by bauerj** [comment]
I'm using the current Version 5.1.1.

As I'm currently just doing development build, proguard is not yet enabled.

**Comment by mikepenz** [comment]
@bauerj ah i see. this definition file was updated 9 days ago. i will publish an update later today. which will fix this issue ;)

**Comment by bauerj** [comment]
Thanks you :+1:

Also thanks for this great library :smile:

**Comment by mikepenz** [comment]
@bauerj latest version already published to maven central. should be available in the next 30 minutes ;)

thanks ;)
