### ISSUE TITLE
Some libraries are not detected

### ISSUE THREAD

**Issue by JordanGout** [mikepenz/AboutLibraries#136]
The following libraries are not detected :

`com.google.code.gson:gson:2.3.1`
`com.squareup.picasso:picasso:2.5.2`
`com.facebook.android:facebook-android-sdk:4.0.0`
`com.crashlytics.sdk.android:crashlytics:2.4.0@aar`
`com.timehop.stickyheadersrecyclerview:library:0.4.1@aar`

What I miss ?

**Comment by mikepenz** [comment]
@JordanGout do you have obfuscating activated? perhaps the class i use to check if it is there changed: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_gson_strings.xml#L12 ?

**Comment by mikepenz** [comment]
Will it work if you pass the fields via the builder? 
```java 
.withFields(R.string.class.getFields())
```

**Comment by JordanGout** [comment]
In development obfuscating is disable.

The Gson class didn't change (com.google.gson.Gson)

Here my class to launch AboutLibrariesActivity :

```
new LibsBuilder()
.withFields(R.string.class.getFields())
.withActivityStyle(Libs.ActivityStyle.LIGHT)
.withAutoDetect(true)
.withAboutIconShown(true)
.withAboutVersionShown(true)
```

**Comment by mikepenz** [comment]
@JordanGout interesting so it should understand that it's on the classpath :/. i will have to debug this issue

**Comment by JordanGout** [comment]
I try to add library_XXX_strings.xml files without any change except define_int_XX become define_XX

All libraries are now present so there is a problem with detection :/
I check (Gson, Picasso, Crashlytics, StickyHeader) classpaths everything is good. I do not use the same classpath for Facebook

**Comment by mikepenz** [comment]
@JordanGout without int the libraries are detected because the AboutLibraries thinks those are included in the lib itself.

hmmm i will take a clsoer look

**Comment by JordanGout** [comment]
Ok, thanks.

**Comment by mikepenz** [comment]
@JordanGout all of them are detected here. (can't test crashlytics as this is a different repo)

I have a small feature included which will improve performance after the first start which remembers libs found for a specific app version. Can you count up the current `versionCode` of your app?

**Comment by JordanGout** [comment]
All libraries are detected with a new version code (including crashlitycs)

Thank you for this advice ;)
