### ISSUE TITLE
Failed to resolve: com.mikepenz:aboutlibraries:5.2.1

### ISSUE THREAD

**Issue by vanniktech** [mikepenz/AboutLibraries#138]
I can't get version `5.2.1` from the Maven. Also according to [this](http://mvnrepository.com/artifact/com.mikepenz/aboutlibraries) it seems like it's not there. Did you push it?

**Comment by mikepenz** [comment]
@vanniktech you are right. i have not yet released it on maven central. have done this now. will take ~30 minutes to sync.

**Comment by vanniktech** [comment]
Hmm I still can't see it.

**Comment by mikepenz** [comment]
@vanniktech as of maven central it's there: http://search.maven.org/#artifactdetails%7Ccom.mikepenz%7Caboutlibraries%7C5.2.1%7Caar

**Comment by vanniktech** [comment]
Hmm okay fair enough then mvnrepository has some sync issues. Anyway, thanks.
