### ISSUE TITLE
Layout Issue with title

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/AboutLibraries#145]
The title is a bit cut off on one of my Libs.
Screenshot:
![screenshot_20150908-163612](https://cloud.githubusercontent.com/assets/8021265/9737662/03c979c0-5648-11e5-9120-3ce82c580ae2.png)

I'm using Version 5.2.2 and the LibsBuilder as an Activity.

**Comment by mikepenz** [comment]
@RubenGees interesting. on my phone it adds "..." to cut the name of the library. two lines is no option

**Comment by RubenGees** [comment]
I looked a bit through the layouts, they seem to be correct. I think that might be an Android issue or something, it happens on no other device I have tested this against either. https://code.google.com/p/android/issues/detail?id=13895 maybe it's this bug?

**Comment by mikepenz** [comment]
hmm could be something similar

**Comment by mikepenz** [comment]
@RubenGees is this still a topic for you?

**Comment by RubenGees** [comment]
Well, it was never a real problem, as it is really unlikely to happen, so i'll close this. I just wanted to show it if you maybe would have wanted to look for a solution.

**Comment by mikepenz** [comment]
yeah i have not really found what could cause the problem as it works in some cases. and in your case not. really weird
