### ISSUE TITLE
Jsoup not detected

### ISSUE THREAD

**Issue by randombyte-developer** [mikepenz/AboutLibraries#150]
Hello!

I just added your lib into my app. It was super easy! But it doesn't show all defined libs, e.g. Jsoup.
How I start the AboutLibraries-Activity: https://github.com/randombyte-developer/SGLVertretungsplan/blob/master/app/src/main/java/de/randombyte/sglvertretungsplan/fragments/SettingsFragment.java#L111
My proguard rules: https://github.com/randombyte-developer/SGLVertretungsplan/blob/master/app/proguard-rules.pro
The libs I use: https://github.com/randombyte-developer/SGLVertretungsplan/blob/master/app/build.gradle#L33

What am I doing wrong?
Thanks in advance! :grinning: 

RandomByte

**Comment by mikepenz** [comment]
The classpath of jsoup is not complete. i will improve this. for now just manually add jsoup as library you use :D

**Comment by randombyte-developer** [comment]
Thanks for replying so fast! As I can see, you fixed it right now(but it has to be pushed to maven).

**Comment by mikepenz** [comment]
@randombyte-developer yeah i have not yet released a new version. as mentioned just add it manually at the moment via the builder. 

```java
new LibsBuilder().withLibraries("jsoup") ...
```

**Comment by randombyte-developer** [comment]
Yeah, I did this(also with support lib and appcompat).

**Comment by mikepenz** [comment]
support and appcompat are not auto detected at the moment. they are used by most devs. i am not sure if they really need to be mentioned all the time..
