### ISSUE TITLE
AboutLibrary definition-file builder: custom library not working

### ISSUE THREAD

**Issue by bezineb5** [mikepenz/AboutLibraries#152]
The generated code looks like this:
```
<!-- License section -->
<string name="libray_libid_licenseVersion">LICENSE-NAME</string>
<string name="libray_libid_licenseLink">LICENSE-LINK</string>
<string name="libray_libid_licenseContent">LICENSE-TEXT</string>
```

It should be library instead of libray. However, I'm not sure were the code for this tool is.

Thanks!

**Comment by mikepenz** [comment]
@bezineb5 the online version? http://def-builder.mikepenz.com/

**Comment by mikepenz** [comment]
@bezineb5 ok thanks for reporting. fixed it
