### ISSUE TITLE
Library with internal definition does not show up

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/AboutLibraries#153]
I released a library recently with an internal definition file for AboutLibraries. But it won't show up...
This is the definition file: https://github.com/RubenGees/Introduction/blob/master/library/src/main/res/values/library_introduction_strings.xml

I start the AboutLibraries Activity like the following:
```java
new LibsBuilder().withAboutIconShown(true).withAboutVersionShownName(true)
                    .withAnimations(true).withAboutAppName(getString(R.string.app_name))
.withActivityTitle(getString(R.string.activity_about_title)).withFields(R.string.class.getFields())
                    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR).start(getActivity());
```

Thank you for your help in advance!

**Comment by mikepenz** [comment]
@RubenGees as far as i can see it looks fine. also you do not need this `library_introduction_classPath` for an internal lib. 

the lib is used in the project, and proguard isn't messing something up?

**Comment by RubenGees** [comment]
Ahh I found it. I created an internal file with your generator, but I needed an external one...

**Comment by mikepenz** [comment]
ah ok. haha. just saw that it looked at the fixed version of the definition file :D sure that i can't find an issue :P

**Comment by RubenGees** [comment]
Haha sorry for this pointless Issue... :D
