### ISSUE TITLE
Problems with Proguard

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/AboutLibraries#156]
Thank you for your help all the time and also this time in advance!

I have the following problem: When I build my App as a debug release, all the Libs show up. But when I build a release version with Proguard there are not all Libs. I tried to investigate why this happens, but I can't find a solution. I saw that all Libs with internal declarations are there (your other libs and my own) and also SOME other. It is really weird. For example the Lib 'Android Flow Layout' shows up, but 'Hello Charts' does not. Andorid Flow Layout does not have a proguard file that blocks obfuscation on it. (Or at least I dind't found it)

I added the R class to my proguard-rules as you suggested in your README. These are my proguard rules:

```
-keepclassmembers class * implements android.os.Parcelable {
    static android.os.Parcelable$Creator CREATOR;
}

//For Crashlytics
-keepattributes SourceFile,LineNumberTable

//For support libs
-keep class !android.support.v7.internal.view.menu.**,android.support.** {*;}

//For Play Services
-dontwarn org.apache.http.**
-dontwarn android.net.http.AndroidHttpClient
-dontwarn com.google.android.gms.**
-dontwarn com.android.volley.toolbox.**

//For AboutLibraries
-keep class .R
-keep class .R$* {
    <fields>;
}
```

This is how I build the Activity:

```
new LibsBuilder().withAboutIconShown(true).withAboutVersionShownName(true)
.withAnimations(true).withAboutAppName(getString(R.string.app_name)).withAboutDescription("Some text")
.withActivityTitle(getString(R.string.activity_about_title)).withFields(R.string.class.getFields())
.withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR).start(getActivity());
//Started from a Fragment
```

This is a part of my build.gradle:

```
 release {
        minifyEnabled true
        shrinkResources true
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
 }
```

Note: Yes I tried plain `proguard-android` also.

**Comment by mikepenz** [comment]
please try

```gradle
-keep class .R
-keep class **.R$* {
    <fields>;
}
```

**Comment by RubenGees** [comment]
Doesn't work unfortunately...

**Comment by mikepenz** [comment]
but adding
```java
.withFields(R.string.class.getFields())
```
to the builder should do the trick at least

**Comment by RubenGees** [comment]
Yeah. Really weird. You can look through the project if you want: https://github.com/RubenGees/Vocabletrainer

Maybe it's some issue with the build tools or proguard itself.

**Comment by RubenGees** [comment]
Did you found anything about that yet? I tried it with a somehow fresh project - same problems.

**Comment by mikepenz** [comment]
does this fix the problem?
```java
.withFields(R.string.class.getFields())
```

**Comment by RubenGees** [comment]
No it doesn't. Here is a complete fresh project with minimal configuration. If you build the release, the problem occurres: https://github.com/RubenGees/AboutLibrariesTest

**Comment by mikepenz** [comment]
@RubenGees ah i see. yeah makes sense that it does not work for most libs, as those devs are to lazy to include the definition file inside their lib. proguard modifies the packagename and classes so the autodetect feature is not working for libs where the definition file is included inside the AboutLibraries. It works for libs like the MaterialDrawer which has the definition file inside the lib itself. 

You have 2 options. 
* Exclude the class which is used to autodetect from obfuscating
* Manually define and add those libs
* (not really a solution) hope that those devs add the definition file to their libs :D

sorry there are no other solutions

**Comment by RubenGees** [comment]
Hmm, okay I see. I'll go with the manual definition then... 
How do I turn off the autodetection then (as it wastes processing power)? And does that affect the libs with definitions inside them?

**Comment by mikepenz** [comment]
@RubenGees just set `withAutoDetect(false)` this will just disable the autodetection via the classpath. MaterialDrawer etc will still work

**Comment by RubenGees** [comment]
Great, thank you once again!

**Comment by mikepenz** [comment]
no problem. sorry that this is not possible via the autodetection. but gradle removes everything which would allow me to detect an lib.

**Comment by RubenGees** [comment]
Yep. There is only the compile-time based approach left.

**Comment by mikepenz** [comment]
@RubenGees yes. but i really do not have the time to do this
