### ISSUE TITLE
AboutLibraries fragment being replaced by previous fragment in stack

### ISSUE THREAD

**Issue by AngleV** [mikepenz/AboutLibraries#159]
I have an activity which host a PreferenceFragmentCompat.
When user taps on Credits preference item, the AboutLibraries Fragment comes in front.

```
LibsFragment fragment = new LibsBuilder()
                                //get the fragments
                                .withLibraries("glide", "photoview")
                                .withExcludedLibraries("materialize")
                                .withVersionShown(false)
                                .withLicenseShown(false)
                                .withAnimations(false)
                                .fragment();
                        
getFragmentManager().beginTransaction()
                                .setCustomAnimations(R.anim.activity_scale_up_enter, R.anim.activity_scale_up_exit, R.anim.activity_scale_up_enter, R.anim.activity_scale_up_exit)
                                .replace(R.id.feedContainer, fragment)
                                .addToBackStack("Libs")
                                .commit(); 
```

So far so good but when user taps on a library the AboutLibraries Fragment detaches from Activity and being replace by Preferences fragment.

Any idea ?

**Comment by mikepenz** [comment]
@AngleV i think this is no AboutLibraries issue as those just provide the fragment.

**Comment by AngleV** [comment]
@mikepenz 
Yes after more investigation i find out that its nothing to do with AboutLibraries.
But if someone implements this inside a stack fragment he will get the same effect.

The problem has to do with the Intent.ACTION_VIEW

````
    Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse());
    fragment.this.startActivity(intent);
````

But i can figure out how to solve it
