### ISSUE TITLE
Stuttering on first display when using .fragment()

### ISSUE THREAD

**Issue by rubengees** [mikepenz/AboutLibraries#162]
Hi,

As the title says I experience visual stuttering when I call AboutLibraries with .fragment() and display it.
Code:
```java
new LibsBuilder().withAboutVersionShownName(true)
                                .withAboutDescription(getString(R.string.about_description))
                                .withAboutIconShown(true).withAutoDetect(false)
                                .withAboutAppName(getString(R.string.app_name))
                                .withLibraries("glide", "systembartint", "jodatimeandroid",
                                        "bridge", "hawk", "butterknife", "materialdialogs")
                                .withFields(R.string.class.getFields()).fragment());
```

As you can see I disabled the auto detection and specified the used ilbs myself, which should be faster. The Fragment than simply replaces the current fragment, and I don't think the delay comes from there.
When I call it again, the stuttering is gone. (Although it takes some time to load the Fragment)

Below is a video which shows the effect (Sorry for the bad quality, but you get the idea):

![device-2015-10-18-222414](https://cloud.githubusercontent.com/assets/8021265/10566480/4aeb15a6-75e8-11e5-857e-7a948c348d39.gif)

Thank you for your help in advance!

**Comment by mikepenz** [comment]
@rubengees sorry for the late response. i've improved the initialization of the fragment and libs loading will be in v5.2.6

**Comment by rubengees** [comment]
Works great, thank you!
