### ISSUE TITLE
Toolbar colour

### ISSUE THREAD

**Issue by georgeherby** [mikepenz/AboutLibraries#165]
Question - when I set my page up using the style of light and dark toolbar it gives me a toolbar of the same colour at my accent colour not the colorPrimary. How do I correct this?

**Comment by AngleV** [comment]
@georgeherby 

read this 

https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Style#colorsxml

**Comment by georgeherby** [comment]
@AngleV thank you sir :) sorry for being a bit thick and not finding that!!
