### ISSUE TITLE
.withAboutDescription span link listener

### ISSUE THREAD

**Issue by AngleV** [mikepenz/AboutLibraries#169]
i am using this 

```
.withAboutDescription(getString(R.string.website))



<string name="website"><![CDATA[
       Visit our <a href="website.com">website</a>
         ]]>
</string>

```

how to handle the click of url span inside the string ?

**Comment by mikepenz** [comment]
@AngleV you can't directly access this. i will add you 2 new methods to hook into the view creation of the HeaderView and normal library card view (of the RecyclerView)

**Comment by AngleV** [comment]
awesome !
looking forward for the new release :D

**Comment by mikepenz** [comment]
@AngleV was waiting for this release for the other issue to be fixed :D (https://github.com/mikepenz/AboutLibraries/issues/166) but as you mentioned it already works i will release now ;)

**Comment by AngleV** [comment]
You rock mate !!! :+1:

**Comment by mikepenz** [comment]
@AngleV i hope the listener is working for you as i hope to. But it will allow you to access the view containing the description. So you should also be able to overwrite this behavior

**Comment by AngleV** [comment]
i am trying to implement it like this 

```
.withUiListener(new LibsConfiguration.LibsUIListener() {
                                    @Override
                                    public View preOnCreateView(View view) {
                                        return null;
                                    }

                                    @Override
                                    public View postOnCreateView(View view) {
                                        return null;
                                    }
                                })
```

and i get i NullPointerException

Build version: 1.0.1 
Build date: 2015-11-03 00:36:20 
Current date: 2015-11-02 17:37:58 
Device: Genymotion Samsung Galaxy S3 - 4.3 - API 18 - 720x1280 

Stack trace:  
java.lang.NullPointerException
	at com.mikepenz.aboutlibraries.ui.LibsFragment.onCreateView(LibsFragment.java:209)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.

**Comment by mikepenz** [comment]
@AngleV no this is the wrong one. this will allow you to modify the whole ui. but the description is part of the header. 

So you have to use the `LibsRecyclerViewListener` https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L112 for the `LibsRecyclerViewAdapter.HeaderViewHolder`


Just a description why you get this exception above:
You return `null` as view for the fragment, so it will crash. You should return the view again. So the method is meant that you modify the view and then return it so this view will then be returned in the `onCreateView` method.

**Comment by AngleV** [comment]
Yeah you are right return null it gives null and nothing more :D
You mean like this ??

```
.withLibsRecyclerViewListener(new LibsConfiguration.LibsRecyclerViewListener() {

                                    /**
                                     * OnBindHeaderViewHolder called after the headerView was filled inside the recyclerViews onBindViewHolder method
                                     *
                                     * @param headerViewHolder
                                     */
                                    @Override
                                    public void OnBindViewHolder(LibsRecyclerViewAdapter.HeaderViewHolder headerViewHolder) {
                                        
                                    }

                                    /**
                                     * OnBindViewHolder called after the item view was filled inside the recyclerViews onBindViewHolder method
                                     *
                                     * @param headerViewHolder
                                     */
                                    @Override
                                    public void OnBindViewHolder(LibsRecyclerViewAdapter.ViewHolder headerViewHolder) {

                                    }
                                })
```
i think i need some sleep :|

**Comment by mikepenz** [comment]
@AngleV right ;). 

The `onBindViewHolder` method is called after a specific item was created inside the `Adapter` of the `RecyclerView`

The `HeaderViewHolder` has the `descriptionTextView`
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/adapter/LibsRecyclerViewAdapter.java#L464

**Comment by AngleV** [comment]
still cant figure out how to access the descriptionTextView  :(
