### ISSUE TITLE
remove V4 Fragments

### ISSUE THREAD

**Issue by MAndretti** [mikepenz/AboutLibraries#170]
Hi,

only a view (four percent) Apps use API Level below 11. So 96 percent of all Apps use normal fragment manager and not support fragment manager. Can you please replace the support fragment manager with normal fragment manager or create a class for that.

Thanks and regards,
Mario Adamo Andretti

**Comment by mikepenz** [comment]
@MAndretti sorry but i stay with API Level 10, as many devs still support apps down to API 10. 
As an additional note most apps also come with the appcompat-v7 library which has the support-v4 as dependency, so those also support the v4.Fragment. 

What usecase do you have that you can't use v4 fragmet?

**Comment by MAndretti** [comment]
HI,

I love AboutLibraries. In the past it was easy to replace V4 Fragments with
current Fragments (v11). But since last version (async task change) i am
unable to change the source. Try to change getContext to getActivity, but
get runtime error (in both cases). All my apps use the current/v11 fragment
manager. V4 fragments are not compatible with current fragment manager. The
new code runs smooth (sample app) but can't get it to run (in my apps).
some hints?

Thanks,
Mario

Mike Penz <notifications@github.com> schrieb am Mo., 2. Nov. 2015 22:22:

**Comment by mikepenz** [comment]
@MAndretti next update will fix it for you ;) 

There is now a method `.supportFragment()` which will return the `v4` fragment, 
and the `.fragment()` method which will return the normal fragment
