### ISSUE TITLE
Need a way to know when the LibraryTask completes its task.

### ISSUE THREAD

**Issue by manjunathc23** [mikepenz/AboutLibraries#177]
I have a requirement where I need to show progress bar till the about fragments loads completely. 
Is there any way I can know when the recycler view within the lib is completes it's task. 

Thanks!
Manju

**Comment by mikepenz** [comment]
@manjunathc23 there was no such listener until now.

Thanks to @PDDStudio  there is now a new callback which allows you to hook in for this task

**Comment by manjunathc23** [comment]
Awesome!  Is it available in prod?

Thanks a lot for the all the support and help. 
Thank you @mikepenz  @PDDStudio 

Thanks!
Manju

**Comment by mikepenz** [comment]
maven central will needs about 15 to 30 minutes to sync, afterwards it will be available ;). 

The sample includes a small code snippet how to use it ;). 

I hope it works, as you expect it to work ;). 

Best,
Mike

**Comment by manjunathc23** [comment]
Sounds good thanks!

**Comment by PDDStudio** [comment]
@manjunathc23 you're welcome! Hope it helps
@mikepenz thanks for the mention and merging my pr 😆

**Comment by manjunathc23** [comment]
Tested it works all good! Thanks @mikepenz  @PDDStudio
