### ISSUE TITLE
Pass Runnable to Special Buttons instead of Text only

### ISSUE THREAD

**Issue by markusressel** [mikepenz/AboutLibraries#179]
Awesome library, great work!

I have a feature suggestion.
I would like to be able to set my own actions when pressing an "AboutSpecial" button. I have my changelog available only on my Website and don't want to copy everything between my website and the app sourcecode all the time. So it would be great to be able to just open a webpage with the button. It would be great to pass in a runnable as button action instead of just a string description.

Also Links used in the AboutSpecial dialogs are highlighted as links (HTML) but are not clickable. In the app description however links _are_ clickable.

**Comment by mikepenz** [comment]
@markusressel hi. you can do this already. Just define a `listener` via the `LibsConfiguration` (in your `Activtiy`, or a Custom`Application`) 

There is a sample with such a listener in the sample application. Look here:

https://github.com/mikepenz/AboutLibraries/blob/develop/sample/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L155

(You can implement the interface, or just extend the `impl` of the listener (if you do not want all methods to be overwritten)

**Comment by markusressel** [comment]
I will check this out in the coming days, unfortunately I don't have much time currently.
Thanks for the quick response!

**Comment by mikepenz** [comment]
@markusressel no problem ;) let me know if you need something else.

**Comment by markusressel** [comment]
Works great, thx.

Maybe you should think about updating the Wiki, I found nothing about this on the GitHub Wiki (or did I miss it?). It was also confusing that I *have* to call `.withAboutSpecial1Description("test")` with a valid text in addition to `.withAboutSpecial1("bla")` before the button was showing up. If the description is necessary IMO this should be one method call with 2 arguments or the description should be optional (with a dummy text in the dialog?).

Keep coding ;)

**Comment by mikepenz** [comment]
@markusressel many things are "documented" via the sample application ;). Makes far more sense for me, because it allows me to showcase things, and to test them (and document them via the app) in once. 

But i see that some things could be improved ;). 

In fact the requirement of the description can be eliminated. If there is a listener. 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/adapter/LibsRecyclerViewAdapter.java#L104

Thanks
