### ISSUE TITLE
Improvement suggestion - Used other sources

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/AboutLibraries#180]
Would be nice to have a simple method to add used other sources that don't need a license but just a reference link. For example, https://icons8.com/ does need that.

Currently I added a pseudo license where everything points to the page above... And created a pseudo library that uses this library...

Things like that could be easily setup in code via the builder. A simple title, description, link and icon would be more than enough.

Maybe you think that's useful as well and add it...

**Comment by mikepenz** [comment]
@MFlisar this is already possible. You can simply add a project to the lib by creating ressources like this one:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <string name="define_ItsATest">year;owner</string>
    <string name="library_ItsATest_author">Mike Penz</string>
    <string name="library_ItsATest_authorWebsite">http://mikepenz.com/</string>
    <string name="library_ItsATest_libraryName">It is a test</string>
    <string name="library_ItsATest_libraryDescription">
        <![CDATA[
            Just a test
        ]]>
    </string>
    <string name="library_ItsATest_isOpenSource">true</string>
    <string name="library_ItsATest_repositoryLink">http://itsatest.com</string>
    <!-- Custom variables section -->
    <string name="library_ItsATest_owner">Mike Penz</string>
    <string name="library_ItsATest_year">2014</string>
</resources>
```
Just replace `ItsATest` with something new per library. And it will display it ;)

**Comment by MFlisar** [comment]
Thanks, that's a little easier... Still, having the ability to add an icon would be a nice to have.
