### ISSUE TITLE
Improve RTL language support

### ISSUE THREAD

**Issue by Aqua-Ye** [mikepenz/AboutLibraries#186]
Title and licence don't display well on RTL devices.

**Comment by mikepenz** [comment]
@Aqua-Ye could you please add a screenshot too?

**Comment by Aqua-Ye** [comment]
@mikepenz here

![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/85234/13009304/0fc4d060-d19c-11e5-8c27-7b716659862b.png)

**Comment by mikepenz** [comment]
@Aqua-Ye fixed in v5.5.2
