### ISSUE TITLE
Unable to include external libraries

### ISSUE THREAD

**Issue by sparkitny** [mikepenz/AboutLibraries#187]
Hi,

I try to include about informations of external libs I use, but I'm not able to get them shown. Here's the code snippet I used (I tried to visualize the lib "Otto" in several ways but nothing):

```java
new LibsBuilder()
                    .withFields(R.string.class.getFields())
                    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                    .withAboutIconShown(true)
                    .withVersionShown(true)
                    .withAboutDescription("Testbeschreibung")
                    .withAboutVersionShown(true)
                    .withLibraries("AboutIt", "Otto", "com.squareup.otto", "otto-1.3.8")
                    .withAboutAppName(getString(R.string.app_name))
                    .withLicenseShown(true)
                    .start(this);
```

What am I doing wrong?

**Comment by mikepenz** [comment]
@sparkitny just checked. There is a definition file for otto. and using `.withLibraries("Otto")` should work. Perhaps `.withLibraries("otto")` (if this works I have to check if everything is done case insensitiv) 

Otherwhise. Do you see other libraries?

**Comment by sparkitny** [comment]
Ok,

it works on my android phone. With the emulator it doesn't work. Another lib I use is https://github.com/EverythingMe/easy-content-providers. Using providers-android it unfortunately doesn't show up.

**Comment by mikepenz** [comment]
@sparkitny it just doesn't show up on your emulator? ok that's weird. Shouldn't make a difference. Perhaps the built in caching of auto detected libraries gets active here. 

Regarding **easy-content-providers**. There is not yet a definition file for this library. 

You can easily create new **definition files** with this easy web tool:
http://def-builder.mikepenz.com/


All files are in here if you want to find one:
https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values

**Comment by sparkitny** [comment]
Hi,

now it works perfectly. I don't know what happened to the emulator, but after a complete restart of my pc it accepted the code changes and now shows the libraries.

Thanks for this lib,

Sebastian

**Comment by mikepenz** [comment]
@sparkitny perhaps **instant run** issue?

**Comment by sparkitny** [comment]
Perhaps,

Now it works perfectly

Thanks
Am 14.02.2016 12:33 nachm. schrieb "Mike Penz" <notifications@github.com>:
