### ISSUE TITLE
About description alignment

### ISSUE THREAD

**Issue by zishanj** [mikepenz/AboutLibraries#190]
How can I make about description to be left aligned? It's currently showing text in center. I have tried using HTML `align="left"` and `style="text-align:left"` attributes but it doesn't work.

**Comment by mikepenz** [comment]
@zishanj you can't align the text, center is default

You could copy this layout to your project (keep the name) and change the gravity of the description to `left`
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listheader_opensource.xml#L86
