### ISSUE TITLE
set textSize & textColor for header and description Dynamically 

### ISSUE THREAD

**Issue by kprathap23** [mikepenz/AboutLibraries#192]
is there any way to set textSize and textColor for header and description Dynamically

**Comment by mikepenz** [comment]
@kprathap23 no there isn't you could only overwrite the layout which is used for the cards

**Comment by mikepenz** [comment]
Copy this to your project https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/res/layout/card_library.xml (keep the name) and change the text sizes
