### ISSUE TITLE
Javadoc gradle task failing

### ISSUE THREAD

**Issue by andrebcmarinho** [mikepenz/AboutLibraries#196]
Hi! I'm trying to compile this library but I get an error: "Execution failed for task ':library:generateDebugJavadoc'.". I've already read that this can be related with some special characters like html tags but I don't find any method comment with html tags. Can you please point out the files which have illegal characters? Thanks a lot in advance for your help

**Comment by mikepenz** [comment]
@andrebcmarinho you just checked out this project without any modifications? I can compile it and it works on my machine. 

If you build the project from the terminal, just scroll up and find the lines where it states **ERROR** for the javadoc. So you can simply fix those lines there.

**Comment by andrebcmarinho** [comment]
@mikepenz thanks for quick reply. In fact I was trying to use JitPack and here is the log: https://jitpack.io/com/github/mikepenz/AboutLibraries/v5.6.0/build.log

I think my problem could be the same of this user (http://stackoverflow.com/questions/26552279/gradle-build-fails-with-javadoc-nullpointerexception) but I din't find any illegal characters on your method comments. That's why I was asking for your help on this issue. Thanks

**Comment by mikepenz** [comment]
@andrebcmarinho sorry I do not support jitpack. Please use the published dependency on jCenter or mavenCentral

**Comment by andrebcmarinho** [comment]
Ok, thanks anyway.
