### ISSUE TITLE
Basic Support Lib Detection

### ISSUE THREAD

**Issue by jaredsburrows** [mikepenz/AboutLibraries#197]
Based on this issue: https://github.com/mikepenz/AboutLibraries/issues/185

@mikepenz you said:
```
they are excluded of the auto detection by default. this is intended. You can simply add them with the withLibraries as you already did.
```

So how do we detect these? 
```
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:preference-v7:23.1.1'
    compile 'com.android.support:preference-v14:23.1.1'
```
**Like:**

```
 .withLibraries("RecylcerView", "Support v4 Library", "AppCompat v7 Library", "Butterknife",
                                      "Eventbus", "LeakCanary", "OkHttp",
                                       "Retrofit", "Retrofit2", "gson", "rxJava", "rxAndroid")
```

**Comment by mikepenz** [comment]
@jaredsburrows at the moment there are only definition files for the play services and for the general support libraries
https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values

For the other ones we will first need to add the definition files like:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_googleplayservices_strings.xml
or 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_supportlibrary_strings.xml

**Comment by jaredsburrows** [comment]
@mikepenz Alright, I'll make a PR for the libraries that are missing. I'll just follow the exact format you have the for previous libraries?

**Comment by mikepenz** [comment]
@jaredsburrows yes exactly. You can also use this tool: http://def-builder.mikepenz.com/ if you want to.

**Comment by jaredsburrows** [comment]
Wow thanks. Will do!

**Comment by jaredsburrows** [comment]
@mikepenz Here is my PR:https://github.com/mikepenz/AboutLibraries/pull/198

I took the time to update retrofit and okhttp.

**Comment by jaredsburrows** [comment]
I will add more after my first PR is in :)
