### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jaredsburrows** [mikepenz/AboutLibraries#199]
@mikepenz If you sign up for TravisCI, I'll make a PR to add a badge to your README and help setup TravisCI.

**Comment by mikepenz** [comment]
@jaredsburrows TravisCI is already enabled for the `MaterialDrawer` and for the `FastAdapter`. I can also enable it for the `AboutLibraries ;)

**Comment by jaredsburrows** [comment]
@mikepenz Thanks. Here is the PR: https://github.com/mikepenz/AboutLibraries/pull/200.

**Comment by mikepenz** [comment]
merged. Thank you so much

**Comment by jaredsburrows** [comment]
@mikepenz Your repo's default branch is `develop`, if you change it to `master`, the badge will change to "passing".

**Comment by mikepenz** [comment]
@jaredsburrows should also change as soon as the master was built. I prefer the `develop` as default branch as I work with `git-flow` and I want `pull-request`s on `develop`

**Comment by jaredsburrows** [comment]
@mikepenz I need to change the badge's branch to `develop`?

**Comment by mikepenz** [comment]
@jaredsburrows no I think it's fine if it always shows the current `stable` branch which is the `master`
