### ISSUE TITLE
AboutLibrary showing a blank activity

### ISSUE THREAD

**Issue by javiersantos** [mikepenz/AboutLibraries#205]
I'm using this library in some of my apps, but now I'm experiencing a blank activity when the activity is shown.

```java
public class LicenseActivity extends LibsActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        setIntent(new LibsBuilder()
                .withActivityTitle(getResources().getString(R.string.help_license))
                .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                .withLicenseShown(true)
                .intent(this));

        super.onCreate(savedInstanceState);
    }
}
```

The log shows `Have you missed to call withFields(R.string.class.getFields())? - autoDetect won't work -` but even adding the `withFields` method it still shows the same blank screen.

**Comment by bornvanchris88** [comment]
- [ ] i k
I

**Comment by mikepenz** [comment]
@javiersantos what have you changed, as you write it was working already?

The 
```
.withFields(R.string.class.getFields())
``` 

Part is really important.

**Comment by javiersantos** [comment]
I've been using the library without adding `.withFields(R.string.class.getFields())` multiple times, as you can see in this examples::
https://github.com/javiersantos/MLManager/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fjaviersantos%2Fmlmanager%2Factivities%2FLicenseActivity.java
https://github.com/javiersantos/WhatsAppBetaUpdater/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fjaviersantos%2Fwhatsappbetaupdater%2Factivity%2FLicenseActivity.java
https://github.com/javiersantos/AppUpdater/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fjaviersantos%2Fappupdater%2Fdemo%2FAboutActivity.java

I will check today if adding `.withFields(R.string.class.getFields())` solves the problem, but I think yesterday was showing the same result (even with the same log message).

**Comment by mikepenz** [comment]
@javiersantos perhaps those apps don't have proguard enabled? or they do not define an `applicationId` inside the `build.gradle` (which would both block the auto detecting of the `R` class) 

Also you might need to update the current versioncode of the app as the `AboutLibraries` caches the auto detected libraries for each version, after the first launch

**Comment by javiersantos** [comment]
It's working now when adding `.withFields(R.string.class.getFields())` and updating the versionCode.
