### ISSUE TITLE
Title covered by status bar

### ISSUE THREAD

**Issue by jgindin** [mikepenz/AboutLibraries#206]
I'm building the about screen with:
```java
aboutBuilder = new LibsBuilder()
  .withFields( "define_zehut_yosef", "define_zmanim", "define_kosherjava", "define_materialdrawer", "define_AboutLibraries" )
  .withAutoDetect( false )
  .withAboutAppName( context.getString( R.string.app_name ) )
  .withAboutDescription( description )
  .withAboutVersionShownCode( false )
  .withActivityTheme( R.style.EliPurple )
  .withActivityTitle( context.getString( R.string.action_about_title ) )
  .withLibraryComparator( libraryComparator );
aboutBuilder.show( context );
```

What I'm getting is the title partially obscured by the system status bar:
<img src='https://cloud.githubusercontent.com/assets/1209704/14135230/39e934dc-f611-11e5-88cc-f80518b87807.png' width='250px'>

Clearly, I'm doing something wrong, but cannot figure out what. I would appreciate any pointers.

Thanks!

**Comment by mikepenz** [comment]
@jgindin I assume your theme has a translucent `StatusBar` You might want to use a default `AboutLibraries` theme and just alter the `primaryColor`

**Comment by mikepenz** [comment]
See the following for the default themes. 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/styles.xml

**Comment by jgindin** [comment]
Thanks! All taken care of!
