### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by lawloretienne** [mikepenz/AboutLibraries#212]
Is there a straightforward way to customize the font with a different Typeface then Roboto for the adapter in the LibsSupportFragment?

**Comment by mikepenz** [comment]
There's no api to do so. It should be possible if you use https://github.com/chrisjenx/Calligraphy

**Comment by mikepenz** [comment]
If you need complete custom style you could just use the `Libs` class and just fetch the information of the libs. Then you can fill your own `RecyclerView` with the information

**Comment by lawloretienne** [comment]
Hey @mikepenz thanks for pointing me to you `Libs` class.  I just called the constructor
`Libs libs = new Libs(this);`
and I can see two member fields `externLibraries` and `internLibraries`.

`externLibraries` has a size of 3 and `internLibraries` has a size of 138.

How can I filter out to just get the dependencies that i have included in my `build.gradle` ?  Is the `externLibraries` accounting for all nested dependencies or something?

**Comment by mikepenz** [comment]
Just use the following method it will prepare all the library for you and return them as list:

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/Libs.java#L146

**Comment by lawloretienne** [comment]
So this seems to be returning a subset of the libraries that i have in my `build.gradle` .

**Comment by mikepenz** [comment]
@lawloretienne yeah here's what the library does:

AboutLibraries builds around the concept of "defintion"-files (basically a defined naming pattern for strings split up in different files) So in general the library only knows about the libs which were added as definition file. (You can find a full list here: https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values)

The next thing is that it distinguishes between intern and extern library definition files. That means definition files which are included in the libs themself. Those are easy to detect and display (This happens for a few, like my libraries). The others can't be auto detected that easily, and it will try this via a "class" specified in the definition file. If it can init the class the lib is there. (this also is not possible if proguard renames the classes) So all those which do not include the info, or can't be auto detected can either miss the definition file in the lib or just fall out from the above, so you can also define with the method I sent you above to include them manually via their identifier.

**Comment by lawloretienne** [comment]
So since there is no definition file in https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values
for some of those libraries that were not picked up, then I must include them manually?

**Comment by mikepenz** [comment]
@lawloretienne so since there is no definition file, you need to create such an file (you can use the online tool for this) and add it to your project (or even better create a pull request so it will be included in the AboutLibraries)

Yes correctly. Just use the identifier of those libs:

The identifier is always the string after "define_int_" or "define_"
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_actionbarsherlock_strings.xml#L4

Best,
Mike

**Comment by lawloretienne** [comment]
Thanks @mikepenz I will be creating a pull request soon to add my definition files.  I had an issue with the `prepareLibraries()` method.  There is a param that you can pass in to exclude libraries.  I have tried a couple different combinations but i can't quite exclude anything. For example I would like to exclude `Android-Iconics` and `FastAdapter`.

**Comment by lawloretienne** [comment]
I also noticed that the version number for something like `Timber` is outdated
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_timber_strings.xml

Idk how you can keep the version numbers up to date.

**Comment by lawloretienne** [comment]
![affix_20160418_150923](https://cloud.githubusercontent.com/assets/311187/14621456/cd3a1fa6-0577-11e6-8e5c-7b550d00a60b.png)

Thanks for you advice.  I was able to customize the UI.

**Comment by mikepenz** [comment]
@lawloretienne you can't exclude libraries which have the definition inside the lib itself because it is a fact that those are included. But could probably be revisited. 

If you show versions they are in most cases outdated as I can't fetch this info directly from the lib and has to be included in the definition file. Normally I choose not to display the version but the license. 

Oh your change looks nice. ;).

**Comment by lawloretienne** [comment]
Thanks again for all the help.  This is a great library btw.

**Comment by mikepenz** [comment]
Thank you :)
