### ISSUE TITLE
Custom onClickListener for special buttons.

### ISSUE THREAD

**Issue by caman9119** [mikepenz/AboutLibraries#213]
Allow registering an onClickListener for one of the special buttons in the LibsBuilder, or some method of having custom button actions.

**Comment by mikepenz** [comment]
@caman9119 you can via the `LibsConfiguration` 
Create an instance and define a `LibsListener`
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L34

Which allows you to listen for the `ExtraButton` click event:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L194

**Comment by caman9119** [comment]
Brilliant, got it working. Thanks!
