### ISSUE TITLE
Return view

### ISSUE THREAD

**Issue by Mansourali** [mikepenz/AboutLibraries#214]
Hi Mike
I just wonder if I can return view from the Lib object to use it in instantiateItem of viewpager 
thanks

**Comment by mikepenz** [comment]
@Mansourali you can retrieve a `Fragment`. Otherwhise you could extract the logic to get just a `Adapter` from here: 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsFragmentCompat.java

**Comment by Mansourali** [comment]
Thanks for you replay 
If I got you right, you mean I should initiate the Lib by using `Fragment`, then I retrieve that `Fragment `inside the `instantiateItem `of the `viewpager`.

**Comment by mikepenz** [comment]
@Mansourali if you can use a fragment you can just build it via the LibsBuilder. if you really need a view, you will have to check out the source of the `LibsFragmentCompat` and extract the logic to get the exact same view. 

As an alternative you can use the `adapter` method of the `LibsBuilder` to get the adapter which you can then set on any `RecyclerView` 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L473

**Comment by Mansourali** [comment]
I think I will go for the Recycleview, i will try my best
thanks for your help
