### ISSUE TITLE
License link in card should have it's own selector

### ISSUE THREAD

**Issue by austynmahoney** [mikepenz/AboutLibraries#215]
When you long press on the license text, the ripple should only happen on section that contains it. Currently the ripple fills the entire card when anything is pressed.

This makes it hard for the user to discover that long pressing on the license text will open the License dialog.

![screen-shot-2016-04-18-at-10 16 14-am](https://cloud.githubusercontent.com/assets/1133292/14611442/7a1872be-054f-11e6-969a-45eb370a7f46.png)

**Comment by mikepenz** [comment]
@austynmahoney you might want to open a PR for this

**Comment by irobotman** [comment]
I got this error:Could not find com.android.support:appcompat-v7:23.3.0. And I couldn't download Android support lib 23.3.0 by sdk manager，what should I do......

**Comment by mikepenz** [comment]
I don't have this on my TODO if you really want it four your project, I would really love to merge in a Pull Request. Thanks

**Comment by austynmahoney** [comment]
@mikepenz Can you keep the issue open if you want a pull request for the feature? I'm planning on making this change, just haven't had time yet.

**Comment by mikepenz** [comment]
@austynmahoney I already had a look at it a week ago, but it isn't as easy as it sounds in the first place :/

**Comment by mikepenz** [comment]
I still will close this for now as it is no issue, and will might make a great addition if you find some time to provide it someday. (Going over all issues right now from my libs, have to do this to keep overview)
