### ISSUE TITLE
Could not find com.android.support:appcompat-v7:23.3.0.

### ISSUE THREAD

**Issue by irobotman** [mikepenz/AboutLibraries#217]
I got this error:Could not find com.android.support:appcompat-v7:23.3.0. And I couldn't download Android support lib 23.3.0 by sdk manager，what should I do......

**Comment by mikepenz** [comment]
https://github.com/mikepenz/AboutLibraries/issues/216

Please search for an answer on **Stackoverflow** I can not change anything regarding this.

**Comment by irobotman** [comment]
Thx,I download the Android Support Repository v30 by SDK Manager and solve this issue.
