### ISSUE TITLE
LibsFragmentCompat libraries size is 0

### ISSUE THREAD

**Issue by kiezkicker** [mikepenz/AboutLibraries#218]
I have the problem that the static libraries in LibsFragmentCompat is not null - the list is empty and prepareLibraries and so the libraries are not initialized correctly. 

In another app this problem does not occur.

Is it possible to load the libs if libraries are null or the size is 0?

Thanks in advance

**Comment by mikepenz** [comment]
@kiezkicker I am not sure what your issue is? You do not have libraries and just want the upper area? Or what do you want to achieve?

Do you use proguard? Do you pass the fields from your R variable? (have you defined an applicationId in your gradle?)

**Comment by kiezkicker** [comment]
@mikepenz Thanks for the fast reply!

My app should show 22 libraries but the static field 'libraries' in LibsFragmentCompat shows 0. If I debug the library I found out that the field 'libraries' is never null so the prepareLibraries-Method is never called.

I wonder how the field "libraries" is initialized. This should be the place, but in my case libraries is never null. LibsFragmentCompat:
```
if (libraries == null) {
                //apply modifications
                libs.modifyLibraries(builder.libraryModification);

                //fetch the libraries and sort if a comparator was set
                boolean doDefaultSort = (builder.sort && null == builder.libraryComparator && null == comparator);

               libraries = libs.prepareLibraries(ctx, builder.internalLibraries, builder.excludeLibraries, builder.autoDetect, doDefaultSort);

                if (comparator != null) {
                    Collections.sort(libraries, comparator);
                } else if (builder.libraryComparator != null) {
                    Collections.sort(libraries, builder.libraryComparator);
                }
            }
```

My project is a multi-apk projekt (different applicationIds). It uses gradle sourceSets. In the "main" Source Set the library is working correct. In the others I have the mentioned problem. Could this be a gradle configuration issue?

I use proguard for release builds - the problem occurs also on debug builds. I have defined an applicationId in my gradle file.

**Comment by mikepenz** [comment]
@kiezkicker if it is already size == 0 in that place you pasted here. The preparation inside the `Libs` calss resulted in 0 libraries.

That can be due to the fact that you have defined an applicationId in your build.gradle. So it is not able to automatically detect the `R` class. 

If this is the case you have to provide the `R` fields here:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L70

Also keep in mind that the AboutLibraries caches the found libraries per version in the `SharedPreferences` so if there were none found once (and you add the `R` fields now) it will still return size 0
(https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/Libs.java#L204)

**Comment by xiaobailong24** [comment]
Hello, I try to use it to get the fragment in Fragment, then i get an error that the method `fragment()` cannot be resolved. And I search for the `fragment` in the `LibsBuilder.java`, I cannot find that. Thank you.

```
@TargetApi(Build.VERSION_CODES.HONEYCOMB)
    public static class AboutPreferenceFragment extends PreferenceFragment {
        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

            LibsFragment fragment = new LibsBuilder()
                    //Pass the fields of your application to the lib so it can find all external lib information
                    .withFields(R.string.class.getFields())
                    //get the fragment
                    .fragment();
        }
}
```

**Comment by kiezkicker** [comment]
@mikepenz it is working with the withFields-Method! Thanks a lot!
