### ISSUE TITLE
Issues with colors and padding

### ISSUE THREAD

**Issue by fncapps** [mikepenz/AboutLibraries#220]
Hi, I've just started setting up your library and some issues which I cannot solve came up:

1. In the screenshot below, I don't know why the home indicator doesn't show in white. I'm using `.withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)` and any of the other options make it white.

2. Also in the screenshot you can see there is more padding in the right side than in the left side of the screen. Is it possible to fix this?

![screen](https://cloud.githubusercontent.com/assets/9203317/15808528/c8716fc4-2b79-11e6-8e45-136012227874.png)

Thanks in advance

**Comment by mikepenz** [comment]
@fncapps do you overwrite any dimensions or any styles from the `AboutLibraries`?

**Comment by fncapps** [comment]
I don't overwrite any of them to my knowledge. I'm starting the activity like this:
```
    new LibsBuilder()
            .withFields(R.string.class.getFields())
            .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
            .withActivityTitle("TEST")
            .withActivityTheme(R.style.CustomTheme)
            .withAboutIconShown(false)
            .withAboutVersionShown(false)
            .withLicenseShown(true)
            .start(getActivity());
```

**Comment by mikepenz** [comment]
@fncapps your `CustomTheme` also has to be correct, if this one is not with `DarkToolbar` the `ActivityStyle` can't change everything for you

**Comment by fncapps** [comment]
`CustomTheme` has MaterialDrawerTheme.Light.DarkToolbar` as parent which I believe is also yours. I'll leave you the XML here:


    <style name="CustomTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
        
        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryDark">@color/color_primary_dark</item>
        <item name="colorAccent">@color/color_accent</item>

        
        <item name="material_drawer_background">@color/color_drawer_bkg</item>
        <item name="material_drawer_selected">@color/color_drawer_selected_bkg</item> 
        <item name="material_drawer_selected_text">@color/color_drawer_selected_text</item> 
        <item name="material_drawer_header_selection_text">@color/color_drawer_header_selected_bkg</item> 


        <item name="colorControlNormal">@color/color_primary_dark</item>
        <item name="colorControlActivated">@color/color_accent</item>
        <item name="colorControlHighlight">@color/color_primary</item>
        <item name="colorButtonNormal">@color/color_primary</item>

        <item name="windowActionModeOverlay">true</item>
        <item name="android:windowBackground">@color/view_background</item>
        <item name="android:actionModeBackground">@color/color_primary</item>

    </style>

**Comment by fncapps** [comment]
Sorry @mikepenz, was my fault. I changed that theme to:

    <style name="LicensesTheme" parent="AboutLibrariesTheme.Light.DarkToolbar">

        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryDark">@color/color_primary_dark</item>
        <item name="colorAccent">@color/color_accent</item>
        <item name="android:windowBackground">@color/view_background</item>

    </style>

Now all the colors are shown correctly. The padding still being wrong, any way to fix that?

**Comment by mikepenz** [comment]
@fncapps ok great at least this works. 
But you explicitly set the background color so?

The padding is set here: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/fragment_opensource.xml#L9 (the same for all sides but the bottom)
And no other padding anywhere. So it has to be the same on both sides. (As of the code)

**Comment by fncapps** [comment]
I'm setting the background color with `<item name="android:windowBackground">@color/view_background</item>` as shown in the theme above. It I add `<item name="colorControlNormal">COLOR</item>` the scrollbars color will change, but so will do the arrow... is there any way I could change the scrollbars color or instead just hide them?

Ok, the padding is alright. The cards don't seem to be centered because of the scrollbars in the right side.

**Comment by mikepenz** [comment]
@fncapps you can hook into the ui creation with the `LibsConfiguration` 

If you put the following (before) creating the `AboutLibraries` it will remove the scrollbar

```java
LibsConfiguration.getInstance().setUiListener(new LibsConfiguration.LibsUIListener() {
            @Override
            public View preOnCreateView(View view) {
                return view;
            }

            @Override
            public View postOnCreateView(View view) {
                RecyclerView rv = ((RecyclerView) view.findViewById(com.mikepenz.aboutlibraries.R.id.cardListView));
                rv.setVerticalScrollBarEnabled(false);
                rv.setHorizontalScrollBarEnabled(false);
                return view;
            }
        });
```

**Comment by fncapps** [comment]
@mikepenz That works great! Thanks!
