### ISSUE TITLE
LibsFragment fragment = new LibsBuilder()... not working

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/AboutLibraries#230]
My issue is similar to [this](https://github.com/mikepenz/AboutLibraries/issues/173). However, I have been using the latest 5.7.1 dependency.

the IDE highlights the 
> cannot resolve the method 'fragment()'

So here is the code I posted in my project.

```java
LibsFragment AboutFragment = new LibsBuilder()
                .withLibraries("Butterknife", "Retrofit", "glide", "Calligraphy", "Gson")
                .withActivityStyle(Libs.ActivityStyle.DARK)
                .withVersionShown(false)
                .withLicenseShown(false)
                .withListener(libsListener)
                .fragment();

        getFragmentManager().beginTransaction()
                .replace(R.id.acpr_fragment_container, AboutFragment)
                .commit();
```
Am I missing something?

p.s.: not posting any code related to libsListener. Simply makes this issue too big. No problems with libsListener.

Regards

**Comment by mikepenz** [comment]
@CeJienAJPC there is only the method `supportFragment()` 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L544

Do you really need the normal "non" support v4 fragment?

**Comment by mikepenz** [comment]
If you want a normal `Fragment` use the following:
https://github.com/mikepenz/AboutLibraries/blob/742af897d06987e26f5903545dec0446b50b4886/library/src/main/java/com/mikepenz/aboutlibraries/LibsCompat.java

**Comment by CeJienAJPC** [comment]
Thank you for the response. SupportFragment is good enough
