### ISSUE TITLE
.withActivityStyle() not working

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/AboutLibraries#231]
Due to issue #230, I continued using the
> LibsSupportFragment

Things are working fine as expected except for `.withActivityStyle()`.

My my activities extend `AppCompatActivity` and use the parent theme `Theme.AppCompat.DayNight.NoActionBar`. I tried using the options `Libs.ActivityStyle.LIGHT_DARK_TOOLBAR` and the `Libs.ActivityStyle.DARK` for `.withActivityStyle()`. Unfortunately, the result is always displayed in Light theme.

The day and night modes in the rest of the app are working properly. Even the background of fragment container which holds the `AboutLibraries` fragment swaps between day and night modes as expected.

Tried using corresponding colors (as mentioned in [wiki)](https://github.com/mikepenz/AboutLibraries/wiki) in colors.xml. Yet no effect. No sure what's wrong. And BTW why is it not possible to add custom styles (like `.withActivityStyle(R.style.###)`) Any suggestion/help would be appreciated

Regards

**Comment by mikepenz** [comment]
@CeJienAJPC if you use the `fragment` from the `LibsBuilder` it doesn't use the theme as this makes no sense. 

The fragment is embedded in your activity so you should define the activity style on your own.

If you can't use a `AboutLibraries` style as your activity style you should add the `AboutLibrary` style attributes to your theme:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/styles.xml#L14

**Comment by CeJienAJPC** [comment]
Sorry for getting back late.

my bad. Didn't try using custom Theme for the Preferences Activity. Working as expected. Thanks for the response.

Regards
