### ISSUE TITLE
using onLibraryContentClicked() {} to open the URL in WebView

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/AboutLibraries#232]
Clicking the cards containing the License information triggers an Intent. Choosing the browser from the available options opens the library's corresponding URL in the browser.

Since my project already uses a WebView, I would like to know how to open the selected Library's URL in a webView. I just need to pass the URL  to the WebView's activity. Where can I get access to the URL of the library?

Regards

**Comment by mikepenz** [comment]
You can define a `LibsListener` as shown here:
https://github.com/mikepenz/AboutLibraries/blob/72bbacaa001febf93c24199eef766b91c50834dd/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L76

Defined here:
https://github.com/mikepenz/AboutLibraries/blob/72bbacaa001febf93c24199eef766b91c50834dd/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L133

and when the bottom is clicked the callback here:
https://github.com/mikepenz/AboutLibraries/blob/72bbacaa001febf93c24199eef766b91c50834dd/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L150

Which comes with the `Library` object which contains the url

**Comment by CeJienAJPC** [comment]
Yes, i am already using the `LibsListener`. My question was where/how to get the URL of the corresponding library I clicked? My apologies, the question wasn't elaborate (didn't mention anything about using the LibsListener).

If I want to use the method `onLibraryContentClicked(View v, Library library){}` in `LibsListener` this would be code

```
    @Override
    public boolean onLibraryContentClicked(View v, Library library) {
        Intent intent = new Intent(PreferencesExtendedActivity.this, BrowserActivity.class);
        intent.putExtra("PutExtra_URL", "LibraryURL");
        startActivity(intent);
        return true;
    }
```

using `putExtra` I pass the URL from Preferences activity to the Browser activity. In Browser activity I open the URL using the WebView fragment. In order to pass the URL using `putExtra`, I need the address. The parameters available are `View v`, `Library library` and finally the `Libs.SpecialButton specialButton`.

Hence, my question. Where/how to fetch the URL info of the library?

**Comment by mikepenz** [comment]
Either from here from the `Library` object:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/entity/Library.java#L87

or here:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/entity/Library.java#L111

depending on which information is defined or available for a specific library.
