### ISSUE TITLE
Cutom library..

### ISSUE THREAD

**Issue by SuSandiWai** [mikepenz/AboutLibraries#236]
I tried custom library which extends your library but can only get about library for 
  compile 'com.mikepenz:iconics-core:2.6.6@aar'
  compile 'com.mikepenz:fastadapter:1.6.0@aar' 
above two. Can't get about for other libraries. Can you help me for this?

**Comment by mikepenz** [comment]
@SuSandiWai I am not quite sure what you mean? Some libraries are not displayed or what's the issue? 

Do you use proguard: https://github.com/mikepenz/AboutLibraries#proguard ?

Do you have a custom `applicationId` set or anything which may prevent the automatic `R` field detection. 

You may provide the `R` fields programatically like this:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L64

If you obfuscate code it may can't auto-detect libs so you then have to define them:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L91
Passing their identifiers. A list of all included definition files is here: https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values 

The identifier is the part after the `define_int_`
For example here: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_alexei_strings.xml#L4
