### ISSUE TITLE
Scroll EdgeEffect color in LibsActivity always blue

### ISSUE THREAD

**Issue by Jawnnypoo** [mikepenz/AboutLibraries#237]
There should probably be a way to customize the scroll edge effect, since the blue may look harsh with other color schemes. Looks like this may provide a solution

http://stackoverflow.com/questions/27104521/android-lollipop-scrollview-edge-effect-color

One of the solutions there mentions how to change the edge effect programatically via reflection. Thoughts?

**Comment by Jawnnypoo** [comment]
I suppose this is resolvable if you initiate the activity with a theme with the proper attributes. Just curious if this would be something worth fixing since you can presently customize the toolbar and status bar colors manually

**Comment by Jawnnypoo** [comment]
Yeah, nvm, I think with the fact that you can just set this up with a theme, no need for this

**Comment by mikepenz** [comment]
@Jawnnypoo if you still need to do something like this programatically. There is always the possibility by providing a `LibsUiListener` 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L414

Which allows you to hook into the view creation for the fragment. Allowing you to access the `RecyclerView`

**Comment by Jawnnypoo** [comment]
Ahh, very nice! Thanks a bunch for answering this. Appreciate this lib!

**Comment by mikepenz** [comment]
No problem ;). Thank you
