### ISSUE TITLE
LibsActivity leaked 61KB

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#238]
LeakCanary
- com.mikepenz.aboutlibraries.ui.LibsActivity has leaked:
- GC ROOT static android.os.UserManager.sInstance
- references android.os.UserManager.mContext
- references android.app.ContextImpl.mOuterContext
- leaks com.mikepenz.aboutlibraries.ui.LibsActivity instance

Details:
- Class android.os.UserManager

|   static DISALLOW_ADJUST_VOLUME = java.lang.String@1869326016 (0x6f6ba6c0)
|   static DISALLOW_CONFIG_BLUETOOTH = java.lang.String@1869326104 (0x6f6ba718)
|   static DISALLOW_SAFE_BOOT = java.lang.String@1869327352 (0x6f6babf8)
|   static sInstance = android.os.UserManager@321253488 (0x1325f070)
|   static DISALLOW_CONFIG_WIFI = java.lang.String@1869326472 (0x6f6ba888)
|   static ALLOW_PARENT_PROFILE_APP_LINKING = java.lang.String@1869038592 (0x6f674400)
|   static DISALLOW_SMS = java.lang.String@1869327448 (0x6f6bac58)
|   static DISALLOW_WALLPAPER = java.lang.String@1869327648 (0x6f6bad20)
|   static DISALLOW_FUN = java.lang.String@1869326808 (0x6f6ba9d8)
|   static DISALLOW_ADD_USER = java.lang.String@1869325976 (0x6f6ba698)
|   static DISALLOW_DEBUGGING_FEATURES = java.lang.String@1869326696 (0x6f6ba968)
|   static DISALLOW_SHARE_LOCATION = java.lang.String@1869327392 (0x6f6bac20)
|   static DISALLOW_CROSS_PROFILE_COPY_PASTE = java.lang.String@1869326624 (0x6f6ba920)
|   static DISALLOW_RECORD_AUDIO = java.lang.String@1869327256 (0x6f6bab98)
|   static DISALLOW_CONFIG_MOBILE_NETWORKS = java.lang.String@1869326296 (0x6f6ba7d8)
|   static DISALLOW_CONFIG_CELL_BROADCASTS = java.lang.String@1869326160 (0x6f6ba750)
|   static DISALLOW_CREATE_WINDOWS = java.lang.String@1869326568 (0x6f6ba8e8)
|   static DISALLOW_APPS_CONTROL = java.lang.String@1869326520 (0x6f6ba8b8)
|   static TAG = java.lang.String@1869005856 (0x6f66c420)
|   static DISALLOW_CONFIG_VPN = java.lang.String@1869326424 (0x6f6ba858)
|   static DISALLOW_REMOVE_USER = java.lang.String@1869327304 (0x6f6babc8)
|   static DISALLOW_INSTALL_APPS = java.lang.String@1869326840 (0x6f6ba9f8)
|   static DISALLOW_UNMUTE_MICROPHONE = java.lang.String@1869327536 (0x6f6bacb0)
|   static DISALLOW_CONFIG_TETHERING = java.lang.String@1869326368 (0x6f6ba820)
|   static KEY_RESTRICTIONS_PENDING = java.lang.String@1869407304 (0x6f6ce448)
|   static ENSURE_VERIFY_APPS = java.lang.String@1869233952 (0x6f6a3f20)
|   static $staticOverhead = byte[312]@1873721977 (0x6faeba79)
|   static PIN_VERIFICATION_FAILED_INCORRECT = -3
|   static DISALLOW_USB_FILE_TRANSFER = java.lang.String@1869327592 (0x6f6bace8)
|   static DISALLOW_MOUNT_PHYSICAL_MEDIA = java.lang.String@1869327200 (0x6f6bab60)
|   static DISALLOW_MODIFY_ACCOUNTS = java.lang.String@1869326960 (0x6f6baa70)
|   static DISALLOW_INSTALL_UNKNOWN_SOURCES = java.lang.String@1869326888 (0x6f6baa28)
|   static PIN_VERIFICATION_FAILED_NOT_SET = -2
|   static DISALLOW_OUTGOING_BEAM = java.lang.String@1869327064 (0x6f6baad8)
|   static PIN_VERIFICATION_SUCCESS = -1
|   static DISALLOW_CONFIG_CREDENTIALS = java.lang.String@1869326232 (0x6f6ba798)
|   static DISALLOW_UNINSTALL_APPS = java.lang.String@1869327480 (0x6f6bac78)
|   static DISALLOW_OUTGOING_CALLS = java.lang.String@1869327112 (0x6f6bab08)
|   static DISALLOW_NETWORK_RESET = java.lang.String@1869327016 (0x6f6baaa8)
|   static DISALLOW_FACTORY_RESET = java.lang.String@1869326760 (0x6f6ba9a8)

- Instance of android.os.UserManager

|   static DISALLOW_ADJUST_VOLUME = java.lang.String@1869326016 (0x6f6ba6c0)
|   static DISALLOW_CONFIG_BLUETOOTH = java.lang.String@1869326104 (0x6f6ba718)
|   static DISALLOW_SAFE_BOOT = java.lang.String@1869327352 (0x6f6babf8)
|   static sInstance = android.os.UserManager@321253488 (0x1325f070)
|   static DISALLOW_CONFIG_WIFI = java.lang.String@1869326472 (0x6f6ba888)
|   static ALLOW_PARENT_PROFILE_APP_LINKING = java.lang.String@1869038592 (0x6f674400)
|   static DISALLOW_SMS =

**Comment by mikepenz** [comment]
@Rainer-Lang what do you define in your `LibsConfiguration`?

**Comment by mikepenz** [comment]
@Rainer-Lang please provide the information how you define and create your `LibsBuilder` and what you configure via the `LibsConfiguration`

**Comment by Rainer-Lang** [comment]
On Wednesday when I'm back.

**Comment by mikepenz** [comment]
@Rainer-Lang any updates?

**Comment by mikepenz** [comment]
I am not able to see anything which could leak the context inside the `LibsActivity` nothing static defined neither anything else which could cause this. 
The same for all other classes nothing which could hold the context is kept static.

**Comment by mikepenz** [comment]
@ankitbatra11 do you use the `LibsConfiguration` too?

**Comment by ronaldsmartin** [comment]
Hi @mikepenz, thanks for making this library. I am trying it out now and really like it so far.

I'm also encountering this leak report via LeakCanary as in issue #241. I've been able to trigger it on occasion by rotating my device a lot with the Library Activity in the foreground, which suggests to me this is a class configuration change-caused `AsyncTask` leak.

My instantiation looks like this so far (using Kotlin):

```kotlin
    LibsBuilder()
                .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                .withActivityTitle(resources.getString(R.string.about))
                .withLicenseShown(true)
                .withAboutAppName(appName)
                .withAboutIconShown(true)
                .withAboutVersionShown(true)
                .withAboutSpecial1(resources.getString(R.string.about_button_source))
                .withAboutSpecial1Description(resources.getString(R.string.about_button_source_description))
                .withAboutSpecial2(resources.getString(R.string.about_button_rate))
                .withAboutSpecial2Description(resources.getString(R.string.about_button_rate_description))
                .start(context)
```

I peeked inside `LibsActivity` and also didn't see any obvious places where it could be leaking memory. However, I noticed in `LibsFragmentCompat` that the `LibraryTask` [is being passed the inflated view's Context](https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsFragmentCompat.java#L98). This might be the activity instance that's leaking.

**Comment by mikepenz** [comment]
@ronaldsmartin thank you for your closer look and research. I will try to eliminate this and make additional checks.

**Comment by mikepenz** [comment]
Could you please retry with the latest version. I changed something. But I was not really able to reproduce the leak with the sample app

**Comment by ronaldsmartin** [comment]
Unfortunately, I was still able to replicate the leak with v5.7.2 with rapid device rotation.

I'm working on a potential fix myself but haven't verified it yet. I'll let you know how it goes and hope to submit a pull request tonight.

**Comment by mikepenz** [comment]
@ronaldsmartin hmm weird. was never able to reproduce it with the sample on my Nexus 6P :/
thank you

**Comment by ronaldsmartin** [comment]
I think I've worked out a fix.

My first thought was to make `LibraryTask` static and use `WeakReferences` to prevent the task from leaking the passed-in `Context`, but unfortunately that didn't help.

Instead, I simply used the application Context instead of the activity Context from the view. When using this version, I've been unable to replicate the leak in my own app. It's a really simple change that avoids using a Context that's more likely to be destroyed.

Should I submit a pull request? https://github.com/mikepenz/AboutLibraries/compare/develop...ronaldsmartin:bugfix-context-leak?expand=1

**Comment by mikepenz** [comment]
@ronaldsmartin oh ok I see. What I don't get is, why the leak still occurs even if I set the `Context` to null, so the task does no longer reference the context there. 

But fine :D If android is not happy with setting it to null. Let's go with the `ApplicationContext`. 

Yes please open the PR ;). So it is visible that you found the fix ;)

**Comment by mikepenz** [comment]
Should be solved thanks to @ronaldsmartin (https://github.com/mikepenz/AboutLibraries/commit/166752cfcfb9bbeb438f3bbc584ce040163d65f2) in the next release

**Comment by ronaldsmartin** [comment]
If I understand correctly, even though `LibsFragmentCompat`'s reference to the context is set to null, the `LibraryTask` is still holding onto its own reference for that same context (the one set in its constructor).

These situations are inherently complex, so I might be off the mark! Hopefully this fixes the issue, though.

Thanks again for your hard work in this library and for actively working to resolve this!

**Comment by mikepenz** [comment]
@ronaldsmartin will release the update later today.

Yeah for the `Context` I have added this: https://github.com/mikepenz/AboutLibraries/commit/d74a73b2649e48c563a5da6affe440cdddeeb221#diff-9cd1826525cb325600b1ae16c978cc2eR128 but seems to be not enough

**Comment by Anty0** [comment]
This is not leak in AboutLibraries and can't be fixed from this library, it is leak in system Android. [https://code.google.com/p/android/issues/detail?id=173789](https://code.google.com/p/android/issues/detail?id=173789)

This leaks first started activity to UserManager in system.
To fix this leak you should add this few lines to your application:

    public class ApplicationBase extends Application {

        @Override
        public void onCreate() {
            super.onCreate();
            if (Build.VERSION.SDK_INT > 17) {
                try {
                    UserManager.class.getMethod("get", Context.class).invoke(null, this);//fixes system leak in android
                } catch (Exception ignored) {
                }
            }

            LeakCanary.install(this);
        }
    }

Sorry for my English :)

**Comment by mikepenz** [comment]
@Anty0 the latest commit already improved this, but you could be right that something else is adding to this issue. 

Thank you for adding this here.
