### ISSUE TITLE
Memory Leak Detected

### ISSUE THREAD

**Issue by ankitbatra11** [mikepenz/AboutLibraries#241]
Hi,

Thanks for coming up with this useful library. I would like to report a memory leak that [LeakCanary](https://github.com/square/leakcanary) library found with AboutLibraries. Here are the details:
![screenshot_20160809-233954](https://cloud.githubusercontent.com/assets/7021351/17527838/91f69f48-5e8a-11e6-91a3-1c9c31512b0e.png)

**Comment by mikepenz** [comment]
@ankitbatra11 any additional details about your setup? Do you use the `LibsConfiguration`?

**Comment by ankitbatra11** [comment]
I launch the LibsActivity using following code:

ThemeSetting themeSetting = DaggerUtils
                .getSettingsComponent(getActivity().getApplication())
                .themeSetting();
        LibsBuilder builder = new LibsBuilder()
                .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                .withLicenseShown(true)
                .withVersionShown(true)
                .withAboutIconShown(true)
                .withActivityTheme(themeSetting.getThemeRes())
                .withAboutDescription(getString(R.string.app_name));
        builder.activityTitle = getString(R.string.about);
        builder.start(getContext());

Code is trigged on press of a menu item in settings fragment.

**Comment by mikepenz** [comment]
Seems to be related to: https://github.com/mikepenz/AboutLibraries/issues/238
