### ISSUE TITLE
AboutLibraries doesn't always show the right license

### ISSUE THREAD

**Issue by Namnodorel** [mikepenz/AboutLibraries#242]
For example I use Jsoup in my Android App. AboutLibraries shows it is published under the Apache 2.0 license although it actually is published under the MIT license.

**Comment by mikepenz** [comment]
@Namnodorel that can happen if the license was changed by time, or the user who added the lib choose the wrong library. Please create a pull request and update the library if it's license was changed. 

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_jsoup_strings.xml#L19
