### ISSUE TITLE
Include Kotlin?

### ISSUE THREAD

**Issue by rubengees** [mikepenz/AboutLibraries#246]
I am currently working on a new application which I write in [Kotlin](https://kotlinlang.org/). Should we include it as a library? It is not a library, but a language, but I think it could be relevant. What do you think? If you are positive about including I could do a PR with it and some other libs I use.

**Comment by Rainer-Lang** [comment]
For my understanding - no.

**Comment by mikepenz** [comment]
@rubengees I don't think it needs to be added as library. But you can still create the definition file for your application and just have it displayed in your app.
