### ISSUE TITLE
Package proguard rules with library

### ISSUE THREAD

**Issue by jaredsburrows** [mikepenz/AboutLibraries#252]
Can you put your proguard rules here: https://github.com/mikepenz/AboutLibraries#proguard in the AAR itself?

Similar to https://github.com/JakeWharton/butterknife/blob/master/butterknife/build.gradle#L11.

**Comment by mikepenz** [comment]
@jaredsburrows no not really, as I don't want to force all users of the lib to go with a not obfuscated `R` class. 

Those people can still use the lib without the proguard rule and define the libs manually.

**Comment by Jawnnypoo** [comment]
I think it would be nice to make a note of this issue in the README so that others don't go about requesting or attempting to add this.
