### ISSUE TITLE
Can't change toolbar and status bar color even after using withActivityColor()

### ISSUE THREAD

**Issue by mddanishansari** [mikepenz/AboutLibraries#257]
Ok the problem is I'm not able to change the colors of toolbar and status bar even after using
```java
withActivityColor(new Color(R.color.md_grey_900,R.color.md_black));
```

This is my code snippet
```java
new LibsBuilder()
.withAboutAppName(getResources().getString(R.string.app_name))
.withAboutIconShown(true)
.withActivityTitle(getResources().getString(R.string.nav_implemented_libraries))
.withAboutVersionShown(true)withActivityColor(new Colors(R.color.md_red_500, R.color.md_green_500))
.start(HomeActivity.this);
```
This is how the default toolbar and status bar looks in my app.

![screenshot_2016-09-25-17-25-51-707_com md recipedia](https://cloud.githubusercontent.com/assets/11080523/18815170/207d4a2a-8346-11e6-9f9e-c5da82fff91c.png)

If I use 

```javas
withActivityColor(new Color(R.color.md_grey_900,R.color.md_black));
```

![screenshot_2016-09-25-17-25-58-211_com md recipedia](https://cloud.githubusercontent.com/assets/11080523/18815171/2081b8ee-8346-11e6-94d1-ed1e89687d50.png)

If I don't use any method

![screenshot_2016-09-25-17-27-02-118_com md recipedia](https://cloud.githubusercontent.com/assets/11080523/18815169/207bb674-8346-11e6-92ef-ee297e751854.png)

So what's the issue.

**Comment by mikepenz** [comment]
@mddanishansari the `AboutLibrary` activity will have the color you define. You can see the implementation here: 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.java#L72

The `Colors` object takes `int` colors:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/util/Colors.java#L14

You provide a ressource which wont work
