### ISSUE TITLE
"about_libraries_window_background" not working properly

### ISSUE THREAD

**Issue by ste23droid** [mikepenz/AboutLibraries#258]
Hi,
I can't change the background activity color even when I set "about_libraries_window_background"; it seems like that the color chosen is ignored. Here is how i'm using it:

**STARTING THE ACTIVITY**
```java
new LibsBuilder()
                    .withActivityTheme(R.style.AppTheme)
                    .withAutoDetect(true)
                    .withVersionShown(true)
                    .withLicenseShown(true)
                    .withLicenseDialog(false)
                    .withActivityTitle("Libraries")
                    .start(StartingActivity);
```

**CUSTOM THEME**
The AppTheme is a style with 

> Theme.AppCompat.Light.DarkActionBar

 as parent
```xml
<item name="windowNoTitle">true</item>
  <item name="windowActionBar">false</item>

        <item name="colorPrimary">#2196F3</item>
        <item name="colorPrimaryDark">#1976D2</item>
        <item name="colorAccent">#536DFE</item>
       
        <item name="colorControlNormal">@android:color/white</item>
        <!-- needed in order to have the Toolbar's title white instead of black -->
        <item name="android:textColorPrimary">@android:color/white</item>

        <!-- AboutLibraries specific values -->
        <item name="about_libraries_window_background">#9C27B0</item> <!-- a violet color -->
        <item name="about_libraries_card">#FFC107</item>
        <item name="about_libraries_title_openSource">#2196F3</item>
        <item name="about_libraries_text_openSource">#727272</item>
        <item name="about_libraries_dividerLight_openSource">#EEEEEE</item>
```

I am using aboutlibraries:5.8.1, compileSdkVersion 24, buildToolsVersion "24.0.1".

![device-2016-09-25-213425](https://cloud.githubusercontent.com/assets/11226457/18817740/5ea6b86e-8368-11e6-8ba0-861c6c16bc4d.png)

Am I doing something wrong here?

**Comment by mikepenz** [comment]
Yes you are right. :O

Please just use the android default way of setting the window background:

http://stackoverflow.com/a/11441392/325479

**Comment by ste23droid** [comment]
Thanks, I've just tested and using this works in the style works fine :) `<item name="android:windowBackground">@color/custom_color</item>`

**Comment by 7172** [comment]
I got one ques is libraries is what what is the correct point it pol need it that why that dont make it provided easyly


Sent from my Samsung device

-------- Original message --------

**Comment by 7172** [comment]
Hi mikepenz/AboutLibrar,

I'd like to add you to my professional network on LinkedIn.

- Waqas

Confirm that you know Waqas: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Bj4jx36W&invitationId=6189783536824836099&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eityd373s%7E6y








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ityd373s-6y&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHvd1FncNZXEgAAAVeaHpjUDOkw9w8EXV281gSh3prNmKkVSNoQV5HoXGFMp2svo-JlKT5FGumWAMzzEqJWvyDcqQvVBKBZXIbaCXcuNrvnjszVIZKg_DpE9TDgyuLIfS9Nd4dON_KykwOJQ9o78kzfxdzAKQdpDxDe3LsN5Yhi_bI9AMcRhhccTNx1HC_6Vqzy&eid=0-ityd373s-6y


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ityd373s-6y&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by 7172** [comment]
Waqas Khan would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Bj4jx36W&invitationId=6189783536824836099&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-c1wjru%7Eiu6ew2t6%7Eaz

View Waqas Khan&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Bj4jx36W&invitationId=6189783536824836099&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-c1wjru%7Eiu6ew2t6%7Eaz





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=c1wjru-iu6ew2t6-az&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=c1wjru-iu6ew2t6-az&loid=AQFVXWiAi0JEDgAAAVe4YP1qqnxJKGTCi1O3GMwgWs8pDwnJEbiLaV34BNLKD_bqDkpcKX8TIWMjJ5mONzSfQL_I5tGWIwem2PaRLKxlAK3WwS0Xa6c3pV051pZMzykkDPM7x_NwGGeBqE-coAOsO9w5GoIP_Qs9er4YG7txmcq8ZGOsqWB46Wld8BZEa8ugtbDM

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=c1wjru-iu6ew2t6-az&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by 7172** [comment]
Hi ,

Waqas Khan would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Bj4jx36W&invitationId=6189783536824836099&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-c1wjru%7Eiugexm61%7Eey

View Waqas Khan&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Bj4jx36W&invitationId=6189783536824836099&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-c1wjru%7Eiugexm61%7Eey





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=c1wjru-iugexm61-ey&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=c1wjru-iugexm61-ey&loid=AQHzROBsucVBSAAAAVfb9r_JIBrJwJXV4yKiYfKnu3gZEASrBl_tqyY_idl-U2XpBG50nC-3XopyCUjsafBwyGjisOlc7YBS3BLPXd8QB0pMwx6-Eq1vYQLR0J8-dAokmY5xQj1qeDbUZN2BV3KrHVoF5seDWuLNJy8IHBBNe-Qzix0_VuGNA6TUdv3Xc68_tlU9

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=c1wjru-iugexm61-ey&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by roman-ku** [comment]
Jesus, I spent at least half an hour with this.

What is "about_libraries_window_background" for then?
