### ISSUE TITLE
How To Add Google Play Services License

### ISSUE THREAD

**Issue by aguragorn** [mikepenz/AboutLibraries#260]
It seems that the correct way to obtain the license for google play services is through
```java
GoogleApiAvailability.getInstance().getOpenSourceSoftwareLicenseInfo(Context);
```
based on:
http://stackoverflow.com/a/15112345
http://android-er.blogspot.com/2012/12/include-open-source-software-license.html

how could I include it in the cards of libraries?

**Comment by mikepenz** [comment]
You can't directly add them with the above method. Either you add a `definition` file as for all other libs. Or you use just the `Adapter` of the `AboutLibs` which will allow you to add your own `LibraryItem` by manually creating one and adding it to the list
