### ISSUE TITLE
Adding libraries in-code

### ISSUE THREAD

**Issue by Namnodorel** [mikepenz/AboutLibraries#264]
Ie. I got some small libraries which I want to include in the "about" section, but don't want to add them to a fork, make a pull-request etc. for each one, that would be too much work. Now I want to add these libraries in-code, like

`ALLibrary library = new Library("My coold library")
library.setAuthor("Example author");
library.setLicense(License.MIT);
etc.`

is that possible/could you implement it?

**Comment by Rainer-Lang** [comment]
Sure that you don't want to make a pr?

**Comment by Namnodorel** [comment]
It is not about a specific case, just in general. I often add some small libraries while working, and don't want to add each of them here every time I add another one.

**Comment by Namnodorel** [comment]
Also the detection doesn't always work well with the XML files. For example both ProcessPhoenix and Butterknife *should* be included automatically, but they aren't...

**Comment by Rainer-Lang** [comment]
Butterknife should be, yes. Strange. 
Maybe you could provide the libs which aren't detected.

**Comment by Namnodorel** [comment]
I can, but that's not the point. There needs to be a way to add libraries to the local project quick and easy.

**Comment by mikepenz** [comment]
@Namnodorel you can quickly and simple add libraries to your project by adding the definition file. That's the easiest thing. 

The problem of those being not detected. I can only autodetect libraries which have the classPath defined in there definition file. Proguard may also prevent autodetection, which would require you to add the libraries manually. 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L106

As of the solution when you add manual libraries and you want them to show up, no matter of what happens. 
Just define the xml like this:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_aboutlibraries_strings.xml#L4
(remove the "_int" after "define") This will result those libraries to show up all the time
