### ISSUE TITLE
Different text color in library cards and app description

### ISSUE THREAD

**Issue by fettlaus** [mikepenz/AboutLibraries#266]
I'm using `about_libraries_text_openSource` to change the color of my app description. Unfortunately `HeaderItem` and `LibraryItem` both use this attribute to style their text color. 

I need to set different colors on these texts because my Activity uses a dark background and I'd like to keep the library cards in the RecyclerView rather bright.

Is there some other way I just can't think of right now?

**Comment by mikepenz** [comment]
The only solution would be to copy and paste the layouts for those items to your project:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listheader_opensource.xml
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml

and modify the color's for these texts. 

The build will automatically overwrite the layouts from the library when the apk is created

**Comment by fettlaus** [comment]
That is not possible, because the text color gets overwritten every time by 
`aboutAppDescription = (TextView) headerView.findViewById(R.id.aboutDescription);
            aboutAppDescription.setTextColor(UIUtils.getThemeColorFromAttrOrRes(headerView.getContext(), R.attr.about_libraries_text_openSource, R.color.about_libraries_text_openSource));`
in HeaderItem.
