### ISSUE TITLE
No libs shown when using different application id

### ISSUE THREAD

**Issue by guntherhoppe** [mikepenz/AboutLibraries#270]
I have a problem when use AboutLibraries together with a different application id defined in gradle build file.

For my dev and staging environments all works fine. But for the production app it doesn't. My package as it is configured within manifest is: ch.company.android.myapp.  

The application ids in gradle are defined as:
dev : ch.company.android.myapp.dev 
stage: ch.company.android.myapp.stage 
(works!)

**prod: ch.company.mobile 
(doesn't work!)**

When I change it to e.g. "ch.company.android.myapp" it works. So I assume it has something to do with the app identifier.

Version 5.8.+

**Comment by mikepenz** [comment]
@guntherhoppe if the library is not able to automatically (via reflection) get the `R` fields of your application it won't be able to show the libs. 

You will have to pass the libs then in like this:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L81

**Comment by guntherhoppe** [comment]
Thx - works perfect! 
I tried this before, but used R.class.getFields instead of R.string.class.getFields ... My mistake. :)

**Comment by mikepenz** [comment]
Awesome :)
