### ISSUE TITLE
Scroll Listener

### ISSUE THREAD

**Issue by shanno29** [mikepenz/AboutLibraries#271]
Is it possible to observe the recyclerview in any way? I'm using your fragment variant and have a bottom bar that I would like to hide when scrolling through the list of libraries, and show when not scrolling. Excellent library by the way!

AboutLibraries/library/src/main/res/layout/fragment_opensource.xml
```
<android.support.v7.widget.RecyclerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/cardListView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    android:divider="@null"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_horizontal_margin"
    android:scrollbarStyle="outsideInset"
    android:scrollbars="vertical" />
```

**Comment by mikepenz** [comment]
That can be done for example with the `LibsUIListener` 
https://github.com/mikepenz/AboutLibraries/blob/54abd1254c71beb856533ac68146e19c6529404b/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L121

Just hook into the view creation (so after postOnCreateView)  there you are able to access the parent view which hosts the `RecyclerView`

```java
(RecyclerView) view.findViewById(R.id.cardListView)
```

**Comment by shanno29** [comment]
Thank you very much Mike!
