### ISSUE TITLE
NullPointerException when calling adapter() on LibsBuilder()

### ISSUE THREAD

**Issue by DanStout** [mikepenz/AboutLibraries#273]
Apologies if I've missed something obvious. Here is how I'm creating the adapter:

```
AbstractAdapter adap = new LibsBuilder().adapter(this);
```

This throws an exception with the cause: `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.fastadapter.FastAdapter.registerTypeInstance(com.mikepenz.fastadapter.IItem)' on a null object reference`

It seems that to me that the issue is the following in `LibsBuilder#adapter()`:

```
itemAdapter.add(libraryItems);
return itemAdapter.wrap(new FastAdapter());
```

The `ItemAdapter#add` method indirectly calls `AbstractAdapter#mapPossibleType`, which accesses the `mFastAdapter` field that is null until the `ItemAdapter#wrap` method is called on the next line of the `LibsBuilder#adapter`

Maybe those last two lines could be changed to something like this? Admittedly I haven't looked into this very closely..
```
AbstractAdapter adap = itemAdapter.wrap(new FastAdapter());
itemAdapter.add(libraryItems);
return adap;
```

**Comment by mikepenz** [comment]
@DanStout oh yes you are right. those two lines have to be switched. Thanks for the info. I will release an update with the change.
