### ISSUE TITLE
Memory Leak  with LibsConfiguration : Solved

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/AboutLibraries#275]
Hi Mike,
I am experiencing memoryLeak in LibsConfiguration.mListener and .libsListener.

![memoryleak](https://cloud.githubusercontent.com/assets/15603039/20757711/7190a486-b73d-11e6-994f-53f7a9c89475.png)

The Configuration is pretty basic.

        `LibsSupportFragment LicensesFragment = new LibsBuilder()
                .withAboutIconShown(true)
                .withAboutAppName(getResources().getString(R.string.app_name))
                .withAutoDetect(false)
                .withAboutVersionShown(true)
                .withFields(R.string.class.getFields())
                .withLibraries("aboutlibraries", "butterknife", "glide")
                .withLicenseShown(true)
                .withListener(new LibsConfiguration.LibsListener() {
                                  @Override
                                  public void onIconClicked(View v) {
                                  }

                                  @Override
                                  public boolean onLibraryAuthorClicked(View v, Library library) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onLibraryContentClicked(View v, Library library) {
                                      loadWebUrl(library.getLibraryWebsite());
                                      return true;
                                  }

                                  @Override
                                  public boolean onLibraryBottomClicked(View v, Library library) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onExtraClicked(View v, Libs.SpecialButton specialButton) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onIconLongClicked(View v) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onLibraryAuthorLongClicked(View v, Library library) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onLibraryContentLongClicked(View v, Library library) {
                                      return false;
                                  }

                                  @Override
                                  public boolean onLibraryBottomLongClicked(View v, Library library) {
                                      return false;
                                  }
                              }
                )
                .withVersionShown(false)
                .supportFragment();

        getSupportFragmentManager().beginTransaction()
                .replace(R.id.acsu_fragment_container, LicensesFragment)
                .commit();`

` loadWebUrl()` displays the URL in WebView. The leak happens soon after I backPress to Parent Activity.  The average leak size is 250 to 350 KB

Am I missing something, Mike?

**Comment by mikepenz** [comment]
@CeJienAJPC I think this would be solved if you create the listeners as static inner class within the class. or as a seperate class. if it's an annonymous inner class it will have the context which will be leaked

**Comment by CeJienAJPC** [comment]
Issue Solved. Thanks
