### ISSUE TITLE
Truncated names on cards with long title

### ISSUE THREAD

**Issue by marconealberto** [mikepenz/AboutLibraries#278]
This is an awesome library but I'm facing this simple issue:

Most of the libraries have their names truncated. How can I fix that? is there a way to have a multiline textfield in the cardview? or at least truncate only part of the last word?
One of the truncated titles is "Android SQLiteAssetHelper"

![schermata 2016-12-15 alle 11 13 44](https://cloud.githubusercontent.com/assets/779070/21220095/aa565a24-c2b7-11e6-81d2-ceb744f81c68.png)

**Comment by IonutNegru87** [comment]
I think you have to manually create the style you want and populate with the data provided by the library.

**Comment by mikepenz** [comment]
@marconealberto interesting. the text of the element itself has a weight of 5 and the lib creator name a weight of 2:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml#L27

You can overwrite this layout for your project if you want to change some things

**Comment by mikepenz** [comment]
@IonutNegru87 thanks for answering
