### ISSUE TITLE
Custom library name ,author,version

### ISSUE THREAD

**Issue by thisisPratzz** [mikepenz/AboutLibraries#281]
how to add many Custom library name ,author,version name to the list on cards in AboutActivity?

**Comment by mikepenz** [comment]
@thisisPratzz what do you mean? you want to overwrite the defined values? or you want to add your own libraries?

**Comment by thisisPratzz** [comment]
add names,description of libraries which where not included  in gradle

Eg.
app has  used libraries A,B but not used library C
Still add decription,name of  C aboutLibrary View

**Comment by mikepenz** [comment]
you can just add your own definition files to the project to add additional projects.

**Comment by mikepenz** [comment]
Like this one: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_aboutlibraries_strings.xml

**Comment by thisisPratzz** [comment]
Thank you :+1:
