### ISSUE TITLE
Add onExtraLongClick method?

### ISSUE THREAD

**Issue by ItsCalebJones** [mikepenz/AboutLibraries#283]
Any chance you'd be open to adding that?

I have a special button that directs to a Support page, would like to longClick to access a Debug menu.

**Comment by mikepenz** [comment]
@caman9119 you can add this one on your own :) Just add a `LibsUIListener` and hook into the view creation after it was done: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L131

https://github.com/mikepenz/AboutLibraries/blob/54abd1254c71beb856533ac68146e19c6529404b/library/src/main/java/com/mikepenz/aboutlibraries/LibsFragmentCompat.java#L91

There are also other listeners you could use.
