### ISSUE TITLE
Feature: custom divider

### ISSUE THREAD

**Issue by Scrounger** [mikepenz/AboutLibraries#285]
@mikepenz:
Can you please add the option for a custom divider style. Just define a style in style.xml that can be overridden and remove the option to set color by code? So it would be possible to use a drawable as divider

styles.xml;
```
    <style name="aboutlibraries_custom_divider">
        <item name="android:layout_width">1dp</item>
        <item name="android:layout_height">match_parent</item>
        <item name="android:background">@drawable/divider_vert_blue_middle</item>
    </style>
```

**Comment by mikepenz** [comment]
@Scrounger so you want to have a divider between the items? or a divider in the card? 

You can already adjust the design of the card by either overwriting the xml of one item
Copy and paste this in and adjust hte xml:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml

or you hook into the view generation with the `LibsConfiguration` via: 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L240

**Comment by Scrounger** [comment]
Overriding the layout file is easier. Just setted your diverders color to transparent and added my custom divider
