### ISSUE TITLE
Please add to AboutLibraries

### ISSUE THREAD

**Issue by Scrounger** [mikepenz/AboutLibraries#286]
@mikepenz:

Please add the apenden library files and licencse file to the rep.

[libs.zip](https://github.com/mikepenz/AboutLibraries/files/721051/libs.zip)

**Comment by Rainer-Lang** [comment]
Please make a PR. Thanks.

**Comment by Scrounger** [comment]
Still tried but it doesn'r work and i dont know why

**Comment by mikepenz** [comment]
@Rainer-Lang do you want to open a PR with the libs still missing?

**Comment by Rainer-Lang** [comment]
I don't know which libs are inside, but I'll have a look in the next days.

**Comment by Rainer-Lang** [comment]
@Scrounger I made a commit.
