### ISSUE TITLE
Add progress indicator to activity 

### ISSUE THREAD

**Issue by roman-ku** [mikepenz/AboutLibraries#289]
On my phone it takes 3-4 seconds to load the library page (not sure why so slow tbh), I would love a simple progress circle in the middle of the page.

**Comment by roman-ku** [comment]
I wanted to turn off auto detection and supply the library names myself in this fashion: https://github.com/mikepenz/AboutLibraries/issues/272#issuecomment-263132830

But it doesn't appear to work. Any ideas?

**Comment by Rainer-Lang** [comment]
Try to increase versionCode or reset app data.

**Comment by mikepenz** [comment]
@roman-ku 3-4 seconds seems really long. doesn't take so long on any phone I ever tested it on :)

have you also disabled auto detection?

**Comment by roman-ku** [comment]
I am trying to disable auto detection (using `.withAutoDetect(false)`)  but it never works. Maybe there is some requirement to using that command? I'm not sure what versionCode @Rainer-Lang is referring to and I will try to reset app data but maybe later since I don't want to lose what I have saved.

**Comment by mikepenz** [comment]
withAutoDetect(false) . will just not try to find libs via the class defined in the definition file. Libraries which include the definition files (Like FastAdapter, ...) will still show up.

**Comment by roman-ku** [comment]
Thanks for adding the progress indicator feature!
