### ISSUE TITLE
Possibility to change toolbar background using drawable

### ISSUE THREAD

**Issue by odin-** [mikepenz/AboutLibraries#295]
I would like to be able to set the toolbar background using a drawable to match my app. Would this be possible to fix?

**Comment by mikepenz** [comment]
You can hook into the view creation via the LibsConfiguration and access everything you want to

**Comment by odin-** [comment]
Excellent. Thank you for a nice lib.

**Comment by mikepenz** [comment]
with this listener you have access to the whole view: 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L131

Thank you

**Comment by odin-** [comment]
The preOnCreateView returns the RecylerView. So to get the Toolbar is in the parents parent right?

LinearLayout contains FrameLayout contains RecylerView
The LinearLayout contains the toolbar?

**Comment by mikepenz** [comment]
@odin- yeah something like this. a different solution would simply be for you to use the `Fragment` and handle the activity around on your own. Either use your own activity or base on this one:
https://github.com/mikepenz/AboutLibraries/blob/54abd1254c71beb856533ac68146e19c6529404b/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.java

**Comment by odin-** [comment]
Ah of course. That's the smart thing to do :-). More clean than trying to find parent views if you happen to change something in the future.

Thanks.
