### ISSUE TITLE
Add https://mvnrepository.com/artifact/cz.msebera.android/httpclient/4.4.1.1

### ISSUE THREAD

**Issue by odin-** [mikepenz/AboutLibraries#296]
Add support for https://mvnrepository.com/artifact/cz.msebera.android/httpclient/4.4.1.1

dependencies {
    compile 'cz.msebera.android:httpclient:4.4.1.1'
}

**Comment by mikepenz** [comment]
@odin- you can also do a PR by adding these ;)

You can use this handy online tool to do it

http://def-builder.mikepenz.com/

everything is described in the README

**Comment by odin-** [comment]
OK I'll do that for httpclient then! Thanks.
