### ISSUE TITLE
Usage of multiple instances with different content

### ISSUE THREAD

**Issue by bematthias** [mikepenz/AboutLibraries#300]
First, thank you for your helpful library. :)

I want to use multiple instances of the library in my app with different lists of libraries, but I can't achieve that.

What I would like to do...
... is having two AboutActivities in my app. One to show a couple of custom-defined libraries (no native and no auto-detected) and the about-descriptions. The second (called from the first one) should be used to show all other libraries including the auto-detected.

My approach so far:
The first Library-Activity is extending the LibsActivity:
```
setIntent(new LibsBuilder()
        // ...styling and descriptions are set here...
        .withAutoDetect(false)
        .withFields() // to suppress all default libraries
        .withLibsRecyclerViewListener(new LibsConfiguration.LibsRecyclerViewListener() {
                @Override
                public void onBindViewHolder(HeaderItem.ViewHolder headerViewHolder) {
                        // altering the product icon
                }
                @Override
                public void onBindViewHolder(LibraryItem.ViewHolder viewHolder) {  }
        })
        .intent(this));
super.onCreate(savedInstanceState);
```

On an clicked menu item in the first activity I want to create the second one:
```
new LibsBuilder()
        // ... styling again ...
        .withAboutIconShown(false)
        .withAboutVersionShownCode(false)
        .withAboutVersionShown(false)
        .withFields(R.string.class.getFields())
        .withAutoDetect(true)
        .start(this)
```

But whenever I use `.withAutoDetect(false)` and ` .withFields()` at the first creation, there will no library shown in the second one. The other changes are made correctly. 
Am I using the false approach or how can I achieve the desired behaviour?

Thank you very much in advance!

**Comment by mikepenz** [comment]
@bematthias why don't you just define libs you want to use manually in both cases? Explicit definition of libs is anyways faster 

In general it was not designed to be used multiple times, and optimized for single fragment / activity usage to be faster in this case

**Comment by bematthias** [comment]
@mikepenz I'm a little bit lazy in that case ;) and I wouldn't forget a library when I add a new one. 

So, is it at least possible to use two fragments / activities with different LibraryItems? At the moment a LibraryItem is "lost" whenever I exclude it in a previous builded instance.
