### ISSUE TITLE
Any way to disable the new loader?

### ISSUE THREAD

**Issue by Aqua-Ye** [mikepenz/AboutLibraries#311]
Hi,

I have my own implementation for that, and would like to disable the integrated loader. 
Any way to customize the loader or disable it?

**Comment by mikepenz** [comment]
@Aqua-Ye no not (yet). You can stay on the previous version which didn't have the loader, only new definitions were added but no bugfixes or so

**Comment by Aqua-Ye** [comment]
👍

**Comment by mikepenz** [comment]
new release is coming soon
