### ISSUE TITLE
What is the proper way to add undetected libraries manually?

### ISSUE THREAD

**Issue by matmedev** [mikepenz/AboutLibraries#315]
Hi,
I have some libraries in my project that are not detected by your library.
Could you show me an example to add completely unknown libraries to the list (eg. with author name and description)?

Thanks!

**Comment by mikepenz** [comment]
@matmedev have you looked if they are included in the lib, just not auto detected?
https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values

If they are not there. Just create a definition file like the ones already included. Here is a nice website helping you. https://def-builder.mikepenz.com/ and include it in your app. 
(it would be awesome if you could then also open a PR adding those missing libs to the AboutLibraries)

**Comment by matmedev** [comment]
OK. I'll try that one, Thanks!
