### ISSUE TITLE
manual Libraries not used when using default Activity

### ISSUE THREAD

**Issue by fmt-Println-MKO** [mikepenz/AboutLibraries#323]
when using the default Activity manuell added libraries are not shown

looks like, that the builder is not passed and checked in activity, like it's done in the fragment

`
new LibsBuilder()
                        .withLibraries("android_job")
                        .withAutoDetect(false)
                        .withAboutIconShown(true)
                        .withAboutVersionShown(true)
                        .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                        .withActivityTitle("Licenses")
                        .start(this) 
`

**Comment by mikepenz** [comment]
@fmt-Println-MKO can you please also provide the definition file you used for "android_job"? 
Or what would you expect to see?

**Comment by fmt-Println-MKO** [comment]
android job is included in your repo already:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_android_job_strings.xml

I just took this as an example. 
for me, only the automatic found libs are shown, all libs added manuell are not shown. 

when I checked the source code, it looks like, that in case you use a fragment, the builder (which contains the lib list) is passed as "data". but when using the activity like me, this information is lost / not passed. 
so all manual added libs are not listed in this case

**Comment by mikepenz** [comment]
@fmt-Println-MKO hmmm I can not reproduce this issue. I tried it with the sample application, and it shows up quite fine. 

Is there something in your project which possibly deletes / removes these resources?

**Comment by fmt-Println-MKO** [comment]
ah ok sorry, i missed the line where the builder is also passed to activity to fragment,
but I debugged, and android_job is not in the libraries list, so search by name would result null in there, als ahbottomnavigation ist not there. and as I used debug build, nothing should have removed the resources. strange....

**Comment by mikepenz** [comment]
you can run and check the sample app it will show up. 

It's really weird. I copy pasted your provided code, and it worked

**Comment by fmt-Println-MKO** [comment]
yes it is, 
sure I will check out whats going wrong in may app. 
thank you

**Comment by mikepenz** [comment]
thanks. Please let me know if you find something.

**Comment by mikepenz** [comment]
@fmt-Println-MKO I'll close this until further details are provided :)
