### ISSUE TITLE
Dependency collision with MaterialDrawer

### ISSUE THREAD

**Issue by kylealanr** [mikepenz/AboutLibraries#325]
Both libraries suggest setting transitive to true in the build.gradle, but when using both together different versions of FastAdapter are included.

**Comment by mikepenz** [comment]
@kylealanr oh that's true, if the versions do not have an API change, then you simply can overwrite the version to use. 

like that (adjust to the fastadapter name) 
```gradle
configurations.all {
    resolutionStrategy.force "com.android.support:support-v4:${versions.supportLib}"
}
```

If there it's a version with API change I have to provide an update. (I am planing to do this sometimes this week)
