### ISSUE TITLE
Updating wiki

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/AboutLibraries#327]
The [custom](https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Custom) portion of the wiki may need to be updated

`Libs libs = Libs.getInstance(getActivity(), R.string.class.getFields());`

no longer exists and seems to be done with 

`Libs(context)`

**Comment by mikepenz** [comment]
@AllanWang you should be able to simply update it :). The wiki is very old. Maybe I just delete it otherwise :D

**Comment by AllanWang** [comment]
Updated
