### ISSUE TITLE
[Showcase] Usage of About Libraries

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/AboutLibraries#332]
You have a section in your read me for apps using this lib, so I though I'd share my projects.

I built a kotlin library, and one of its submodules combines this lib along with Plaid's about UI. It is showcased [here](https://allanwang.github.io/KAU/about/#readme)

![About Activity Gif](https://raw.githubusercontent.com/AllanWang/Storage-Hub/master/kau/kau_about_activity.gif)

I also use my lib in my actual project, [Frost for Facebook](https://play.google.com/store/apps/details?id=com.pitchedapps.frost)

**Comment by mikepenz** [comment]
@AllanWang looks really nice :). Great work

**Comment by mikepenz** [comment]
@AllanWang please open a PR and add it to the list of projects using this lib :)

**Comment by AllanWang** [comment]
Addressed in #333
