### ISSUE TITLE
New lib compatible with AboutLibraries

### ISSUE THREAD

**Issue by zTrap** [mikepenz/AboutLibraries#334]
Thanks for this great library, and now we have definitions for `AboutLibraries` in [SlideUp](https://github.com/mancj/SlideUp-Android). Just saying and nothing more :)

**Comment by mikepenz** [comment]
@zTrap that'S awesome! :)

**Comment by mikepenz** [comment]
It's so sad that not more devs do this. 

Added your lib here:
https://github.com/mikepenz/AboutLibraries/wiki/Compatible-Libs#libs-which-are-natively-supported
