### ISSUE TITLE
Missing/Invisible AboutAppName

### ISSUE THREAD

**Issue by markusressel** [mikepenz/AboutLibraries#338]
Hey there, great library.
I have a small issue regarding the latest release (5.9.7) - the app name field is missing/invisible. The view is there but there is simply nothing shown:
![image](https://user-images.githubusercontent.com/14024504/28378062-284e47f6-6caf-11e7-934d-cc6c8c89ec42.png)

I have updated Iconics to 2.9.0 and everything works as expected, except this little thing.

This is the code that I'm using to create the page:
```
String aboutAppName = getString(R.string.powerswitch_app_name) + "\n(" + PowerSwitch.getAppBuildTime() + ")";
if (eu.power_switch.BuildConfig.DEBUG) {
    aboutAppName += "\n" + "DEBUG";
}

Fragment fragment = new LibsBuilder()
        //get the fragment
        .withAboutAppName(aboutAppName)
        .withAboutIconShown(true)
        .withAboutVersionShown(true)
        .withAboutVersionShownName(true)
        .withLicenseShown(true)
        .withVersionShown(true)
        .withAutoDetect(true)
        .withAboutDescription(getString(R.string.app_description_html))
        .withAboutSpecial1(getString(R.string.changelog))
        .withAboutSpecial1Description(getString(R.string.changelog))
        .withAboutSpecial2(getString(R.string.github))
        .withAboutSpecial2Description(getString(R.string.github))
        .withAboutSpecial3(getString(R.string.license))
        .withAboutSpecial3Description(getString(R.string.gpl_v3_description_html))
        .withListener(new LibsConfiguration.LibsListener() {
            @Override
            public void onIconClicked(View v) {
                String url = "https://power-switch.eu/";
                startActivity(ChromeCustomTabHelper.getBrowserIntent(getActivity(), url));
            }

            @Override
            public boolean onLibraryAuthorClicked(View v, Library library) {
                return false;
            }

            @Override
            public boolean onLibraryContentClicked(View v, Library library) {
                return false;
            }

            @Override
            public boolean onLibraryBottomClicked(View v, Library library) {
                return false;
            }

            @Override
            public boolean onExtraClicked(View v, Libs.SpecialButton specialButton) {
                if (specialButton == Libs.SpecialButton.SPECIAL1) {
                    String url = "https://power-switch.eu/download/";
                    startActivity(ChromeCustomTabHelper.getBrowserIntent(getActivity(), url));
                    return true;
                } else if (specialButton == Libs.SpecialButton.SPECIAL2) {
                    String url = "https://github.com/Power-Switch/PowerSwitch_Android";
                    startActivity(ChromeCustomTabHelper.getBrowserIntent(getActivity(), url));
                    return true;
                } else if (specialButton == Libs.SpecialButton.SPECIAL3) {
                    return false;
                }

                return false;
            }

            @Override
            public boolean onIconLongClicked(View v) {
                return false;
            }

            @Override
            public boolean onLibraryAuthorLongClicked(View v, Library library) {
                return false;
            }

            @Override
            public boolean onLibraryContentLongClicked(View v, Library library) {
                return false;
            }

            @Override
            public boolean onLibraryBottomLongClicked(View v, Library library) {
                return false;
            }
        })
        .supportFragment();
```

**Comment by mikepenz** [comment]
@markusressel and you did not have the issue in old versions?

**Comment by markusressel** [comment]
Hey,

I tried to test this on older versions (down to 5.9.5 until I got ClassNotFoundExceptions) and it happened on all of them. I finally tried it on a new project and realized that it's a theming issue.
When I use my light theme it is visible as expected:
![image](https://user-images.githubusercontent.com/14024504/28391249-824330e0-6cdd-11e7-8266-901f5eeb9777.png)

In my themes I am overwriting your theme values for both light and dark theme. In my tests I found that you use the primaryColor for the title text. In my app this happens to be the same color as my background color so the text is rendered in the same color as the background.

My suggestion would be to either use a different color (like textColorPrimary) or give us the ability to set this color manually with an additional theme item.

**Comment by mikepenz** [comment]
Well this color is already themed:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/item/HeaderItem.java#L273

Color id: about_libraries_text_description

Or you should also be able to use this: about_libraries_text_description and set it in your theme

**Comment by markusressel** [comment]
That fixed it 👍 
I was looking for the "about_libraries_title_description" value though.

![image](https://user-images.githubusercontent.com/14024504/28392009-7d7f8fba-6ce0-11e7-8fff-cc057770e4e7.png)

And (although I'm repeating myself) I'd like to mention that the wiki is outdated. If you don't want to update the information on there (which I can fully understand) at least put a disclaimer on the top of the pages that the info might be out of date and that the demo app has all the up to date infos (if thats the case). I was actually looking in there and found nothing about a theme value for the appName text - but as you told me now it already exists.

Thx again for this great library and your very fast response :)

**Comment by mikepenz** [comment]
@markusressel yeah true. You can add this info to the wiki please. that would be really helpful.

Thank you very much :)

**Comment by markusressel** [comment]
I did.
