### ISSUE TITLE
Can I use AboutLibraries if I want to target Android Oreo?

### ISSUE THREAD

**Issue by allowthere** [mikepenz/AboutLibraries#345]
My `build.gradle` says:

    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
     ...
     targetSdkVersion 26
     ...
     }
     dependencies {
     implementation fileTree(dir: 'libs', include: ['*.jar'])
     compile 'com.android.support:appcompat-v7:26.0.1'
     compile 'com.android.support:recyclerview-v7:26.0.1'
   
      .....

       compile('com.mikepenz:materialdrawer:5.9.5@aar') {
        transitive = true
        exclude group: "com.android.support"
      }
     compile('com.mikepenz:aboutlibraries:5.9.7@aar') {
         transitive = true
        //exclude group: "com.android.support"
     }

`gradlew assembleDebug` outputs:

    Error:Execution failed for task ':app:processDebugManifest'.
    > Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1)          from [com.android.support:appcompat-v7:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:cardview-v7:25.4.0] AndroidManifest.xml:25:13-35 value=  (25.4.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

What should I do? The only way I can get this to work is to change 'com.android.support:appcompat-v7:26.0.1' to 25.4.0 and `compileSdkVersion` to 25 and `targetSdkVersion` to 25.

Is there another way?

**Comment by mikepenz** [comment]
@allowthere sure you can. just exclude the support libraries of this project. https://stackoverflow.com/a/30649660/325479
