### ISSUE TITLE
Nested Scrolling

### ISSUE THREAD

**Issue by floschu** [mikepenz/AboutLibraries#348]
Would it be possible to have an option to enable or disable nested scrolling for the RecyclerView of the displayed libraries cards?

**Comment by mikepenz** [comment]
@floschu you can define a `LibsUIListener` on the `LibsConfiguration` accessing the views of the `AboutLibraries`:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.java#L53
