### ISSUE TITLE
Configure ProgressBar style

### ISSUE THREAD

**Issue by dariobanfi** [mikepenz/AboutLibraries#353]
I would like to configure the ProgressBar style and make it smaller.
I read the documentation and I didn't find any way to do that, from what I see here it's hardcoded to large style: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listloader_opensource.xml (assuming that's the right file I'm looking at).

Is it possible in any way and if not, is a PR welcome?

Thanks for the great library!

**Comment by mikepenz** [comment]
@dariobanfi if you want to adjust it. just copy paste this `layout` to your project and adjust it to your needs. Make sure it stays a `ProgressBar` and it's id is the same, but beside this you can adjust or style it to anything you need

**Comment by dariobanfi** [comment]
Works like a charm, thanks!
