### ISSUE TITLE
Exclude all support and play services libraries

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/AboutLibraries#354]
I would like to exclude all support and play services libraries from the about screen.
Is there a way to exclude them all at ones or do I have to do this for each library individually?

Or even better: Can I create a file with all libraries I would like to add? Then I do not have to keep the R references in my ProGuard rule.

**Comment by mikepenz** [comment]
@Cilenco you can use the `exclude` function to pass in the identifiers of the support libs:

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L120

To get them just look them up in the `definition files`

for example support-v4: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_support_v4_strings.xml#L4
`define_int_support_v4` --> identifier: `support_v4`
