### ISSUE TITLE
AndroidAnnotations not auto-detected

### ISSUE THREAD

**Issue by 10erlosh** [mikepenz/AboutLibraries#355]
Thank you for this grat library!

I'm using 6.0.1 of AboutLibraries and AndroidAnnotations does not seem to be auto-detected.

`    implementation 'org.androidannotations:androidannotations-api:4.4.0'
`

Am i missing something?
Thanks!

**Comment by mikepenz** [comment]
@10erlosh the `androidannotations` definition file does not define a `Class` which can be checked for existence:

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_androidannotations_strings.xml

Either open a PR to adjust this, or just use it's identifier so it shows up

**Comment by 10erlosh** [comment]
> or just use it's identifier so it shows up

how?

**Comment by mikepenz** [comment]
As shown in the sample here:

https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/ExtendActivity.java#L19

it's id is. `androidannotations`

**Comment by 10erlosh** [comment]
created a [PR](https://github.com/mikepenz/AboutLibraries/pull/356) (hopefully correct)

**Comment by mikepenz** [comment]
Oh sorry missed you PR. the classpath needs to point to a real java class. Sadly I can not detect a package name in java. it's only possible to check for the class.
