### ISSUE TITLE
use caching for building library info

### ISSUE THREAD

**Issue by QuadTriangle** [mikepenz/AboutLibraries#362]
I am an android beginner, currently building a small application. It was very easy to use your library.
thank you for building such a great library.

I have found that every time I open 'about activity', it takes a small amount of time to load it. as it builds library info at runtime, it's okay. but I think you are not using caching at all.  isn't it possible to detect version info, build library info and store it? if next time user open about screen for the same version, use that cached version instead of building again. 

## Details

- [x] Used library version: 6.0.2

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@QuadTriangle so there is already a mechanism built in to use it via a shared preference, per version (so if you change version it will recheck) otherwise it will be used form the shared preferences. 

In generell I anyways suggest to define the libraries manually (via their id) and disable the automatic detection. This will be the fastest as it does not need reflection and it will just use your list.

**Comment by QuadTriangle** [comment]
may be something wrong on my part
my code (with some xml definition):
```java
    private void showAbout() {
        new LibsBuilder()
                .withLibraries("aboutlibraries", "materialdialogs", "appupdater", "support_cardview",
                        "constraint_layout", "materialprogressbar", "okhttp", "okio", "design",
                        "support_v4", "appcompat_v7", "recyclerview_v7", "support_annotations",
                        "fastadapter", "androidiconics")
                .withAutoDetect(false)
                .withLicenseShown(true)
                .withActivityTheme(getAppTheme())
                .withActivityTitle(getString(R.string.about))
                .start(context);
    }
```

I will get back to you after releasing my app.

**Comment by mikepenz** [comment]
@QuadTriangle what'S the issue with this? no auto detect is done. that's correct. the adapter will load the libs via an async task to it is not blocking the ui, and when it's ready it will display (the async task in this case will finish quite fast, but still a tiny bit, just to not block the ui)

**Comment by QuadTriangle** [comment]
it does not block theUI instead it shows a spinner. auto detection on and off doesn't make huge deference. it's same. If I enable auto detection it creates a file containing 

```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<string name="autoDetectedLibraries">OkHttp;appcompat_v7;constraint_layout;design;materialdialogs;materialprogressbar;okio;recyclerview_v7;support_annotations;support_cardview;support_v4</string>
</map>
```

so I think it spends most of the time collecting author names, licenses, website urls etc.

**Comment by mikepenz** [comment]
well it is a async task. the android system defines . a lower priority for those, so it can take a short bit while until it is really starting the tasks. 

For gathering the strings. I really love to have this done during compilation time as this would be the fastest, but I guess I'd need to wait for a PR for this. as I am currently really flooded with other libs.

**Comment by QuadTriangle** [comment]
I guess it can be done using a plugin (like https://github.com/chaquo/chaquopy).  I am still fine with current version but compiles time information gathering will be better. I think I should close this issue and wait for a plugin.
