### ISSUE TITLE
Have direct button to header of license

### ISSUE THREAD

**Issue by EmmanuelMess** [mikepenz/AboutLibraries#366]
## About this issue

I notice no way to reliably obtain the license notice (what if the user cannot access the library's web page? Or there isn't a copy of the copyright notice there?).
For example, I am obligated by GNU GPL v4 section 4 (highlight added) to present a copy of the copyright notice:

> 4. Conveying Verbatim Copies.
>  You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you ***conspicuously*** and
appropriately publish on each copy an appropriate copyright notice; [...]

I would suggest adding a button that directly shows the information required to be shown by the library's license. 

Using AboutLibraries v6.0.2, support library v26.1.0.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
the library offers the license name + if the user clicks on it, it shows a popup with the license text

**Comment by EmmanuelMess** [comment]
This is your own image:
<img src="https://raw.githubusercontent.com/mikepenz/AboutLibraries/master/DEV/screenshots/screenshot2_small.png" height="300"/>
Where is the license name? Did I miss something?

**Comment by mikepenz** [comment]
@EmmanuelMess you can enable this: `.withLicenseShown(true)`

https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L72

**Comment by EmmanuelMess** [comment]
Thanks!
