### ISSUE TITLE
Translate descriptions?

### ISSUE THREAD

**Issue by mueller-ma** [mikepenz/AboutLibraries#369]
Hey,
Have you thought about making all strings except library_..._libraryDescription in the libary strings files non-translatable? And would you like to have the descriptions translated, maybe even use a web based translation system?

**Comment by mikepenz** [comment]
I think it would cause quite some overhead. currently developer can translate it by using the strings. and have them translated in their app. 

Also there are quite many files already. updating them all will be some work :D (well at least the approving part. changing to non translateable should be just a regex replace away :D)

**Comment by mueller-ma** [comment]
It might cause some overhead in this libary, but one translation here is used in all apps using this libary. I use at least two apps with this libary and sending the same translation to both apps seems to me the larger work.

**Comment by mikepenz** [comment]
I think with the current approach it will not be too good to have the translation in here. 

we might have in the future a more advanced solution. like a web based translation system as you say. and a gradle plugin which will do more work during compilation time. 

But that's not available right now. and I find no time to do it. perhaps some contributor at some time

**Comment by wangpung12** [comment]
ดีคับ
