### ISSUE TITLE
Are you deleting the old SharedPrefs?

### ISSUE THREAD

**Issue by EmmanuelMess** [mikepenz/AboutLibraries#371]
Here:
https://github.com/mikepenz/AboutLibraries/blob/34d3ce10330d22198702b60edb7951cd95fc5b95/library/src/main/java/com/mikepenz/aboutlibraries/Libs.java#L204

You are saving a SharedPreference String for each app version, are you deleting old ones? If so where? If not, why not?

**Comment by mikepenz** [comment]
@EmmanuelMess that never got implemented. As it is not too much of a size. But I would gladly take a PR to improve this ;) 

Closing this. Feel free to open a PR if you wanna improve this ;)
