### ISSUE TITLE
Version 6.0.3 causes build error on LGPL2.1 document.

### ISSUE THREAD

**Issue by masahiro-ikemoto** [mikepenz/AboutLibraries#372]
The error is:

> .../build/intermediates/res/merged/debug/values/values.xml:6076: error: Apostrophe not preceded by \ (in GNU LESSER GENERAL PUBLIC LICENSE&lt;br /&gt;...)
> FAILED
> FAILURE: Build failed with an exception.
> &lowast; What went wrong:
> Execution failed for task ':app:android:Personary:processDebugResources'.
> &gt; com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by mikepenz** [comment]
@masahiro-ikemoto I don't even have such a document in my library

**Comment by mikepenz** [comment]
oh I do :D

**Comment by mikepenz** [comment]
Sorry for the first comment. totally got confused with the other open source project :D

**Comment by masahiro-ikemoto** [comment]
I found new version 6.0.4, but it seems that license_lgpl_2_1_strings.xml still includes apostrophe not preceded by backslash.

**Comment by mikepenz** [comment]
Thanks again. 

Will be fixed in v6.0.5
