### ISSUE TITLE
Version 6.0.3-6.0.4 causes build error on LGPL2.1 document (repost).

### ISSUE THREAD

**Issue by masahiro-ikemoto** [mikepenz/AboutLibraries#373]
I posted an issue #372, but Mike said 'Fix issues (which magically disappeared)' in releases page.
I've already add comment to Issue #372, but Mike might not see it?

So I'll repost issue, because I still have build error on version 6.0.4.

The error is:

> .../build/intermediates/res/merged/debug/values/values.xml:6076: error: Apostrophe not preceded by \ (in GNU LESSER GENERAL PUBLIC LICENSE&lt;br /&gt;...)
> FAILED
> FAILURE: Build failed with an exception.
> &lowast; What went wrong:
> Execution failed for task ':app:android:Personary:processDebugResources'.
> &gt; com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by mikepenz** [comment]
@masahiro-ikemoto oh my god. I guess the weird `caching` of the github homepage fooled me. 

Sorry. 

I'd definitely love to figure out where this is. As you can see I replaced all apostrophes, and surrounded it with a CDATA https://github.com/mikepenz/AboutLibraries/commit/f07cc0cca41404d98a3179d8156278e41be599e3

**Comment by masahiro-ikemoto** [comment]
For example, the line 301 of 
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/license_lgpl_2_1_strings.xml
have an apostrophe that not preceded by backslash.

`modification of the work for the customer's own use and reverse`

I think it shold be quoted like following:
`modification of the work for the customer\'s own use and reverse`

And there are many other alone apostrophes in the document.

**Comment by mikepenz** [comment]
yep found them :(. Too bad I was only looking for --> " 
Sorry. Usually the build informed me when building it. Not really sure why it stopped :D

**Comment by mikepenz** [comment]
@masahiro-ikemoto can you have a quick look at the changes :D just to be safe before I release a new version

**Comment by masahiro-ikemoto** [comment]
I'll try it, wait a moment.

**Comment by mikepenz** [comment]
@masahiro-ikemoto thank you. :) will do a release after that

**Comment by masahiro-ikemoto** [comment]
I build latest repository clone, and replaced my ~/.gradle aar cache by created library-release.aar as a test.
Then, build of my app was succeed with no error, so all problems may have been fixed.

I wait for updating jcenter repository.
thanks a lot.

**Comment by mikepenz** [comment]
Thanks for reporting :)
