### ISSUE TITLE
auto detecting libraries problem

### ISSUE THREAD

**Issue by JohannesDev** [mikepenz/AboutLibraries#374]
## About this issue

- A lot of libraries are not getting auto-detected although they are supported. I added the Proguard rules
> -keep class .R
> -keep class **.R$* {
>     <fields>;
> }

and followed the wiki. 

I'm using this library in a fragment but I guess this shouldn't make any difference when it comes to auto-detecting. BTW I'm also using kotlin but I assume this should neither make a difference.
```
val fragment = LibsBuilder()
                        .withFields(R.string::class.java.fields)
                        .withVersionShown(false)
                        .withLicenseShown(true)
                        .withLibraryModification("aboutlibraries", Libs.LibraryFields.LIBRARY_NAME, "_AboutLibraries")
                        .supportFragment()

                val fragmentManager = fragmentManager
                fragmentManager?.beginTransaction()?.replace(R.id.replacer_layout, fragment)?.addToBackStack(null)?.commit()

```
I could add the libraries manually, just curious if I'm missing something.

## Details
- AboutLibraries version: 6.0.5
- support library version: 27.0.2
- Android Studio version: 3.0.1

## Checklist
- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@JohannesDev kotlin actually could make a difference. Auto detection works by checking if a class which is well known is there in the app. if yes it will show up. Obfuscation or anything else which changes the possibility to detect via reflection will break it. 

The recommended solution is anyways to define the libraries manually. as it is faster. 
You can then also disable auto detection in general. 

It could also be that some libraries do not have auto detection enabled (so no classPath defined)

**Comment by JohannesDev** [comment]
Well thanks for your quick answer. Makes a lot of sense. I will just add the libraries manually as you suggested.

Anyways thanks a lot for your awesome library.
