### ISSUE TITLE
Title style issue

### ISSUE THREAD

**Issue by nuhkoca** [mikepenz/AboutLibraries#379]
Hi Mike!

Thanks for the great lib!

So, in my project, I use the normal style for Toolbar title, but your lib seems to be bold. How do I convert it to the normal one? Thanks!

Or even better idea, how can I use a custom toolbar?

**Comment by mikepenz** [comment]
@nuhkoca you can use the `ABoutLibraries` as fragment, and embed it in your activity. This will then just be the scrolling container and the rest is up to you ;) 

https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java
