### ISSUE TITLE
Issue with different Flavor

### ISSUE THREAD

**Issue by Spettacolo83** [mikepenz/AboutLibraries#385]
## About this issue

- I have problem using different flavors in build.gradle with different packages (applicationId):

```
android {
    ...
    defaultConfig {
        applicationId "com.myapp.free"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 04
        versionName "0.4"
    }
    flavorDimensions "base"
    productFlavors {
        free {
            dimension "base"
            applicationId 'com.myapp.free'
            resValue "string", "app_name", "My App free"
        }
        full {
            dimension "base"
            applicationId 'com.myapp.full'
            resValue "string", "app_name", "My App full"
        }
    }
    ...
}
```

- Create different flavors and you can see that in the non-default flavor there is not the libraries list.
Probably something wrong when package changes.

## Details
- [6.0.8] Used library version
- [26.0.2] Used support library version
- [3.0.1] Used gradle build tools version
- [3.1.1] Used tooling / Android Studio version
- [x] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.java#L83

**Comment by mikepenz** [comment]
you have to call that method on your own then. (as the fields can not be auto resolved if the package does not match)

**Comment by Spettacolo83** [comment]
@mikepenz thank you very much for your quick reply.
May I ask you an example in order to understand which parameter needs to be passed as Field[] fields.
Thank you!

**Comment by mikepenz** [comment]
as the javadoc says `R.string.class.getFields()` (with the `R` of your project)

**Comment by Spettacolo83** [comment]
I've just tested and it works like a charm!
Thank you very much for your help!
Great library, great support!
