### ISSUE TITLE
Remove definitions for FABsMenu

### ISSUE THREAD

**Issue by flocke** [mikepenz/AboutLibraries#386]
You can remove the included definitions for FABsMenu (https://github.com/jahirfiquitiva/FABsMenu) since it already includes the definitions in the library itself. As it is now I have two entries for it:

![](https://i.imgur.com/Pk0QUiM.png)

Btw. feel free to add my project andOTP (https://github.com/andOTP/andOTP) to the list of apps that use AboutLibraries.

**Comment by mikepenz** [comment]
@flocke please open a PR :)

**Comment by flocke** [comment]
@mikepenz sure, will do.

**Comment by mikepenz** [comment]
thank you
