### ISSUE TITLE
Libraries with MIT licence are not shown, although defined in AboutLibraries

### ISSUE THREAD

**Issue by burakozhan** [mikepenz/AboutLibraries#388]
## About this issue

- Briefly describe the issue

Libraries that use MIT licence are not displayed in the list.

- How can the issue be reproduced / sample code

add following dependencies into your gradle file: 
```
implementation "com.nispok:snackbar:2.11.0"
implementation "com.amulyakhare:com.amulyakhare.textdrawable:1.0.1"
implementation "com.klinkerapps:link_builder:2.0.3"
```

## Details
- [ 6.0.8 ] Used library version
- [ 27+ ] Used support library version
- [ Gradle 4.4 ] Used gradle build tools version
- [ 3.1.1 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries ?? 

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] -Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)- Not related, first usage.

**Comment by mikepenz** [comment]
@burakozhan tested and verified that at least the snackbar one works (the others may have no definition file available) . 

Be aware that the ABoutLibraries caches the libs for one version to speed up loading. if you added them without changing verison they won't show up, clear app data, or adjust the version number :)
