### ISSUE TITLE
Improve naming for bundle keys

### ISSUE THREAD

**Issue by johnjohndoe** [mikepenz/AboutLibraries#39]
As a new user of the library I find it quite difficult to understand the meaning and usage of the various bundle keys. I think by renaming some of them you could also remove a lot of the [comments which describe their function](https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Activity).
Mostly, it is obvious - you can just re-use the variable names from the Java code. **Do not shorten bundle names** for the price of understanding problems. In general I would recommend to prefix all with `BUNDLE_KEY_` for clarity.

# Boolean values

* Rename [`BUNDLE_AUTODETECT`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L84) to `BUNDLE_KEY_DETECT_AUTOMATICALLY`
* Rename [`BUNDLE_LICENSE`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L88) to `BUNDLE_KEY_SHOW_LICENSE`
* Rename [`BUNDLE_LICENSE_DIALOG`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L89) to `BUNDLE_KEY_SHOW_LICENSE_DIALOG`
* Rename [`BUNDLE_VERSION`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L90) to `BUNDLE_KEY_SHOW_VERSION`
* Rename [`BUNDLE_APP_ABOUT_ICON`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L108) to `BUNDLE_KEY_SHOW_APP_ABOUT_ICON`
* Rename [`BUNDLE_APP_ABOUT_VERSION`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L119) to `BUNDLE_KEY_SHOW_APP_ABOUT_VERSION`

# Collection values

* Rename [`BUNDLE_LIBS`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L81) to `BUNDLE_KEY_INTERNAL_LIBRARIES_KEYS`
* Rename [`BUNDLE_EXCLUDE_LIBS`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L82) to `BUNDLE_KEY_EXCLUDE_LIBRARIES_KEYS`
* Rename [`BUNDLE_FIELDS`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L80) to `BUNDLE_KEY_FIELDS` - *Actually this is the hardest one to understand. I cannot tell what this is used for from its name.*

# String values

* Rename [`BUNDLE_APP_ABOUT_DESCRIPTION`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsFragment.java#L131) to `BUNDLE_KEY_APP_ABOUT_DESCRIPTION`
* Rename [`BUNDLE_TITLE`](https://github.com/mikepenz/AboutLibraries/blob/v4.3.7/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.java#L40) to `BUNDLE_KEY_TITLE`

... and so on.

**Comment by mikepenz** [comment]
They are now deprecated. and the builder should be used.

**Comment by johnjohndoe** [comment]
:+1:
