### ISSUE TITLE
Manually added libs are not displaying in 6.0.7/6.0.8

### ISSUE THREAD

**Issue by illuzor** [mikepenz/AboutLibraries#391]
## About this issue

With 6.0.6 no problem.

![about_libs](https://user-images.githubusercontent.com/1530314/39662703-b66832e2-506e-11e8-94cc-ed25c48fd757.png)

My code:
```kotlin
LibsBuilder()
   .withLibraries("Mighty Preferences", "Apache Commons IO", "MaterialRangeBar")
   .withActivityTheme(R.style.AboutTheme)
   .withActivityTitle(getString(R.string.settings_other_open_source_libs))
   .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
   .withFields(R.string::class.java.fields)
   .start(this)
```

My xml files - https://gist.github.com/illuzor/ab74263f6a89d9f0e726870c6b949d83

## Details
- [ 6.0.7/6.0.8] Used library version
- [ 27.1.1] Used support library version
- [ 4.5] Used gradle build tools version
- [ 3.1.2] Used tooling / Android Studio version
- [ -] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
remove the characters `int_` of the define. 

like:
```xml
 <string name="define_int_commonsio" translatable="false" />
```
to
```xml
 <string name="define_commonsio" translatable="false" />
```
