### ISSUE TITLE
Making LibsSupportFragment Android Navigation library friendly.

### ISSUE THREAD

**Issue by OmkarAmberkar** [mikepenz/AboutLibraries#394]
## Unable to use LibsSupportFragment via navigation graph.

- I tried using LibsSupportFragment directly into the navigation graph, the navigation was successful but since I had not passed in an instance of LibsBuilder, the adapter was not attached to recyclerview.
- Try using this in your navigation graph.
```
<fragment
        android:id="@+id/libsSupportFragment"
        android:label="About Libraries"
        android:name="com.mikepenz.aboutlibraries.ui.LibsSupportFragment"
        tools:layout="@layout/fragment_opensource" />
```

## Details
- [6.0.8] Used library version
- [28.0.0-alpha1] Used support library version
- [3.2.0-alpha15] Used gradle build tools version
- [3.2 Canary 15] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
I am happy to take PRs to improve compatibility.

There are currently no plans to adjust this as the dependencies are not stable

**Comment by mikepenz** [comment]
Closing this as no action right now. If you'd like to open a PR. I am more than happy to check it out! :)

**Comment by kuhnroyal** [comment]
I am using something like this:
```
    <fragment
        android:id="@+id/foo"
        android:name="com.mikepenz.aboutlibraries.ui.LibsSupportFragment"
        android:label="foo">
        <argument android:name="data" app:argType="com.mikepenz.aboutlibraries.LibsBuilder"/>
    </fragment>
```
And use the `LibsBuilder` to set the argument.
It would be good if the provided fragments would be an `open class` so one can extend them.
