### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by csensen** [mikepenz/AboutLibraries#395]
Hi,

Crashlytics today caught the following error:
`Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
android.os.AsyncTask$3.done`

**Caused by java.lang.OutOfMemoryError
Failed to allocate a 28356 byte allocation with 19912 free bytes and 19KB until OOM**
com.mikepenz.aboutlibraries.Libs.insertVariables
`ava.lang.AbstractStringBuilder.enlargeBuffer (AbstractStringBuilder.java:95)
arrow_drop_down
java.lang.String.replace (String.java:1016)
arrow_right
com.mikepenz.aboutlibraries.Libs.insertVariables (Libs.java:495)
com.mikepenz.aboutlibraries.Libs.genLibrary (Libs.java:444)
com.mikepenz.aboutlibraries.Libs.init (Libs.java:107)
com.mikepenz.aboutlibraries.Libs.<init> (Libs.java:68)
com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground (LibsFragmentCompat.java:164)
com.mikepenz.aboutlibraries.LibsFragmentCompat$LibraryTask.doInBackground (LibsFragmentCompat.java:136)
android.os.AsyncTask$2.call (AsyncTask.java:295)`

This is the code I use to start the library:
`new LibsBuilder()
                .withAutoDetect(true)
                .withActivityTitle("Title")
                //.withActivityColor(R.color.white.xml)
                //.withActivityStyle(R.style.LicenseTheme)
                .withActivityStyle(Libs.ActivityStyle.LIGHT)
                .withAboutAppName("Name")
                .withAboutVersionShownName(true)
                .withAboutIconShown(true)
                .withAboutDescription(text)
                .withLicenseShown(true)
                .withLicenseDialog(true)
                .start(context);`

Device information:
`Device
Brand: motorola
Model: Moto G4 Play
Orientation: Portrait
RAM free: 1.23 GB
Disk free: 9.71 GB
plat_android Operating System
Version: 6.0.1
Orientation: Portrait
Rooted: No`

This error has only popped up on Crashlytics once. I myself cannot reproduce it and have no idea what it might be caused by. 

I would appreciate it, if you could have a look at this issue.

**Comment by mikepenz** [comment]
@csensen the error looks like something else might consumed all the memory and the about libraries did not even have a tiny bit memory to replace a string. 

I am pretty sure it is not related to this library as there were no other reports. 

Please provide more details or more resources if it turns out to be related after all.
