### ISSUE TITLE
Theme not changing

### ISSUE THREAD

**Issue by Kelvao** [mikepenz/AboutLibraries#399]
## About this issue

When i use: 
```
getSupportFragmentManager().beginTransaction().replace(R.id.contentFragment,
                        new LibsBuilder()
                                .withAboutIconShown(true)
                                .withAboutAppName(getResources().getString(R.string.app_name))
                                .withAboutVersionShown(true)
                                .withLicenseShown(true)
                                .withVersionShown(true)
                                .withAutoDetect(true)
                                .withActivityStyle(Libs.ActivityStyle.DARK)
                                .supportFragment()
                ).commit();
```
The theme does not change.

## Details
- [ x ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
You use a fragment and not the activity make sure your activity style has a proper theme and the proper theme values
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/styles.xml
