### ISSUE TITLE
Not displayed on real machine

### ISSUE THREAD

**Issue by Tezzeret1603** [mikepenz/AboutLibraries#402]
## About this issue

- license information is not showing on real machine via Distributed APK file.
but ,debug mode on real machine is showing it.
(Icon is showing both)
There is no applicable error log and no warning log.

## Details
- [6.0.9 ] Used library version
- [27.1.1 ] Used support library version
- [3.1.3 ] Used gradle build tools version
- [3.1.3 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [o] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [o] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [o] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [o] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [o] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Did you look at this: https://github.com/mikepenz/AboutLibraries#proguard

Also the auto detection might not work if the libraries are obfuscated as there is no way to detect them then. In this case you need to set them up by manually defining the ids of the libs you want to show

**Comment by Tezzeret1603** [comment]
Hi, solve it.
Thank you for your cooperation.
