### ISSUE TITLE
Default Volley from google detected as Volley Plus

### ISSUE THREAD

**Issue by jboxx** [mikepenz/AboutLibraries#404]
## About this issue
I used `com.android.volley:volley:1.0.0` but it's detected as Volley Plus.

```
new LibsBuilder()
    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
    .withCheckCachedDetection(false)
    .withActivityTitle(getString(R.string.third_party_software_license))
    .withAboutIconShown(false)
    .withAboutVersionShown(false)
    .withAboutVersionShownName(false)
    .withAboutVersionShownCode(false)
    .withFields(R.string.class.getFields())
    .start(this);
```

I though it's happen because of auto detect read that class
`<string name="library_volleyplus_classPath">com.android.volley.RequestQueue</string>`
Volley from Google used that class too and have same classpath
Volley Plus should detecting this classpath `com.android.volley.toolbox.Volley` or `com.android.volley.toolbox.VolleyTickle`

## Details
- [6.0.9] Used library version
- [27.1.1] Used support library version
- [3.1.3] Used gradle build tools version
- [3.1.3] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [V] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [V] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [V] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [V] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [V] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
they most likely share the same classpath :/
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/library_volleyplus_strings.xml#L17

any sourcefile which is not existing in volley from google but in volleyplus which can be used to identify?
