### ISSUE TITLE
withLibraries method not working

### ISSUE THREAD

**Issue by joanpuigsanz** [mikepenz/AboutLibraries#405]
## About this issue

I'm using Proguard and the lAboutLibraries only detects AboutLibraries, Android-Iconrics, Constraint Layou and FastAdapter, so I decided to use the ```withLibraries ``` to show the rest of the libraries. The problem is that the activity is not showing the specified libraries. Here is the code I use (Kotlin)

```
LibsBuilder()
    .withFields(R.string::class.java.fields)
     withLibraries("crouton, actionbarsherlock", "showcaseview") // This is taken from the examples just for testing
    .withActivityTitle(activity.getString(R.string.preference_title_libs))
    .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
    .start(activity)
```

I've actually compiled and run the test app and I don't see the libraries specified when running the following code:

```
LibsBuilder builder = new LibsBuilder()
                .withLibraries("crouton, actionbarsherlock", "showcaseview", "glide")
                .withActivityTheme(R.style.MaterialDrawerTheme)
                .withLibraryComparator(new LibraryComparator());
```

Do you know if I'm missing something?
Thanks!

## Details
- [ 6.1.0] Used library version
- [27.1.1 ] Used support library version
- [3.1.3 ] Used gradle build tools version
- [ 3.1.3] Android Studio version
- [27.0.0] Build tools
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
```java
.withLibraries("crouton, actionbarsherlock", "showcaseview", "glide")
```

you somehow missed to add '"'  :D

try:

```java
.withLibraries("crouton", "actionbarsherlock", "showcaseview", "glide")
```

**Comment by joanpuigsanz** [comment]
I've tried an I still have the same problem. I think you can try it using the ```CustomSortActivity``` in your test app, actually the following code is from there:

```
.withLibraries("crouton, actionbarsherlock", "showcaseview", "glide")
```

**Comment by mikepenz** [comment]
Published an update to fix this problem. 

Thank you very much
