### ISSUE TITLE
Is it possible to add additional license to the result ?

### ISSUE THREAD

**Issue by skauss** [mikepenz/AboutLibraries#407]
Hi,
I have the requirement to add additional licenses into the output.

For example we use Lottie animation  (which are third party json resource's) with this license
https://www.lottiefiles.com/license https://creativecommons.org/licenses/by/4.0/

Is it possible to to add this information in an external file and the them to the output.
Regards
Stephan

**Comment by mikepenz** [comment]
Licenses are defined similar to this one: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/licence_cc40_strings.xml

You can create a new strings resource file with that license from lottie, ensure you have a identifier for it (the above linked file uses 'cc40' as identifier) 

and then you can use it similar to this library (which uses cc30 (as no lib uses cc40))
https://github.com/mikepenz/AboutLibraries/blob/8d1a117e7b1dc9e89f3a19b3ec8bef8992eed7d4/library/src/main/res/values/library_useravatarspack_strings.xml#L18

**Comment by skauss** [comment]
Thanks
