### ISSUE TITLE
Narrate displaying with PhotoView

### ISSUE THREAD

**Issue by ccomeaux** [mikepenz/AboutLibraries#408]
## About this issue

When the PhotoView library (https://github.com/chrisbanes/PhotoView) is included as a dependency, the Narrate app (https://github.com/timothymiko/narrate-android) is displayed in the list of open source licenses. The issue appears to be an invalid class path at https://github.com/mikepenz/AboutLibraries/blob/bb4b3e7f2edbce7d2134d78e65e3651d910b61ce/library/src/main/res/values/library_narrate_android_strings.xml#L17

## Details

- Used library version = 6.0.6
- Used support library version = 27.1.1
- Used gradle build tools version = 3.1.4
- Used tooling / Android Studio version = 3.1.4
- Other used libraries, potential conflicting libraries
  - com.github.chrisbanes.photoview:library:1.2.4

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Oh thank you very much. could you please open a PR?

**Comment by ccomeaux** [comment]
I can, but it may be a while before I can get to it. I think the class path for PhotoView is incorrect - I believe it should be `com.github.chrisbanes.photoview.PhotoView`.

**Comment by mikepenz** [comment]
will be in the next release, sorry did not make it into this one
