### ISSUE TITLE
LibraryVersion from BuildConfig

### ISSUE THREAD

**Issue by akallabeth** [mikepenz/AboutLibraries#410]
## About this issue
Currently the library version is read from a resource string in an XML file.
Would be nice to read it from the `BuildConfig` of the library itself, as that is always up to date.

**Comment by mikepenz** [comment]
Interesting idea for an enhancement. 

This will require though that the reflection automatically finds the `BuildConfig` which might not work as we don't necessarily know the `applicationId` we could adjust the definition files, but that would result every single file to be adjusted. 

I would still hope that we can figure out a compile time approach, which would detect included libs based on the gradle file, resulting in the latest version, and would help to eliminate included resources, (only resources needed would be included as source)

**Comment by mikepenz** [comment]
I was trying to look into a compile time approach via a gradle plugin. Sadly I came to a blocker:
https://discuss.gradle.org/t/resolve-transitive-dependencies/30534

Closing this ticket as the Buildconfig approach will most likely not be used. 

Will still investigate further though to somehow be able to collect all the dependencies at dependency resolution time in gradle which should make it a lot faster and lightweight
