### ISSUE TITLE
Providing a bit more customization on the default activity

### ISSUE THREAD

**Issue by athkalia** [mikepenz/AboutLibraries#418]
Hello, I am wondering if it would be possible to customize the following in the default activity of the library:

a) The activity title colour
b) The shadows of the card views
c) Having round edges in the cards

Please let me know of your thoughts!

Thanks,
Sakis

**Comment by mikepenz** [comment]
@athkalia you can theoretically use the `Libs` class directly and build your own fully custom UI, which will give you all the control. 

Right now the default style can be adjusted for the activity. 
You can use `withActivityTheme()`
https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/ExtendActivity.java#L19
https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.java#L75

See more details here:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.java#L29

**Comment by athkalia** [comment]
Hi @mikepenz , I can set the activity theme but i can't customize the card theme cause the card has no default style set. If you set a custom style for the card view then I can override it I guess.

**Comment by athkalia** [comment]
I was only able to set the toolbar title text colour via `android:textColorPrimary`

**Comment by mikepenz** [comment]
I'd be happy to take a PR to improve this. Perhaps having proper styles for the different components which can then be changed in people's themes. 

Sorry for the late answer

**Comment by mikepenz** [comment]
Closing as no further communication. Please still consider a PR to improve things like this :)

Thanks a lot

**Comment by mikepenz** [comment]
@androidacy-user it was, for situations like these the library offers the `LibsSupportFragment`, which offers significantly more flexibility as you can include it in whatever host activity you have. 


In case that's not suiteable, you could copy over the https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.kt and apply what you need for your theme.

**Comment by mikepenz** [comment]
@androidacy-user I don't see how this fragment would cause such behaviour: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsSupportFragment.kt

Happy for contributions to improve it though.
