### ISSUE TITLE
Autodetect not working (?)

### ISSUE THREAD

**Issue by fei0316** [mikepenz/AboutLibraries#421]
Working on my first ever Android app, super sorry for silly mistakes...

I wanted the fragment to show the name and licenses for all libraries I have used in my app, which Google's `OssLicensesMenuActivity` is able to do. I don't really mind to have no description or other details. I used this code to generate the fragment and is included in an activity:
`LibsFragment fragment = new LibsBuilder()
                .withFields(R.string.class.getFields())
                .fragment();`
However, not all libraries are shown, even some that are included in the values xml folder (of `AboutLibraries`) are there.

Is this the expected behavior? If no, what else did I miss? If yes, what can I do?

As a side question, what will happen if the library is not defined in the xml folder?

Thank you so much!

## Details
- [6.1.1 ] Used library version
- [27.1.1 ] Used support library version
- [4.6 ] Used gradle build tools version
- [ Android Studio 3.2.1 ] Used tooling / Android Studio version
- [  ] Other used libraries, potential conflicting libraries

## Libraries used
```
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.github.clans:fab:1.6.4'
    implementation 'com.github.Kunzisoft:Android-SwitchDateTimePicker:2.0'
    implementation 'biz.kasual:materialnumberpicker:1.2.1'
    implementation 'uk.co.samuelwall:material-tap-target-prompt:2.14.0'
    implementation 'com.mikepenz:aboutlibraries:6.1.1'

```

**Comment by mikepenz** [comment]
The one from google uses the maven POM description info during compile time, and will generate a file which then shows up. in the past tests it missed a lot of libraries. But they do great progress so at some point it might replace this lib. 

Well some libraries might not have the classPath defined, as such it can not try to find it. 
Also if you have proguard it won't be able to find them. 

Which libs are missing? Which do show up? 

If you want to make sure, disable autodetect, and show libs by providing the "id" of those you wanna have visible

**Comment by fei0316** [comment]
If all libraries referenced in gradle should appear, then floating action button, material number picker, Android switch date time picker, as well as some more AOSP libraries are missing, despite some of them being defined in the xmls. Only material tap target and your libraries show up.

Proguard is disabled (minify not enabled, and I'm building debug apks)

What could be the problem? Also how do I provide the id for manual inclusion of packages?

**Comment by fei0316** [comment]
A little update... I found out what you mean by "id" and it worked by manually including the missing ones, but only when it's included in `AboutLibraries`. So I have to create my own if some libraries I used are not included?
Also, I still don't have a clue as to what happened to autodetect...

**Comment by mikepenz** [comment]
If a library is not available in the definitions a PR would be highly appreciated to add the details. 

Yeah as mentioned auto detect works only if it can detect the class file at runtime, anything which makes the class file being named differently, or a change in it, or missing definition of it will result in auto detection not able to detect it. 

Also another thing which sometimes happens: The `R` field not being found due to a different package name. so sometimes the `R` fields have to passed in. (I think that is mentioned in the README tooo)

**Comment by fei0316** [comment]
Found the problem... 
One included definition file for a library is old and does not include a classpath, therefore it cannot be updated. My custom-made definition files and included ones with classpath worked flawlessly.
Thank you very much for your help, turned out there is nothing wrong with the library.
I will be making a PR for my custom files.

**Comment by mikepenz** [comment]
Thank you so much :)

Sorry for the difficulties.
