### ISSUE TITLE
missing library definitions for gpl 2/3

### ISSUE THREAD

**Issue by mbiebl** [mikepenz/AboutLibraries#426]
I was looking for library definitions for gpl 3.0 and gpl 2.1 but it seems AboutLibraries is missing those.
Would be nice if those were added by default.

**Comment by mikepenz** [comment]
you can open a PR to add them similar to the LGPL license which are already provided: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/values/license_lgpl_2_1_strings.xml

**Comment by mbiebl** [comment]
will do. thanks for the quick reply

**Comment by mbiebl** [comment]
Anyway, thanks for still being open to accept a fix for it. 
I'm a bit undecided what to do about the license name wrt #427.
I see a couple of options here
a/ Set licenseName to `GPL 3.0` instead of spelling it out
b/ Introduce a shortLicenseName field (which would require a more elaborate code change
c/ Don't shorten the license name to 50% but give it all available space

Wdyt?

**Comment by mikepenz** [comment]
I can reopen if you prefer.

Hmmm well it highly depends on the configuration. theoretically 100% are available if the version is not shown. it always depends on the configuration in the end :/

**Comment by mbiebl** [comment]
Would a layout like this be an option?
-----------------------------
library name (*)
-----------------------------
authors
-----------------------------
description
-----------------------------
license
-----------------------------

*) If a library version has been set, it's added in brackets, all fields span 100%

**Comment by mbiebl** [comment]
That said, discussing the specific UI changes should probably move over to #427

I just wanted to know which route I should take when preparing the PR, i.e. use a shortened license name like `GPL 3.0` or spell it out and hope #427 get's fixed one way or another.

**Comment by mikepenz** [comment]
@mbiebl I am not sure if the layout would look good with so many sections under each other. also it will make them a lot higher than before. 

But yes you are right. the ui discussion should be on the other ticket. 

I suppose using `GPL 3.0` would be in general better. if clicked and the full description is opened that would show the full name then I guess.
