### ISSUE TITLE
library and author names are shortened too aggressively

### ISSUE THREAD

**Issue by mbiebl** [mikepenz/AboutLibraries#427]
I was trying to add a section like this:
```
    <string name="define_cert4android" translatable="false" />
    <string name="library_cert4android_author" translatable="false">Ricki Hirner, Bernhard Stockmann</string>
    <string name="library_cert4android_authorWebsite">https://www.davx5.com/</string>
    <string name="library_cert4android_libraryName" translatable="false">cert4android</string>
    <string name="library_cert4android_libraryDescription">Android service + TrustManager for managing custom certificates in an app-private key store.</string>
    <string name="library_cert4android_libraryWebsite" translatable="false">https://gitlab.com/bitfireAT/cert4android</string>
    <string name="library_cert4android_isOpenSource" translatable="false">true</string>
    <string name="library_cert4android_licenseId">lgpl_3_0</string>
```
(cert4android is gpl 3.0, but see #426, so for testing purposes I chose lgpl_3_0)

The result is the attached screenshot:
![screenshot_1548364538](https://user-images.githubusercontent.com/3609611/51709294-45003b80-2026-11e9-8f30-250fba8c9b78.png)

As you can see both the name of the main author: "Bernhard Stockmann" is shortened to "Bernhard" for no apparent reason as well as the library information reads "GNU LESSER GENERAL", which is incomplete, as it should read "GNU LESSER GENERAL PUBLIC LICENSE 3.0"

**Comment by mikepenz** [comment]
Right now there is a a 70% area for the title and a 30% area for the right part
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml#L32

and 50:50 for the bottom:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml#L89

**Comment by mikepenz** [comment]
btw. you can also just overwrite the `listitem_opensource.xml` layout (this works still, at some point in the future the build tooling will prevent overwriting for resources (but at that time I will need to introduce an API to do so)) 

So you could for example put the creator under the libraryName. have it 2 lined. and change horizontal of the container to vertical

**Comment by mbiebl** [comment]
Thanks for that information. Still, I somehow think that AboutLibraries should by default make better use of the available space. In the example above, there would be more then enough space to list both names in full.

**Comment by mikepenz** [comment]
Thank you so much for the feedback. I think for the standard it is ok so far. I will potentially revisit this in the future.
