### ISSUE TITLE
Clarify support library version in release notes

### ISSUE THREAD

**Issue by johnjohndoe** [mikepenz/AboutLibraries#431]
## About this issue
- I figured that the release notes can be a bit clearer about when the support library version on which your library depends on is raised.

## Details
- I was about to integrate your library in my project while still depending on support library 26+. Therefore, I looked into your release notes to find out which is the maximum version of _AboutLibraries_ which has been released with support library 26+. Judging from the release notes it looks like as if [v5.9.8](https://github.com/mikepenz/AboutLibraries/releases/tag/v5.9.8) is the one I could use because of the release notes in [v6.0.0](https://github.com/mikepenz/AboutLibraries/releases/tag/v6.0.0):

  > update supportLibs to 27
- When I include that version in my app project however it turns out that v5.9.8 depends on support library 27.0.0.
- Looking into the particular commits of your project I found that you updated the support library in the "update to latest tooling" commit (875451efa236dea3529f37cc52e4e105244c02bc).

## Action
- [ ] Please correct the release notes on v5.9.8 and v6.0.0.

## Personal wish
- From my experience of publishing and using libraries it is very convenient to app developers if libraries always publish a new version every time a dependency such as support library is increased. I even suggest not stepping over a certain version such as from 26 to 28 because app developers might have their own reasons to stay at 27 and to incrementally update version-wise.

**Comment by mikepenz** [comment]
Yes I really understand this. 

The whole situation is now a bit different luckily due to androidX. 

What I highly suggest always is to have a resolution strategy and have the version you require specified in your app to ensure only this one you require is used. 

https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L87

I will outline the dependent androidX dependencies in the README to help developers more with v7. 
Thank you very much

**Comment by johnjohndoe** [comment]
Thank you for your response. You linked to the HEAD of the repository when you wrote your comment. Since then the build.gradle file has been modified. I believe you were linking to this [`configuration` block](https://github.com/mikepenz/AboutLibraries/blob/fbd8dcbe5c61cd7f60dc9f6184c3ccbda28b6798/app/build.gradle#L87-L96) (?).

I however disagree with your suggestion to force a certain support library version from an app onto a library. To my experience this is bad idea since the API of the support library might change from version to version and the author of the app does not know which APIs are being used by the library. Please correct me if you have made different experiences.

Can you please point to the README changes you proposed?

As a friendly reminder, I ask you to correct the release notes as mentioned above. It would nice if the next person trying to use these versions does not have to figure out the same as I did.

**Comment by mikepenz** [comment]
Yes I meant this block. 

I guess with the new semantic versioning, it would be rather save to say to specify the major version which is needed, but minor and patch versions should not matter. 

So I guess I should update this:

``` 
//required support lib modules
implementation "androidx.appcompat:appcompat:${versions.appcompat}"
implementation "androidx.cardview:cardview:${versions.cardview}"
implementation "androidx.recyclerview:recyclerview:${versions.recyclerview}"
implementation "com.google.android.material:material:${versions.material}"
``` 

to 

```
//required support lib modules
implementation "androidx.appcompat:appcompat:1.x.y"
implementation "androidx.cardview:cardview:1.x.y"
implementation "androidx.recyclerview:recyclerview:1.x.y"
implementation "com.google.android.material:material:1.x.y"
``` 

and if the readme specifies it like this you can jump to that particular readme state to see what major versions were required. 



Oh you meant to adjust for the already released versions. Sorry I might have missed that.

**Comment by mikepenz** [comment]
Ok I won't add dependencies moving backwards. So for this case please just go to the tag and see which versions are specified in the root build.gradle.

But moving forward I will specify the major required version in the README and in the release notes to hopefully simplify and prevent conflicts

**Comment by johnjohndoe** [comment]
Thanks for adding details to the README. I guess people can figure it out somewhat easier this way.
