### ISSUE TITLE
Prevent orientation change

### ISSUE THREAD

**Issue by ComanderKai77** [mikepenz/AboutLibraries#432]
Is there a way to force the activity to stay in portrait mode?

**Comment by mikepenz** [comment]
@ComanderKai77 you could define that by setting the activity in your manifest and defining its screen orientation

**Comment by ComanderKai77** [comment]
`<activity
            android:name=".Activity"
            android:screenOrientation="portrait" />`
I have to specify it for every activity, because the name attribute is mandatory.
So what should I use as activity name?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/AndroidManifest.xml

**Comment by ComanderKai77** [comment]
That worked. Thank you so much.
