### ISSUE TITLE
Build with version 7.0.0 failing

### ISSUE THREAD

**Issue by mueller-ma** [mikepenz/AboutLibraries#433]
## About this issue

When bumping this lib to 7.0.0 (https://github.com/openhab/openhab-android/pull/1391/files), the build fails with the following error:
https://travis-ci.org/openhab/openhab-android/builds/548876276#L1901

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile:transformResourcesWithMergeJavaResForFossBetaDebug'.
> More than one file was found with OS independent path 'META-INF/library-core_release.kotlin_module'
````

## Details
- [ ] Used library version: 7.0.0
- [ ] Used support library version
````
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.2"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.2"
    implementation "androidx.core:core-ktx:1.0.2"
    implementation "androidx.fragment:fragment-ktx:1.0.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.40"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
````
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I am not sure it sounds like something which happens when compiling with kotlin. 

```
    packagingOptions {
        exclude 'META-INF/library-core_release.kotlin_module'
    }
``` 

Should fix it

**Comment by mueller-ma** [comment]
Thanks, that works. Can you add this to the library? Otherwise this must be fixed in every app that uses AboutLibraries.

**Comment by mikepenz** [comment]
I don't think it will make a difference to add this line to the library. I can try though for the next update.
