### ISSUE TITLE
Update Wiki to have Kotlin version

### ISSUE THREAD

**Issue by kaushalyap** [mikepenz/AboutLibraries#436]
I am trying [this in wiki](https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Custom)

I am having difficult time translating it to Kotlin

```
Libs libs = Libs(context, Libs.toStringArray(R.string.class.getFields()));

var libs = Libs(applicationContext, Libs.toStringArray(R.string::class.java!!.fields))
```
error: `Unresolved reference toStringArray`

casting also not successful

`var libs = Libs(applicationContext, R.string::class.java!!.fields as Array<String>)`

Please update the Wiki to have Kotlin version also

**Comment by janwelocampo** [comment]
Hi,  you could try this code for Kotlin.

`val libs = Libs(this).prepareLibraries(this, emptyArray(), emptyArray(), true, true, true)`

I don't know if the current wiki is the latest one but based on what I read on the code, that should work.

**Comment by kaushalyap** [comment]
Thanks for reaching out. code even list the libraries that I am not using. I think this uses some repo to get info. I think its better to do things manually, since there is not much to add.

**Comment by kaushalyap** [comment]
Other than that I have to add following to app.gradle
```
packagingOptions{
        exclude 'META-INF/library-core_release.kotlin_module'
    }
```
to run the project which distort my fab colors
