### ISSUE TITLE
Please add https://github.com/GrenderG/Toastyand the corresponding LGPL license 

### ISSUE THREAD

**Issue by AlanInsam** [mikepenz/AboutLibraries#437]
## About this issue
Please add the library
- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by AlanInsam** [comment]
License is LGPL 3.0 after including it manually, license text doesn't show up

**Comment by mikepenz** [comment]
Please follow the proper format to report an issue. 

The identifiers for LGPL are either:
`lgpl_3_0` or `lgpl_2_1`
