### ISSUE TITLE
Add androidx/kotlin definitions

### ISSUE THREAD

**Issue by kuhnroyal** [mikepenz/AboutLibraries#438]
Since this library is now based on AndroidX and Kotlin, it would probably be useful to include these definitions. Right now, not even the used/required AndroidX libs by the sample app are detected.

**Comment by mikepenz** [comment]
I am more than happy to take a PR to add new definition files to the library :)

**Comment by loko1389** [comment]
Someone alludas me I still don't have much knowledge

**Comment by loko1389** [comment]
Please I would greatly appreciate it

**Comment by AllanWang** [comment]
Fyi, assuming this is for the androidx "support version":

https://github.com/mikepenz/AboutLibraries/blob/b22abe6798960f4cdbd16d6a2243b40c5b74de98/library/build.gradle#L16

perhaps this should be replaced with `versions.appcompat`? There isn't a single androidx version

**Comment by mikepenz** [comment]
Will be fixed with v8 :)
