### ISSUE TITLE
Library incompatible with Material Components 1.0.0 by default

### ISSUE THREAD

**Issue by vlad-roid** [mikepenz/AboutLibraries#445]
This library shouldn't be using non-stable Google libraries. Adding it broke all my colors and it took me a while to find out that the material:1.1.0-alpha is the culprit, which involves major theming related changes. The latest stable Material Components version is 1.0.0 while AppCompat is 1.1.0, which should be used here to prevent undesirable consequences.
Temporary solution if anyone else encounters this:
```
implementation ('com.mikepenz:aboutlibraries:7.0.3') {
    exclude group: 'com.google.android.material', module: 'material'
}
```

**Comment by mikepenz** [comment]
The changelog for v7.0.1 mentions that a v1.1.x version of the MDC is used:

https://github.com/mikepenz/AboutLibraries/releases/tag/v7.0.1

This is intended. Your workaround should be fine for this project. note for you or other uses. the MaterialDrawer v7.x requires MDC 1.1.x

**Comment by vlad-roid** [comment]
I see, I suggest adding this to the readme, so new users like me can see it too :)
