### ISSUE TITLE
Weird scroll bug on Lollipop device

### ISSUE THREAD

**Issue by choryuidentify** [mikepenz/AboutLibraries#448]
## About this issue

I'm testing my application on Samsung Galaxy S4 Active, Lollipop.
When scrolling down and up, Randomly CardView getting padding.
I'm trying turn off Version and License, nothing changed. (.withVersionShown(false).withLicenseShown(false))

Video -> https://youtu.be/9TnfrEgZ_oo

## Details
- [ ] Used library version
    7.0.3
- [ ] Used support library version
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
- [ ] Used gradle build tools version
    classpath 'com.android.tools.build:gradle:3.5.1'
- [ ] Used tooling / Android Studio version
    Android Studio 3.5.1
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
hmmm I don't really know what could cause this :/

**Comment by mikepenz** [comment]
I can not seem to get it behave like this. Does it happen on other devices for you too?

**Comment by choryuidentify** [comment]
Not really. I have Xiaomi Redmi Note 5 Pro (Android 9), and this device is ok.

Test it on Android Emulator and report back later!

**Comment by choryuidentify** [comment]
Hmm... same behavior on emulator. I test the code on Genymotion 5.0.0 Lollipop device.

My code is
```
LibsBuilder()
                        .withAutoDetect(true)
                        .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                        .withAboutIconShown(true)
                        .withAboutAppName(getString(R.string.app_name))
                        .withActivityTitle(getString(R.string.nav_title_info))
                        .withAboutDescription("테스트 프로젝트, Project TESTAMENT")
                        .withVersionShown(true)
                        .withLicenseShown(true)
                        .start(this)
```

**Comment by mikepenz** [comment]
I anybody has any clue why this might happen. I got none at the moment :/

**Comment by mikepenz** [comment]
The item is a default constraint layout 

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml

**Comment by mikepenz** [comment]
I am sorry but. could never find out this problem. nor reproduce :/ 

Most likely some problem in the RV or any other libryary
