### ISSUE TITLE
Library License not recognized

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#458]
## About this issue

License of `pl.droidsonroids.foqa:deviceinfo` is not recognized by AboutLibraries. Some other libraries e.g. Dagger are recognized properly.

On maven central both license name and url works correctly:
https://search.maven.org/artifact/pl.droidsonroids.foqa/deviceinfo

Usage:
```kotlin
childFragmentManager.commit {
                replace(R.id.ossLicensesContainer, LibsBuilder().withLicenseShown(true).supportFragment())
            }
```
Actual result:
![image](https://user-images.githubusercontent.com/3340954/71646889-2272aa00-2cee-11ea-908e-3fec1f5fbf98.png)

Library sources: https://github.com/DroidsOnRoids/FoQA

## Details
- [x] Used library version: 8.0.0-a02 (with Gradle plugin)
- [x] Used support library version: not used (AndroidX used instead)
- [x] Used gradle build tools version: 6.1-rc-1
- [x] Used tooling / Android Studio version: 4.0.0-alpha07
- [x] Other used libraries, potential conflicting libraries: nothing I'm aware of

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@koral-- thanks for the report about the not yet recognized MIT license. I am working to get support for all, but couldn't yet find POM files with all informations. 


Regarding your comment with `Dagger` being not properly recognized, can you point out a bit more specific what you mean by that? I see dagger showing up in your screenshot.
With all the information they specified in their POM file: https://search.maven.org/artifact/com.google.dagger/dagger/2.25.4/jar

**Comment by mikepenz** [comment]
Published v8.0.0-a03 with a fix
Please also note that the plugin id changed because I am trying to get it included in the gradle plugin portal and that ones requires a full identifier

**Comment by koral--** [comment]
Thanks for the quick response.

> `Dagger` being not properly recognized

I said the opposite ;)

> Some other libraries e.g. Dagger are recognized properly.

**Comment by mikepenz** [comment]
Oh oops :D sorry read it wrong. 

Thanks a lot for the report :) 

If you got any libraries with licenses other than MIT or Apache 2.0 license please let me know I wish I can get a sample one for all the supported once prior to a final release with the plugin :)
