### ISSUE TITLE
Broken character encoding of  library author name

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#459]
If default java character encoding during build is set to something else than UTF-8 then About Libraries displays my name as Karol Wr?tniak instead of Karol Wrótniak.
If it is set to UTF-8 then there is no issue.

It looks like system default character encoding is used by gradle task.
I expect that character encoding of author's name in this case is taken from POM. If encoding is not explicitly set in XML Prolog then it should default to UTF-8.

Steps to reproduce and all other info incl. screenshot are present in another issue:https://github.com/mikepenz/AboutLibraries/issues/458#issue-544405677

**Comment by mikepenz** [comment]
Published v8.0.0-a03 with a fix
Please also note that the plugin id changed because I am trying to get it included in the gradle plugin portal and that ones requires a full identifier

**Comment by marcauberer** [comment]
I'm using version 8.1.2 (latest) of your lib and the bug still appears.
![Screenshot_20200422-125544](https://user-images.githubusercontent.com/59527509/79974623-f3996300-8499-11ea-9678-026550c23e4b.png)

Btw: Funny that this issue was opened by this developer ;)

**Comment by mikepenz** [comment]
@marcauberer do you have the wrong encoding already in the strings.xml?

**Comment by marcauberer** [comment]
Yes. Looks like this:
`<string name="library_pl_droidsonroids_gif__android_gif_drawable_author" translatable="false">Karol WrÃ³tniak</string>`

Btw: The name in the license dialog is also affected.

**Comment by mikepenz** [comment]
Oh well I think this time it is not an issue of AboutLibraries, but actually the meta data of that library on maven central:

https://search.maven.org/artifact/pl.droidsonroids.gif/android-gif-drawable/1.2.19/jar

**Comment by mikepenz** [comment]
![image](https://user-images.githubusercontent.com/1476232/79975479-5808f200-849b-11ea-8e96-118e237e76a5.png)


you may overwrite the info manually but I would suggest you report this on the respective project instead: https://github.com/koral--/android-gif-drawable

**Comment by marcauberer** [comment]
Okay thanks! I'll do that.
