### ISSUE TITLE
Some licenses are not recognized

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#460]
Follow-up of https://github.com/mikepenz/AboutLibraries/issues/458
Steps to reproduce and configuration is the same except for About Libraries version which is now `8.0.0-a03`

Libs which I've found not working:
* `com.github.piasy:BigImageViewer:1.6.2` https://github.com/Piasy/BigImageViewer
* `com.github.piasy:GlidImageLoader:1.6.2` https://github.com/Piasy/BigImageViewer
* `com.google.auto.value:auto-value-annotations:1.6.5` https://github.com/google/auto/tree/master/value
* `com.google.firebase:firebase-analytics:17.2.1` there is `Android Software Development Kit License` in POM
* few other artifacts from `com.google.firebase` group, seem to be similar to one above
* `com.google.android.gms:play-services-measurement:17.2.1`
* ditto others from this group
* `com.tbuonomo.andrui:viewpagerdotsindicator:4.1.2` https://github.com/tommybuonomo/dotsindicator

**Comment by mikepenz** [comment]
thank you so much. :) I will have a look at those libs and see to get them handled too

**Comment by mikepenz** [comment]
https://jcenter.bintray.com/com/tbuonomo/andrui/viewpagerdotsindicator/4.1.2/ has no license at all specified :/

**Comment by koral--** [comment]
In repo there is Apache v2: https://github.com/tommybuonomo/dotsindicator/blob/master/LICENSE
it is sent also to bintray: https://github.com/tommybuonomo/dotsindicator/blob/master/viewpagerdotsindicator/deploy.gradle#L33
but does not seem to be added to POM: https://github.com/tommybuonomo/dotsindicator/blob/ad9b4c4759bf1744914895ff6d05cb115fb2b448/viewpagerdotsindicator/deploy.gradle#L40

PR or issue in that repo is needed.

**Comment by mikepenz** [comment]
I made the experience in most cases those issues will not lead to any proper resolution. 
for that matter I will construct a flexible way to have available information be possible to inject. 

a property file for:
license
library name
library description

and a property file to map:
available_custom_definition_file with the resolved information from the pom

this will still happen automatically behind the scenes.

**Comment by mikepenz** [comment]
This should be fixed now at least for most parts :)

**Comment by koral--** [comment]
I've added an issue to https://github.com/tommybuonomo/dotsindicator (linked above).
Autovalue has license defined in parent POM (the same case with another library is also in #461).

Rest of the cases seems to be covered by recent changes, so this issue may be probably closed.
