### ISSUE TITLE
define_plu_com_squareup_okio__okio resource is generated twice

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#463]
Environment is the same as in previous issues except that I've removed dependency on BigImageViewer and GlideImageLoader.
About libraries version is now 8.0.0-b01 but issue also occurs in a06-a08.

`aboutlibraries.xml` contains 2 strings with the same id:
```xml
<string name="define_plu_com_squareup_okio__okio"></string>
<string name="define_plu_com_squareup_okio__okio">owner</string>
```

**Comment by koral--** [comment]
It looks like each other string resource related to okio, apart from that one is duplicated (not empty) I've checked few ones.
Here are my quick workarounds: https://github.com/DroidsOnRoids/AboutLibraries/commits/feature/aboutlibs_next_gen
Proper solution needs to be cleaner.

**Comment by mikepenz** [comment]
hmmm I will have to investigate. 

do you have the dependency which causes this? theoretically it should be impossible that you h ave the same dependency twice

**Comment by mikepenz** [comment]
I'd love to try to reproduce it as equal as possible

**Comment by koral--** [comment]
It's a multi-module project with dozens of dependencies.
Here are fragments of dependency graph containing okio:
```
|    \--- com.squareup.leakcanary:leakcanary-android:2.1
|         +--- com.squareup.leakcanary:leakcanary-android-core:2.1
|         |    +--- com.squareup.leakcanary:shark-android:2.1
|         |    |    +--- com.squareup.leakcanary:shark:2.1
|         |    |    |    +--- com.squareup.leakcanary:shark-graph:2.1
|         |    |    |    |    +--- com.squareup.leakcanary:shark-hprof:2.1
|         |    |    |    |    |    +--- com.squareup.leakcanary:shark-log:2.1
|         |    |    |    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61 (*)
|         |    |    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61 (*)
|         |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61 (*)
|         |    |    |    |    \--- com.squareup.okio:okio:2.2.2
|         |    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.60 -> 1.3.61 (*)
|         |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61 (*)
|         |    |    |    \--- com.squareup.okio:okio:2.2.2 (*)
```
```
|    +--- com.github.ChuckerTeam.Chucker:library:3.0.1
|    |    +--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.41 -> 1.3.61
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.41 -> 1.3.61 (*)
|    |    +--- com.google.code.gson:gson:2.8.5
|    |    +--- com.squareup.okhttp3:okhttp:3.12.2
|    |    |    \--- com.squareup.okio:okio:1.15.0 -> 2.2.2 (*)
```
```

**Comment by mikepenz** [comment]
@koral-- hmmm that doesn't seem to be it. could it be that you have 2 different build variants?

**Comment by mikepenz** [comment]
Just adding those dependencies does not result in the problem

**Comment by koral--** [comment]
Yes, I have 3 build types (and 0 flavors) so 3 varinats.
Chucker is only dependency in 2 of them.
Leakcanary in 1 of 2 above.

**Comment by mikepenz** [comment]
I have the feeling that this is the problem. and that version is different in those 2 variants. as such the componentIdentifier does not match

**Comment by koral--** [comment]
Yep, they depend on different okio versions: `com.squareup.okio:okio:1.15.0 -> 2.2.2 (*)`

**Comment by mikepenz** [comment]
Your fix seems to be fine though. based on the fact that we require the xml parsing first to get the proper unique ID (which is without the version) 

Will do a b02 and then slow down with updates again :D
