### ISSUE TITLE
Gradle plugin 8.0.0-b2 is not available on jcenter

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#464]
https://jcenter.bintray.com/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/8.0.0-b02/aboutlibraries-plugin-8.0.0-b02.pom returns 
```json
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```
https://jcenter.bintray.com/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/ contains versions up to b01

**Comment by mikepenz** [comment]
Oh sorry. forgot to press the publish button. 

Should be available in the next few minutes
