### ISSUE TITLE
Unable to user gradle plugin with joda time library

### ISSUE THREAD

**Issue by claudiodegio** [mikepenz/AboutLibraries#468]
Hi when include joda time library in my project i cant build the application due invalid string resources 

## Details

I have used the versione 8.0.0-b04 when i include the lib 

` implementation 'joda-time:joda-time:2.10.5'
`
After the compilation 

Android resource compilation failed
/Users/claudio/progetti/test/easy/expensediary_2/app/build/generated/aboutlibraries/res/values/aboutlibraries.xml:603:3-99: AAPT: error: unescaped apostrophe in string
    
/Users/claudio/progetti/test/easy/expensediary_2/app/build/generated/aboutlibraries/res/values/aboutlibraries.xml:603:3-99: AAPT: error: not a valid string.

Opening the resource file i found an invalid string

`<string name="library_joda_time__joda_time_owner">Stephen Colebourne, Brian S O\\'Neill</string>
`
regs

**Comment by mikepenz** [comment]
Thanks for the report. We'll fix it in the next update. Looks like this particular library pre escapes the string and we'll escape it again.

**Comment by mikepenz** [comment]
Released v8.0.0-b05 with a fix

**Comment by claudiodegio** [comment]
Thank You very much

Il dom 26 gen 2020, 10:25 Mike Penz <notifications@github.com> ha scritto:

**Comment by claudiodegio** [comment]
It's works thank you for support
