### ISSUE TITLE
Copyright YEAR is not handled correctly

### ISSUE THREAD

**Issue by adrianlandborn** [mikepenz/AboutLibraries#469]
## About this issue

- Briefly describe the issue
In all Licence and Copyright dialogs the year isn't properly parsed and only shows up as **YEAR**.
Eg. "Copyright (c) **YEAR**, AOSP" or  "Copyright (c) **YEAR**, Mike Penz"

- How can the issue be reproduced / sample code
Also repruducible here https://play.google.com/store/apps/details?id=com.mikepenz.aboutlibraries.sample but in this version **OWNER** is also left out.

I have just started to use you lib so not sure if the error is on my side. Good work with this lib so far!

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@adrianlandborn so the main issue with v8 is that the POM nor any information we have offers the year as information
I could replace it with the current year if available but that seems kind of wrong too :/ 

Currently there would be no other source than doing this manually

**Comment by adrianlandborn** [comment]
Thanks for your answer! Yes, I also saw this, that "year" is not part of the POM specification. This is a bit tricky and for me current year seems wrong.

**Comment by mikepenz** [comment]
for the automatic detection it seems to be impossible unless the poms would start to list the year which is most likely not gonna happen. 

So either keep the unknown year, replace with current year. Or you can specify it manually if you want to ensure you specify the year. 

Basically by modifying the various library you use.


If you have better suggestions I'd love to discuss any :)

**Comment by adrianlandborn** [comment]
Btw, I might have found another issue. License mapping do not work in all cases. Eg.
mit <-> MIT 
Apache-2 <-> apache_2_0

**Comment by mikepenz** [comment]
Thanks for reporting these. 

We try to map licenses as flexible as possible but sadly repos tend to not follow the standards so they slip through. 

Will add those variations :) 

```xml
if (name.contains("Apache") && url.endsWith("LICENSE-2.0.txt")) {
            return "apache_2_0"
        } else if (name.contains("MIT License")) {
            return "mit"
        } else if (name == "Android Software Development Kit License") {
            return "asdkl"
        } else if (name == "Eclipse Public License v2.0" || url == "https://www.eclipse.org/legal/epl-v20.html") {
            return "epl_2_0"
        } else if (name == "Crashlytics Terms of Service") {
            return "cts"
        } else if (name == "Fabric Software and Services Agreement" || name == "Answers Terms of Service") {
            return "fssa"
        } else {
            return name
        }
```

**Comment by mikepenz** [comment]
I believe with b06 I did the improvements currently the best. 

Improved matching for MIT and apache, added theoretical support for all SPDX identifiers. 

Also added a way for you to provide the license years for libraries you include. I would still love to automate this somehow, but right now I am in the believe this is out of scope. 

We might have an API(?) which scrapes the license info and tries to get the year. from the README. if somehow applicable. 

Not sure though if we really want to consider this due to performance / speed topics.

**Comment by mikepenz** [comment]
Apply a custom mapping with the year for the licenseId per line:
https://github.com/mikepenz/AboutLibraries/blob/develop/config/custom_license_year_mappings.prop

config the path to the configs: 
https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L64-L66

get all libraryIds as in your project:

```
 ./gradlew findLibraries --warning-mode all
```
