### ISSUE TITLE
License text(s) incorrect?

### ISSUE THREAD

**Issue by adrianlandborn** [mikepenz/AboutLibraries#470]
## About this issue
- Briefly describe the issue
I'm not completely sure but shouldnt the license text for Eg. Apache 2.0 license also include these rows. Because the 'License' should/must include version and year/date of original Apache license and not only the lib Copyright year and owner.

```
Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/
```
(source https://www.apache.org/licenses/LICENSE-2.0 and https://www.apache.org/licenses/LICENSE-2.0.txt)

And then to follow your layout move this part with copyright to the top.

```
Copyright [yyyy] [name of copyright owner]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
```

This should be valid for all licenses, not only Apache.

- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@adrianlandborn I fear that this information is even less available than the year of copyright. this is definitely not available in any datasets I am aware of. 


I suppose for apache it is always 2004. 
https://github.com/mikepenz/FastAdapter/blob/develop/LICENSE#L1-L4

**Comment by adrianlandborn** [comment]
@mikepenz yes, it is a bit tricky but Apache 2.0 is always 2004 (until they update it but in that case they will probably be 2.0+ or 3.X). I any case I am not sure that it is valid (from a legal point of view) if the year is not added? I have a collegue that has a bit more knowledge about this than me.

**Comment by mikepenz** [comment]
@adrianlandborn I would definitely love to hear about the legal aspect regarding the date. 

In any case I suppose it will most likely go to the single solution of this potentially be required to be provided manually if expected? 
The library offers the APIs to "enchant" data when data is not up 2 date. 

We made the experience that even if open source, people tend not to help with keeping those versions/years updated. and manually doing that is kind of problematic. 

so that's how the goal was to move forward with auto generating as much as possible with all the information somehow available. 

1 thing I could still think of which (most likely is not gonna work out for all things either) would be to follow the github link. try to find the LICENSE file for the active branch and include the details form that. but that may explode compile times :/

**Comment by adrianlandborn** [comment]
@mikepenz I am sure you have already seen this but is a nice read, even though I have to admit that I haven't read through avery part. Anyway there seems to be some Licences that could be added to https://github.com/mikepenz/AboutLibraries/tree/develop/library-definitions/src/main/res/raw

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository 

And here is also a bit more info on the legal part of open source. https://opensource.guide/legal/

**Comment by mikepenz** [comment]
So based on the POM spec the year is not relevant it seems: 
https://maven.apache.org/pom.html#Licenses (otherwise they would have added it. right?) 

As a second note. I believe I will adjust the code to identify licenses by the recommended spdx name or id: https://spdx.org/licenses/

and only make an exception for MIT and apache (to have better identification) 

Alternative we may be able to actually fallback to displaying the license information from the SPDX website (e.g. if we use a license which is not directly supported, load up the website)

**Comment by mikepenz** [comment]
It's actually interesting how little licenses: https://developers.google.com/android/guides/opensource is able to detect.

Not sure if it can detect any open source licenses for you, but for me it fails to find any. It would be good to figure what they display for name / year

**Comment by mikepenz** [comment]
With b06 I did the improvements to the license. If the full license information is there, the short header should be obsolete I believe.

**Comment by adrianlandborn** [comment]
Great. I have gone through some of your commits and they look good. Will try out the new relelease tomorrow at work. Hopefully it will resolve som of the issues we have. We have 123 dependancies in our project (most if them apache 2.0) so the date header is a nice addition.

One thing I came to think of with b05 is that since we only hade one lib under MIT licence which didn't match then the licence itself wasnt included in the apk. So when adding our own extra libraries with MIT licence then we had to add our own version of the MIT license. Not sure if you understand what I mean but I would suggest to include all license texts to the build or a way to provide/map the "licenseId" with a user-provided licence xml.

Btw, thanks for the work you are putting in.

**Comment by mikepenz** [comment]
I am glad that things look good. Really hope that we can work towards the most appropriate solution possible, to ensure it will get a lot easier for people to give proper attribution. (One thing I had in my head though is that it will be necessary a bit to re-brand the libraries README as now with the gradle plugin it is no longer only about the UI the library offers, but in general about the library information, which allows developers to easily build their own UI and access the information even if not using the provided UI) 

Oh I see what you mean. So I wonder though. is this library a dependency or an internal library? If it is a normal dependency you may consider providing a license mapping config (similar to the year one, just provide a file with the same name as linked into the config folder) https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/raw/custom_license_mappings.prop and specify the libraries ID with the license it is supposed to have. 

I understand it may be more convenient to include all license files, but after doing this the past (including with the (old, manual) meta information) I highly try not to do this, as it will lead to resources being in your project which will not be removed by R8 if not used. Just adding in size, ... 
The new version will try to really only include what's needed to keep things slim and fast :) 

Btw. in the very very very worst case and you need to have the license in your project. Have a look at the definitions (which practically could included as dependency, but you shouldn't) 
Just add the raw license information to your project: https://github.com/mikepenz/AboutLibraries/tree/develop/library-definitions/src/main/res/raw
and then the license information: 
https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/values/license_mit_strings.xml

And it will also be included. you would do that once and after that it will stay accessible. 

This also allows you to add any custom libraries you need... (one thing I believe is sadly not possible, is to overwrite the resources copied over from the gradle plugin. I think the resource priority is like:
```
library < app < generated from plugin
```
I am not 100% sure yet. Maybe in the future we may allow providing custom modifications as needed via the config folder. 


Thanks a lot!
Btw. Thank you too for contributing with your input! It is highly appreciated :)

**Comment by adrianlandborn** [comment]
I do not really follow what you mean with the README changes.

===============================

Where am i supposed to put the "custom_license_mappings.prop" to make it work? Putting it in a raw folder in my on project doesn't trigger the changes.
My current solution is this (and it is not good but i works)

_Problem_:
 **Apache-2** does not map to **apache_2_0**

_Solution_:
Create a local xml file (eg. oss_license_mods.xml) with:
```
  <string name="define_xcom_facebook_soloader__annotation">owner</string>
  <string name="library_xcom_facebook_soloader__annotation_libraryName">SoLoader</string>
  <string name="library_xcom_facebook_soloader__annotation_licenseId">apache_2_0</string>
```
 Add to builder 
`.withLibraryEnchantment("com_facebook_soloader__annotation", "xcom_facebook_soloader__annotation")`
Added the x in the files otherwise I get **duplicate resources** error 

Suggestions?

===============================

I agree it is not good to add all licenses to the build. As you say it will only add to apk size. 

===============================

Yes I tried to copy the raw license file and the license xml:s last week, not sure I was able to solve this.

**Comment by mikepenz** [comment]
I'm currently not around a computer. But I'll come back to you as soon as possible.

**Comment by adrianlandborn** [comment]
FYI
These files are spelled wrong. But I assume that wont cause any errors?
licen**c**e -> licen**s**e
```
licence_CC0_10_strings.xml	* move licenses also to the definitions module	27 days ago
licence_cc30_strings.xml	* move licenses also to the definitions module	27 days ago
licence_cc40_strings.xml	* move licenses also to the definitions module	27 days ago
```

**Comment by adrianlandborn** [comment]
> Yes I tried to copy the raw license file and the license xml:s last week, not sure I was able to solve this.

Managed to solve this now

**Comment by mikepenz** [comment]
@adrianlandborn the spelling won't cause errors, but we should fix it before going stable :D 

----------

Currently the README is focused around the UI the AboutLibraries provide, but with v8 it is more than that, as it will also be super useful if you just want to display the information, even though if you choose to use your own UI. 

----------

The `custom_license_mappings.prop` is a configuration for the plugin, so it is not something which ends up in your project. 

1.) config the aboutLibs plugin (specify the folder which will contain this file): https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L64-L66
2.) put the file with the name there. 
3.) fill the file with the information required

This will only provide the library information, no further steps needed. 

Using the library enchantment, as you did will work too. And I think adding the prefix or so is not that wrong.

**Comment by mikepenz** [comment]
@adrianlandborn are all the concerns (as far as possible) resolved with the latest beta? 

If yes we ma be able to close this one :)

**Comment by adrianlandborn** [comment]
Yeah, I am satisfied with changes! Thanks for doing this. You can close the issue. :)
