### ISSUE TITLE
Gradle plugin not working in JAVA

### ISSUE THREAD

**Issue by alan-insam** [mikepenz/AboutLibraries#475]
## About this issue

Gradle plugin only working with Kotlin? I used this library for months now, all my code is written in Java. I implemented the library WITHOUT the gradle plugin which looks like it is not recommended anymore as seen in the README. I used version 7.0.1 and included some libraries manually in xml files.

When migrating, I followed your guide and used version v8.0.0-rc02 for the library implementation. I have now seen, that all is written in Kotlin. That's why  tried Java && AndroidX | v6.2.3 version but the gradle plugin is not working. How can I use the Gradle plugin in Java?

## Details
- [7.0.1 ] Used library version
- [1.1.0 ] Used support library version
- [ 3.6.1] Used gradle build tools version
- [3.6.1 ] Used  Android Studio version
- [ not relevant] Other used libraries, potential conflicting libraries

## Checklist

- [x ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [yes, I need a java version tho] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The AboutLibraries v8 is only targeted towards kotlin users. Whereas it may be used from java users, it will bring kotlin with it. 

Old versions still can be used as is, but beside bugfixes those won't get any more changes.

The gradle plugin is not and won't be supported in previous versions.
