### ISSUE TITLE
Execution failed for task ':app:prepareLibraryDefinitions'.

### ISSUE THREAD

**Issue by beeline09** [mikepenz/AboutLibraries#476]
Android Studio Canary 4.1
Gradle wrapper version: 6.2.1-all
Build gradle version: 4.1.0-alpha01
AboutLibs Version: 8.0.0-rc02

When i add apply plugin: 'com.mikepenz.aboutlibraries.plugin' to app build.gradle, a get error:

> Execution failed for task 
':app:prepareLibraryDefinitions'.
Could not find matching constructor for: com.android.build.gradle.internal.scope.VariantScopeImpl(com.android.build.gradle.internal.scope.GlobalScope, com.android.build.gradle.internal.pipeline.TransformManager, com.android.build.gradle.internal.variant.ApplicationVariantData)

**Comment by mikepenz** [comment]
Seems they changed this API again in `4.1.0-alpha01` so it is currently not supporting that version

**Comment by mikepenz** [comment]
I looked in the API changes for those internal APIs and it seems with all those changes we won't be able to do it via this approach anymore. 

I am not yet sure what may allow us to add support again. but for now only 3.x and 4.0.x is supported

**Comment by mikepenz** [comment]
removed usage of internal APIs so all versions should now work. 

please update to v8.0.0-rc03
