### ISSUE TITLE
Possibility to add youtube channel, instagram, etc

### ISSUE THREAD

**Issue by manuelarte** [mikepenz/AboutLibraries#477]
## About this issue
I think it could be a nice feature to being able to add social media links
- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@manuelarte if you want to change the UI from what is offered, just use the core library and use the information provided by the library inside your own UI :) 

there are currently no plans to adjust beyond the very minimalistic `About this app` screen integrated.

**Comment by mikepenz** [comment]
Btw. theoretically if you do not want special there are APIs and ways to also modify the header provided. 

copy the xml for the header from the org project, and modify it (make sure original layouts and IDs stay the same) 

You can also look into the `LibsConfiguration` which allows to intercept various aspects of the provided UI and modify things for your usecase

**Comment by manuelarte** [comment]
Thanks @mikepenz
