### ISSUE TITLE
Generated strings spam the translations editor

### ISSUE THREAD

**Issue by binarynoise** [mikepenz/AboutLibraries#478]
## About this issue

Generated strings spam the translations editor so that it is hard to find my own strings
It would be great if you marked the generated Strings as untranslatable so they could easily be excluded 

## Details

 - Used library version 8.0.0-rc2
 - Used gradle build tools version 3.5.3
 - Used tooling / Android Studio version IntelliJ IDEA 2019.3.3 (Community Edition)
 - other libs:
```
'androidx.appcompat:appcompat:1.1.0'
'androidx.cardview:cardview:1.0.0'
'androidx.constraintlayout:constraintlayout:1.1.3'
'androidx.preference:preference:1.1.0'
'androidx.recyclerview:recyclerview:1.1.0'
'com.github.topjohnwu.libsu:core:2.5.1'
'com.github.topjohnwu.libsu:io:2.5.1'
'com.google.android.material:material:1.1.0'
```

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by binarynoise** [comment]
I just found a temporary solution:
If you double click on the Resource Folder column header you can sort it and then my own strings appear on top

**Comment by mikepenz** [comment]
I hope the definition in the header of the file works, because adding it to every single entry sounds overkill

**Comment by binarynoise** [comment]
Nope, that doesn't work. You need to apply it to every single string
And it should be without the `tools:` namespace. `translatable="false"` is enough

**Comment by mikepenz** [comment]
Ok done in v8.0.0-rc04

**Comment by binarynoise** [comment]
Thanks. This helps me a lot!
Still missing the flag are the following strings:
```
config_aboutLibraries_plugin
define_license_Apache_2_0
license_Apache_2_0_licenseName
license_Apache_2_0_licenseWebsite
license_Apache_2_0_licenseShortDescription
define_license_mit
license_mit_licenseName
license_mit_licenseWebsite
license_mit_licenseShortDescription
```

**Comment by mikepenz** [comment]
I added it to all license files now too @binarynoise try out v8.0.1
the config will left over I believe :D

**Comment by mikepenz** [comment]
v8.0.2 will handle this last one too :D
