### ISSUE TITLE
Unable to load class 'org.gradle.internal.deprecation.DeprecatableConfiguration'.

### ISSUE THREAD

**Issue by Direwolfik** [mikepenz/AboutLibraries#481]
## About this issue

As of version 8.0.0-rc03 gradle build **with plugin** crashes with:
`Unable to load class 'org.gradle.internal.deprecation.DeprecatableConfiguration'.`

8.0.0-rc02 builds ok. Without plugin it builds ok too.

## Details
- Used library version 8.0.0 (happens since 8.0.0-rc03)
-  Used support library version androidx 1.1.0
- Used gradle build tools version 3.6.1 with gradle wrapper 5.6.4
- Used tooling / Android Studio version 3.6.1

**Comment by mikepenz** [comment]
could you please try with a gradle 6.x version?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/AboutLibraries/blob/919ff4d4c9cea8f9e3574cd2bc322817aaa0d596/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/DependencyCollector.kt#L68-L81

**Comment by Direwolfik** [comment]
I confirm that it works with gradle 6.2.x

I suppose it would be great to mention it in README tho, because gradle 5.6.4 seems to be baseline for current gradle plugin 3.6.0+ (https://developer.android.com/studio/releases/gradle-plugin).

Thank you for your response!

**Comment by mikepenz** [comment]
Oh yeah I was not aware myself that it would be breaking with gradle 5.6. 
I changed it away from a different API used before which would not work with gadle 4.1.0 and hoped the new approach would not be using anything gradle version specific. 

gradle loves to change their APIs

Will see if I can somehow figure out a way to do it with gradle 5.6

**Comment by binarynoise** [comment]
Would it be possible to use a gradle version check just like in Android (`if (Build.VERSION.SDK_INT >= 29) ...`) ?
