### ISSUE TITLE
How to migrate from 7.x.x to 8.x.x

### ISSUE THREAD

**Issue by systemallica** [mikepenz/AboutLibraries#487]
## About this issue

- I cannot find detailed documentation on how to upgrade.
- I get an error `unresolved reference: withActivityStyle`. It seems that this method is not available anymore.

```
 LibsBuilder()
              .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
              .withAutoDetect(true)
              .withAboutIconShown(true)
              .withAboutVersionShown(true)
              .start(activityContext)
```

## Details

Used UI and plugin version: 8.1.0

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@systemallica this is correct `withActivityStyle` does no longer exist, `withAutoDetect` should also be removed as the gradle plugin is not the preferred approach to detect dependencies. 

If you want to style your aboutLibraries have a look at the styling section: https://github.com/mikepenz/AboutLibraries#style-the-aboutlibraries-%EF%B8%8F

**Comment by systemallica** [comment]
Alright thanks
