### ISSUE TITLE
Consider adding MPL to okhttp

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#491]
## About this issue

okhtp is itself Apache-licensed however it contains MPL-licensed list of public suffices https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/okhttp3/internal/publicsuffix/NOTICE
Since okhttp is widely used I think it is worth considering adding an entry about public suffix list automatically by AboutLibraries when okhttp is used.

## Details
- Used library version: 8.1.1
- Other used libraries: okhttp 4.5.0

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Not sure how we should resolve this :/ based on the current setup a library usually only has 1 license. :/ 

theoretically the whole element should handled as a full standalone dependency. 

but I have yet to see a single project which actually notes this MPL element of okhttp :/

**Comment by koral--** [comment]
According to the POM specification it can contain multiple licenses: https://maven.apache.org/pom.html#Licenses

So it seems that AboutLibraries should be able to handle such cases perhaps. Currently only the first one seem to be taken into account. So regardless this particular okhttp case it may be a good idea to support multiple licenses for a single artifact.

Indeed I have no exact idea how to display that. The simplest way is probably to just insert a separate list item for each license.
WDYT?

**Comment by koral--** [comment]
The initial issue (like with public suffix list) seems to be fixable by pseudo-libraries like https://github.com/DroidsOnRoids/public-suffix-mpl.

Not sure what about supporting multiple licenses. Maybe we should close this issue and create a new one for that case?

**Comment by mikepenz** [comment]
Yes I think it makes sense to open a feature request to allow for multiple licenses for a library. 

Additionally I still would love at some point to provide some form of "library-merging" if we for example talk about the same library but just different modules of itself
