### ISSUE TITLE
Android.view.InflateException: Binary XML file line #46 in :layout/listheader_opensource:

### ISSUE THREAD

**Issue by imranbaigshortcut** [mikepenz/AboutLibraries#493]
## About this issue

I am continuously getting  Android.view.InflateException: Binary XML file line #46 in :layout/listheader_opensource on runtime although my project includes
    **implementation "com.google.android.material:material:1.0.0"**

**Exception**
android.view.InflateException: Binary XML file line #46 in 
<xxxx app package>:layout/listheader_opensource: 

Binary XML file line #46 in <xxxx app package>:layout/listheader_opensource: Error inflating class com.google.android.material.button.MaterialButton
    Caused by: android.view.InflateException: 

Binary XML file line #46 in <xxxx app package>:layout/listheader_opensource: Error inflating class com.google.android.material.button.MaterialButton

**Comment by mikepenz** [comment]
Please try material 1.1.0. Also make sure your activity uses the material theme as parent

**Comment by imranbaigshortcut** [comment]
setting the activity theme to this solved the issue
android:theme="@style/Theme.MaterialComponents.Light.NoActionBar"
