### ISSUE TITLE
Auto Detection skipping libraries with no name

### ISSUE THREAD

**Issue by Zardozz** [mikepenz/AboutLibraries#494]
## About this issue

- Auto Detection skips Libraries with no name even if they have a valid license to report.  
The `Name` attribute is not consider basic information according to https://maven.apache.org/pom.html

A Default sensible fallback `Name` should be used if no name is found, quite often the name is the same as the `artifactId` or if you want more unique a combination of `groupID` and `artifactId`

Log output of of an Example failure by running `gradlew findLibraries -d`

``` lang-xml
22:33:28.883 [DEBUG] [com.mikepenz.aboutlibraries.plugin.AboutLibrariesProcessor] Processing artifact result tableview.pom (com.evrencoskun.library:tableview:0.8.9.3)
22:33:28.883 [DEBUG] [com.mikepenz.aboutlibraries.plugin.AboutLibrariesProcessor] --> ArtifactPom for [com.evrencoskun.library:tableview]:
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.evrencoskun.library</groupId>
  <artifactId>tableview</artifactId>
  <version>0.8.9.3</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>androidx.annotation</groupId>
      <artifactId>annotation</artifactId>
      <version>1.1.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>androidx.core</groupId>
      <artifactId>core</artifactId>
      <version>1.1.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>androidx.recyclerview</groupId>
      <artifactId>recyclerview</artifactId>
      <version>1.1.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://github.com/evrencoskun/TableView/blob/master/LICENSE</url>
    </license>
  </licenses>
</project>



22:33:28.884 [DEBUG] [com.mikepenz.aboutlibraries.plugin.AboutLibrariesProcessor] --> No Artifact Parent Pom found for [com.evrencoskun.library:tableview]
22:33:28.884 [QUIET] [system.out] Could not get the name for com_evrencoskun_library__tableview, Skipping
```

- To reproduce, Find a package that has a license but no Name in the pom xml.
The example of com.evrencoskun.library:tableview:0.8.9.3 is local version in my m2 cache where I added the license URL.  There is a complicated procedure to reproduce this with this package but a probably easier way is to get a package in the the Maven Cache, Edit the pom in the cache to remove the Name Attribute if it has one and then add `mavenLocal()` to your repository list and run gradle with the --offline flag

## Details
- [8.1.1 ] Used library version
- [androidx.appcompat:appcompat:1.2.0-beta01 ] Used support library version
- [com.android.tools.build:gradle:3.6.1 ] Used gradle build tools version
- [3.6.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ X ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ X ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ X ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ X ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ X ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

But there is no MIGRATION GUIDE for 8.x in the listed location :smirk:

**Comment by mikepenz** [comment]
@Zardozz thank you so much for this report. it is great. I will have a look at this and have hopefully an update this weekend

**Comment by Zardozz** [comment]
It should be a very simple change to change the test at https://github.com/mikepenz/AboutLibraries/blob/develop/plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesProcessor.groovy#L225

From 
```
if (!isNotEmpty(libraryName)) {
            println "Could not get the name for ${uniqueId}, Skipping"
            return
        }
```

To something like
```
if (!isNotEmpty(libraryName)) {
            println "Could not get the name for ${uniqueId}, Using ${groupId}:${artifactPom.artifactId}"
            libraryName = "${groupId}:${artifactPom.artifactId}"
        }
```
