### ISSUE TITLE
Gradle Plugin Info Documentation improvement about over/under detection of licenses

### ISSUE THREAD

**Issue by Zardozz** [mikepenz/AboutLibraries#495]
## About this issue

I've migrated from the previous 7.x library to 8.1.1 and the number of Licenses identified has grown massively and a lot were not reproduced and distributed in my App.

While these are all Apache 2 license and not harmful, it just might be a shock to some and questions might be raised about the validity of the plugin.  For example I wondered why it showed the License for ` Support View Pager` when I know my App does not use that functionality.

After some investigation, I determined that most of these comes in because of the default inclusion of androidx.appcompat:appcompat and is pretty much unavoidable due to Google Packaging Structure, even if the functionality and code is never used and might not actually be included in your app e.g. especially with `minifyEnabled=true` (so it could be argued that some of these Licenses don't need to be included?)

I think that AboutLibraries needs some more explanation in the Documentation/Readme.md about why Licenses are included and why there might be more or less than you think.  
This is to head off any question on it's detection correctness.

Also there should be included some information about Debug build, because Debug builds include information about `testImplementation` and `androidTestImplementation` dependencies even if you are not doing any testing and for `androidTestImplementation` the dependencies are actually included in a separate APK file that is not part of your App.

Below is my thoughts on some additional documentation for the Gradle plugin section of the Readme.md

> Some of what the plugin identifies for Attribution might not be reproduced and distributed in your App, it also might fail to identify Licenses if the packages don't include their License details.
> Careful optimisation of your build.gradle dependency section should be considered along with a review of all Licenses identified and a review of the `findLibraries` Gradle Task output.
> Debug builds will also include Licenses from packages identified as "testImplementation" and "androidTestImplementation"
> Some high level packages like androidx.appcompat:appcompat can cause the inclusion of large number of Licenses because of their structure.

Below is an example of what I consider is over detection with minifyEnabled=true 

Below is the list of the Licenses reported by `exportLibrariesRelease` for Project created using the "Empty Actvity" wizard in Android Studio 3.6.1

> LIBRARIES:
> Android Arch-Runtime;androidx.arch.core:core-runtime:2.0.0;Apache_2_0
> Support Cursor Adapter;androidx.cursoradapter:cursoradapter:1.0.0;Apache_2_0
> Support AnimatedVectorDrawable;androidx.vectordrawable:vectordrawable-animated:1.1.0;Apache_2_0
> Android Lifecycle LiveData;androidx.lifecycle:lifecycle-livedata:2.0.0;Apache_2_0
> Android ConstraintLayout Solver;androidx.constraintlayout:constraintlayout-solver:1.1.3;Apache_2_0
> SavedState;androidx.savedstate:savedstate:1.0.0;Apache_2_0
> Android Lifecycle-Common;androidx.lifecycle:lifecycle-common:2.1.0;Apache_2_0
> Support compat;androidx.core:core:1.1.0;Apache_2_0
> Android Lifecycle Runtime;androidx.lifecycle:lifecycle-runtime:2.1.0;Apache_2_0
> Support fragment;androidx.fragment:fragment:1.1.0;Apache_2_0
> Support Drawer Layout;androidx.drawerlayout:drawerlayout:1.0.0;Apache_2_0
> Support loader;androidx.loader:loader:1.0.0;Apache_2_0
> Support Custom View;androidx.customview:customview:1.0.0;Apache_2_0
> Support Annotations;androidx.annotation:annotation:1.1.0;Apache_2_0
> Support View Pager;androidx.viewpager:viewpager:1.0.0;Apache_2_0
> Support collections;androidx.collection:collection:1.1.0;Apache_2_0
> Android Arch-Common;androidx.arch.core:core-common:2.1.0;Apache_2_0
> Android Resources Library;androidx.appcompat:appcompat-resources:1.1.0;Apache_2_0
> Android Lifecycle ViewModel;androidx.lifecycle:lifecycle-viewmodel:2.1.0;Apache_2_0
> Android Lifecycle LiveData Core;androidx.lifecycle:lifecycle-livedata-core:2.0.0;Apache_2_0
> Support VectorDrawable;androidx.vectordrawable:vectordrawable:1.1.0;Apache_2_0
> Support Interpolators;androidx.interpolator:interpolator:1.0.0;Apache_2_0
> Activity;androidx.activity:activity:1.0.0;Apache_2_0
> Android ConstraintLayout;androidx.constraintlayout:constraintlayout:1.1.3;Apache_2_0
> VersionedParcelable;androidx.versionedparcelable:versionedparcelable:1.1.0;Apache_2_0
> Android AppCompat Library v7;androidx.appcompat:appcompat:1.1.0;Apache_2_0

E.g. things like ` Support View Pager` won't be used but impossible to remove due to the structure of Google's Packages.

- This can be easily reproduced, in Android studio, Create a New project using the "Empty Activity" template, Select Language "Java", Select Minimum API as "22".
Add aboutLibraries to the Project  build.gradle dependencies, also apply the aboutLibraries plugin in the App build.gradle  
Run exportLibraries

## Details
- [ 8.1.1 ] Used library version
- [ androidx.appcompat:appcompat:1.1.0 ] Used support library version
- [ 3.6.1 ] Used gradle build tools version
- [ 3.6.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

## Checklist

- [ X ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ X ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ X ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ X ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ X ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@Zardozz I believe that being over inclusive is important. especially as if a library is used in your build pipeline code ends up in the project and that's what makes you require to give attribution. 
It does not really matter if used in the end, if a piece of it's code is in the app attribution is required, and that's usually the case if the dependency is linked as a sub dependency :) 

The latest versions of the app split the licenses based on the build variant so debug will only contain what debug had while compiling. There seems to be something else if test dependencies show up in normal debug build variants. 

Btw. you can always see which and how dependencies are in your project by using:


```
./gradlew app:dependencies
```

it will list the dependency tree per flavor

**Comment by Zardozz** [comment]
This was not a request to change the behaviour of possible over inclusion just really to a request to highlight in documentation that auto detection by the plugin could possibly not be 100% correct for various reasons and really the result should be manually reviewed.

The arguments on whether the attribution is required if you referenced it at the start of the build pipeline but it never made it to the end to trigger the "and distribute" clause of some licenses is a question for lawyers and not the tooling.

Having worked at a BIG$CORP in the past with lawyers on License detection and Licensing issues, the key is for you to review the result of any tooling detection.

The documentation improvement ways also an attempt to help head off issues being raised about why the plugin did or did not include a particular license and give a possible common example of "grey" areas that might raise questions.

**Comment by mikepenz** [comment]
@Zardozz makes absolute sense :) 

Beside the clarifications I still wonder about:

> Debug builds will also include Licenses from packages identified as "testImplementation" and "androidTestImplementation"

I think this should not be the case, and I wonder if there is a bug or a problem in the configuration / something how gradle builds the dependency tree

**Comment by Zardozz** [comment]
I don't think there is a bug about the "Debug builds will also include Licenses from packages identified as "testImplementation" and "androidTestImplementation".

This type of tooling tends to "overload" the information compilers/build tool chain needs to do it's job to come up with a good starting point for what should be Attributed (I've not checked the code to see exactly how it is done in aboutLibraries, but used my experience how I did it in the past for Maven/Nuget/NPM/and other packages) 

The information set of what the compiler/build tool chain needs is not a perfectly over lapping set with License Attribution set, so this comes back to the manual review and understanding.

Most of the time their is no negative effect with a lot of license types in claiming to use a particular package when lawyers might be able to argue that you don't because they were in the non distributed test code.

BUT there could be instance where this is not true. I have seen instances where commercial licensed code has illegally re-badged (as open source Licensed) 

So I would just again highlight in the documentation this behaviour to head of any questions and make people aware of this behaviour is probably the best course of action.

If there was some functionality to be added to aboutLibraries to cover all eventualities, it would be the ability to manually exclude a package license information from display that the plugin had detected, this would match the functionality you already have to include additional License details.

**Comment by mikepenz** [comment]
Added a disclaimer section to the README which hopefully clarifies potential questions regarding this. 

Thank you again for bringing this issue up. Any improvement to simplify and correct giving credits is always appreciated
