### ISSUE TITLE
8.1.1 clashes with cardviews in coordinatorlayout

### ISSUE THREAD

**Issue by Testator** [mikepenz/AboutLibraries#496]
## About this issue

Updating to the new version 8.1.1 makes my cardview that is in a coordinatorlayout disappear
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please follow the issue template. the provided information is not enough to look into this. 

this library does not have any cardviews. nor does it use a coordinatorlayout

I suppose you may need to adjust how you added the `DrawerLayout` to your project. 

v8 of this library will no longer manage the root view automatically and that is now fully in your control
