### ISSUE TITLE
No right window insets on landscape mode

### ISSUE THREAD

**Issue by marcauberer** [mikepenz/AboutLibraries#500]
## About this issue
If the edgeToEdgeMode and the landscape mode are enabled, it looks like this:

![Screenshot](https://user-images.githubusercontent.com/59527509/83331351-0a4f8880-a296-11ea-8d44-cfe6fb5ac550.png)

I don't think, this should be this way. The right side gets cropped off.

## Details
- [X] Used library version: 8.1.3
- [X] Device: Google Pixel 3a
- [X] Gradle plugin version: 4.0.0
- [X] AS version 4.0

## Checklist
- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by marcauberer** [comment]
Thanks for fixing!

**Comment by mikepenz** [comment]
uploading v8.1.6 right now.

Thanks for reporting.
