### ISSUE TITLE
Some dependencies not detected

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#501]
## About this issue

UPDATE:
see https://github.com/mikepenz/AboutLibraries/issues/501#issuecomment-637460667

Multi-module project layout as follows:
```
:app (Android app module)
- dependency1 (library recognized correctly by AboutLibraries)
- :lib1 (Android library module)
-- dependency2 (library NOT recognized)
```

dependency2 is declared only in some library modules (not in the app module directly) using `implementation` configuration.
It is not present in output of `findLibraries` nor `exportLibraries` tasks.
AboutLibraries gradle plugin is applied to :app module. No custom configuration.
Not sure if all such transitive dependencies are affected but it is true for few randomly chosen.

It worked at most in 8.0.0-a02 because I've reported another issue here with displaying author of one of the libraries which are now missing (https://github.com/mikepenz/AboutLibraries/issues/459).
AFAIR since that project layout has not changed, only the dependency versions incl. AboutLibraries, Gradle and AGP.

## Details
- Used library version: 8.1.6, with Gradle plugin
- Used gradle build tools version: 6.5-milestone-1
- Used tooling / Android Studio version: 4.1.0-alpha10

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@koral-- I believe that this changed with us stopping to use internal APIs which break with every single change of the android plugin to the proper available APIs from gradle which will stay more stable. 

We need to setup a sample and look at it. but I believe I tested it with a newer version in one of the SDKs I help in and it worked also on sub dependencies. so not sure yet what it may be. 


something implementation vs api?

**Comment by koral--** [comment]
OK. I'll try to create a sample which reproduces this issue.

Regarding `implementation` vs `api` as I wrote in 1st post, currently there is an `implementation` and it has not changed.
It starts working again if I add the same dependency with `implementation` scope to app module.

**Comment by koral--** [comment]
@mikepenz I was able to reproduce the same issue even without transitive dependency. Reason seem to be different.

Steps to reproduce:
* add this dependency to app module in the sample app on current develop: `implementation group: 'com.google.zxing', name: 'core', version: '3.4.0'`

`ZXing Core (3.4.0) -> com_google_zxing__core` is printed to the console when running `findLibraries` task. However, `com_google_zxing__core` is not added to generated XML.

**Comment by mikepenz** [comment]
that's interesting. thanks for your additional investigation.

I'll need to debug that to see what may goes on. but I believe this info will already greatly help

**Comment by mikepenz** [comment]
Hmmm are you sure? 

If I add it to the sample app it works for me :/ 
Some caching issue? did you do a clean build?

**Comment by mikepenz** [comment]
![image](https://user-images.githubusercontent.com/1476232/83944877-0cba6100-a807-11ea-83cb-c7181a5ea78c.png)

**Comment by koral--** [comment]
Indeed it looks like cache/daemon issue in case of zxing (on clean build it shows up). However, is still reproducible also on clean build. I'll try to isolate a minimal sample which reproduces the issue.

**Comment by koral--** [comment]
@mikepenz branch linked above reproduces this issue for me. Even on clean build.
Dependency is added using implementation scope to library module.

**Comment by mikepenz** [comment]
I think I found what this behavior was caused by v8.2.0 should fix this :)
