### ISSUE TITLE
overwrite License owner

### ISSUE THREAD

**Issue by markush473** [mikepenz/AboutLibraries#503]
## About this issue

First of all: Thank you, for this useful library/plugin.

Is there a way to overwrite the owner of a license? 
Currently some only state "OWNER", and I would like to correct that.
Can this be done per mapping file, similar to "year"(custom_license_year_mappings.prop)?

## Details
- [8.1.2] Used library version
- [8.1.2 ] Used support library version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@markush473 currently there is no file for the owner, but you could "enchant" the ones programmatically. 

When you launch you can define various things to overwrite: 
https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.kt#L175

You need the identifier for the libs (you can get it via the gradle task) and then `LibraryFields.AUTHOR_NAME` should do what you need :)

**Comment by markush473** [comment]
@mikepenz Thank you, for the fast response, but this only changes the author's name.

I want to overwrite the owner, that is displayed in the copyright notice at the top of the licence text (Apache Version 2.0) 

It currenty says:
Copyright © 2020, OWNER
All rights reserved
...

**Comment by mikepenz** [comment]
do you have by any chance a library which misses the owner? 
theoretically the author should be used from the pom file for this

**Comment by markush473** [comment]
This problem seems to only appear with some libraries. 
Some of them are:
javax.inject 1
Okio 1.15.0
transport-backend-cct 2.2.1
Gson 2.8.4
firebase-installations 16.2.1
firebase-crashlytics 17.0.0

**Comment by mikepenz** [comment]
v8.2.0 allows for overwriting the library owner with the same approach as the year mappings :)

**Comment by markush473** [comment]
Thank you very much! That is awesome! :)
