### ISSUE TITLE
Add support for multiple licenses per single library

### ISSUE THREAD

**Issue by koral--** [mikepenz/AboutLibraries#506]
Follow-up of #491 

According to the POM specification it can contain multiple licenses: https://maven.apache.org/pom.html#Licenses

So it seems that AboutLibraries should be able to handle such cases perhaps. Currently only the first one seem to be taken into account (https://github.com/mikepenz/AboutLibraries/blob/c550624d1340f022c23a973567b4cd84ac9cc1cd/plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesProcessor.groovy#L209). So it may be a good idea to support multiple licenses for a single artifact.

Indeed I have no exact idea how to display that. The simplest way is probably to just insert a separate list item for each license.

**Comment by mikepenz** [comment]
In the "simple" viewer it will be easier as the license is displayed when you press. but for the one which tries to show everything at once it may get a little bit limiting :D
