### ISSUE TITLE
[Question][Android] Toolbar back arrow and title color

### ISSUE THREAD

**Issue by marcqtan** [mikepenz/AboutLibraries#508]
Hello, how can we be able to customize the title and back arrow color of the toolbar? I'm using this                 
`       .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)`

but the toolbar text is White. I want to change it to my apps' primary color

I'm using: implementation "com.mikepenz:aboutlibraries:6.2.3" 

Fullcode:

```
                        new LibsBuilder()
                        //provide a style (optional) (LIGHT, DARK, LIGHT_DARK_TOOLBAR)
                        .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
                        .withAboutIconShown(true)
                        //.withAboutAppName(activity.getString(R.string.app_name))
                        .withAboutDescription("Libraries Used")
                        .withActivityTitle("license title")
                        .withAboutVersionShownCode(true)
                        .withAboutVersionShownName(true)
                        .withLicenseDialog(true)
                        .withLicenseShown(true)
                        //start the activity
                        .start(activity);
```

Thanks!

**Comment by mikepenz** [comment]
You want to change only the color for AboutLibraries?

Beside changing the general theme you can also adjust more theme colors for the `LibsActivity`

https://github.com/mikepenz/AboutLibraries/blob/v6.2.3/app/src/main/res/values/styles.xml#L3

As you can see it uses genera theme attributes from your apps theme: https://github.com/mikepenz/AboutLibraries/blob/v6.2.3/library/src/main/res/layout/activity_opensource.xml#L7

So if you adjust those the colors will also chagne

**Comment by marcqtan** [comment]
I want to change the text to another color (e.g yellow)

<img width="209" alt="Screen Shot 2020-06-15 at 8 20 03 PM" src="https://user-images.githubusercontent.com/66229352/84656701-af7c8900-af45-11ea-8551-0acbe5c33a23.png">

**Comment by mikepenz** [comment]
If you want full custom style I'd suggest to use the fragment API and embed it in an activity with your own custom toolbar :)

**Comment by marcqtan** [comment]
> If you want full custom style I'd suggest to use the fragment API and embed it in an activity with your own custom toolbar :)

I just want to change the text color only. :D

**Comment by mikepenz** [comment]
usually this is done by themes. you define the theme which will then be used by the Toolbar component. this is nothing special to this library :) 

you can also copy paste the activity layout from above to your project (keep the same name) and modify the colors

**Comment by marcqtan** [comment]
Thanks. It's working now using customized styles attribute. :D
