### ISSUE TITLE
`aboutLibrariesWindowBackground` not being applied

### ISSUE THREAD

**Issue by mgray88** [mikepenz/AboutLibraries#509]
## About this issue

`aboutLibrariesWindowBackground` not being applied. Using a fragment. Frankly I've search through the code and I don't even see where this attribute is applied

## Details
- [ ] Used library version: 8.2.0
- [ ] Used support library version
- [ ] Used gradle build tools version: 4.0.0
- [ ] Used tooling / Android Studio version: 4.0.0
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@mgray88 there is a high chance I missed to remove this one after upgrading to v8 which refactored the styling portion of the lib. 

I'll have a look and remove it. thanks for the report

**Comment by mgray88** [comment]
Also the README
https://github.com/mikepenz/AboutLibraries/blob/develop/README.md#L156
