### ISSUE TITLE
Combine dependencies?

### ISSUE THREAD

**Issue by mgray88** [mikepenz/AboutLibraries#510]
## About this issue

Is there a way to combine dependencies? The only thing I see is `shouldSkip(uniqueId)` but that is very specific to your library.

If this isn't implemented anywhere my thoughts were have another config file that maps ids to a new id. Maybe simpler would be use the name mappings, where if multiple libraries map to the same name, they are consolidated to the same entry?

My particular use case is the Splitties set of libraries. There are 20+ entries that look almost exactly the same, and I wanted to consolidate them under one entry

## Details
- [ ] Used library version - 8.2.0
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@mgray88 thanks for the report. currently we do not yet have a feature which would merge together libraries. 

But that is actually something on our roadmap as more libraries have a huge set of libraries in different modules

**Comment by mgray88** [comment]
I was actually just about to fork and see if I could implement something that would work for me. If I can get something working and submit a PR is there a direction you suggest I go in?

**Comment by mikepenz** [comment]
@mgray88 sounds great. 

I am not yet 100% sure if this is solely a feature which would only be for the gradle plugin or if we should do it in the kotlin library code. 

Advantages in the kotlin library code is that it will also apply for other libraries passed in manually and I suppose configurations would be better fitted and allow for greater flexibility

the main question is if it would be mainly an exclusion or more a merge functionality?

Exclusion is basically already given via: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L116

**Comment by mgray88** [comment]
I can see arguments for both gradle and kotlin. I'm thinking one way might be include all by default in the core library, but in the ui library, use the `libraryComparator` to unique the list of libraries (custom user comparator with regex?). For the plugin, potentially another config file? An idea I haven't fully fleshed out yet. Or maybe a gradle plugin setting that modifies how already existing data is processed? Or (and I'm not a fan of this one) add another field to the enchant mapping file that is pulled out in the gradle processing. (personally I don't like cluttering up my `res` folder with library definitions)

As for the exclusion I'd actually love to see this functionality pulled out into the plugin instead of in code. I'm sure there's a valid use case for having it in code, however it fractures the data set and makes it a bit harder to grok what's being presented

I think merge would be more the desired result of this added functionality? My predilection is towards including this in the gradle plugin, as I think it ideal to have all the configuration in one place

**Comment by mikepenz** [comment]
Thanks again for your PR :) Your changes are part of v8.3.0
