### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by mueller-ma** [mikepenz/AboutLibraries#512]
## About this issue

In #507 @mikepenz wrote:

> thank you for the PR. but starting with v8 of the AboutLibraries this is no longer necessary :)
> The gradle plugin will make sure to pull the relevant information from the POM file.
> If there is some information not properly maintained by that library in the POM file it would be interesting which particular thing is missing / what needs adjustment

However the docs still say that a definition file is required: https://github.com/mikepenz/AboutLibraries/wiki/HOWTODEV:-Include-in-your-library

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I have added a note that it is deprecated and no longer needed for v8

**Comment by mikepenz** [comment]
Thanks for the report :)
