### ISSUE TITLE
Adding help for creating POM information

### ISSUE THREAD

**Issue by cyb3rko** [mikepenz/AboutLibraries#513]
## About this issue

Referring to #512:
Maybe you could also briefly include an explanation, how to include information about own libraries in a POM file, so that AboutLibraries can detect those information.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@cyb3rko so in this regards. basically if you create a library, it is suggested that you make use of the POM specification and fill as much information as possible. E.g. author, name, license, ...
And the plugin will automatically pick it up

https://maven.apache.org/pom.html

Also look into the spec on data like licenses:
https://maven.apache.org/pom.html#Licenses

**Comment by cyb3rko** [comment]
Oh ok, thanks.
I asked because I want to add information via POM to an existing library.
I hope I can find it now, thanks!

**Comment by mikepenz** [comment]
If it is not your library and you want to add information to your project that is a bit of a different topic. 

Usually information from maven should be sufficient. but in some cases that's sadly not the case. 

so for these you can still do the library definition file (as linked above, the old approach) and then "enchant" a library with this information. 

There are various files to add information to a library:
https://github.com/mikepenz/AboutLibraries#gradle-plugin-configuration

or you can do it programmatically to add pieces of information to a library:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L373

**Comment by cyb3rko** [comment]
I think you missunderstood me, the library owner asked me to implement the information to his open source library by opening a new PR, so I think it is not that hard.

**Comment by cyb3rko** [comment]
I want to improve the library by directly coding IN the library code.
Where exactly do I include all the things that are listed on the [site you sent](https://maven.apache.org/pom.html)?

And where did you include them e.g. in this library here? Do they belong in the gradle.properties (because if you search for "POM" in this library here in the gradle.properties you can find that you included some POM information in the gradle.properties)?

**Comment by mikepenz** [comment]
Well that really depends on the setup of that library. there are many ways for a dev to set that up. 

I usually have the infos in the gradle.properties. but I also had projects where I did it within gradle 

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/gradle.properties
https://github.com/mikepenz/FastAdapter/blob/develop/gradle.properties

**Comment by cyb3rko** [comment]
Ok, thanks a lot!
