### ISSUE TITLE
Customizing toolbar color and background color

### ISSUE THREAD

**Issue by kylec0231** [mikepenz/AboutLibraries#514]
## About this issue
I followed ReadMe and successfully applied custom to aboutlibraries attributes but I would like to know more customs on these below.

Question
- how to customize toolbar color and background color
![image](https://user-images.githubusercontent.com/44420319/87185334-3146a480-c2af-11ea-8c25-21bc0429295e.png)
yellow - (assuming) Toolbar
blue - (assuming) background
green - (assuming) some kind of title background?

## Details
- [8.3.0] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [Y] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [Y ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)

**Comment by mikepenz** [comment]
The toolbar uses the normal toolbarStyle: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/activity_opensource.xml#L10

and blue and green are the same background

**Comment by mikepenz** [comment]
I hope this link helped :)
