### ISSUE TITLE
No proper library name shown

### ISSUE THREAD

**Issue by cyb3rko** [mikepenz/AboutLibraries#518]
## About this issue

I implemented my own library (which is still in development), and I recently added information via POM:

```
...

# Additional Information
GROUP=com.github.cyb3rko

POM_NAME=About Icons Library
POM_DESCRIPTION=Android library to easily give credits if using icons which require attribution
POM_URL=https://github.com/cyb3rko/about-icons

POM_SCM_URL=https://github.com/cyb3rko/about-icons
POM_SCM_CONNECTION=scm:git@github.com:cyb3rko/about-icons.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:cyb3rko/about-icons.git

POM_GITHUB_REPO=cyb3rko/about-icons
POM_GITHUB_README=README.md

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=cyb3rko
POM_DEVELOPER_NAME=Cyb3rKo
```

<br/>

I think I did everything in the correct way but why is the name of the library shown as following:

<img src="https://user-images.githubusercontent.com/46033730/87727128-abe85600-c7c0-11ea-94ff-9bc828ed437e.jpg" width="350">

I really don't understand what I have done wrong...

## Details
- [8.3.0] Used library version
- [ ] Used support library version
- [29.0.3] Used gradle build tools version
- [Android Studio 4.0 (Build 193.6911.18.40.6514223)] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
how does the published pom look like? Couldn't find the lib on maven central or bintray

See the name here in the fastadapter pom: https://repo1.maven.org/maven2/com/mikepenz/fastadapter/5.2.1/fastadapter-5.2.1.pom

perhaps you got somewhere a different property where the name is not yet set properly

**Comment by cyb3rko** [comment]
Oh I see the problem.
Here's the POM: https://jitpack.io/com/github/cyb3rko/about-icons/70c2a0c/about-icons-70c2a0c.pom

There the wrong name is shown, so how do I change it?
Is `POM_NAME=About Icons Library` in the gradle.properties not working?

**Comment by cyb3rko** [comment]
Oh, you have set the `POM_NAME=...` in the gradle.properties in the library folder.
Is this the solution?

**Comment by mikepenz** [comment]
possibly. really always depends on your setup :) there are many ways to have publishing to maven configured.

**Comment by cyb3rko** [comment]
What do you mean with "setup"?

I tested everything now and nothing changes the library name.
(For further information: I just publish my project to GitHub and let Jitpack do the rest; I think that's what you call "setup")

**Comment by mikepenz** [comment]
Well there are many ways of releasing libraries. via gradle plugins, via scripts, ... 

But that's not part of this libraries concern :) 

If you publish your library so it defines the name you want to display. AboutLibraries will pick it up :) 

It does right now too, just sadly the different value which is not the expected one.

**Comment by cyb3rko** [comment]
Yeah you're right. You have shown, that the problem is not oart of this library.

Thanls for your help.

**Comment by mikepenz** [comment]
I am sure you can figure it out :) 

Sadly I also don't really know much about jitpack so perhaps it's its problem. 

I prefer to have bintray or maven central anyways as it allows me to sign the packages so people can verify that it is really built by me

**Comment by cyb3rko** [comment]
Btw, i figured out that this behaviour I described is normal for jitpack packages.
It seems like you can't change the name, it's always the same syntax: "authorname/artifactid".
Those libraries using jitpack then are all shown in the same way by your library :neutral_face:, I think it is not just mine.

I found example packages by jitpack on GitHub and your library also shows "jitpack/examplename", so I think there is no way to change it.

I contacted the support and asked, if there is a possibility or if they want to add the possibility.

So I think I have to live with that fact, because I now tried two full days to publish to bintray, nothing works. There is always one thing, that does not work.

Greetings!
