### ISSUE TITLE
Potential Missing Dependencies

### ISSUE THREAD

**Issue by ZeeOne** [mikepenz/AboutLibraries#523]
Hi there! Thank you for this awesome library! 

I was wondering if the issue described here: https://github.com/mikepenz/AboutLibraries/issues/501
might also be an issue for the AndroidX/Java version (6.2.3). As an extra test, I also added the zxing dependency, but it does not show up. I might be doing something weird though, since this is my first time trying out this library. 

This is what my gradle file looks like (some parts removed):

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'
    defaultConfig {
        applicationId "removed"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode removed
        versionName "removed"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        renderscriptTargetApi 22
        renderscriptSupportModeEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures{
        dataBinding = true
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.exifinterface:exifinterface:1.0.0'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.googlecode.plist:dd-plist:1.16'
    implementation 'com.github.siyamed:android-shape-imageview:0.9.+@aar'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android:flexbox:2.0.1'
    implementation 'com.otaliastudios:zoomlayout:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.2.0'
   implementation "com.mikepenz:aboutlibraries:6.2.3"
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'com.journeyapps:zxing-android-embedded:3.5.0'
}
```
 
But the only dependencies that show up are: 
1. AboutLibraries
2. Android-Iconics
3. dd-plist
4. Fast Adapter
5. FlexboxLayout
6. Google Play services. 

Zxing, ZoomLayout and mcxiaoke's Volley do not show up, for example. Initially, I thought it was (as mentioned in your disclaimer) because these libraries maybe set their POM files up incorrectly. But, since it seems Zxing is supposed to work, I was wondering if it was maybe relevant to bring up?

As an aside, IF it is their POM files, is there a way to include libraries with incorrect POMs to show up? Google's oss-licenses-plugin manages to show all dependencies - but it doesn't look nearly as beautiful as this library. 

## Details
- [ 6.2.3] Used library version
- [4.0.1] Used gradle build tools version
- [4.0.1] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
@ZeeOne how did you configure the gradle plugin?

**Comment by mikepenz** [comment]
I fail to find it in your shared one above: 

https://github.com/mikepenz/AboutLibraries#gradle-plugin

**Comment by ZeeOne** [comment]
That was the quickest response in the history of humanity!

Ok, I didn't set up the plugin, since I incorrectly assume I should use the 6.2.3 version there - and then thought I set it up incorrectly when it did not work. 

I have now set it up like so: 
root: 
```
dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:8.3.0"
    }
```

and then in the app gradle: added apply plugin: 'com.mikepenz.aboutlibraries.plugin' to the top. 

It still behaves the same as describer above though. 

Thank you for taking the time to respond to a greenhorn!

**Comment by mikepenz** [comment]
Oh I am actually sorry I totally missed that you are on a very old version of the library. 

So v6.x is no longer maintained. it used provided definition files to fill the UI with the dependencies. with that approach libraries may be missing as they were not added yet. 

With v8 we finally made a new approach which retrieves the information via maven (the pom files) which will now catch all the libraries. 

It is highly suggested for you to upgrade to it. 

If you regardless want to stay to v6 you can have a look at the tag at that state: https://github.com/mikepenz/AboutLibraries/tree/v6.2.3

The libraries which were supported back then: 
https://github.com/mikepenz/AboutLibraries/tree/v6.2.3/library/src/main/res/values

if one is not showing up or not existing you'd have to add your own definition file to provide the missing information

**Comment by ZeeOne** [comment]
Its working!! Thank you so much! Sorry, this is totally my fault - I was under the impression that one has to use V6.2.3 for AndroidX/Java. I updated everything to the latest and greatest version, and now it works perfectly. It looks SO nice. Sorry for wasting your time with silly mistakes, and thank you again for your effort!

**Comment by mikepenz** [comment]
Happy to be able to help :)
