### ISSUE TITLE
Does not seem to be working on build.gradle.kts files

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/AboutLibraries#524]
I have the appropriate section in the classpath of the app gradle.kts  , and the plugins for section for the project gradle.kts

I run my application. i open the about library.  No libraries show.

**Comment by mikepenz** [comment]
which version of the library are you using? 

please list the configuration for both gradle files you do.

**Comment by CarlosEsco** [comment]
build.gradle.kts for project 
```
buildscript {
    dependencies {
        classpath(BuildPluginsVersion.FIREBASE)
        classpath(BuildPluginsVersion.AGP)
        classpath("com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:8.3.0")
        classpath(BuildPluginsVersion.GOOGLE_SERVICES)
        classpath(BuildPluginsVersion.ANDROID_EXTENSIONS)
        classpath(BuildPluginsVersion.KOTLIN_GRADLE)
        classpath(BuildPluginsVersion.KOTLIN_SERIALIZATION)
        classpath(BuildPluginsVersion.KOTLINTER)
    }
}
```
build.gradle.kts for app
```
plugins {
    id("com.android.application")
    id("com.mikepenz.aboutlibraries.plugin")
    kotlin("android")
    kotlin("android.extensions")
    kotlin("kapt")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.firebase.crashlytics")
    id("org.jmailen.kotlinter")
    id("com.google.gms.google-services") apply false

}
...
....
implementation("com.mikepenz:aboutlibraries-core:8.3.0")
implementation("com.mikepenz:aboutlibraries:8.3.0")
```
as stated above.  the LibsBuild  start works.  But no libraries are actually populated

**Comment by mikepenz** [comment]
What's the output you see if you do: 

```
./gradlew exportLibraries 
```

or 

```
./gradlew findLibraries
```

?

if you look into the generated sources will you see the information generated?

**Comment by CarlosEsco** [comment]
exportLibraries and FindLibraries seem to be working fine  a few libraries that error but the task completes and they list libraries in the console.  Though i can't find a csv file from exportLibraries.

as for generated sources it was there also.  I checked logs again and saw this

AboutLibraries: Have you missed to call withFields(R.string.class.getFields())? - autoDetect won't work - https://github.com/mikepenz/AboutLibraries/wiki/HOWTO:-Fragment

For some reason i had to launch it like this even though it wasnt a fragment.
```
 LibsBuilder().withFields(R.string::class.java!!.fields)
                        .start(activity!!)
```

but now they are populating
