### ISSUE TITLE
Is there a way to use the withAboutSpecial to create a web link?

### ISSUE THREAD

**Issue by Leepee** [mikepenz/AboutLibraries#525]
Is there a possibility to make a special link directly to a web page? Or any other way to make a clickable weblink with the library?

Thanks a lot for all the work :)

**Comment by mikepenz** [comment]
Do you mean for every single library? or a top level button action?

**Comment by Leepee** [comment]
Apologies - a button at the top I can use to go to a web URL - where I can give more detail about my project on my own website.

Thanks for the prompt reply!

**Comment by mikepenz** [comment]
So you'd enable the special button by setting it's name:
https://github.com/mikepenz/AboutLibraries/blob/bb3eb47a2f5a7358a6b7ffe8a616833c682ec378/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L294

and then you'd set the special button listener here:
https://github.com/mikepenz/AboutLibraries/blob/bb3eb47a2f5a7358a6b7ffe8a616833c682ec378/library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.kt#L18

https://github.com/mikepenz/AboutLibraries/blob/bb3eb47a2f5a7358a6b7ffe8a616833c682ec378/library/src/main/java/com/mikepenz/aboutlibraries/util/LibsListenerImpl.kt#L24-L26

**Comment by Leepee** [comment]
King. I'll look into this tomorrow, thanks a ton for the help :)

**Comment by Leepee** [comment]
Perfect, cracked it. 

Huge thanks for this man, it's a fantastic library, especially for a newb codemonkey like me!

**Comment by mikepenz** [comment]
you are welcome :) glad it works
