### ISSUE TITLE
Libs(context).libraries is empty

### ISSUE THREAD

**Issue by vernazza** [mikepenz/AboutLibraries#528]
## About this issue

I tried to use the library without the UI component, as I'm going to use my own UX
I added the classpath, applied the plugin and added the core-module through the implementation
then, from my activity, I call
` Libs(context).libraries`
anyway, libraries returns an empty list.
It seems that the toStringArray() functions filters out every field, so the init constructor doesn't find any library

## Details
Used library version: 8.3.1
Used gradle build tools version:4.0.1
Android Studio version: 4.0.1

**Comment by mikepenz** [comment]
@vernazza please also call `prepareLibraries` to make it read in the libs

**Comment by vernazza** [comment]
No, nothing changes.
I tried both with

`Libs(context).prepareLibraries(context)`
and with
`Libs(context).also{it.prepareLibraries(context)}.libraries`

Same empty result

**Comment by mikepenz** [comment]
@vernazza do you have some custom package id or use obfuscation or so?

E.g. could it be that it can't find the R class? 

E.g. could it require you to provide the fields? `R.string::class.java.fields`

**Comment by vernazza** [comment]
I use obfuscation but only on release. Now I'm in debug, so that should not be the problem.
It can find the R class: if I step in with the debugger here:

```
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP_PREFIX)
fun Context.getFields(): Array<String> =
        resolveRClass(packageName)?.fields?.toStringArray() ?: emptyArray()
```

I can see that 
`resolveRClass(packageName)?.fields`
returns a lot of fields, but `toStringArray` filters them out for the filter `it.contains(Libs.DEFINE_EXT) `

Running the ./gradlew exportLibraries command gives me 240 entries.

**Comment by vernazza** [comment]
I found the problem.
The package id of the manifest was different from the applicationId in the gradle.
I changed the manifest one, and now the libraries can be found.

**Comment by mikepenz** [comment]
@vernazza I think if you pass in the fields manually via the API it should also solve this problem :) Sadly the reflection approach is not picking them up nicely

Glad it works now :)

**Comment by kassim** [comment]
Hi. This still seems to be an issue.  I don't think it should be closed.
Is there no solution when you have an application ID that doesn't match the manifest? (e.g. changed at build time)

**Comment by mikepenz** [comment]
@kassim please see in the README. for those cases you should pass in the R class having the strings 
https://github.com/mikepenz/AboutLibraries#fragment

**Comment by kassim** [comment]
yeah, that's done, the thing is the generated string keys aren't part of `R.string` – though all my other string keys are present there (checked in debugger), and I see the `/app/build/generated/aboutlibraries/stagingEnvDebug/res/values/aboutlibraries.xml` file generated has everything it should have – but I guess at build time the resources aren't properly merged

**Comment by kassim** [comment]
ah ok, so actually you need to ensure the R class is the one for the package name in the AndroidManifest of the module with the plugin

so if your `app` module's build.gradle config has the package `com.example.sampleapp` but the AndroidManifest.xml has `com.example.sampleapp.app` > the R file should be `com.example.sampleapp.app.R`
