### ISSUE TITLE
What is the recommended way to use this library with Jetpack navigation?

### ISSUE THREAD

**Issue by yashx** [mikepenz/AboutLibraries#530]
## About this issue
What is the recommended way to use this library with Jetpack navigation? I couldn't find anything about it on the README.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Generally it's meant to be launched via the builder as Activity or you get the fragment and put this in your fragment manager. 

The builder set's itself as serializeable data into the `Bundle` of the fragment. So I believe if you use the safe-args plugin you can use the fragment this library offers as a target to navigate to.

https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L577-L583

**Comment by yashx** [comment]
What you suggested works. By adding this to the nav graph and passing a LibsBuilder object.
```
<fragment
        android:id="@+id/aboutFragment"
        android:name="com.mikepenz.aboutlibraries.ui.LibsSupportFragment"
        android:label="fragment_about" >
        <argument
            android:name="data"
            app:argType="com.mikepenz.aboutlibraries.LibsBuilder" />
</fragment>
```
Tbh I think this destination should be self-contained.
Maybe a subclass of LibsSupportFragment that would work similarly to a DialogFragment. Basically, people can subclass it and define the LibsBuilder inside it and set that as a destination. Should I send a PR for this or do you prefer the first approach?

**Comment by mikepenz** [comment]
@yashx totally agree with it making a lot of sense to be self contained. `LibsSupportFragment` should be open so extending it should already work. 

Wouldn't hurt to showcase the usage of it in the sample though :). So if you like to showcase how it can be done, more than happy to include it in the sample

Thank you!

**Comment by koral--** [comment]
BTW `com.mikepenz.aboutlibraries.LibsBuilder` must not be renamed during obfuscation. At least ~AGP-4.2.0-alpha09 was not smart enough to generate R8 rules for nav args classes.

**Comment by mikepenz** [comment]
@koral-- great point
