### ISSUE TITLE
StackOverflowError when running findLibraries task

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [mikepenz/AboutLibraries#532]
## About this issue
```
Execution failed for task ':app:findLibraries'.
> java.lang.StackOverflowError (no error message)
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:findLibraries'.
	at 
...
Caused by: java.lang.StackOverflowError
	at com.mikepenz.aboutlibraries.plugin.DependencyCollector.addChildDependencies(DependencyCollector.kt:79)
	at com.mikepenz.aboutlibraries.plugin.DependencyCollector.addChildDependencies(DependencyCollector.kt:83)
	at com.mikepenz.aboutlibraries.plugin.DependencyCollector.addChildDependencies(DependencyCollector.kt:83)
	at com.mikepenz.aboutlibraries.plugin.DependencyCollector.addChildDependencies(DependencyCollector.kt:83)
	at com.mikepenz.aboutlibraries.plugin.DependencyCollector.addChildDependencies(DependencyCollector.kt:83)
... etc - many more dupe lines
```
## Details
- [8.3.1 ] Used library version
- [androidx.legacy:legacy-support-v4:1.0.0 ] Used support library version
- [4.0.1 ] Used gradle build tools version
- [4.0.1 AS ] Used tooling / Android Studio version
- [sooooo many ] Other used libraries, potential conflicting libraries

## Checklist

- [ Y] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ Y] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ Y] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ Y] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ Y] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

exportLibraries does the same as i assume they're dependent

**Comment by mikepenz** [comment]
@OliverCulleyDeLange could you please provide a sample app which allows us to reproduce this issue?

This problem seems to not be reproducible on our end. 

Can you potentially also provide the gradle version you use?

**Comment by OliverCulleyDeLange** [comment]
Sure.
https://github.com/OliverCulleyDeLange/bugs/tree/about-libraries-soe

**Comment by mikepenz** [comment]
I don't know yet why but it seems to be related to:


```

    // TEST
    def junitVersion = "5.7.0"
    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
    testCompileOnly('junit:junit:4.13') // To allow running JUnit 4 Tests
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:$junitVersion")

    def kotestVersion = '4.2.5'
    testImplementation "io.kotest:kotest-runner-junit5-jvm:$kotestVersion"
    testImplementation "io.kotest:kotest-assertions-core-jvm:$kotestVersion"

```

If you remove those. it will work

**Comment by mikepenz** [comment]
Ok I think I found the problem. And will have a new update available soon. 

(The problem seems to be an infinite loop with the child dependencies in gradle, applying a patch to catch this) 
(additionally one of those dependencies references a *.pom file which has a invalid xml file, applying a patch to this too)

**Comment by OliverCulleyDeLange** [comment]
Great, thanks for the library 👍

**Comment by mikepenz** [comment]
I need to fix something with the plugin publishing. But I hope the update is ready in a few hours. 

Thanks for the report. And thank you for the sample app. That helped a lot

**Comment by mikepenz** [comment]
Ok it will take a bit longer as gradle has to approve the update: 

![image](https://user-images.githubusercontent.com/1476232/94956219-12d9f900-04ec-11eb-94dc-251ef25776a6.png)

As I moved to only host it on gradle plugin portal. let's hope this goes through soon. :)

**Comment by mikepenz** [comment]
v8.4.2 is now available with the fixes for the above issue :)
