### ISSUE TITLE
LibsBuilder().start(this) builds an overview without license Information 

### ISSUE THREAD

**Issue by profriemke** [mikepenz/AboutLibraries#538]
## About this issue
LibsBuilder().start(this) builds an overview as in the screenshots but without license Information (expected to be shown in the right bottom corner). All other information is included, also clicks opens browser.
Manual programmatic approach delivers all information as expected.

## Details
- Used library version: 8.3.0 (others are not available through Android Studio)
- Gradle 6.1.1 and also before upgrade
'androidx.core:core-ktx:1.3.1'
'androidx.appcompat:appcompat:1.2.0'
'androidx.legacy:legacy-support-v4:1.0.0'
'com.google.android.material:material:1.2.1'

**Comment by mikepenz** [comment]
@profriemke do you have the plugin configured in your build? 

Have you tried a clean build?

**Comment by profriemke** [comment]
Yes I have and also did clean builds. The strange thing is that the cards are generated and everything is working fine, only the license is missing on the cards.

Doing this manually like

val libraries = Libs(this.requireContext()).libraries
 for (lib in libraries) {
Log.e("AboutLibraries", lib.licenses)
}
delivers information.

**Comment by profriemke** [comment]
Solution:
LibsBuilder().withLicenseShown(true).start(this)
It was not quite clear from the docs that this is neccessary to get the result.

[btw thank you for your work on this project!]

**Comment by mikepenz** [comment]
can you reproduce this if you remove `.withLicenseShown(true)` again? it shouldn't be required :/

**Comment by profriemke** [comment]
Yes, it's gone on the card when I remove it.

**Comment by mikepenz** [comment]
@profriemke oh sorry I think I missunderstood the issue then. You were not meaning no libraries show up in the list, but you miss the UI section in the card. 

Yes you are correct that this can be toggled with that flag. If you have time at your hand I'd appreciate a PR on the README to put that more into spotlight so future users have an easier time to find it :) 


thanks so much for reporting bakc

**Comment by profriemke** [comment]
I try to find some time :-)
