### ISSUE TITLE
Custom licenses not displayed since 8.3.0

### ISSUE THREAD

**Issue by awoisoak** [mikepenz/AboutLibraries#543]
## About this issue

Since 8.3.0 the [custom licenses](https://github.com/mikepenz/AboutLibraries#custom-licenses) are not being displayed. Downgrading to 8.2.0 fixes the issue.
(I checked 8.4.2 but the issue is still there)

**Comment by mikepenz** [comment]
can you please showcase in a sample app what you do and what is not working? 

I know that for various users it's working

**Comment by awoisoak** [comment]
Thanks for the quick answer, I uploaded a sample app [here](https://github.com/awoisoak/AboutLibrariesTest) with a single personalized library called _Bunch_ that uses a custom license (see [res/values/about_libraries.xml](https://github.com/awoisoak/AboutLibrariesTest/blob/master/app/src/main/res/values/about_libraries.xml)).
I setup version [8.2.0](https://github.com/awoisoak/AboutLibrariesTest/blob/b47b6e47269c600dd749df7d17f9804c35589f01/build.gradle#L4) so the _Bunch_ license is correctly displayed. If I upgrade it to 8.3.0 the _Bunch_ library will still be displayed but with an empty license.

**Comment by mikepenz** [comment]
Thank you. I'll try it out as soon as possible and let you know what's up

**Comment by mikepenz** [comment]
@awoisoak the change to support multiple licenses changed the specification from:

> add support for custom license mapping to allow multiple licenses

Please change
```
<string name="library_xcom_tompee_bunch__annotations_licenseId" tools:ignore="UnusedResources">bunch</string>
```

To: 
```
<string name="library_xcom_tompee_bunch__annotations_licenseIds" tools:ignore="UnusedResources">bunch</string>
```


Also please consider using the latest release of the library v8.4.2. 
I will have a look and possibly adjust it to fallback to the `licenseId` if no `licenseIds` is specified

**Comment by awoisoak** [comment]
Thank you!
