### ISSUE TITLE
Missing plugin version 8.4.3.

### ISSUE THREAD

**Issue by illabo** [mikepenz/AboutLibraries#549]
Latest downloadable release is 8.3.1 when root project `build.gradle` repositories are set to 
```gradle
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
```
Had to add `maven { url "https://plugins.gradle.org/m2/" }`.
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:8.4.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/8.4.3/aboutlibraries-plugin-8.4.3.pom
       - https://jcenter.bintray.com/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/8.4.3/aboutlibraries-plugin-8.4.3.pom
       - https://repo.maven.apache.org/maven2/com/mikepenz/aboutlibraries/plugin/aboutlibraries-plugin/8.4.3/aboutlibraries-plugin-8.4.3.pom
```
I believe you just forgot to publish it?

**Comment by mikepenz** [comment]
Due to complications with bintray publish the plugin is now only available via the officiale gradle plugin portal:

https://plugins.gradle.org/plugin/com.mikepenz.aboutlibraries.plugin

I'll add the info in regards to the plugin hosting to the README. thanks for the report
