### ISSUE TITLE
Inconsistent results with manual libraries and bundled licenses?

### ISSUE THREAD

**Issue by rpavlik** [mikepenz/AboutLibraries#550]
## About this issue

- I'm using this for an Android app with a native component, which means I'm adding resources for native libraries. Other deps appear mainly to be Apache 2.0, but license on native code varies: some are BSL-1.0 (for which I added a custom license, which worked fine), some are MIT. The MIT ones don't have the license field show up in the GUI, perhaps in part because there is a `license_apache_2_0.txt` generated in the raw directory by the plugin, but none for `license_mit.txt` despite it existing in the plugin. The only difference I can see is that the MIT license is bundled by the plugin, but not used by any Java/detected dependencies.

- How can the issue be reproduced / sample code

Here's a library resource file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="define_plu_cJSON"></string>
    <!-- Author section -->
    <string name="library_cJSON_author">Dave Gamble and cJSON contributors</string>
    <!-- Library section -->
    <string name="library_cJSON_libraryName">cJSON</string>
    <string name="library_cJSON_libraryDescription">cJSON is a parser that tries to share the same philosophy as JSON itself. Simple, dumb, out of the way.</string>
    <string name="library_cJSON_libraryWebsite">https://github.com/DaveGamble/cJSON</string>
    <string name="library_cJSON_libraryVersion">1.7.12</string>
    <!-- OpenSource section -->
    <string name="library_cJSON_isOpenSource">true</string>
    <string name="library_cJSON_repositoryLink">https://github.com/DaveGamble/cJSON</string>
    <!-- License section -->
    <string name="library_cJSON_licenseId">mit</string>
    <string name="library_cJSON_licenseIds">mit</string>

</resources>
```

I added both licenseId and licenseIds fields as a troubleshooting measure. Also tried lowercase names, no change.

The full project is available here: https://gitlab.freedesktop.org/ryan.pavlik/monado/-/commits/android2

## Details
- [x] Used library version - 8.4.3
- [x] Used support library version `implementation 'androidx.appcompat:appcompat:1.2.0'` and the dependencies in the README as of filing.
- [x] Used gradle build tools version- gradle 6.7
- [x] Used tooling / Android Studio version - 4.1
- [x] Other used libraries, potential conflicting libraries - Just kotlin and some internal (fairly simple) libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@rpavlik that's actually anticipated behaviour of the plugin to not fill your apps resources with non discovered libraries / licenses. As the library solely functions based on gradle dependencies and not being aware of any other app resources, it sadly fails to understand that in your case you have a native lib which requires the `mit` license. 

The best solution for this usecase would be to include the relevant (non auto discovered) library information as resource in your project. 

https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/values/license_mit_strings.xml
https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/raw/license_mit.txt

---- 

A more complex solutions would be to have a license only dependency created for such a case: https://github.com/mikepenz/AboutLibraries/issues/502 (this was an issue, related to that approach, but fixed since)

**Comment by rpavlik** [comment]
Got it, so it's not actually parsing the resources at gradle time, only deciding libraries to include based on the gradle-discovered deps. (I traced most of the source code but not all of it.) 

So, if I understand correctly, this is as-expected then (cJSON and Eigen are both native libraries I added stuff for manually, but that use MIT and MPL2, respectively)

![image](https://user-images.githubusercontent.com/61129/98381515-9ae18000-200f-11eb-8a02-0a3ad3875196.png)

and this is expected because I explicitly include this license since it's not bundled already:

![image](https://user-images.githubusercontent.com/61129/98381595-b3ea3100-200f-11eb-81fc-4ad1eac13cfe.png)


Could we maybe add something to the Gradle extension object to manually specify libraries to include in addition? I also tried adding it to one of the property files, since it seemed like the plugin parsed that, but it didn't do the trick.  (I've had an uncomfortably large amount of Gradle practice this week, figuring out how to get the BSL 1.0 license automatically processed and added as a raw resource in the build process...) I might take a crack at it today if I can figure out how to easily make my build prefer a local version of the plugin from a composite build instead of the published version.

**Comment by mikepenz** [comment]
@rpavlik I chose not to parse any resources of the project, as this may be a security concern for some, additionally that would require significant knowledge about the different places resources may originate from (different languages, ...) so choosing to only parse the gradle dependencies seemed to be a better more future proof approach. 

yes exactly. the current approach would be to include the license manually perhaps as resource. 

----

I believe it would actually make sense to have the capability to configure the plugin so it will also try to include additional licenses even if they are not directly linked. 
Gradle is interesting, had a lot of struggle to read into the way to create a plugin initially too, not sure if it's just me, but docs seemed to be not really clear :D 

anyways. I'd really love and appreciate a PR / addition to extend the functionality of the plugin to also give some easier approach to add these licenses. 


Btw. the way I usually tend to try things out locally: build and install the library with a new version number in gradle locally and then execute the normal project build, which should then pick up the local library. 

If you find a good way to directly link against the gradle plugin source and possibly have debugging I'd be more than happy :D 

(Doing Log debugging works, but using the real debugger is just so much more convenient)
