### ISSUE TITLE
No view in fragment

### ISSUE THREAD

**Issue by illabo** [mikepenz/AboutLibraries#551]
## About this issue

I'm trying to add  the `LibsSupportFragment` as a child fragment inside another fragment or replace a layout element of a parent fragment with it.
```kotlin
                val childFragment = LibsBuilder()
                    .withFields(R.string::class.java.fields)
                    .withAboutIconShown(true)
                    .withAboutVersionShown(true)
                    .withAboutDescription("Description")
                    .supportFragment()

                Log.d("CHILDFRAGMENT", "$childFragment")
                Log.d("CHILDFRAGVIEW", "${childFragment.view}")

                childFragmentManager.beginTransaction()
                    .replace(R.id.child_fragment_container, childFragment)
                    .commit()
```
The `child_fragment_container` is a ConstraintLayout.
And boom! I'm getting such an output in run log:
```
D/CHILDFRAGMENT: LibsSupportFragment{90aacdf} (4219d9a1-64f6-42ed-a676-b841d574dcdd)}
D/CHILDFRAGVIEW: null
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.illabo.crabdelivery, PID: 2796
    java.lang.IllegalArgumentException: No view found for id 0x7f0900a4... 
```
For obvious reason adding fragment's view to `ViewGroup` is also impossible.

It looks same to lines 170—180 in `FragmentActivity.kt` of sample app.
Haven't read MIGRATION GUIDE as I had never used this library before.

## Additional context

My app is based on `NavController` navigation, my goal is to add it inside `BottomSheetDialogFragment` subclass, so the only way (as I assume) to utilize `Libs` is to add its fragment programmatically to some other fragment `onViewCreated`.

## Details
- Used library version: 8.4.3
- Used support library version: androidx.legacy:legacy-support-v4:1.0.0 
- Used gradle build tools version: 29.0.2 
- Android Studio version 4.1 
- Other used libraries, potential conflicting libraries ¯\\\_(ツ)_/¯

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by illabo** [comment]
Ok, finally found #530 and was able to accomplish what I wanted. To tie up the shards of information together was a challenge, though.

**Comment by mikepenz** [comment]
@illabo great to hear that you were able to resolve your issue. If you'd love to improve the documentation, or enhance sections which may not be clear, don't hesitate to open a PR. We'd really appreciate all the things improving the library!
