### ISSUE TITLE
Using with AndroidX navigation.

### ISSUE THREAD

**Issue by fourofspades** [mikepenz/AboutLibraries#572]
Hopefully this is just a documentation task.  I am using gradle plugin 8.6.2 (latest)  and looking at the issue tracker, it should be possible to use this using AndroidX navigation.  However I couldn't find any documentation on the wiki, or sample code.

I am using this XML:

`	<fragment
		android:id="@+id/nav_about"
		android:name="com.mikepenz.aboutlibraries.ui.LibsSupportFragment"
		android:label="fragment_about" >
		<argument
			android:name="data"
			app:argType="com.mikepenz.aboutlibraries.LibsBuilder" />
	</fragment>
`
but it just crashes at runtime.

    java.lang.NullPointerException: null cannot be cast to non-null type com.mikepenz.aboutlibraries.LibsBuilder
        at com.mikepenz.aboutlibraries.LibsFragmentCompat.onCreateView(LibsFragmentCompat.kt:49)

I suspect my XML syntax is wrong, but I couldn't find anything that helps me with the correct syntax.

Thanks,

**Comment by mikepenz** [comment]
There's a sample implementation of a fragment making it compatible with the `Navigation` library:

https://github.com/mikepenz/AboutLibraries/pull/531/files#diff-d63c8456e793a2f644e6d36c804b7904baea2c5df547c67b78925e5ce1333858R11

The `Fragment` requires the `LibsBuilder` as input (which configures it)

**Comment by fourofspades** [comment]
Still really confused, in the sample code, NavHostDestinationFragment isn't referenced anywhere.  There is no navigation XML.

What I have done, I have created a new fragment class that extends LibsSupportFragment

`
public class NavHostDestinationFragment extends LibsSupportFragment
{
	@Override
	public View onCreateView( LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState )
	{
		savedInstanceState.putSerializable( "data", new LibsBuilder() );
		return super.onCreateView( inflater, container, savedInstanceState );
	}
}

and modified my navigation XML as follows:

`
	<fragment
		android:id="@+id/nav_about"
		android:name="uk.droidsoft.overtimelog.ui.about.NavHostDestinationFragment"
		android:label="fragment_about" >
		<argument
			android:name="data"
			app:argType="com.mikepenz.aboutlibraries.LibsBuilder" />
	</fragment>
`

However i'm still missing something from the picture, as it's not playing ball.   The Jetpack stuff makes Android development much easier, so it would be really nice if AboutLibraries supported it easily.

**Comment by mikepenz** [comment]
I can see and think of a way to provide out of the box addition for it. And
check if a target could be provided by default. Or to showcase usage with
it.
Stay tuned.


That being said. With the provided sample fragment implementation no config
is needed and that fragment can be directly used via navigation. It was an
addition by a user who's using navigation already successfully.

**Comment by fourofspades** [comment]
Perfect, thanks. It's now really easy to have a basic about page than you can control with the strings.xml and navigation,.xml alone without writing a single line of code 👍
