### ISSUE TITLE
Missing license when defining custom library

### ISSUE THREAD

**Issue by akiller** [mikepenz/AboutLibraries#576]
Hi,

I need to manually include an embedded libraries license (ffmpeg) which is LGPL 2.1. No matter what I do I can't seem to get AboutLibraries to display the license name.

This can be reproduced with the demo app from this repository. I add to strings.xml the following:

```xml
<string name="define_plu_lipsum">2020;Lorem Ipsum</string>
<string name="library_lipsum_author">Lorem Ipsum</string>
<string name="library_lipsum_libraryName">_Lorem Ipsum</string>
<string name="library_lipsum_libraryDescription">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</string>
<string name="library_lipsum_libraryVersion">1.2.3</string>
<string name="library_lipsum_licenseIds">lgpl_2_1</string>
<string name="library_lipsum_isOpenSource">true</string>
<string name="library_lipsum_owner">Lorem Ipsum</string>
<string name="library_lipsum_year">2020</string>
```

And as you can see it doesn't reference the LGPL license:

![image](https://user-images.githubusercontent.com/63985/103773532-1fa64580-5023-11eb-851e-4cefdcaccddf.png)

If I set it to use say Apache 2.0 (`<string name="library_lipsum_licenseIds">apache_2_0</string>`) it works.

I think the issue may be that the LGPL license doesn't get added to foundLicenseIdentifiers in the init of Libs.kt  which means it isn't added to the `private val licenses = mutableListOf<License>()` field which is referenced when initiating a Library() definition.

Most likely it's user error on my behalf though!

Thanks

**Comment by mikepenz** [comment]
Yes your investigation is correct. the license is not added to the data as the plugin itself will not parse through all your xml files, and as this library does not exist it will not include the license in your app. 

There's an API as a result of this issue: https://github.com/mikepenz/AboutLibraries/issues/550 which allows you to force it to include additional licesnes:

See it in action here: https://github.com/mikepenz/AboutLibraries/blob/cc1a6ddc893aff9e92a6a688f47945d5645091a5/app/build.gradle#L78-L81

**Comment by akiller** [comment]
> 
> 
> Yes your investigation is correct. the license is not added to the data as the plugin itself will not parse through all your xml files, and as this library does not exist it will not include the license in your app.
> 
> There's an API as a result of this issue: #550 which allows you to force it to include additional licesnes:
> 
> See it in action here:
> 
> https://github.com/mikepenz/AboutLibraries/blob/cc1a6ddc893aff9e92a6a688f47945d5645091a5/app/build.gradle#L78-L81

Ahh thank you. I did search for an answer and didn't find that issue, sorry. Also for anyone who comes across this issue I needed to use `LGPL_2_1_or_later` (CaSe SenSiTiVE) not `LGPL_2_1 `for it to work, in both my string and gradle definitions,  e.g.:

```xml
<string name="library_lipsum_licenseIds">LGPL_2_1_or_later</string>
```

```gradle
aboutLibraries {
    additionalLicenses {
        LGPL_2_1_or_later
    }
}
```

---

In this situation where it can't find the license and displays a blank field, would it not be better to list the raw license name at the bottom instead of a blank field? E.g., just display "LGPL_2_1_or_later".

For my use case I have an FFmpeg embedded project which is compiled into my own library. I then reference that library in my app. Am I right in thinking there's no way to automatically bubble up the need to add the `additionalLicenses { LGPL_2_1_or_later }` inclusion from the library?

I know you mentioned you didn't want to scan all the xml files to do this automatically - most plugins seem to include an AndroidManifest.xml, I wonder if you could put a key in there to do it? E.g., in my library:

```xml
<meta-data android:name="com.mikepenz.aboutlibraries.additionallicenses" android:value="LGPL_2_1_or_later,mit" />
```

Just a thought!

**Comment by mikepenz** [comment]
> In this situation where it can't find the license and displays a blank field, would it not be better to list the raw license name at the bottom instead of a blank field? E.g., just display "LGPL_2_1_or_later".

This would be something to consider, but it may result in different non anticipated display. Will check about that. 

> CaSe SenSiTiVE

Will have a look and see in how far we can be non case sensitive.

> Needed to use `LGPL_2_1_or_later`

You can find all license mappings here: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/License.kt Those match the identifiers according to: 
https://spdx.org/licenses/

------

The plugin itself has as little understanding of "android" as possible. the actual main logic which is android related is only writing the xmls in the format I defined for the `AboutLibraries` to find the strings + in the format android can read them. 
The whole finding dependencies logic is fully independent of Android and fully depends on gradle providing the information. 
As such there are currently no plans to have it check the manifest.

**Comment by akiller** [comment]
Sorry was just about to reply when you closed this.

> You can find all license mappings here: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/License.kt Those match the identifiers according to:
> https://spdx.org/licenses/
> 
> The plugin itself has as little understanding of "android" as possible. the actual main logic which is android related is only writing the xmls in the format I defined for the `AboutLibraries` to find the strings + in the format android can read them.
> The whole finding dependencies logic is fully independent of Android and fully depends on gradle providing the information.
> As such there are currently no plans to have it check the manifest.

That makes sense, thanks for clearing it up.

I did have one thought for those of us who don't mind the extra bulk of including all the licenses. Adding a new property alongside additionalLicenses called includeAllLicenses (which defaults to false). It could be used to avoid having to explicitly list the extra licenses you need.

```gradle
aboutLibraries {
    includeAllLicenses = true
}
```

I've had a play with it this afternoon and managed to get it working this way.. I can submit a PR if you'd like?

**Comment by mikepenz** [comment]
@akiller that's an interesting proposal. I am just wondering how often this is needed. ultimately I would assume you will only have around 5 different licenses max in your project. it is very uncommon to have much more than that. Especially Android libs most of the time are either Apache 2.0 or MIT. 

One thing which is a strong argument against including all is that those resources which will be included in your project (even though you wont use them) adding not only in size, but even more importantly it will count against the dex limit, as every single string will be added to the `R` class.

It may also result in performance issues of the localisation UI within Android Studio (at least it has been slow in the past with many strings). 

It may even slow down compilation due to the amount of strings and fields. 

Ultimately that flag would result in around 300 different license specifications to be generated.

**Comment by mikepenz** [comment]
I am curious though how many licenses you usually have in average and if you see problems by having only specific listed?

**Comment by akiller** [comment]
Sorry the weekend got in the way of my reply.

> 
> 
> @akiller that's an interesting proposal. I am just wondering how often this is needed. ultimately I would assume you will only have around 5 different licenses max in your project. it is very uncommon to have much more than that. Especially Android libs most of the time are either Apache 2.0 or MIT.

Very rarely I hope.

> 
> One thing which is a strong argument against including all is that those resources which will be included in your project (even though you wont use them) adding not only in size, but even more importantly it will count against the dex limit, as every single string will be added to the `R` class.
>
> It may also result in performance issues of the localisation UI within Android Studio (at least it has been slow in the past with many strings).
> 
> It may even slow down compilation due to the amount of strings and fields.
> 
> Ultimately that flag would result in around 300 different license specifications to be generated.

That's a good point. It's definitely a special case to want to include them all.

Perhaps by including all the license information it _may_ allow more flexibility for the consumer (the app using your library) to filter out the strings they don't need (via Proguard rules etc). I wonder if it might even allow libraries like mine to define something in consumerProguardFiles to specify which ones we need to keep.

Or perhaps someone might want to use your library as a way of listing all the licenses available - you have an extensive list with a nice interface that could be hijacked for that purpose.

I'll submit a pull request for you regardless. You're obviously welcome to ignore it 😃.

**Comment by mikepenz** [comment]
> Perhaps by including all the license information it may allow more flexibility for the consumer (the app using your library) to filter out the strings they don't need (via Proguard rules etc). I wonder if it might even allow libraries like mine to define something in consumerProguardFiles to specify which ones we need to keep.

Sadly I don't think that's possible. e.g. the effort would exceed the effort of just defining the licenses needed in the first place. 
It's a more rare situation already where sadly gradle / the pom files won't be of much use as native libs are rarely shipped as such (which is a pity) 

Haha yeah. That's one idea to not require users of this lib to use the UI provided. the `Libs` and `LibsBuilder` classes will allow you to just use the generated data and display it in any form needed (including licenses) 

Thanks. I'll have a look at it, and depending on the risk / complexity I'll consider getting it in regardless  ;) 

----

Btw. one thing I remembered. a more complex but complete approach to hook into the plugin is generate a pom only dependency which will be meant to host the meta information. 

https://github.com/mikepenz/AboutLibraries/issues/502
