### ISSUE TITLE
Cannot modify librarys with same prefix

### ISSUE THREAD

**Issue by andrewreeman** [mikepenz/AboutLibraries#577]
## About this issue

We use the Permissions Dispatcher library found [here](https://github.com/permissions-dispatcher/PermissionsDispatcher).
This includes the main library with an id of: org_permissionsdispatcher__permissionsdispatcher
and their annotation library with an id of: org_permissionsdispatcher__permissionsdispatcher_annotation

The main library license information is not displaying automatically so we have to add modifications like so: 

`.withLibraryModification("org_permissionsdispatcher__permissionsdispatcher",Libs.LibraryFields.LICENSE_NAME,"Apache_2_0")
`
However because in Libs.modifyLibraries it is internally using:  findInExternalLibrary this returns the main library and the annotation library. This does not then satisfy the following guard:
`if (foundLibs.size == 1) { ... do modifications }`

As modifyLibraries expects an id should it require that the definedname equals the id instead of just containing the id? This could break existing usage though so perhaps if the modifications hashmap contains a "STRICT_SEARCH" key then it can find the libraries only where the id is equal.

Happy to provide a pull request.

## Details
- [ ] Used library version - 8.6.3
- [ ] Used support library version - androidx.legacy-support-v4:1.0.0
- [ ] Used gradle build tools version - 4.1.1
- [ ] Used tooling / Android Studio version - 4.1.1
- [ ] Other used libraries, potential conflicting libraries - org.permissionsdispatcher:permissionsdispatcher:4.5.0

**Comment by mikepenz** [comment]
@andrewreeman thank you very much for the ticket details. 

Have you had the look at the potential of providing custom id to license mapping for the gradle plugin via:

https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/raw/custom_license_mappings.prop

If provided via a configured config folder like: https://github.com/mikepenz/AboutLibraries/tree/develop/config it would allow to define the license id for libraries lacking the details in their `pom.xml`. 

This will also be a safer approach as it will ensure that required licenses are included in the app during build time.

**Comment by andrewreeman** [comment]
Thanks Mike, I was expecting the modifications to strictly compare the ids but can see the advantage of the current setup.

I just tried the config option now but it does not seem to be working.
I believe it could either be me doing it wrong or be a slight bug in the `collectMappingDetails` method in AboutLibrariesProcessor.groovy.

The first instance of `customMappingText` inside if(configFolder != null) does not start with a `def`.
When I copy this function into our project and run it then it throws an exception.
`groovy.lang.MissingPropertyException: Could not set unknown property 'customMappingText' for project`
Adding a `def` to this seems to work. Can raise a new issue for this?

Thanks for creating this library by the way. Very readable and elegant api and there is so much flexibility to it.

**Comment by mikepenz** [comment]
@andrewreeman I will jump deeper into the above problem and will hopefully have a chance to try on the weekend to check it and reproduce your report. 

That would be great if you could please open a new issue for this, or if you maybe want to open a PR for it that would also be very great. 

Thank you so much. Really appreciate your kind words.

**Comment by andrewreeman** [comment]
Thanks, I've raised an issue in #578 and will provide a pull request shortly

**Comment by mikepenz** [comment]
@andrewreeman thanks again for the PR. I went ahead and do a small bugfix release for this one bug. will follow up on the other topic hopefully this weekend

**Comment by andrewreeman** [comment]
Thanks for the quick release and responses. Much appreciated.

**Comment by mikepenz** [comment]
@andrewreeman in the process of publishing another update which will prefer equal id matches over finding elements via the searchterm. it should resolve the problems you had been seeing whereas the contains was not allowing for the exact element to be modified.

**Comment by mikepenz** [comment]
Thank you os much again for the great input

**Comment by andrewreeman** [comment]
Yes this is great. So in the case where you set the limit to 1 it uses equality and above that it uses contains. That's fantastic. Thanks for the help!

**Comment by mikepenz** [comment]
You are welcome. Glad we were able to improve it
