### ISSUE TITLE
Custom config is ignored

### ISSUE THREAD

**Issue by jp-andr** [mikepenz/AboutLibraries#582]
## About this issue

I'd like to adjust the "year", "owner" and "license" for some libraries, but I have some difficulties.
I added in the app `build.gradle`:
```
aboutLibraries {
    configPath = "config"
}
```

On project level I added the config-direction with these configurations:
```
custom_author_mappings.prop
custom_license_mappings.prop
custom_license_year_mappings.prop
custom_name_mappings.prop
```

For example I added inside `custom_license_year_mappings.prop`:
`com_mikepenz__aboutlibraries_core:2021`

When I build the app it still shows YEAR instead of 2021.
I tried different paths for the configPath, but somehow it won't work.

## Details
- [8.6.3 ] Used library version: 8.6.3

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@jp-andr can you please try with v8.6.4

**Comment by jp-andr** [comment]
@mikepenz Unfortunately it does not work with v8.6.4 either. DoI need to add something somewhere else or is the configPath wrong?

**Comment by mikepenz** [comment]
Could you please specify your project structure a bit more? 

so you have configured

```
/app
/config/custom_author_mappings.prop
```

or you do something like


```
/app
/app/config/custom_author_mappings.prop
```

in the case of the later you will have to configure 

```
aboutLibraries {
    configPath = "app/config"
}
```

**Comment by jp-andr** [comment]
My project structure is:
```
/app
/config/custom_author_mappings.prop
/config/custom_license_year_mappings.prop
```
Inside the app `build.gradle` I added:
```
aboutLibraries {
    configPath = "config"
}
```
And the `custom_license_year_mappings.prop` currently looks like:
```
com_mikepenz__aboutlibraries_core:2021
androidx_activity__activity:2021
```

**Comment by mikepenz** [comment]
![image](https://user-images.githubusercontent.com/1476232/104003160-59518a80-51a2-11eb-89ae-cb17b219b5c4.png)

Just verified with dev. and it works. Could you please ensure you did a gradle sync and a full project clean to ensure caches are deleted?

**Comment by jp-andr** [comment]
Thanks, invalidating the caches and rebuilding the whole project worked. Only cleaning and rebuilding the project and a gradle clean did not work, the caches were apparently the problem.
