### ISSUE TITLE
Enhancement - Disable Hyperlinks

### ISSUE THREAD

**Issue by fourofspades** [mikepenz/AboutLibraries#589]
The Google play store automation spends a very long time in the about libraries fragment, opening browsers and even embedded youtube videos rather than testing the app. . This is not a real world use use.  I think it would be useful to have a property that disables hyperlinks.  My users, I'm sure don't care or want a link to the library page, they mostly don't care about the list of libraries, and it's a compiiance / courtesy thing.

**Comment by mikepenz** [comment]
> My users, I'm sure don't care or want a link to the library page, they mostly don't care about the list of libraries, and it's a compiiance / courtesy thing.

This library is meant to give the proper attribution and visibility to the work library creators do to help developers build their work. As such providing links to their work is very important. 

There are no plans to remove this behaviour from the full detailed UI as it is the least we can do in our apps to appreciate the free work all those people do. 

--------

That being said. If you want to work around this / or you only want a very minimal UI. have a look at the `Minimal Design` highlighted in the sample app: https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.kt#L138

```
                        LibsBuilder()
                                .withAboutMinimalDesign(true)
                                .withEdgeToEdge(true)
                                .withActivityTitle("Open Source")
                                .withAboutIconShown(false)
                                .start(this@FragmentActivity)
```

--------

If you require custom behaviour beyond this, the library offers you to only include the `core` module and build your own UI which meets the full requirements.

**Comment by fourofspades** [comment]
Thanks, the minimal design was the trick.  My apps now passes automated testing on the Google Play store, even on low memory devices and doesn't go off down long alleyways of webviews and embedded youtube Jetpack tutorials!  They now test the actual app.
