### ISSUE TITLE
eula integration

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#59]
I suggest to make it possible to pass the eula: .setEula(R.string.xyz)
If passed then show an eula-button, maybe at the bottom of a also passed description but at top of the cards.
Please make it also possible to set the text of the eula-btn:
in English: "EULA"
in German: "Endbenutzerlizenzvereinbarung" ;-) --- a bit long :-(

**Comment by mikepenz** [comment]
Fixed in v4.5.6
