### ISSUE TITLE
Feature Request: exclude libraries by prefix

### ISSUE THREAD

**Issue by tinder-levonpetrosyan** [mikepenz/AboutLibraries#598]
Hi Mike, is it possible to add functionality to exclude libraries by passing a prefix? I want to use the library in a multi-module project and my main module depends on a couple of dozens of modules from my project, and I do not want to display any information about them.
This feature can be also helpful for excluding libraries from the same group, without worrying about newly added sublibraries. 

Possible workarounds can be 
1. Manually define all excluded libraries, but that does not scale well in terms of adding new dependencies from the project
2. Use `prepareLibraries()` and compose a list of excluded libraries by checking by prefix, but as far as this should be done on user click, it adds a bit delay before launching `LibsActivity`

Thank you in advance

**Comment by mikepenz** [comment]
Hi @tinder-levonpetrosyan thank you very much for the feature report. 

It sounds like this will make sense to exclude sub modules or make it easier to exclude such. 
Would it be sufficient to exclude them by their identifier? or would it require a different indicator for this? 

Ultimately this should already handled by the gradle plugin so there's no runtime penalty.

**Comment by tinder-levonpetrosyan** [comment]
I think it should be sufficient to exclude by their identifier, seem like the project libraries share the same prefix for `definedName` - `com_myrpoject_` and `libraryArtifactId`-`com.myrpoject.`

**Comment by mikepenz** [comment]
Thanks for the details. will have a look on that hopefully already this week

**Comment by tinder-levonpetrosyan** [comment]
Thanks a lot

**Comment by mikepenz** [comment]
Currently in the release process. Thanks again for the feature request
