### ISSUE TITLE
FYI: Bintray is shutting down on May 1st, 2020

### ISSUE THREAD

**Issue by arkon** [mikepenz/AboutLibraries#613]
This is just a heads up since I noticed that you're using Bintray to sync to Maven Central.

cf. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by mikepenz** [comment]
Yes :) 

I sync to maven central. just that maven central loves to be non stable 🙃 


![image](https://user-images.githubusercontent.com/1476232/106912892-c73a9480-6703-11eb-9ef9-b0727c1ae2c1.png)


Thanks for the info too :)

**Comment by arkon** [comment]
To be clear, I'm letting you know that you'll need to adjust your workflow to publish to Maven Central directly at some point, since Bintray is shutting down.

Thanks for the library!

**Comment by mikepenz** [comment]
Yep :) planning to do so over the weekend. thank you very much!

**Comment by Aguilar296** [comment]
I know 0 of that! Nothing, I don't know what that is, and if I did is
because of all the bs around me, I trust no one

**Comment by Aguilar296** [comment]
I work for my money, I thought someone was trying to get to my bank
