### ISSUE TITLE
SampleApp code

### ISSUE THREAD

**Issue by Mas7erMind** [mikepenz/AboutLibraries#622]
Hello, thanks for this awesome library. Do you have the SampleApp code somewhere to use as a starting point?

Thanks!

**Comment by mikepenz** [comment]
You can find it under `app` in this repo

https://github.com/mikepenz/AboutLibraries/tree/develop/app :) 

It has a bunch of different variants on using the library.

**Comment by Mas7erMind** [comment]
Oh sorry, I missed it while looking at the codebase. Thanks!
