### ISSUE TITLE
aboutLibrariesStyle not recognized

### ISSUE THREAD

**Issue by Mas7erMind** [mikepenz/AboutLibraries#623]
Hello! Any idea why `aboutLibrariesStyle` is not recognized in my style sheet?

![image](https://user-images.githubusercontent.com/35771256/109313635-6b50c080-7816-11eb-8f24-63faddab68b5.png)

**Comment by mikepenz** [comment]
Which version of the library are you using? 

You can see it in action in the sample app implementation: https://github.com/mikepenz/AboutLibraries/blob/develop/app/src/main/res/values/themes.xml#L10

**Comment by Mas7erMind** [comment]
Yes, I've looked at the sample app, but I can't find what I'm missing.

I'm using version 6.1.1 for compatibility with AppCompat but I've also tried with 6.2.3 with no luck.

`   implementation "com.mikepenz:aboutlibraries:6.1.1"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.1.0"`

**Comment by Mas7erMind** [comment]
Thanks, I downloaded the sample app for this version (6.2.3) and I figured out how it works :)
