### ISSUE TITLE
Empty license strings since 8.8.1 version

### ISSUE THREAD

**Issue by Faierbel** [mikepenz/AboutLibraries#624]
As of version 8.8.1, libraries downloaded using `Libs(contex).libraries` have empty strings in the `licenseDescription` and `licenseShortDescription` fields. 

The only solution is to use version 8.8.0

**Comment by mikepenz** [comment]
@Faierbel the main difference between those 2 versions would be the publishing to maven. Which is interesting. 

may you please try if it is related to the plugin or the library code?

(use 8.8.0 in library code but 8.8.1 plugin, and in reverse) 
Please clean in-between just to make sure.

**Comment by Faierbel** [comment]
Thanks for the quick reply

8.8.0 plugin, 8.8.1 library -> strings aren't empty
8.8.1 plugin, 8.8.0 library -> strings are empty

It looks like the problem is the plugin

**Comment by mikepenz** [comment]
I assume you also tried with the newest version 8.8.3 already before?

**Comment by mikepenz** [comment]
Could you by coincidence please also add the info which libraries lost the license string?

**Comment by mikepenz** [comment]
Found the issue fill release an update as quick as possible

**Comment by mikepenz** [comment]
The fix will be released with v8.8.4 within the next few minutes (~30-60 minutes until it's on maven central) 

Sorry for the inconvenience, and thank you so much for reporting the issue!

**Comment by Faierbel** [comment]
Thank you so much for fixing this problem so quickly. :)
