### ISSUE TITLE
Better Documentation for use in Java

### ISSUE THREAD

**Issue by Zardozz** [mikepenz/AboutLibraries#629]
## About this issue

- Briefly describe the issue
The Documentation gives details for Kotlin only 

This is related to #484 and the ProGuard item in the Readme.md https://github.com/mikepenz/AboutLibraries#proguard

`.withFields(R.string::class.java.fields)` is specific to Kotlin and gives a Lint error and won't compile when trying to use this option from a Java based App.

The correct value for a Java App seems to be

`.withFields(R.string.class.getFields())`

The other documentation on how to use was easy enough to convert from Kotlin examples to Java just the "withFields" was a bit more problematic to determine the right value

- How can the issue be reproduced / sample code
Build a Release Version of a Java based App using the libary

## Details
- [8.8.4 ] Used library version
- [4.1.0 ] Used gradle build tools version
- [4.1.3 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [X ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@Zardozz Java is no longer officially supported. While it may work we don't plan to provide documentation for it. 

I would highly recommend that you have a look into Kotlin as it will significantly improve your work. 

The last version which was officially targeting Java was v6.2.3 which can be found here: https://github.com/mikepenz/AboutLibraries/tree/v6.2.3

Beware that this old version lacks a ton of features.

**Comment by Zardozz** [comment]
I have looked in to Kotlin, it is more work than is worth it, it's a shame that you limit the usability of your library artificially and if other library developer took a similar attitude then by moving to Kotlin I would just get a bigger problem is reverse.
