### ISSUE TITLE
Fails with Gradle 7

### ISSUE THREAD

**Issue by arkon** [mikepenz/AboutLibraries#631]
## About this issue

The following exception is thrown when using `gradle-7.0-rc-1` (currently the minimum version required for Android Studio Canary):

```
A problem was found with the configuration of task ':app:prepareLibraryDefinitionsDebug' (type 'AboutLibrariesTask').
  - Type 'AboutLibrariesTask' property 'configPath' is annotated with @InputDirectory but missing a normalization strategy.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':app:prepareLibraryDefinitionsDebug' (type 'AboutLibrariesTask').
  - Type 'AboutLibrariesTask' property 'configPath' is annotated with @InputDirectory but missing a normalization strategy.
    
    Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
    
    Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
    
    Please refer to https://docs.gradle.org/7.0-rc-1/userguide/validation_problems.html#missing_normalization_annotation for more details about this problem.
[...]
```

## Details
- Used library version: 8.8.4
- Used support library version: N/A
- Used gradle build tools version: 7.0-rc-1
- Used tooling / Android Studio version: Android Studio Arctic Fox | 2020.3.1 Canary 14
- Other used libraries, potential conflicting libraries: N/A

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@arkon thanks for the report! :)

**Comment by carstenhag** [comment]
`exportLibraries` seems to be broken with gradle 7. I will create a new issue.
