### ISSUE TITLE
How to use this in java

### ISSUE THREAD

**Issue by rahul-119966** [mikepenz/AboutLibraries#636]
v6.2.3 is throwing errors while syncing. Version can not be found.
I tried with v8.8.5 and it worked but now LibsBuilder() is not coming.
I can only use Libs.Companion for now.

How to resolve this?

P.S. - I've imported all UI libraries that are required

**Comment by mikepenz** [comment]
@rahul-119966 the latest version is not targeted to be used via Java anymore. While it may work, it is not officially supported. 

Highly encourage you to update to Kotlin as this is the way to go moving forward in the Android world.

**Comment by mikepenz** [comment]
v6 is (I believe) only available from jcenter. 

https://github.com/mikepenz/AboutLibraries/tree/v6.2.3

**Comment by rahul-119966** [comment]
ok thanks

**Comment by mikepenz** [comment]
The library is no longer updated for java, and all APIs are Kotlin only. 
You might be able to use it in Java, however no support provided for it.
