### ISSUE TITLE
exportLibraries task not working with Gradle 7

### ISSUE THREAD

**Issue by carstenhag** [mikepenz/AboutLibraries#637]
## About this issue

- Briefly describe the issue
exportLibraries` task does not work with Gradle 7. `findLibraries` does work.
- How can the issue be reproduced / sample code
Any android project with Gradle 7 configured, I'm guessing.

## Details
- [x] Used library version - 8.8.5
- [x] Used support library version - fairly recent AndroidX versions
- [x] Used gradle build tools version: AGP 4.1.3, Gradle 7.0-all
- [x] Used tooling / Android Studio version: AS 4.2.1

```
$ ./gradlew exportLibraries
> Task :app:exportLibraries FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:exportLibraries' (type 'AboutLibrariesExportTask').
  - Type 'AboutLibrariesExportTask' property 'librariesWithoutLicenses' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'AboutLibrariesExportTask' property 'neededLicenses' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'AboutLibrariesExportTask' property 'unknownLicenses' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'AboutLibrariesExportTask' property 'variant' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues). See #631
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by carstenhag** [comment]
With 6.8.3 it works fine :)

**Comment by mikepenz** [comment]
Are you really on the latest version? we had updated things to rc02 back here: https://github.com/mikepenz/AboutLibraries/pull/633 So that seems very interesting

**Comment by carstenhag** [comment]
If 8.8.5 is the latest one, then yes :P. Or was the fix not released yet, being only in the branch?

**Comment by carstenhag** [comment]
Thanks!

**Comment by mikepenz** [comment]
Thank you so much for reporting the problem

**Comment by fourofspades** [comment]
Has something changed?  My working 885 is not broken on 886.

Execution failed for task ':app:prepareLibraryDefinitionsDebug'.
> Receiver class com.mikepenz.aboutlibraries.plugin.AboutLibrariesProcessor does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.

**Comment by mikepenz** [comment]
@fourofspades / @mueller-ma  I suppose that could be due to: https://github.com/mikepenz/AboutLibraries/compare/v8.8.5...v8.8.6#diff-e6a7317f36842898d8b7503d337e6c868886a1d08ddd7c79048aa73b883efa7bR42

But even that seems odd as the stacktrace points to a different location. 
Please open a new issue for that
