### ISSUE TITLE
Mapbox (BSD) license not detected

### ISSUE THREAD

**Issue by carstenhag** [mikepenz/AboutLibraries#638]
## About this issue

- Briefly describe the issue
`exportLibraries` doesnt know what to do with the BSD license of mapbox dependencies.
```
UNKNOWN LICENSES:
BSD
-- [com.mapbox.navigation:metrics:1.4.0, com.mapbox.base:annotations:0.4.0, com.mapbox.navigation:notification:1.4.0, com.mapbox.navigation:navigator:1.4.0, com.mapbox.base:common:0.4.0, com.mapbox.navigation:router:1.4.0, com.mapbox.common:common:9.1.0, com.mapbox.navigation:core:1.4.0, com.mapbox.common:logger:0.4.0, com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0, com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0, com.mapbox.navigation:base:1.4.0, com.mapbox.navigation:ui:1.4.0, com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.2.0, com.mapbox.navigation:utils:1.4.0]
```

- How can the issue be reproduced / sample code
According to one of the .pom files it's the 2-clause BSD license. Would be cool if the lib could automatically detect it, without us having to define it :)
https://repo1.maven.org/maven2/com/mapbox/navigation/core/1.0.0-beta.1/core-1.0.0-beta.1.pom

We actually import these libs:
```
    implementation 'com.mapbox.navigation:ui:1.4.0'
    implementation 'com.mapbox.navigation:core:1.4.0'
```
but to even download them you will need to create a mapbox account, get an api key with sdk download scope, set up these maven repos...:

```
        maven {
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication { basic(BasicAuthentication) }
            credentials {
                username = "mapbox"
                password = project.properties['mapbox_sdk_download_token'] ?: ""
            }
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication { basic(BasicAuthentication) }
            credentials {
                username = 'mapbox'
                password = project.properties['mapbox_sdk_download_token'] ?: ""
            }
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/snapshots/maven'
            authentication { basic(BasicAuthentication) }
            credentials {
                username = "mapbox"
                password = project.properties['mapbox_sdk_download_token'] ?: ""
            }
        }
```

## Details
- [x] Used library version: 8.8.5

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues): Did, no results

**Comment by mikepenz** [comment]
@carstenhag would you please be so kind to provide the pom.xml of this library?

**Comment by carstenhag** [comment]
For `com.mapbox.common:logger:0.4.0`: https://repo1.maven.org/maven2/com/mapbox/common/logger/0.4.0/logger-0.4.0.pom

For an older version of `com.mapbox.navigation`, which I do not sure: https://repo1.maven.org/maven2/com/mapbox/navigation/core/1.0.0-beta.1/core-1.0.0-beta.1.pom

**Comment by mikepenz** [comment]
Oh that sadly didn't make it into the update :( should cover in the next version at some point. 

Until that please provide a custom mapping
