### ISSUE TITLE
Hamcrest BSC License 3 not detected

### ISSUE THREAD

**Issue by carstenhag** [mikepenz/AboutLibraries#639]
## About this issue

- Briefly describe the issue

`exportLibraries` says:
```
UNKNOWN LICENSES:
BSD License 3
-- [org.hamcrest:hamcrest:2.2]
```

- How can the issue be reproduced / sample code

Import `testImplementation "org.hamcrest:hamcrest:2.2"`

## Details
- [x] Used library version: 8.8.5

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)

**Comment by mikepenz** [comment]
This one is not matched because that lib does not use the specific spdx identifier. `BSD-3-Clause` 

As this seems to be more common though, will expand the matching to the license url

**Comment by carstenhag** [comment]
Thanks! Yeah, I figured that the bsd ones sometimes have different names
