### ISSUE TITLE
Jetpack navigation and XML configuration

### ISSUE THREAD

**Issue by ts65** [mikepenz/AboutLibraries#645]
I included your excellent library in my project using Jetpack navigation as described in https://github.com/mikepenz/AboutLibraries#jetpack-navigation which worked nicely. When I want to configure what is shown on the fragment using the XML part of https://github.com/mikepenz/AboutLibraries#about-this-app-ui I cannot change any boolean values. The XML is used in the sample app too and only certain values can be changed there too. For example aboutLibraries_description_showIcon can be set to false but the icon will be shown regardless of this setting. If I understand it correctly, the value is read in LibsFragmentCompat.kt by using extractBooleanBundleOrResource() from ContextExtension.kt but will allow to override null values only. But in LibsBuilder.kt it is initialized with true (and showIcon can't be null anyway) so that will be used not what is specified in the XML. Am I missing something or how can I configure the shown data for the boolean values? Thanks in advance

**Comment by mikepenz** [comment]
@ts65 thank you so much for the report. I'll have a look

**Comment by ts65** [comment]
Thank you so much, it works nicely with the latest version. Would you be willing to expand it to support showLicence in XML/LibsFragmentCompat too?

**Comment by ts65** [comment]
Thank you!

**Comment by mikepenz** [comment]
@ts65 the changes for the additional feature are not yet published, will be in a future version. thank you for the issue and the suggestions :)
