### ISSUE TITLE
Usage in a multi module project gives 0 libraries

### ISSUE THREAD

**Issue by DDihanov** [mikepenz/AboutLibraries#647]
Hey! 

Trying to use this lib in a multi module project, and I am always getting 0 libraries in a module. The module I am using it has no relation to the app module - they are fully decoupled. Am I doing something wrong?

**Comment by mikepenz** [comment]
Thank you for the report @DDihanov 

The action has been mainly targeted for application modules, and there may be some impacts when using it on a library module. 

This sounds like a great enhancement though and something to investigate. 

do you by coincidence have a sample app to test this on? otherwise it's something we will look into within the sample project.

**Comment by DDihanov** [comment]
Thanks for the quick answer.

My project layout is the following:
One main app module where the Application class is situated. It includes dependencies to all other modules. I am not using this module for anything else other than wiring DI(so it only has this one class). When I run the app and check out the libraries ```Libs(this).libraries``` in the Application ```onCreate``` they are 0.

All other modules are ```apply plugin: 'com.android.library```. The UI component works, but the libraries are 0 there as well.

Also calling any single ```get(...)``` method on ```Libs(this)``` yields 0 libraries.

I don't know if this is worth noting, but I have all my dependencies in the ```buildSrc``` folder and referencing them from there.

**Comment by mikepenz** [comment]
Sorry for the late answer. 

Could you maybe also look on the generated files in the build folder. Are those generated or missing?
<img width="268" alt="Screenshot 2021-05-28 at 11 19 33" src="https://user-images.githubusercontent.com/1476232/119961645-94fcbd80-bfa6-11eb-84fe-672d7c953eb1.png">

Also please adjust the approach you use to retrieve the libraries. 

It's suggested to provide the fields so it is not having trouble with obfuscation, and additionally `prepareLibraries` has to be called

Sample code:

```kotlin
Libs(this, R.string::class.java.fields.toStringArray())
                .prepareLibraries()
                .forEach {
                    Log.d("AboutLibraries", it.libraryName)
                }
```

**Comment by mikepenz** [comment]
The action is now also applied to libraries: https://github.com/mikepenz/AboutLibraries/commit/ea8a03884cae10af2ff3c886b12d1845e4f5af16
