### ISSUE TITLE
Register tasks lazily

### ISSUE THREAD

**Issue by eygraber** [mikepenz/AboutLibraries#651]
A build scan of my project highlights that the following 3 tasks from this plugin aren't created lazily:

```
aboutLibrariesClean, exportLibraries, findLibraries
```

I think that all that would be required is to replace the call to `create` with a call to `register`, but I'm not sure if there is anything that will be affected by that.

**Comment by mikepenz** [comment]
Thank you very much @eygraber for the suggestion. 

It's something we can try and see how it behaves
