### ISSUE TITLE
define other color for withAboutSpecialX-Button and also other size for text in the dialog

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#66]
I want to set another color for the buttons. How can this be done?
I also want to define the text size in the dialog.

**Comment by Rainer-Lang** [comment]
Please make separate methods to set color for the buttons. Thanks. ;-)

**Comment by mikepenz** [comment]
@Rainer-Lang changing the text-size within the dialog would require you to change the AlertDialog style for the theme you use with the AboutLibraries library

**Comment by Rainer-Lang** [comment]
@mikepenz OK. Thanks for the info.
