### ISSUE TITLE
Export to CSV seems to be not working

### ISSUE THREAD

**Issue by loyalman** [mikepenz/AboutLibraries#666]
`./gradlew exportLibraries` does not create CSV file anywhere

`./gradlew exportLibraries` shows a list of libraries in terminal but does not create CSV file anywhere.
The only setting applied is 
`aboutLibraries {
    configPath = "config"
}`
It doesn't show any error in the terminal.
The config path is empty after running this command.

AboutLibraries v 8.9.1 included by Gradle Plugin (without UI stuff)
Android Studio v 2020.3.1
Gradle Plugin v 7.0.1
with enableFeaturePreview("VERSION_CATALOGS") (all deps are in .toml file)
Mas OS 11.5.2 (if it matters)

**Comment by mikepenz** [comment]
The `exportLibraries` will export as a CSV format, in the output of the task, it does currently not write it to a file.

Do you have some more details around the usecase you are looking into?

**Comment by loyalman** [comment]
Oh, my wrong.
I wanted to use this in order to collect all the dependencies with names, versions, authors, licenses and descriptions just before app release to check the things out.
And I thought this command get me everything in one place.
Definitely I can copy-paste from the output to some file by myself.

**Comment by loyalman** [comment]
So for now I can't find the way to add some fields to `exportLibraries` output

**Comment by mikepenz** [comment]
@loyalman if you require the information exported to a CSV file for compliance reasons you can use the `exportComplianceLibraries` task. 

Both these tasks are designed to get an overview of the included libs + libraries and licenses not covered (helpful for debugging purposes) 

They are not meant to fully dump all information the library collects, as the primary way of consumption and display is via the `Libs` class inside the app. (with or without the UI) 


This may be a new feature we can add.

**Comment by mikepenz** [comment]
For now I think the `./gradlew app:exportComplianceLibraries{Release/Type}` command matches the needs. 

Please report if there's something missing in that csv export not matching the needs.
