### ISSUE TITLE
A licenses year field is always "YEAR"

### ISSUE THREAD

**Issue by zoltish** [mikepenz/AboutLibraries#674]
## About this issue

- Each license description only includes a placeholder YEAR label instead of the actual year; e.g. Copyright © YEAR, AOSP.

## Details
- [8.9.3] Used library version
- [-] Used support library version
- [7.1.0-alpha03] Used gradle build tools version
- [Android Studio Arctic Fox | 2020.3.1 Patch 2] Used tooling / Android Studio version
- [-] Other used libraries, potential conflicting libraries

## Checklist

- [-] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [-] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [-] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [-] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [-] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Sadly the library can not automatically resolve the year as it is not part of the `*.pom` file on maven (See the spec for POM files: https://maven.apache.org/pom.html#Licenses) 
The library can't just assume the latest year as this may not be the accurate information. 

What's offered by the library though is that you can provide the year for different libraries:
https://github.com/mikepenz/AboutLibraries#gradle-plugin-configuration

Via the `custom_license_year_mappings.prop` file. 

See a sample here:
https://github.com/mikepenz/AboutLibraries/blob/develop/config/custom_license_year_mappings.prop

Use `./gradlew findLibraries` to get all the dependencies + their identifier

**Comment by zoltish** [comment]
Gotcha, thanks for clearing that up for me! 

Do you have any insight into how [Google](https://developers.google.com/android/guides/opensource) manages to include the year in its licenses? Its by no means perfect, sometimes the date is in the header, sometimes part of the copyright text near the end - but its pretty much always there.

**Comment by mikepenz** [comment]
Sadly the pom won't contain it: https://maven.google.com/androidx/lifecycle/lifecycle-livedata/2.4.0-rc01/lifecycle-livedata-2.4.0-rc01.pom

Sadly there is also no `LICENSE` file included in the aar. 

It could be that they may do some clever parsing of the `AndroidManifest.xml`

Or maybe they follow the repo on github and check if there's a `LICENSE` file located. 


Some reverse engineering of the gradle plugin may lead to some hints.

**Comment by mikepenz** [comment]
[third_party_license_metadata.txt](https://github.com/mikepenz/AboutLibraries/files/7286492/third_party_license_metadata.txt)
[third_party_licenses.txt](https://github.com/mikepenz/AboutLibraries/files/7286493/third_party_licenses.txt)

That's for example the output of googles plugin

**Comment by mikepenz** [comment]
You can read their source here: https://github.com/google/play-services-plugins/blob/master/oss-licenses-plugin/src/main/groovy/com/google/android/gms/oss/licenses/plugin/LicensesTask.groovy#L86-L101

They do some special handling for their own libraries (with some special license artifact). 

For other libraries, they will just download the LIBRARY spec as found on the defined URL in the *.pom file

**Comment by zoltish** [comment]
Thats interesting. Ive dug into their plugin several times but Im all too unfamiliar with groovy to understand the inner workings of it; what youre saying makes sense though. I appreciate all the fast responses! 👍🏾

**Comment by koral--** [comment]
There is an `inceptionYear` POM property.

> The year of the project's inception, specified with 4 digits. This value is used when generating copyright notices as well as being informational.

https://maven.apache.org/archives/maven-1.x/reference/maven-model/3.0.2/maven.html#project

Not 100% sure if this is a right source of the year for license purposes.
"copyright notices" seems to be a similar thing.

**Comment by mikepenz** [comment]
@koral-- usually the `inceptionYear` indicates the introduction of the library. Often this sadly does not match the actual current license year. 

I would wish they had the `licenseYear` in the spec

**Comment by mikepenz** [comment]
Created a super early prototype of the next major release for `AboutLibraries`. This will contain:
- loading licenses from the github repository (if LICENSE available and project is open source)
  - otherwise will load license specification from SPDX
  - Curious if there are alternative resolution strategies possible
- store the library information in a new JSON format
  - no more string resources for library in this format -> smaller, does not count against dex limit

See the initial PR here
https://github.com/mikepenz/AboutLibraries/pull/675

**Comment by mikepenz** [comment]
#675 is superseded by: https://github.com/mikepenz/AboutLibraries/pull/685 

Published as v10.0.0-a01, happy to get early feedback :)

**Comment by mikepenz** [comment]
v10 is new available as a first beta with the ability to fetch the licenses from GitHub which would include the right year.
