### ISSUE TITLE
Question: How to add custom mapping for an .aar library?

### ISSUE THREAD

**Issue by Berki2021** [mikepenz/AboutLibraries#678]
## About this issue

I would like to add a custom license but even after adding the strings, it does not show. Furthermore, I do not understand this sentence: 

> Finally, you have to use the specified identifier myLicense when referencing this license in your mappings.

What exactly is meant with "in your mappings"? Could you provide an example? Here is how I've done it:

```
<resources>
    <!-- HereSDK Licence Agreement -->
    <string name="define_license_herelicense" translatable="false" />
    <string name="license_herelicense_licenseName" translatable="false">Here SDK</string>
    <string name="license_herelicense_licenseShortDescription" translatable="false">
        <![CDATA[
            <p>Here SDK is a Location Service to enhance apps with rich maps and location context.</p>
        ]]>
    </string>
    <!-- name of the license file under the raw folder -->
    <string name="license_herelicense_licenseDescription" translatable="false">raw:herelicense</string>
    <!-- -->
</resources>
```

When only adding the above, nothing changed and the dependency was not recognized. I had to furthermore add the following:

```
<resources>
    <string name="define_plu_herelicence">year;owner</string>
    <string name="library_herelicence_author">Here</string>
    <string name="library_herelicence_libraryName">Here SDK</string>
    <string name="library_herelicence_libraryDescription">
        Here SDK is a Location Service to enhance apps with rich maps and location context.
    </string>
    <string name="library_herelicence_libraryWebsite">https://developer.here.com/products/here-sdk</string>
    <string name="library_herelicence_licenseIds">herelicense</string>
</resources>
```

But when I added this, my `herelicense.txt` was not recognized.

## Details
- [8.9.3] Used library version
- [-] Used support library version
- [7.0.3] Used gradle build tools version
- [Android Studio Arctic Fox | 2020.3.1 Patch 3] Used tooling / Android Studio version
- [-] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@Berki2021 you are already very close. The plugin/library can not automatically detect licenses to match a dependency. 

For manual mapping of a library to a license you can use the `config` files. You can see all relevant changes for this for example here: 

https://github.com/mikepenz/AboutLibraries/commit/e43d7530f4cc907d6d7d6a6d62a514e23c87fd9a

For demo app showcase purposes I assigned the license to the activity-ktx dependency. but you can use `findLibraries` to get the `id` of the dependency you want to specify the license for.

**Comment by Berki2021** [comment]
> 
> 
> @Berki2021 the library is not loaded via maven? ok in this case the library information itself also needs to be provided.
> 
> Expanded the sample branch to highlight this too: [ea7a484](https://github.com/mikepenz/AboutLibraries/commit/ea7a4847e8f68b1df7a337f4c022b65496a56d23)

Okay, now it is shown, but I am a bit confused: What is the need of the "raw:file" when the card is opening a website?

**Comment by mikepenz** [comment]
It depends on how you configure the library. 

You have the option to choose from showing a dialog, vs loading the website:
https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L225
