### ISSUE TITLE
Jetpack Compose UI?

### ISSUE THREAD

**Issue by adrianlandborn** [mikepenz/AboutLibraries#684]
## About this issue

- Briefly describe the issue
The current app I am working on is built completely with **Jetpack Compose** UI components. Is there a plan to implement the Licenses UI with Compose? The reason for this would be to rely in Design tokens (theme, fonts, colors) from the Compose Theming functionality.

## Details
- [ 8.9.4] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ 2020.3.1 patch 3] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ x ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ x ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ x ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ x ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ x ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
v10.0.0-a01 was just pushed with an early compose module and a fully reworked plugin. 

Happy to get some early feedback: https://github.com/mikepenz/AboutLibraries/pull/685

**Comment by leinardi** [comment]
Hi, I'm trying to test `v10.0.0-a02` on a Compose only project, but I can't find the `LibrariesContainer`. I'm using the artifact `com.mikepenz:aboutlibraries`, should I add something else?

**Comment by mikepenz** [comment]
@leinardi you can find the new artifact with the "-compose" artifact id: https://github.com/mikepenz/AboutLibraries/pull/685/files#diff-fed24da941cbe1f924c94a8ddedaeef146bdfcf9d886bc6795dbdd57843754e4

**Comment by leinardi** [comment]
Thanks!
I managed to get it to work, but I had to use the previous version, `10.0.0-a01`, because the dependency can't be solved when I use `com.mikepenz:aboutlibraries-compose:10.0.0-a02`.

![image](https://user-images.githubusercontent.com/273338/140570612-3859f088-4331-40ba-bbb8-c1076c35a414.png)

**Comment by leinardi** [comment]
I just added a comment on the PR about the use of the default package (was it on purpose?):
https://github.com/mikepenz/AboutLibraries/pull/685/files#r743941700

**Comment by mikepenz** [comment]
> Thanks! I managed to get it to work, but I had to use the previous version, `10.0.0-a01`, because the dependency can't be solved when I use `com.mikepenz:aboutlibraries-compose:10.0.0-a02`.
> 
> ![image](https://user-images.githubusercontent.com/273338/140570612-3859f088-4331-40ba-bbb8-c1076c35a414.png)

Sorry, forgot to `release` the sonatype repo before, did so now. so it should become available via maven central in the next 60 minutes. 

Todays update mainly contained the version updates of compose, and improvements in the gradle plugin. Including strategies to handle situations where multiple artifacts of a single dependency exist. (E.g. aboutlibraries-core, aboutlibraries, ..)

**Comment by mikepenz** [comment]
@leinardi currently releasing v10.0.0-a03 with the adjustments as you had noted, including a fix to the package name. 
If you could please check it out

(will take around ~60 mins to be available on maven central)

**Comment by leinardi** [comment]
@mikepenz sure!

**Comment by leinardi** [comment]
@mikepenz just tested, everything seems fine :+1: 
![image](https://user-images.githubusercontent.com/273338/140608794-09d7d5ab-9a88-494f-b009-6bbe8bb0f43b.png)

There seems to be some issue with the the source code bundled with the library, it is not showing automatically and the on decompiled code is shown instead:
![image](https://user-images.githubusercontent.com/273338/140608870-1929acc2-2b4e-41c2-a49b-8e41f4deacf8.png)

**Comment by mikepenz** [comment]
that may be due to the kotlin multiplatform module or such. thank you. 
Thank you for testing.

**Comment by mikepenz** [comment]
v10.0.0-a04 the first version with compose-desktop and compose on Android support.

The plugin is functional for any target and works for all gradle projects. The `core` module being fully compatible with kotlin multiplatform.

https://github.com/mikepenz/AboutLibraries/pull/685#issuecomment-962505578

**Comment by fuomag9** [comment]
Can anybody guide me on how to add a custom entry? The current examples are not very clear and they do not seem to work

For example, where would I need to put this?
```
<resources>
    <!-- identifier used to reference this library -->
    <string name="define_plu_myLibrary">year;owner</string>
    <string name="library_myLibrary_author">Author</string>
    <string name="library_myLibrary_authorWebsite">https://mikepenz.dev</string>
    <string name="library_myLibrary_libraryName">My Library</string>
    <string name="library_myLibrary_libraryDescription">Some text</string>
    <string name="library_myLibrary_libraryVersion">10.1.1</string>
    <string name="library_myLibrary_libraryWebsite">https://mikepenz.dev</string>
    <!-- you can also reference custom licenses here e.g. myLicense -->
    <string name="library_myLibrary_licenseIds">apache_2_0</string>
    <string name="library_myLibrary_isOpenSource">true</string>
    <string name="library_myLibrary_repositoryLink">https://mikepenz.dev</string>
    <!-- Custom variables section -->
    <string name="library_myLibrary_owner">Owner</string>
    <string name="library_myLibrary_year">2020</string>
</resources>
```

**Comment by mikepenz** [comment]
@fuomag9 I believe your comment is off-topic to this ticket. It would require more information like which used version of the library. v10 will significantly change and simplify adding additional libraries manually. 
Please consider opening a separate issue, with additional information

**Comment by mikepenz** [comment]
Will be part of https://github.com/mikepenz/AboutLibraries/pull/685

Please also provide feedback in the big v10 ticket: https://github.com/mikepenz/AboutLibraries/issues/688
