### ISSUE TITLE
v10 Feedback

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/AboutLibraries#688]
v10 is the brand new and major upgrade to AboutLibraries. It comes with a whole new data structure, a kotlin multiplatform core, and a new kotlin multiplatform compose (desktop / android) module. 

Significantly simplified and cleaned up code base. 

Use the plugin to generate the dependency information 
- automatically for android builds -> always new information 
- partially automatic for all gradle builds  -> commit as part of SCM and be in full control

v10 also comes with a new design, with an early simplified UI showing the major details about used dependencies. 

-------

#### Build
```
// Root build.gradle
classpath "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:10.0.0-b06"

// App build.gradle
apply plugin: 'com.mikepenz.aboutlibraries.plugin'

// Compose UI | App build.gradle
implementation "com.mikepenz:aboutlibraries-compose:10.0.0-b06"
```

#### App

```kotlin 
LibrariesContainer(
    Modifier.fillMaxSize(),
    contentPadding = rememberInsetsPaddingValues(
        insets = LocalWindowInsets.current.systemBars,
        applyTop = true,
        applyBottom = true,
    )
)
```

https://github.com/mikepenz/AboutLibraries/blob/feature/remote_licenses/app/src/main/java/com/mikepenz/aboutlibraries/sample/ComposeActivity.kt#L44-L51

-------

v10 is currently developed on this [branch](https://github.com/mikepenz/AboutLibraries/tree/feature/remote_licenses)

-------

![](https://user-images.githubusercontent.com/1476232/140622857-2c0bd2f2-91b2-43ab-bf10-fc753b400892.png)

![](https://user-images.githubusercontent.com/1476232/140622866-94f1557e-5347-4b17-9041-f6c11d559a20.png)

-------

v10 is still in alpha, which is the perfect time to get feedback and learn about additional needs to make the v10 the best release of it ever!

**Comment by mibac138** [comment]
I've got a `StackOverflowError` with `10.0.0-b03` that wasn't present with `8.9.4`. Code: https://github.com/wulkanowy/wulkanowy
```
Cause: java.lang.StackOverflowError
	at com.google.common.cache.LocalCache$Segment.setValue(LocalCache.java:2009)
	at com.google.common.cache.LocalCache$Segment.storeLoadedValue(LocalCache.java:3158)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2279)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.getOrRegisterResourceLock(AbstractResourceLockRegistry.java:45)
	at org.gradle.internal.work.DefaultWorkerLeaseService$WorkerLeaseLockRegistry.getResourceLock(DefaultWorkerLeaseService.java:351)
	at org.gradle.internal.work.DefaultWorkerLeaseService.getWorkerLease(DefaultWorkerLeaseService.java:93)
	at org.gradle.internal.work.DefaultWorkerLeaseService.getWorkerLease(DefaultWorkerLeaseService.java:100)
	at org.gradle.internal.work.DefaultWorkerLeaseService.getWorkerLease(DefaultWorkerLeaseService.java:55)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.<init>(DefaultBuildOperationQueue.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationQueueFactory.create(DefaultBuildOperationQueueFactory.java:31)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:138)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$runAll$4(DefaultBuildOperationExecutor.java:108)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet.visit(ParallelResolveArtifactSet.java:66)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.sort(DefaultResolvedDependency.java:129)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getModuleArtifacts(DefaultResolvedDependency.java:107)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:113)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
	at org.gradle.api.internal.artifacts.DefaultResolvedDependency.getAllModuleArtifacts(DefaultResolvedDependency.java:115)
<repeated over 1000 times with no other >
```

**Comment by mikepenz** [comment]
@mibac138 thank you very much. looks to be happening somewhere within gradle. I'll have a look. Thanks for providing the repo, that will be super helpful. Is there a branch where you tried it? or just changed the about libs version

**Comment by mikepenz** [comment]
@mibac138 it seems something is strange with `maven { url "https://developer.huawei.com/repo/" }` causing problems. 
If I remove this repository it will build properly, but as soon as I add it back it somehow causes an issue within gradle. 
It seems to be more of a gradle problem :/

**Comment by mikepenz** [comment]
Thank you very much @zoltish

**Comment by Berki2021** [comment]
I wanted to migrate to v10, but with this version, it seems we cannot add manual libraries? How exaclty can I migrate the following code?

```
return LibsBuilder()
            .withFields(R.string::class.java.fields)
            .withVersionShown(false)
            .withLicenseShown(true)
            .withLicenseDialog(true)
            .withLibraryModification("io_coil_kt__coil_base",
                Libs.LibraryFields.LIBRARY_NAME,
                "Coil")
            .withLibraryModification("com_google_guava__guava",
                Libs.LibraryFields.LIBRARY_NAME,
                "Guava")
            .withLibraryModification("pl_droidsonroids_gif__android_gif_drawable",
                Libs.LibraryFields.LIBRARY_NAME,
                "AndroidGIFDrawable")
            .withLibraryModification("aboutlibraries",
                Libs.LibraryFields.LIBRARY_NAME,
                "AboutLibraries")
            .withLibraryModification("fastadapter", Libs.LibraryFields.LIBRARY_NAME, "FastAdapter")
            .adapter(requireContext())
```

**Comment by mikepenz** [comment]
@Berki2021 v10 puts much more focus on the `plugin` and `core` functionality by already offering adjustment options on those API levels. 

The UI module which in the past had a lot of those modifications APIs lost those functionalities in favour of the API improvements compose will bring. 

As for compose you can pass in the libraries directly, normal Kotlin methods to modify the dataset should be used. 

For the legacy UI module in v10 use the config folder for the plugin and provide the json to overwrite fields of libraries. Which looks like this:

https://github.com/mikepenz/AboutLibraries/blob/develop/config/libraries/lib_merge_material_drawer.json

You only need to provide the `uniqueId` and the field you want to modify.

**Comment by ts65** [comment]
I'm not sure this is the right place and I haven't really looked at this new version yet (sorry. One thing I would like is to be more flexible with the design/library items, the previous and current UI seem to be locked to either LibraryItem or SimpleLibraryItem implementations (with the aboutMinimalDesign property of the LibsBuilder). Would you consider something like defining an interface for library items which both classes implement and change LibsBuilder to have a property for the library item? The aboutMinimalDesign property would be replaced by a libraryItem property (maybe the withAboutMinimalDesign method could be kept but sets the libraryItem property accordingly if one doesn't want to specify a class). With something like that one could use LibraryItem and SimpleLibraryItem as before, one could derive either one and adjust it or write a different library item implementation to create more customized designs.

**Comment by mikepenz** [comment]
Thank you very much for the feedback @ts65 

A core push from v10 is, to mark the old view based UI as legacy (and slowly phase it out over time) and offer a new experience via a compose based UI. 

While this does not yet directly solve your concern, it does offer the benefits Compose brings. 
The `composeables` will be significantly more lightweight, as such it's gonna be simpler to just replace the provided UI with any custom UI you may be looking for. 

Another main focus of v10 has been to provide a much more simple yet powerful `core` module which allows you to interact with the `Library` information directly. This gives the flexibility to implement any custom UI deriving from the standard as needed. No limitations set.

**Comment by znakeeye** [comment]
Would be nice to be able to customize the name of the `aboutlibraries.json` resource. In my case, the licenses come from different assets, so `licenses.json` would be more correct.

**Comment by mikepenz** [comment]
@znakeeye v10.0.0-b09 will include a new API which allows you to modify the output filename.

**Comment by leinardi** [comment]
Hi @mikepenz, first of all thanks for the great work you did on this library :) 

I just have a small suggestion for the UI of the Compose version:
![image](https://user-images.githubusercontent.com/273338/155285502-e71ae39b-11b1-4f97-bcb7-4256b21af02a.png)
What about moving the OK button outside the Column so that it will be always visible? 
This way will be also compliant with the Material Design specs:
![image](https://user-images.githubusercontent.com/273338/155285785-e436ca32-7c03-4b17-802c-75b621929627.png)
https://material.io/components/dialogs#behavior

**Comment by leinardi** [comment]
Another improvement would be to remove duplicate lib entries:
![image](https://user-images.githubusercontent.com/273338/155288140-43c973a3-ac8c-4916-a64d-f7b63541ebd5.png)
not sure why but your lib appear twice, despite having it added only once as dependency. If I have to guess, one is the compose lib and the second is the transient core lib. But, since they show the very same info, would make sense to only show unique entries.

**Comment by leinardi** [comment]
The `core` dependency should be added as `api`, not `implementation` to the `compose` library, otherwise `com.mikepenz.aboutlibraries.Libs` won't be visible.
This is needed to be able to run code like this:
```kotlin
val libraries = remember { mutableStateOf<Libs?>(null) }
```

As a workaround you have to add both the compose and core libs as dependencies but, if for the compose lib is exposing classes from the core as API, it should also expose the core lib itself as API.

**Comment by mikepenz** [comment]
@leinardi thank you very much for the feedback. 

On the first comment to have the dialog be adjusted. Absolutely, that would make a lot of sense, if you would like to do a PR, happy to review and get it in!


On your second comment: "duplicated entries". There's handling for duplication. You can configure it on the gradle plugin via the following flags:
```
    // Enable the duplication mode, allows to merge, or link dependencies which relate
    duplicationMode = com.mikepenz.aboutlibraries.plugin.DuplicateMode.LINK
    // Configure the duplication rule, to match "duplicates" with
    duplicationRule = com.mikepenz.aboutlibraries.plugin.DuplicateRule.SIMPLE
```
https://github.com/mikepenz/AboutLibraries/blob/d6a4e41b88592d5fa611d1044a1f8aa3e265b9b8/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt#L123


On your third comment. I am not fully sure, for simpler usecases users most likely won't need to reference `Libs` in their project and only use the `LibrariesContainer`.  Probably it's more a matter on expanding the documentation?

**Comment by leinardi** [comment]
@mikepenz PR created! #733

**Comment by hvsimon** [comment]
Hi there, the theme config in Compose in this lib is hardcode with `MaterialTheme.colors.primary`

https://github.com/mikepenz/AboutLibraries/blob/8ed8f228725a8a304edc3e07b10e933724468e0a/aboutlibraries-compose/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/SharedLibraries.kt#L78

Maybe it would be bettter to provide color parameter like what material compose lib do:

```
@Composable
@NonRestartableComposable
fun Surface(
    modifier: Modifier! = Modifier,
    shape: Shape! = RectangleShape,
    color: Color! = MaterialTheme.colors.surface,
    contentColor: Color! = contentColorFor(color),
    border: BorderStroke? = null,
    elevation: Dp! = 0.dp,
    content: (@Composable () -> Unit)?
): Unit
```

Because not everyone uses `material.MaterialTheme`, some use `material3.MaterialTheme`.

**Comment by mikepenz** [comment]
Great suggestion @hvsimon, not sure when I'll have time to rework this part. Happy to take a PR for this too :)

**Comment by hvsimon** [comment]
@mikepenz This is my first RP #740
If you have any suggestions please let me know :)

**Comment by mikepenz** [comment]
@hvsimon oh well. good point. I suppose it should get its own defaults. but can be a subclass of the newly introduced class.

**Comment by Syer10** [comment]
Can you expose the LazyListState as a variable in the Libraries composable? I want to add a scrollbar since my app does not require a scrollwheel to use, but I cannot do that without having the LazyListState

**Comment by Syer10** [comment]
Thanks! Happy this library got Compose Multiplatform support, it works perfectly on both Desktop and Android

**Comment by koral--** [comment]
Legacy UI seems to miss background. Note the space between cards on the recording.
At a glance, it looks like the LibsActivity may not specify its theme?

Quick workaround:
```
        <activity
            android:theme="@style/Theme.MaterialComponents.NoActionBar"
            android:name="com.mikepenz.aboutlibraries.ui.LibsActivity"
            android:exported="false" />
```

https://user-images.githubusercontent.com/3340954/164219141-d0084c44-9691-4153-b347-2b098066a6e1.mp4

**Comment by mikepenz** [comment]
@koral-- thank you for the feedback. 
The activity does really not specify a theme, as it's meant to pick up the application wide theme (that should have been already the case in v9)

Beyond that if you want to theme it the style should be defined for aboutLibs: https://github.com/mikepenz/AboutLibraries#style-the-aboutlibraries-%EF%B8%8F

**Comment by CarlosEsco** [comment]
For compose - 

Can the alert dialog be themed to match the passed in Library Colors?

Also ability to add some padding on the badges, so the text isn't up to the edges

**Comment by mikepenz** [comment]
@CarlosEsco that's are good proposals to expand theming options for these ones.

**Comment by Berki2021** [comment]
I am quite confused, after updating to v10, there is no `.adapter(context)` function anymore. Furthermore, `LibsBuilder()` can't accept a json, only `Libs.Builder()` can.

**Comment by mikepenz** [comment]
Thank you for adding the additional context @Berki2021 . 

Yes you are correct `withLibraryModification` was dropped in favour of `Libs` which has the information, and libraries could be altered by mapping them and adjusting to your needs. like an example:
```
Libs.Builder().build().libraries.map {
            if(it.artifactId == "xyz") {
                it.copy(name = "custom name")
            }
}
```

You have different options though:
- use the configuration API within gradle, to apply the modifications you highlight above during compile time (instead of runtime) -> so the json will already have the adjusted information
- use the API within gradle so you commit the definition in the CI and you patch it manually
- you stay with v9 or prior until you feel comfortable updating
- you use the core module only `Libs.Builder` retrieve the library information and display libraries with your own custom UI. -> Build your own RV and pass in the items as your app requires them.
- partially start using compose (no need to change the full application) 
- maybe more options

-----

I'll also consider (but can't promise) to look if we can open up an API to pass in a `Libs` instance into the legacy APIs

**Comment by CarlosEsco** [comment]
10.2 alert dialog theme is step in the right direction, there is one last thing missing, the OK button is not themed still.

**Comment by mikepenz** [comment]
Thanks everyone for the feedback in this thread.
