### ISSUE TITLE
Dialog for special buttons should have a close button.

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#69]
The dialogs should have a close button - the text should also be customizable.

**Comment by mikepenz** [comment]
@Rainer-Lang is this really required?

**Comment by Rainer-Lang** [comment]
I would make a button at bottom "close".

**Comment by Rainer-Lang** [comment]
I would really prefer to have this button.

**Comment by RubyDerBoss** [comment]
As seen here: http://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs
Simple Dialogs like those in the library shouldn't have a explicit close button.

**Comment by mikepenz** [comment]
@RubenGees thanks. 

CLOSE :D
