### ISSUE TITLE
Special buttons: Please look at the guidelines.

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#70]
http://www.google.com/design/spec/components/buttons.html#buttons-usage
or here: http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7OU9vRGtPQkhwMHM/components_buttons_usage5.png

Maybe you decide to make also the button background color customizable. :-)

**Comment by mikepenz** [comment]
@Rainer-Lang oh i see ;).
