### ISSUE TITLE
http://def-builder.mikepenz.com/ link is broken 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/AboutLibraries#71]
Hi!

Please update the link. I want to include libraries that are not currently supported by default by you. I am not finding a way to do so. 

Thanks.

**Comment by mikepenz** [comment]
@Shajeel-Afzal i can open the site. still not working for you?

**Comment by Shajeel-Afzal** [comment]
Sorry not sure what is wrong but it is not opening for me :(. Thanks.

**Comment by mikepenz** [comment]
@Shajeel-Afzal strange. you can use the source which is in teh github repo too :D it's a simple html site with javascript:

https://github.com/mikepenz/AboutLibraries/tree/master/DEV/definition-file-builder
