### ISSUE TITLE
Allowed license reported as not allowed when merging

### ISSUE THREAD

**Issue by znakeeye** [mikepenz/AboutLibraries#713]
Thanks for a fantastic library!

## About this issue
Using `10.0.0-b08`. I want to set strict mode. However, for `glide 4.12.0` the license is interpreted as "Other", producing an error. So I thought about merging the correct license information. That, however, gives a similar error for `BSD-2-Clause` - which is indeed **allowed**! What am I doing wrong?

## build.gradle

```gradle
dependencies {
    implementation 'com.github.bumptech.glide:glide:4.12.0'
}

aboutLibraries {
    configPath = 'config'
    offlineMode = false
    fetchRemoteLicense = true
    strictMode = com.mikepenz.aboutlibraries.plugin.StrictMode.FAIL
    allowedLicenses = [ 'asdkl', 'Apache-2.0', 'MIT', 'BSD-2-Clause' ]
    duplicationMode = com.mikepenz.aboutlibraries.plugin.DuplicateMode.LINK
}
```

## config/libraries/lib_merge_disklrucache.json
```json
{
  "uniqueId": "com.github.bumptech.glide:disklrucache",
  "licenses": [
    "Apache-2.0"
  ]
}
```

## config/libraries/lib_merge_gifdecoder.json
```json
{
  "uniqueId": "com.github.bumptech.glide:gifdecoder",
  "licenses": [
    "MIT"
  ]
}
```

## THE ERROR
```
Detected usage of not allowed licenses!
-> License: Simplified BSD License (http://www.opensource.org/licenses/bsd-license), used by:
    com.github.bumptech.glide:glide
    com.github.bumptech.glide:gifdecoder
    com.github.bumptech.glide:disklrucache
    com.github.bumptech.glide:annotations
```

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by znakeeye** [comment]
It seems these URLs point to the same page:
```
https://opensource.org/licenses/BSD-2-Clause
https://opensource.org/licenses/bsd-license
```

Could that cause some confusion for the library?

**Comment by znakeeye** [comment]
Adding `'Simplified BSD License'` to `allowedLicenses` did the trick.

Still a bit confused though. Shouldn't the `spdxId` be used?

**Comment by mikepenz** [comment]
Just checked the details of the glide library. they define `Simplified BSD License` as their license:
```
  <licenses>
    <license>
      <name>Simplified BSD License</name>
      <url>http://www.opensource.org/licenses/bsd-license</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
```

The plugin looks to match for `spdxId`s which would be `BSD-2-Clause`. 

So it fails to cross reference the correct license. 
There's already special handling in case to check for the url you highlighted above, but not for the other variant:

https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt#L388-L390

Will look to add the additional url for proper detection

**Comment by znakeeye** [comment]
Actually, this issue keeps popping up. I ended up not using any customized `json` files for `glide`, since it started working when I added "Simplified BSD License" to `allowedLicenses`. But now it's back.

1. Clean project
2. Rebuild (release)

I believe you should see this issue if you simply include glide in your app.

**Comment by mikepenz** [comment]
@znakeeye one of the tricky parts is that you have 

`fetchRemoteLicense` enabled, as such it pulls the license from GitHub https://raw.githubusercontent.com/bumptech/glide/master/LICENSE which can't be associated automatically to SPDX licenses. 

The reason why you see inconsistent behavior with the fetching of remote license is, that it looks you are not providing a token: `gitHubApiToken = getLocalOrGlobalProperty("github.pat")` as such your build will run out of API quota to github and can't check the existence of LICENSE files anymore. 

You can directly see if you exceeded the rate_limit if you can't load: https://api.github.com/repos/bumptech/glide/license


I'll need to check, currently licenses retrieved from GITHUB have the highest priority and will be taken even if you try to overwrite it custom. as the GitHub defined LICENSE is attached to the source. 

----

Will add better discovery for the BSD based on the secondary url.

**Comment by mikepenz** [comment]
A partial "insecure" workaround could be to allow `noassertion` which is the SDPXId returned by the GitHub license API for this repo

**Comment by mikepenz** [comment]
As you can see glide has the 2 resolved from the POM, and the `other` as returned from GitHub. 

<img width="939" alt="Screenshot 2022-01-28 at 19 26 45" src="https://user-images.githubusercontent.com/1476232/151601549-2dd6e951-62d5-474d-9c07-08b675d64c31.png">

**Comment by mikepenz** [comment]
I think I have an acceptable solution for such cases. Allow to provide the `url` for such special cases via the allowed licenses, as such it's an agreement that the allowance is a well understood decision.

```
allowedLicenses = [ 'asdkl', 'Apache-2.0', 'MIT', 'BSD-2-Clause', 'https://raw.githubusercontent.com/bumptech/glide/master/LICENSE' ]
```
