### ISSUE TITLE
Using wildcards in hash

### ISSUE THREAD

**Issue by znakeeye** [mikepenz/AboutLibraries#714]
## About this issue
I want to strip the generated `aboutlibraries.json` before it lands in the `res/raw` folder of the APK. I don't want to bloat the APK with descriptions etc from hundreds of `androidx` libraries. So the apparent solution is to create a `lib_merge_androidx_XYZ.json` for all libraries... which will take the whole week.

The docs state that if `uniqueId` **overlaps** a merge will occur. So I thought I could accomplish the above using this:

## libraries/lib_androidx.json
```json
{
  "uniqueId": "androidx",
  "developers": [],
  "description": null,
  "scm": null,
  "name": null,
  "website": null
}
```

But it has no effect. Ideas? Can you accomplish this type of stripping somehow?

## Details
- [10.0.0-b08] Used library version

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@znakeeye that's an interesting point. 

Right now it will only merge for exact matches, and add if no overlap occurs. I like the idea though of potentially allowing a more flexible merge strategy for usecases like this or for example the need to add a website for a set of libs. 

But beyond that, I will think of an API to possibly strip fields you won't display generally from the generated information. 

A "quick" solution for the current version could be (especially if your libraries are not meant to change super frequent anymore) to generate the `aboutlibraries.json` once, modifying it to your needs, and keeping as static pre-generated file.

**Comment by znakeeye** [comment]
> @znakeeye that's an interesting point.
> 
> Right now it will only merge for exact matches, and add if no overlap occurs. I like the idea though of potentially allowing a more flexible merge strategy for usecases like this or for example the need to add a website for a set of libs.
> 
> But beyond that, I will think of an API to possibly strip fields you won't display generally from the generated information.
> 
That would be awesome! E.g. `excludedAttributes = [ 'description' ]`

> A "quick" solution for the current version could be (especially if your libraries are not meant to change super frequent anymore) to generate the `aboutlibraries.json` once, modifying it to your needs, and keeping as static pre-generated file.
Good idea. Would it be possible to somehow intercept the "write final json" task using `gradle` magic?

**Comment by znakeeye** [comment]
Also, it would be nice to add be able to add *extra* attributes. Like a classification. That way, you could for instance have different colors for `library`, `font`, `graphics` etc. Dependencies from `pom.xml` should have `type: "library"` and then, for custom dependencies, you could specify another type.

**Comment by mikepenz** [comment]
Theoretically the following would be doable:

Disable the android task registration for the plugin: 
```
registerAndroidTasks = false
```

After that you could register a custom task which will call the export task (below is just the direct cli code for reference):

```
./gradlew app:exportLibraryDefinitions -PexportPath=src/main/resources/ -PexportVariant=release
```

That custom task would run the exporting as `dependsOn` for example, and then you modify the resulting file. 

You could also just do it manually, if things don't change too often. export the file, use regex or such to strip information. and commit the `aboutlibraries.json` as part of your CLI. 


Could you please open a new ticket for the suggestion of a classification?

**Comment by mikepenz** [comment]
@znakeeye there will be a wildcard feature, could you regardless please open a ticket with the proposal on stripping specific fields from the information?
