### ISSUE TITLE
Add classification (MIME?) for different types of dependencies

### ISSUE THREAD

**Issue by znakeeye** [mikepenz/AboutLibraries#715]
It would be nice to have a classification for each "library".

## Motivation
* **For a custom UI** you might want to customize the look'n'feel of licensed items. E.g. a `library` could have a different color than a `font`.
* **During an audit** it could be helpful to search for specific types of licenses. If you are interested in the license of a PNG image, you would simply look for `mime: "image/png"`.
* **Pivoting.** With a classification, you could perform pivoting in Excel etc.

## Classification using MIME?
`class` or `type` or whatever. Perhaps we should consider [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) to get somewhat standardized syntax. E.g.:

* Dependencies from `pom.xml` would have `mime: "application/java-archive"`
* NDK/native library would have `mime: "application/octet-stream"`
* Fonts would have `mime: "font/ttf"`
* A PNG image would have `mime: "image/png"`
* etc

If you settle for _MIME_, the classification could be automated if you - for custom libraries - require a `uniqueId` ending with a MIME-specific extension. E.g.:

```
{
   "uniqueId": "my_font.ttf",
}
```

**Comment by mikepenz** [comment]
Thank you @znakeeye for the proposal. after further thoughts on this, I believe `mimeType` will be miss leading. But I'll add a generic `tag` which can be used for anything like this. 

This will fit not only this usecase but any other usecase people may come up with.

**Comment by znakeeye** [comment]
I agree. Will the tag be `null` for libraries then?

**Comment by mikepenz** [comment]
Correct.
