### ISSUE TITLE
Library not excluded from the list after i removed the .jar file

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/AboutLibraries#72]
Hi!

I first ran the app and came to know that Picasso.jar was auto detected in the list which is nice, but after that i deleted it from the the libs folder and also updated the build path because i was no longer using it in the project. 

But even after that i can see Picasso listed in the libraries. I think the on first run of the app it generates necessary files to indicate libraries used but it does not update on each run. 

I am using the library as: 

		LibsFragment fragment = new Libs.Builder()
				.withFields(R.string.class.getFields())
				// .withLibraries("showcaseview")
				.withVersionShown(true)
				.withAutoDetect(true)
				.withLicenseShown(true)
				.withLibraryModification("aboutlibraries",
						Libs.LibraryFields.LIBRARY_NAME, "_AboutLibraries")
				.fragment();

		FragmentManager fragmentManager = getSupportFragmentManager();
		fragmentManager.beginTransaction()
				.replace(R.id.frame_container, fragment).commit();

Thanks.

**Comment by mikepenz** [comment]
@Shajeel-Afzal no it does not generate any files. the libraries are detected by their definition files, or if the lib can detect a class which is in the classpath. i assume there is still any reference to the picasso lib. perhaps a library is using picasso as dependency?

**Comment by Shajeel-Afzal** [comment]
@mikepenz i will check. But can you please tell me how can i add new libraries? I am assuming that the solution is avaialbe on http://def-builder.mikepenz.com/ but since it is not opening atleast in my country, can you please give the solution here?

**Comment by mikepenz** [comment]
@Shajeel-Afzal the def-builder is just a helper creating definition files. you can then do a pull-request here.

**Comment by mikepenz** [comment]
@Shajeel-Afzal the wiki has some more information about this topic
