### ISSUE TITLE
Why does aboutlibraries-core require minSdkVersion 21?

### ISSUE THREAD

**Issue by znakeeye** [mikepenz/AboutLibraries#721]
Why does `aboutlibraries-core` require `minSdkVersion 21`? Any new fancy APIs needed? I'm still stuck on 19 (just like most Google libraries out there), so I cannot use the library :(

```
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.mikepenz:aboutlibraries-core-android-debug:10.0.0-b08] C:\foo\.gradle\caches\transforms-3\8875de10245fc7b512e35cfea83ae738\transformed\aboutlibraries-core-debug\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.mikepenz.aboutlibraries.core" to force usage (may lead to runtime failures)
```

**Comment by mikepenz** [comment]
@znakeeye I'll have a look, possibly the min sdk version for `core` can be lower. 
During the beta, it was mainly due to simplicity, as the ui modules match the same min requirement.
Due to compose being 21+ though the UI modules won't get a lower API version.

**Comment by znakeeye** [comment]
Perfect. Could you please create a new release soon. This is stopping me from integrating with the lib 🙁
