### ISSUE TITLE
Trim license before duplicate check

### ISSUE THREAD

**Issue by znakeeye** [mikepenz/AboutLibraries#725]
I noticed that Apache 2.0 license sometimes begins with a newline character, sometimes not. This implies two 99.999% equal licenses in the output.

I believe you could trim whitespaces when performing the check for duplicates.

**Comment by znakeeye** [comment]
This ought to be a new Github PR record. Three hours from issue report to PR merged 👍

**Comment by mikepenz** [comment]
@znakeeye :D I think I did achieve 15 minutes once, but for a different library. 

Triggered a release build. It will take around 1-2 hours until all things are synced with maven central after the build succeeded.

**Comment by znakeeye** [comment]
It looks to be ready now (?), but I keep getting an error when building.

**build.gradle**
```gradle
implementation 'com.mikepenz:aboutlibraries-core:10.0.0-b09'
```

**Error:**
```
Unable to resolve dependency for ':app@debug/compileClasspath':
Could not resolve com.mikepenz:aboutlibraries-core:10.0.0-b09.
```

What am I missing?

**Comment by mikepenz** [comment]
@znakeeye still not available? 

Should be up on maven central: https://search.maven.org/artifact/com.mikepenz/aboutlibraries-core/10.0.0-b09/

**Comment by znakeeye** [comment]
Will retry in an hour. Will it work in a Java project?

**Comment by mikepenz** [comment]
The core module is a plain jar with a different variant for Android with different apis specific for Android

**Comment by znakeeye** [comment]
> The core module is a plain jar with a different variant for Android with different apis specific for Android

I keep getting that error. Are you able to get it working?  For the core lib, `mavenCentral()` should be enough, right?

**Comment by mikepenz** [comment]
<img width="405" alt="Screenshot 2022-01-30 at 09 19 53" src="https://user-images.githubusercontent.com/1476232/151692200-e126cb45-81df-47b0-9b3d-d96d3e2011d4.png">

10.0.0-b09 loads just fine for me in an Android Application I have. 

Tried it in a desktop app with the same `implementation` clause as you which worked fine too: 
https://github.com/mikepenz/storyblok-mp-SDK-blog/commit/3719ac93c04759ee5b5e4fab4255f82b9dedd6fe

**Comment by znakeeye** [comment]
I don't get it. Could it be that the core library cannot be consumed by a `Java` project? I keep getting this warning:

![image](https://user-images.githubusercontent.com/958469/151699169-33ca364b-98a0-4ad7-ae8c-cda10d1c98e7.png)

Tried cleaning the cache and restarted the computer etc. Same error. And if I ignore it, the auto-completion will indeed make me aware of the missing library:

![image](https://user-images.githubusercontent.com/958469/151699132-a5d60aeb-ea3e-4c97-9af6-c2e7cb7b1b30.png)

I read somewhere, that there are ways to make (intentionally or unintentionally) a kotlin library non-consumable by a java app. I realize I should migrate to kotlin, but I cannot do that at this point :/

**Comment by mikepenz** [comment]
Could you possibly create a sample app so I can reproduce it?

The core library should be found in java. Some Apis may not be fully
useable but the issue seems that your build already doesn't find the jar
which is strange.

**Comment by znakeeye** [comment]
Just create a new project in Android Studio, choose `Basic Activity`. Add `implementation 'com.mikepenz:aboutlibraries-core:10.0.0-b09'` and sync/compile. Same warning.

**Comment by mikepenz** [comment]
Are you really certain the maven central repository is available?

**Comment by znakeeye** [comment]
How can I check that? Never encountered a similar problem.

**Comment by znakeeye** [comment]
So insanely frustrating... 😛 Are you able to get a simple sample project working with the core lib reference? With Bumblebee? Please show me 😛

**Comment by mikepenz** [comment]
@znakeeye no idea. looks like this is behaviour of kotlin multiplatform.  Have not found real answers to a solution, or to this being the case. 

Seems this is something out of my control, and you'll have to apply the kotlin plugin. 

Tried it with a plain java project as you noted.
