### ISSUE TITLE
Library seems to be incompatible with Android Studio 1.2

### ISSUE THREAD

**Issue by jkane001** [mikepenz/AboutLibraries#73]
I cannot add AboutLibraries to my project in AS 1.2 - it syncs Gradle fine, but fails to build the project with the error "Error:Execution failed for task ':bluetoothdetection:dexTrialDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 2"

I've reproduced this 2 different times this week - all is well until I add compile('com.mikepenz.aboutlibraries:library:4.5.9@aar') { transitive = true }, and then it breaks again. Removing that dependency resolves the problem.

(I am using API 22 & v22 of all the required support libraries, so that might be the root cause as well.)

**Comment by jkane001** [comment]
This turns out to be a problem with my app - too many methods (http://developer.android.com/tools/building/multidex.html).

I've taken care of that, and now I can add AboutLibraries successfully.

**Comment by mikepenz** [comment]
@jkane001 thanks ;)
