### ISSUE TITLE
Changing applicationID is not compatible with the plugin

### ISSUE THREAD

**Issue by kliment-jonceski** [mikepenz/AboutLibraries#732]
## About this issue

- We're facing an issue when for our production app we have a different flavor (prod), where we overwrite the application id. Our package name structure is for example (com.main.app), but for production our applicationId is com.prod.app, where the plugin tries to get the class com.prod.app.R$string which is not existing at all. Can you make this somehow configurable?
- How can the issue be reproduced / sample code
define another flavor of the app, and completely overwrite the applocationID.

## Details
- [ ] Used library version: 8.9.1
- [ ] Used support library version
- [ ] Used gradle build tools version: 7.0.3
- [ ] Used tooling / Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 1
Runtime version: 11.0.10+0-b96-7281165 x86_64
macOS 11.2.3
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Hello @kliment-jonceski 

In case you need to provide the fields instead you can use the `withFields` API for the builder, which is showcased here: https://github.com/mikepenz/AboutLibraries/tree/v8.9.4#fragment

With this you can directly provide the fields instead of the library relying on reflection.

**Comment by kliment-jonceski** [comment]
Thanks @mikepenz, It seems that we missed that one.

**Comment by mikepenz** [comment]
No worries. 

V10 is meant to significantly simplify the complexity around these apis.

And it hit rc01. So maybe it's time 😃
