### ISSUE TITLE
Missing AboutLibraries dependency in collected dependencies

### ISSUE THREAD

**Issue by ILikeYourHat** [mikepenz/AboutLibraries#739]
## About this issue

Just like in the title, for some reason AboutLibraries is not listed as dependency in the licenses output. This happens in my free-time project, a lot is going on here, so not sure what part caused this error:
https://github.com/ILikeYourHat/Large-Scale-Android-App

AboutLibraries configuration is located in 'gradle/extension/libs/about_libraries.gradle'. Also note dependencies are generated from ':app' module, but consumed in ':settings' module.

## Details
- :white_check_mark: Used library version - 10.0.0
- :white_check_mark: Used gradle build tools version - 7.1.2
- :white_check_mark: Used tooling / Android Studio version - AS Bumblebee Path 2
- :white_check_mark: Other used libraries, potential conflicting libraries - many 🙂 

## Checklist

- :white_check_mark: Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- :white_check_mark: Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- :white_check_mark: Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- :white_check_mark: Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@ILikeYourHat would be surprised it being the typesafe project accessors, using it personally in a few projects. 
Do you see any other missing dependencies beside the aboutLibraries one itself? 

Do you check-in the generated `*.json` file as part of your SCM? Or do you maybe have it available?

**Comment by ILikeYourHat** [comment]
@mikepenz Nope, AboutLibraries is the only one missing. Valid `*.json` file with all the other dependencies is generated in the `build` folder, only your library is missing.

I've added a direct dependency for `com.mikepenz:aboutlibraries-core` in `:app` module, but still it's missing

**Comment by mikepenz** [comment]
Could you possibly attach the generated file to this ticket? 

Any helpful output in the gradle log when running `./gradlew findLibraries` ? 

(v10 allows the generated file to be included in the SCM for more enterprise level scenarios where re-generation may not be expected)

**Comment by ILikeYourHat** [comment]
[aboutLibraries.zip](https://github.com/mikepenz/AboutLibraries/files/8272080/aboutLibraries.zip)
[findLibraries.txt](https://github.com/mikepenz/AboutLibraries/files/8272087/findLibraries.txt)

First is the content of "aboutLibraries" directory in build file, the second is the result of `findLibraries` task

**Comment by ILikeYourHat** [comment]
Breaking discovery! If I declare dependency like this:
`implementation libs.aboutLibraries.core`
AboutLibraries is not listed as dependency. BUT if I declare it like this:
`debugImplementation libs.aboutLibraries.core`
then everything is working as expected 😄

**Comment by mikepenz** [comment]
Just checked it with the repo and run `./gradlew findLibraries` 
And it will include the aboutLibraries. Could you plese do clean builds and see if it may be caching?

**Comment by ILikeYourHat** [comment]
Confirmed, this is a caching issue. Licenses are correctly generated only if `gradlew clean` and `gradle findLibraries --no-build-cache` were invoked

**Comment by ILikeYourHat** [comment]
Weird: when invoking `gradlew assembleDebug` dependencies are not refreshed. But when invoking `gradlew assembleDebug --scan` (for gradle build scan), dependencies are refreshed correctly. I think that this might be some sort of race condition. You can check the scan, maybe you find something interesting here: https://scans.gradle.com/s/k7vf4wuablwjo

**Comment by mikepenz** [comment]
The steps in this build were all cached: https://scans.gradle.com/s/k7vf4wuablwjo/console-log#L29,  https://scans.gradle.com/s/k7vf4wuablwjo/console-log#L41

So for some reason: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt#L41-L75 would not yet retrieve the proper full dependency tree the first time :/

**Comment by ILikeYourHat** [comment]
Any update on this? If those tasks were cached and shouldn't be, that probably means some task inputs were declared incorectly

**Comment by mikepenz** [comment]
No update. The tricky part is that I wasn't yet able to reproduce it int he project itself. making it very difficult to debug further.

**Comment by mikepenz** [comment]
Can't seem to find hints on how to best ensure the task is re-run for this situation. 

Would appreciate any input of somebody has pointers or suggestions. 


I would have an idea how this could be made working for android projects but that wouldn't work for non android environments.

**Comment by mikepenz** [comment]
@ILikeYourHat is this problem still happening? (Maybe with newer versions of this plugin / newer version of Gradle)?

**Comment by ILikeYourHat** [comment]
@mikepenz Confirmed, it's still happening. AboutLibraries v10.3.1, Gradle v7.5.

Gradle 7.5 has support for "Dependency resolution results can be used as task inputs", maybe implementing it will solve this issue?

**Comment by mikepenz** [comment]
@ILikeYourHat I looked into Gradle 7.5 but sadly using that new API (based on their demo code) seems to give me quite some problems with Kotlin Multiplatform code.

**Comment by je-ramos-acc** [comment]
Hi @mikepenz @ILikeYourHat! have you found any solution? 
I'm encountering the same issue on gradle 7.5, kotlin 1.7.20 using Android Electric Eel. 
`aboutlibrariesVersion = '10.5.2'`

**Comment by je-ramos-acc** [comment]
I could confirm that this is a caching issue.

My issue was fixed by
1. Delete `~/.gradle/caches/build-cache-1`
2. Invalidate and restart cache in android studio
3. Run `./gradlew clean`
4. Run `./gradlew findLibraries --no-build-cache`
5. App should now build properlyy
