### ISSUE TITLE
Brotli dependency Name not displayed correctly in license tab.

### ISSUE THREAD

**Issue by Fox2Code** [mikepenz/AboutLibraries#741]
## About this issue

- Redirect from issue: https://github.com/Fox2Code/FoxMagiskModuleManager/issues/100
- Source code: https://github.com/Fox2Code/FoxMagiskModuleManager

Name is `${project.groupId}:${project.artifactId}` instead of `Brotli`

Helper link: https://mvnrepository.com/artifact/org.brotli/dec/0.1.2

## Details

- [X] Used library version: 10.0.0
- [X] Used gradle build tools version: 7.1.2
- [X] Used tooling / Android Studio version: Gradle 7.2
- [X] Other used libraries, potential conflicting libraries: n/a

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report @Fox2Code 

The library actually displays the correct information according to the `*.pom` file: https://repo1.maven.org/maven2/org/brotli/dec/0.1.2/dec-0.1.2.pom

this is an issue of `brotli` itself.

You can use the respective APIs to patch wrong information: https://github.com/mikepenz/AboutLibraries#modify-libraries--licenses

**Comment by Fox2Code** [comment]
Is it possible to have a kind of built-in fallbacks when library name is not valid or non existent?

**Comment by mikepenz** [comment]
I don't believe this can be done in a generic fashion so it works properly. 
How would the action know if a library name is not valid? 
If no value is defined various fallbacks exist though. In the case of brotli though, a name is existing in the `*.pom` 

For situations like this, it is best to reach out to the maintainer of the respective library and have them fix the `*.pom` generation.
As their `*.pom` contains this: `<name>${project.groupId}:${project.artifactId}</name>`

**Comment by Fox2Code** [comment]
Well making app ignoring `*.pom` name if it is equal to `${project.groupId}:${project.artifactId}` should be fine.

I don't think any fallback is be worse than that.
