### ISSUE TITLE
Fragment has a background

### ISSUE THREAD

**Issue by theenderer** [mikepenz/AboutLibraries#75]
The fragment returned by AboutLibraries has a set background. Is it not a better idea not to set a background? This reduces overdraw and fits in with the current theme of the user's app.

This relates to:
https://github.com/mikepenz/AboutLibraries/blob/master/library/src/main/res/layout/fragment_opensource.xml

**Comment by mikepenz** [comment]
@theenderer yea thos would probably be a good idea. thanks
