### ISSUE TITLE
Add additional libraries - where to put json files

### ISSUE THREAD

**Issue by ebc81** [mikepenz/AboutLibraries#758]
## Add additional libraries - where to put json files

- This is a maybe a beginner question. Put where to put the config directory for the custom json files in the file explorer hierarchy of an android project ? 

## Details
- [10.2.0 ] Used library version

## Checklist

- [ X] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
You can configure the path in your gradle file via the `aboutLibraries` block: https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L91

The path is relative to the root of your project. 

So given the above configuration, the folder is discovered here: https://github.com/mikepenz/AboutLibraries/tree/develop/config

**Comment by ebc81** [comment]
Sorry but i didn't get it.
I made a clean fresh sample project.
I added the config folder with the json files. But still it is not shown in the about dialog activity.

[https://github.com/ebc81/TestAboutLibaries](https://github.com/ebc81/TestAboutLibaries)

**Comment by mikepenz** [comment]
Given your sample, it looks there is no `aboutLibraries` configuration defining the path it's meant to look for these files:

https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L83-L115

**Comment by ebc81** [comment]
Thanks for your patience.
But when i add the aboutlibaries section in the app build gradle i get compile errors

[https://github.com/ebc81/TestAboutLibaries/blob/master/app/build.gradle](https://github.com/ebc81/TestAboutLibaries/blob/master/app/build.gradle)

> Build file 'C:\Users\atlnz003\Dropbox\ebcTech\2021\MyApplication\app\build.gradle' line: 39

>A problem occurred evaluating project ':app'.
> No signature of method: build_exmmyml1r71kq72qbvsxf1m3d.aboutLibraries() is applicable for argument types: >(build_exmmyml1r71kq72qbvsxf1m3d$_run_closure2) values: [build_exmmyml1r71kq72qbvsxf1m3d$_run_closure2@a7cb770]

>* Try:
> Run with --stacktrace option to get the stack trace.
>Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by mikepenz** [comment]
Could it be the different way how the plugin is applied to the root `build.gradle`? 
https://github.com/mikepenz/AboutLibraries/blob/develop/build.gradle#L20

**Comment by ebc81** [comment]
Thank you very much. Now it is working.
I just leave the config argument.
