### ISSUE TITLE
Library details empty alert dialog

### ISSUE THREAD

**Issue by ahuja-kalido** [mikepenz/AboutLibraries#759]
## About this issue

- Opening empty Dialog box.
```
LibrariesContainer(
Modifier.fillMaxSize() 
)
```

https://user-images.githubusercontent.com/102297676/169959735-55ed318e-234f-4383-b01b-250eb7eebae0.mov

## Details
- [x] Used library version - **ext.latestAboutLibsRelease = "10.2.0"**
- [x] Used gradle build tools version - **30.0.2**
- [x] Used tooling / Android Studio version - **Android Studio Bumblebee | 2021.1.1 Patch 3**

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@ahuja-kalido which library is this information from? Looks like their `.pom` file is already not complete.

If you can possibly share the generated json file of libraries from the plugin?

**Comment by ahuja-kalido** [comment]
here is the generated json.
[aboutlibraries.json.zip](https://github.com/mikepenz/AboutLibraries/files/8760014/aboutlibraries.json.zip)

**Comment by mikepenz** [comment]
Thank you. this will be enhanced in a future release: https://github.com/mikepenz/AboutLibraries/pull/760
