### ISSUE TITLE
Libraries lost with minifyEnabled true

### ISSUE THREAD

**Issue by theenderer** [mikepenz/AboutLibraries#78]
I enable obfuscation in my app to reduce the size.
I guess the strings are accessed via reflection and thus removed by proguard because they seem unused.

Does anyone else experience this problem?

Any easy -keep statements to keep this library working with obfuscation?

**Comment by mikepenz** [comment]
@theenderer what happens? it will stop to auto-detect. This is because the classpaths of the libs are changing. so i can't autodetect. You should still be able to just manually set the used libraries in the builder. 

`.withLibraries("activeandroid", "caldroid")` should do the trick

**Comment by theenderer** [comment]
Thanks, will give it a try.

**Comment by mikepenz** [comment]
@theenderer any luck?

**Comment by theenderer** [comment]
Stating it manually works well thanks. Was hoping there was some kind of
Proguard rule to keep the information for automatic detection.

**Comment by mikepenz** [comment]
@theenderer you will have to exclude each single lib so proguard would not change their package names. but i think this is unnecessary.

**Comment by theenderer** [comment]
Yea would not be worth it. Thanks for the responses, and the awesome
library.
