### ISSUE TITLE
SearchView text doesn't honor primary app theme text color for Theme.MaterialComponents.Light.NoActionBar

### ISSUE THREAD

**Issue by wseemannroku** [mikepenz/AboutLibraries#789]
## About this issue

If my app theme is set to `Theme.MaterialComponents.Light.NoActionBar` and I start the licenses activity with:

```
 LibsBuilder()
     .withSearchEnabled(true)
     .start(this)
```

The text in the search view in the action bar is always white which makes the text unreadable.

I've attached a screenshot and a sample app to reproduce the issue.

## Details
- [x] Used library version - v10.4.0
- [x] Used support library version - N/A
- [x] Used gradle build tools version - 7.2.0
- [x] Used tooling / Android Studio version - Chipmunk (2021.2.1 Patch 1)
- [x] Other used libraries, potential conflicting libraries - N/A

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

![Screenshot_20220819-054730](https://user-images.githubusercontent.com/103459183/185603119-913d0ba8-86bc-4763-8ae4-4c9ee9a9f8ca.png)
[MyApplication.zip](https://github.com/mikepenz/AboutLibraries/files/9381545/MyApplication.zip)

**Comment by mikepenz** [comment]
Thank you for the report @wseemannroku 

This comes from: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.kt#L72-L75 

Will look to have it use theme attributes instead.

**Comment by mikepenz** [comment]
Out of curiosity - What's the main decision factor to go with the view based UI instead of the compose variant? (No worries if that's not something you can speak about) 

Mainly looking to see what people look for in the provided UI and what may be missing in the compose variant.

**Comment by wseemannroku** [comment]
I don't mind sharing, we are actively exploring compose and integrating it into our codebase. It's just not something that everyone is familiar with or full adopted yet so we're sticking with the legacy module for the time being. Your compose version is well written, were just haven't fully adopted compose yet.

**Comment by mikepenz** [comment]
Thanks for sharing. 

I am looking into the color right now, and I remember why it is this way. For whatever wonderful reason the `SearchView` will happily ignore anything applied via the `style`. Theoretically it should work by applying a `theme` to the toolbar, but that would need to be done specifically and wouldn't go via the `toolbarStyle`. 

I believe as a hopefully acceptable middle ground to set the `colorControlNormal` color to the text (which should be equal to the search icon. Which hopefully solves most cases. 

Alternative the used layout from the `AboutLibraries` could be overwritten in the target app and a direct theme set to change that color.

**Comment by mikepenz** [comment]
Gonna release it as v10.4.1-a01 to give you a chance to test this approach
(Used the theme you outlined in the sample and it looked to work)

(will probably take ~30-60 mins to be synced to maven central)
