### ISSUE TITLE
Is it possible to ignore certain libs?

### ISSUE THREAD

**Issue by tarun-roku** [mikepenz/AboutLibraries#794]
## About this issue
I was wondering if there is support to ignore certain libraries? for example I want to ignore Android/Google fw libs
- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Good day. 

Yes there is a Gradle configuration option offering to exclude certain libraries via regex:

https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt#L64-L75

```
aboutLibraries {
     exclusionPatterns = [
         ~"com\.company\..*"
     ]
}
```


(the README is not explicit about that one as I usually advice against skipping the attribution of libraries)

**Comment by tarun-roku** [comment]
thanks, @mikepenz this is helpful.
