### ISSUE TITLE
How to add custom dependency in ui-compose?

### ISSUE THREAD

**Issue by Berki2021** [mikepenz/AboutLibraries#798]
## About this issue

- I would like to add a custom .aar dependency for compose. I knew how to do this with the legacy version, but I can't find any info on how to achieve this with the compose-ui
- See [this](https://github.com/mikepenz/AboutLibraries/issues/678)

## Details
- [10.4 ] Used library version
- [ ] Used support library version
- [X ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [X ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [X ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [X ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ X] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [X ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@Berki2021 if you want to add additional libraries/licenses, this is now fully handled via the plugin -> and as such via json files. 

So in the sample app this is for example adding a single library: https://github.com/mikepenz/AboutLibraries/blob/develop/config/libraries/lib_first.json

This is described here: https://github.com/mikepenz/AboutLibraries#libraries
Within the expandable `Gradle Plugin Configuration` section

**Comment by Berki2021** [comment]
What exactly do I write in the "configPath" and in which folder should I store my json file? Could you give an example?

**Comment by mikepenz** [comment]
This is described here: 
https://github.com/mikepenz/AboutLibraries#gradle-plugin-configuration

```
    // Define the path configuration files are located in. E.g. additional libraries, licenses to add to the target .json
    configPath = "config"
```

These files are for the plugin, as such not related to the android sources themself. for example the sample app: 

https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L90-L91

Which means it picks up files within the `config` folder here:

https://github.com/mikepenz/AboutLibraries/tree/develop/config/

for example libraries: 
https://github.com/mikepenz/AboutLibraries/tree/develop/config/libraries

**Comment by Berki2021** [comment]
Sorry to bother you again... But I don't get it... I just don't know where to exactly put this "Config" folder? Inside the resource folder? Inside the src folder? Here is my folder structure

![grafik](https://user-images.githubusercontent.com/65120636/194858566-98d69978-e063-4352-853d-abf3f7e61250.png)

**Comment by mikepenz** [comment]
Please see again the answer above your message: https://github.com/mikepenz/AboutLibraries/issues/798#issuecomment-1257543896 with the example of this repo. 

The repository shows where the `config` folder is located if "config" was specified as it's path: https://github.com/mikepenz/AboutLibraries/blob/develop/app/build.gradle#L90-L91

E.g. the root of the project: https://github.com/mikepenz/AboutLibraries/tree/develop/config/


Alternative example:

`configPath = "custom/path/"`

This would mean that the files would be in the `custom/path/` folder (starting from the root of the project)
