### ISSUE TITLE
Failed to apply plugin - Compose desktop project

### ISSUE THREAD

**Issue by Cailocan** [mikepenz/AboutLibraries#799]
## About this issue

Hello,

I would like to use AboutLibraries in a Desktop Compose only project. Here is what I got when I add the plugin:

```gradle
An exception occurred applying plugin request [id: 'com.mikepenz.aboutlibraries.plugin', version: '10.4.0']
> Failed to apply plugin 'com.mikepenz.aboutlibraries.plugin'.
   > Could not create plugin of type 'AboutLibrariesPlugin'.
      > Could not generate a decorated class for type AboutLibrariesPlugin.
         > com/android/build/gradle/api/BaseVariant

Unable to load class 'com.android.build.gradle.api.BaseVariant'.
```

Here are some implementation details:

```gradle
plugins {
    kotlin("jvm") version "1.6.10"
    id("org.jetbrains.compose") version "1.1.0"
    ...
    id("com.mikepenz.aboutlibraries.plugin") version "10.4.0"
}

...


dependencies {
    testImplementation(kotlin("test"))
    implementation(compose.desktop.currentOs)

   ...

    implementation("com.mikepenz:aboutlibraries-core:10.4.0")
    implementation("com.mikepenz:aboutlibraries-compose:10.4.0")
}
```

It seem that the gradle plugin contains by default Android platform files. Is it possible to exclude them? Or am I doing something wrong?

## Details
- [10.4.0] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please see the sample compose desktop app below:

https://github.com/mikepenz/AboutLibraries/blob/develop/app-desktop/build.gradle.kts#L36

You'll need to disable the registration of the Android task which occurs automatically by default.

**Comment by Cailocan** [comment]
I did see the sample desktop app and the `registerAndroidTasks` parameter but adding it to the build.gradle.kts file doesn't change anything. Intellij Idea keeps throwing the same error and doesn't recognize `aboutLibraries` parameters block. 

Is Gradle able to apply a plugin and read its parameters at the same time?

**Comment by mikepenz** [comment]
I'll need to have a closer look then. Possibly it behaves different if applied the way you showed versus the classpath. 

Is this project open source or do you have a sample project to reproduce?

Thank you. I'll probably have some time to check it out next week

**Comment by Cailocan** [comment]
My project isn't open source yet, but you can reproduce it by using the default Intellij Compose desktop template project and using kotlin jvm plugin instead of multi-platform.

**Comment by mikepenz** [comment]
Thank you again for the report. The next version will solve this problem

**Comment by Cailocan** [comment]
A big thank for you work!
