### ISSUE TITLE
Button "CHANGELOG" in sample app without "G"

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/AboutLibraries#80]
I use a Nexus5 and the button "CHANGELOG" only shows "CHANGELO" :-(

**Comment by mikepenz** [comment]
@Rainer-Lang because the text is to long :/ and it will show 2 lines. no idea how to change this

**Comment by Rainer-Lang** [comment]
You have free space to the border at the left and the right. Maybe make the buttons wider.
The cards below are using more width.

**Comment by mikepenz** [comment]
@Rainer-Lang the padding is now lowered. It will still cut it off on smaller devices
