### ISSUE TITLE
v10.5.1 not published to Maven Central

### ISSUE THREAD

**Issue by arkon** [mikepenz/AboutLibraries#809]
## About this issue

Renovate opened an automatic PR to bump the dependency, but the artifacts weren't found from Maven Central: https://github.com/tachiyomiorg/tachiyomi/pull/8207

I can verify that 10.5.1 does not appear in https://repo1.maven.org/maven2/com/mikepenz/aboutlibraries-compose/

## Details
- Used library version: 10.5.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Sonatype had some issues yesterday and I couldn't yet publish the artifacts. Hope today works

**Comment by mikepenz** [comment]
Looks things are back to normal. Just did the release via sonatype. Should become available on maven central in the next hour
