### ISSUE TITLE
Feature Request - Please add a pretty print option for the output json.

### ISSUE THREAD

**Issue by apkelly** [mikepenz/AboutLibraries#813]
## About this issue
I'd like a pretty print option for the output json, since each time I generate a new file for inclusion in my source repository, it looks like the whole file is changed (since its just a single line of json). Whereas, if the json was "pretty", I'd be able to tell more easily which library licenses have been added/removed since the last check-in.

## Details
- [ ] Used library version - 10.5.1
- [ ] Used support library version
- [ ] Used gradle build tools version - 7.3.3
- [ ] Used tooling / Android Studio version - Android Studio Flamingo | 2022.2.1 Canary 8
- [ ] Other used libraries, potential conflicting libraries - Jetpack Compose 1.3

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the suggestion. that's a great idea
