### ISSUE TITLE
[Question] Any plan to support/migrate to Material 3?

### ISSUE THREAD

**Issue by leinardi** [mikepenz/AboutLibraries#816]
Any plan to migrate or provide a Material 3 version of the Library?

Currently all the material colors are referring to `androidx.compose.material.MaterialTheme.colors`, while to properly support M3, they should refer to `androidx.compose.material3.MaterialTheme.colorScheme`. Same for `MaterialTheme.typography`.

**Comment by mikepenz** [comment]
@leinardi thank you for the report. 

While I don't have a timeline. You can already use the material3 colors today by passing in the `libraryColors` you want to use: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-compose/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/Libraries.kt#L47

**Comment by leinardi** [comment]
Yep, I know about the `libraryColors` (btw, I just made a PR related to it). I was just curious if the M3 migration was already planned or not :slightly_smiling_face:

**Comment by mikepenz** [comment]
Thank you very much. Really appreciated.

**Comment by mikepenz** [comment]
Explored Material 3 for compose. 

It still is marked as experimental via `compose-jb` at least. 

Will wait for the upgrade until it is no longer experimental. 

Thanks for raising the question

**Comment by mikepenz** [comment]
@leinardi with 10.10.0 there is now a `compose-m3` module

**Comment by leinardi** [comment]
@mikepenz thanks! I just switched to it :+1:
