### ISSUE TITLE
Library definitions cannot be generated due to missing variant

### ISSUE THREAD

**Issue by gelhan** [mikepenz/AboutLibraries#817]
## About this issue

- I have three build types in my project, named "debug", "qtest" and "release".
- I have two product flavors called "standard", "device".
- When I try to build the app with the build variant "standardDebug" or "standardRelease", all libraries from the project are generated and are displayed in the app.
- Only when I try to build the app in the build variant "standardQtest", the libraries are not generated and shown. When I try to run the gradle task "generateLibraryDefinitionsStandardQtest", I get this message:

Task :app:generateLibraryDefinitionsStandardQtest
Variant (standardQtest) was missing from dependencies, this should never happen
Available variants:
-- deviceDebug
-- deviceRelease
-- standardDebug
-- standardRelease

Any ideas how to solve this?

## Details
- [x] Used library version: 10.3.1
- [ ] Used support library version
- [x] Used gradle build tools version: 7.3.3
- [x] Used tooling / Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report. 

Do you have a sample gradle configuration I could use to try to reproduce this locally? Or reproduce as part of the sample app?

**Comment by gelhan** [comment]
Sample gradle config:

`android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "xxx"
        applicationIdSuffix ".yyy"

        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        minSdkVersion 26
        targetSdkVersion 33

        int localVersionCode = 1000
        String systemEnvBuildNumber = System.getenv('BUILD_NUMBER')
        versionCode = systemEnvBuildNumber != null ? Integer.parseInt(systemEnvBuildNumber) + 3000 : localVersionCode

        versionName "1.0.0"
        
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    bundle {
        language {
            enableSplit = false
        }
    }

    buildTypes {
        release {
        }
        qtest {
        }
        debug {
        }
    }

    flavorDimensions += "version"

    productFlavors {
        create("standard") {
            dimension = "version"

            buildConfigField("boolean", "XXX", "false")
        }
        create("device") {
            dimension = "version"
            applicationIdSuffix = ".zzz"
            versionName "2.0.0"

            buildConfigField("boolean", "XXX", "true")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/library_release.kotlin_module']
        }
    }

    viewBinding {
        enabled = true
    }
    dataBinding {
        enabled = true
    }
    lint {
        abortOnError false
        disable 'LockedOrientationActivity'
        ignore 'VectorPath', 'Typos'
        warning 'ContentDescription', 'ConvertToWebp', 'GradleDependency', 'IconDipSize', 'IconDuplicates', 'IconMissingDensityFolder', 'Icons', 'MissingTranslation', 'OldTargetApi', 'Overdraw', 'PluralsCandidate', 'PrivateResource', 'RtlSymmetry', 'TypographyDashes', 'TypographyEllipsis', 'UnusedResources', 'UseCompoundDrawables', 'UselessParent', 'NonConstantResourceId'
        warningsAsErrors true
    }
}

aboutLibraries {
    configPath = "config"
    exclusionPatterns = [~"androidx.*", ~"com.google.android.*", ~"org.jetbrains.*"]
    additionalLicenses = [ "apache_2_0" ]
}`

**Comment by mikepenz** [comment]
Thanks for that. It's due to the name you use for this flavour. 

The plugin marks it as a `test` variant and ignores it as such :/ 
Will fix it as part of the next update.
