### ISSUE TITLE
License for library Apache Commons CSV is empty 

### ISSUE THREAD

**Issue by chrgernoe** [mikepenz/AboutLibraries#827]
## About this issue

For all my used libraries the licenses are included but for library [Apache Commons CSV](https://commons.apache.org/proper/commons-csv/) it is empty. I checked the generated JSON file, too.

## Details

- [x] Used library version: 10.5.2
- [ ] Used support library version
- [x] Used gradle build tools version: 7.3.1
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report. 

With a closer look I identified that this library get's the license from the parent of the parent. Which is currently not checked by the plugin. 

You can see it here:

Library: https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.9.0/commons-csv-1.9.0.pom
Parent: https://repo1.maven.org/maven2/org/apache/commons/commons-parent/55/commons-parent-55.pom
Parent of the Parent: https://repo1.maven.org/maven2/org/apache/apache/29/apache-29.pom <- this one will have the license. 

Will look into this, for the time being you can provide the license mapping manually
