### ISSUE TITLE
Why LICENSES are UNKNOWN?

### ISSUE THREAD

**Issue by Kolyall** [mikepenz/AboutLibraries#832]
Android Project
Version: 
`classpath "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin:10.5.2"`
Run:
`./gradlew exportComplianceLibrariesRelease`
At bottom of the file `export.txt` exist:
```
....
UNKNOWN LICENSES:
Google Maps Platform Terms of Service
-- [com.google.android.libraries.places:places:2.6.0]
Apache-2.0
-- [androidx.work:work-runtime:2.8.0-rc01...and other]
CC0-1.0
-- [org.reactivestreams:reactive-streams:1.0.3]
Public Domain
-- [org.json:json:20220924]
Proprietary
-- [com.appsflyer:af-android-sdk:6.9.4]
Facebook Platform License
-- [com.facebook.android:facebook-bolts:15.2.0]
```

Why this LICENSES are  UNKNOWN?

**Comment by mikepenz** [comment]
Thank you for the report. This is a bug and will be fixed in the next version. (the matching between spdx license to license data failed)
