### ISSUE TITLE
Show library.uniqueId instead of library.name at TitleVIew

### ISSUE THREAD

**Issue by Kolyall** [mikepenz/AboutLibraries#836]
Add posobility to show library.uniqueId instead of library.name at TitleVIew, because some libs has error at pom files for example:
```
{
      "uniqueId": "com.github.davidmoten:rxjava2-extras",
      "funding": [],
      "developers": [
        {
          "name": "Dave Moten"
        }
      ],
      "artifactVersion": "0.1.38",
      "description": "RxJava 2 utilities",
      "scm": {
        "connection": "scm:git:https://github.com/davidmoten/rxjava2-extras.git",
        "url": "scm:git:https://github.com:davidmoten/rxjava2-extras.git",
        "developerConnection": "scm:git:https://github.com/davidmoten/rxjava2-extras.git"
      },
      "name": "${project.artifactId}",
      "website": "http://github.com/davidmoten/rxjava2-extras",
      "licenses": [
        "Apache-2.0"
      ]
    },
```
and then they are displayed like this:
![Screenshot_20230125_120129_emulator-5554](https://user-images.githubusercontent.com/3495165/214521937-f52b8c24-92cf-4e1c-8576-a85a9c567f16.png)

**Comment by mikepenz** [comment]
While not related to the feature request. 

There are different APIs which help you to resolve such data. 

For example is it possible to define a `duplicationMode`: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt#L130-L147 
(E.g. merge duplicates)

Beyond this, you can provide config files to "patch" libraries which may have inconsistent pom information: https://github.com/mikepenz/AboutLibraries/tree/develop/config/libraries (https://github.com/mikepenz/AboutLibraries#gradle-plugin-configuration)
