### ISSUE TITLE
getActionBar() - java.lang.NullPointerException

### ISSUE THREAD

**Issue by Gordey** [mikepenz/AboutLibraries#84]
After dependecy librarie and start SettingsActivity activity with extends PreferenceActivity, have error NullPointerException.
Code where error:
```java
private void setupActionBar() {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
			getActionBar().setDisplayHomeAsUpEnabled(true);
		}
	}
```

**Comment by mikepenz** [comment]
@Gordey this is not AboutLibraries specific. I also assume that you should use getSupportActionBar() Not sure which PreferenceActivity you use. (I think there's also an support version)
