### ISSUE TITLE
Android Compose: Item spacing / Arrangement 

### ISSUE THREAD

**Issue by saad129** [mikepenz/AboutLibraries#841]
## About this issue
Item spacing / arrangement in compose 
- Briefly describe the issue
There is a usecase, where I changed the color of background in compose android but without the item spacing it looks so odd. I attached the sample screenshot.
- How can the issue be reproduced / sample code
I actually added the item arrangement in library. Also update the sample application for the compose UI but i couldn't find the contributing guideline. It in my local repository right now.

## Details
- [ :heavy_check_mark: ] Used library version
- 10.5.2
- [ ] Used support library version
- [ :heavy_check_mark: ] Used gradle build tools version
- 33.0.0
- [:heavy_check_mark:  ] Used tooling / Android Studio version
- Android Studio Electric Eel | 2022.1.1 Canary 10
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [:heavy_check_mark:  ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [:heavy_check_mark:  ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ :heavy_check_mark: ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [:heavy_check_mark:  ] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

![Screenshot from 2023-02-06 12-49-43](https://user-images.githubusercontent.com/33510121/216966549-700a696f-d9aa-45ab-bdd6-c94b548f8d64.png)

**Comment by mikepenz** [comment]
Good day. 

The screenshot is super low resolution, and I am not certain what I should see? Things look like they were set-up to be?

**Comment by saad129** [comment]
@mikepenz Thanks
Yes
But there is one thing missing that i feel the need  that is item spacing.
What i'm saying the ability to add spacing between items.
Something like this.


![Screenshot from 2023-02-06 13-23-46](https://user-images.githubusercontent.com/33510121/216970694-f8796859-f4c9-4744-ba17-b37e7251012a.png)
