### ISSUE TITLE
How to use the exclusionPatterns extension

### ISSUE THREAD

**Issue by jtothe4n** [mikepenz/AboutLibraries#848]
## About this issue

Good day,

I'm trying to use the exclusion pattern. Found some old documentation and issues that still used a string array. The current version wants a List of type Pattern though. When I use it like below I get "unresolved reference **util**" but somehow not when specifying the List type

List<java.util.regex.Pattern>

but only here: java.**util**.regex.Pattern.compile("androidx.*")

```
aboutLibraries {
        exclusionPatterns =   List<java.util.regex.Pattern>(java.util.regex.Pattern.compile("androidx.*"), 
                                             java.util.regex.Pattern.compile("com.google.android.*"))
    }

```

## Details
- [ 10.6.0] Used library version
- [ ] Used support library version
- [x] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Good day. 

The exclusion feature is a bit more hidden, given that normally I'd advice against excluding libraries to be displayed. But I understand that there are usecases where this is needed. 

Within a `*.gradle` file you can use the following to define the regex:

```
exclusionPatterns = [~"androidx.*", ~"com.google.android.*", ~"org.jetbrains.*"]
```

Within a `gradle.kts` file the following should work:
```
exclusionPatterns = listOf(
        Pattern.compile("androidx.*")
    )
```

**Comment by jtothe4n** [comment]
Thanks @mikepenz I tried that before as well in my gradle.kts. It can't resolve **Pattern** then and suggests me to resolve it to java.util.regex.Pattern..then I get the error though that java.**util** can't be resolved.
I'll just follow your advice and keep all libraries displayed. Dankschön!

**Comment by mikepenz** [comment]
@jtothe4n is it possibly a different gradle file which gets included? I think there's something strange about gradle whereas in external gradle files, imports may not resolve (but I think there's not much I can do about it)

You are welcome
