### ISSUE TITLE
UnsupportedClassVersionError / publishing for JDK 11 is broken since 10.6.0

### ISSUE THREAD

**Issue by twwd** [mikepenz/AboutLibraries#849]
## About this issue

- We got the following error when updating to 10.6.0
```
java.lang.UnsupportedClassVersionError: com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0

> com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
- We use the CirrusCI Android docker image in our build pipeline which uses [JDK 11](https://github.com/cirruslabs/docker-images-android/blob/master/sdk/tools/Dockerfile#L19)
- The latest AboutLibraries version is published with bytecode only for JDK >= 15
- I don't know why since the [compatibility options](https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries/build.gradle#L38-L39) are set to JDK 11 (bytecode version 55.0)

## Details

- [x] Used library version: 10.6.0
- [ ] Used support library version: irrelevant
- [ ] Used gradle build tools version: irrelevant
- [ ] Used tooling / Android Studio version: irrelevant
- [ ] Other used libraries, potential conflicting libraries: irrelevant

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by twwd** [comment]
Wow, that was quick. Thanks @mikepenz

**Comment by mikepenz** [comment]
@twwd automation still needs to run :) but the plugin should be available in ~ 10 mins. the library (which is equal to before) would probably take ~ 1 hour (depending on sonatype syncing speed today)

Please let me know afterwards if that worked.

**Comment by mikepenz** [comment]
Ok the plugin update is up 10.6.1

the libraries failed: https://github.com/mikepenz/AboutLibraries/actions/runs/4230331330/jobs/7347535444 thanks to the Windows runner not having java 11 🙃 - will need to look into this later, though

**Comment by twwd** [comment]
I've updated the plugin and it works again 🎉 Thanks!

I hope that you the the Windows pipeline working again 🤞🏻

**Comment by mikepenz** [comment]
Yes. Only required to update the automated workflows to have Java 11 installed instead of 15 :D 

Thanks again for the report

**Comment by mueller-ma** [comment]
I cannot use version `10.6.1` since gradle doesn't find it: https://github.com/openhab/openhab-android/actions/runs/4251147239/jobs/7393126668

**Comment by mikepenz** [comment]
@mueller-ma please retry. Things should be on maven central now.
