### ISSUE TITLE
LibrariesContainer not found

### ISSUE THREAD

**Issue by tassilo-posegga** [mikepenz/AboutLibraries#852]
## About this issue

Trying to upgrade to 10.6.1

root `build.gradle`

```
id("com.mikepenz.aboutlibraries.plugin") version(libs.versions.aboutlibraries)
```

app `build.gradle`

```
implementation(libs.aboutlibraries.core)
implementation(libs.aboutlibraries.compose)
```

`versions.toml`

```
aboutlibraries = "10.6.1"
aboutlibraries_core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries_compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
```

When adding the import statement manually it cannot resolve starting from `ui` package
<img width="528" alt="image" src="https://user-images.githubusercontent.com/54797297/220906488-7c1f3609-4a0b-4217-bb2c-8ed829648533.png">

## Details
Used library version: 10.6.1
Used gradle build tools version: 32.0.0
Used tooling / Android Studio version: Android Studio Electric Eel | 2022.1.1, Build #AI-221.6008.13.2211.9477386
Other used libraries, potential conflicting libraries: AGP 7.3.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
That's super strange. 

The class is here: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-compose/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/Libraries.kt#L39

The only idea I have right now may be some change in the way the multiplatform library is published 🤔 

E.g. Gradle 8 required some changes to the upload part.

**Comment by mikepenz** [comment]
Oh looks my initial guess was wrong. 

Turns out 10.6.1 was not fully released on `sonatype` (the repositories where closed but not released) 

As such they are missing here:
https://repo1.maven.org/maven2/com/mikepenz/aboutlibraries-compose-android/

While you want to use the plugin 10.6.1 the libraries itself are equal to 10.6.0 so you can use these

**Comment by mikepenz** [comment]
V10.6.1 should now be correctly on maven central. Please let me know if it fixed your problem.

**Comment by tassilo-posegga** [comment]
Amazing, thanks.

While I close this issue I have another offtopic question I do not want to raise an issue for:

It looks like aboutlibraries picks all depenencies of a project. Including dependencies of dependencies. Is it possible to limit it to only first level dependencies?

**Comment by mikepenz** [comment]
@tassilo-posegga there's currently no way of limiting it to direct dependencies. 

Here's the code how this plugin collects the dependencies: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt#L66-L75
