### ISSUE TITLE
Location of CSV export

### ISSUE THREAD

**Issue by tassilo-posegga** [mikepenz/AboutLibraries#853]
## About this issue

Having troubles findind the CSV exported.
Looked into root `build` and `app/build` folder after running app:exportLibraries
Also I couldn"t find any information in the documentation. Can we update the docs?

## Details
Used library version: 8.9.4

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The `exportLibraries` task will only export it to the `CLI` as it is noted here: 
https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt#L47

IF you want to have `csv` files generated on disks you may be interested in the `exportComplianceLibraries{BuildVariant}` (which is only available for Android variants)

https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt#L86C2-L89

**Comment by tassilo-posegga** [comment]
> The `exportLibraries` task will only export it to the `CLI` as it is noted here: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt#L47
> 
> IF you want to have `csv` files generated on disks you may be interested in the `exportComplianceLibraries{BuildVariant}` (which is only available for Android variants)
> 
> https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt#L86C2-L89

Thanks for for the quick reply.
https://github.com/mikepenz/AboutLibraries/pull/854 proposed to add the CLI info to the readme. 

I'll dig deeper into the compliance task. I didn't see any file summarizing the dependencies, but only the `dependencies` folder with all listed deps.

**Comment by mikepenz** [comment]
Thank you for the PR, really appreciated. 


You can see here: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt what is being written to `csv` and `txt` file.

**Comment by tassilo-posegga** [comment]
Alright, so default `dependencies` folder in root should contain `export.csv` and `export.txt` correct? It looks like they are not there in my case

**Comment by mikepenz** [comment]
If no export path was defined then it will write those files into the `root` of your project: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt#LL17C9-L17C19

**Comment by tassilo-posegga** [comment]
> If no export path was defined then it will write those files into the `root` of your project: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt#LL17C9-L17C19

Btw looking at the documentation again i couldn't see any property `exportPath` mentioned in the `aboutLibraries {` configuration block. Is it just missing in the docs?

**Comment by mikepenz** [comment]
The `exportPath` is not part of the `aboutLibraries` block but instead provided to the CLI: https://github.com/mikepenz/AboutLibraries#enterprise

```
./gradlew app:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/res/raw/ 
```
