### ISSUE TITLE
Sort additional licenses under configPath

### ISSUE THREAD

**Issue by rocka** [mikepenz/AboutLibraries#856]
## About this issue

This issue counts for reproducible builds too (see #784 for more explanation). For what I'm working on (https://github.com/fcitx5-android/fcitx5-android to be exact), we have several native library dependencies so we use `configPath` property and put their licenses in [`app/licenses/libraries`](https://github.com/fcitx5-android/fcitx5-android/blob/92b5ef5f1ee227b9c9e745c95cf5af4abc0635d2/app/licenses/libraries) directory. The problem is, every time we run the build in a new environment, the order of licenses in generated json file varies.

After some investigation, I found that additional licenses are read by [`listFiles()`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()), and there is no guarantee of string order:

https://github.com/mikepenz/AboutLibraries/blob/f84b96d454b430679e7263b8d0ab24778cc07789/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/parser/LicenseReader.kt#L11-L15

In my perspective, simply

```kotlin
licensesDir.listFiles()?.sortedBy { it.name }
```

would fix this issue. It would be nice if we can have this feature to further improve reproducibility, or at least have it as an option.

## Details

- Used library version 10.6.1
- Used support library version
- Used gradle build tools version 7.6
- Used tooling / Android Studio version AGP 7.4.2 / Android Studio 2022.1.1 
- Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
@rocka that's a great suggestion, we probably should do that for the whole list of libraries prior to writing them out to the json.
