### ISSUE TITLE
Failed to resolve: com.mikepenz.aboutlibraries:library:4.7.1

### ISSUE THREAD

**Issue by ppamorim** [mikepenz/AboutLibraries#86]

**Comment by mikepenz** [comment]
@ppamorim you were to fast :D just released it to maven central. please wait 10-45 minutes longer ;)

**Comment by ppamorim** [comment]
You're fast too.
JitPack is faster than me plus you together. :3

**Comment by mikepenz** [comment]
@ppamorim yeah :D 

That's true, but for now i like maven central :P

**Comment by mikepenz** [comment]
@ppamorim just in case :D v2.7.1 is synced to maven central and it can be used now ;)
