### ISSUE TITLE
Unknown license: GNU General Public License, version 2, with the Classpath Exception

### ISSUE THREAD

**Issue by fede87** [mikepenz/AboutLibraries#869]
### Issue

GNU General Public License, version 2, with the Classpath Exception 
seems not to be recognized as a valid license.

Specified license is available [here](https://openjdk.org/legal/gplv2+ce.html)

### AboutLibraries version

```
plugins {
    id "com.mikepenz.aboutlibraries.plugin" version "10.6.2"
}
```

### Steps to reproduce

```
./gradlew exportLibrariesRelease
```

At bottom of the command output are found the following lines:

```
UNKNOWN LICENSES:
GNU General Public License, version 2, with the Classpath Exception
-- [com.android.tools:desugar_jdk_libs:1.1.5]
```

**Comment by mikepenz** [comment]
The name seems to differ rom the known licenses as retrieved from the SPDX identifier: https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt#L173-L178

```
    <license>
      <name>GNU General Public License, version 2, with the Classpath Exception</name>
      <url>https://github.com/google/desugar_jdk_libs/blob/master/LICENSE</url>
      <distribution>repo</distribution>
    </license>
```

https://spdx.org/licenses/

Licenses not available via SPDX can be provided manually: https://github.com/mikepenz/AboutLibraries#licenses

**Comment by mikepenz** [comment]
The license can be provided like it's shown here: https://github.com/mikepenz/AboutLibraries/pull/877/commits/69b5735e944cdf4024d05babf4220cef012b8441

(Similar to how the `Android Software Development Kit License Agreement` one is provided in the demo) 

Long-term we are looking in expanding to SpdxLicense 2.0 which has a new exception handling - https://github.com/mikepenz/AboutLibraries/issues/878
