### ISSUE TITLE
Is there a way to silence logging?

### ISSUE THREAD

**Issue by stkent** [mikepenz/AboutLibraries#872]
## About this issue

When this plugin's `prepareLibraryDefinitions` task is run, we see lots of build output like:

```
> Task :app:prepareLibraryDefinitionsDebug
--> Retrieved POM for: com.atlassian.commonmark:commonmark from com.atlassian.commonmark:commonmark-parent:0.13.0
----> Retrieved POM for: com.atlassian.commonmark:commonmark from com.atlassian.pom:central-pom:5.0.13
------> Retrieved POM for: com.atlassian.commonmark:commonmark from com.atlassian.pom:base-pom:5.0.13
...
...
...
```

We like to minimize such output as it makes identifying newly-introduced warnings easier.

Is there a way to disable this output? (I scanned docs, but didn't see anything; apologies if I missed something!)

## Details

Library version 10.6.2.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Actually this looks like a bug as this uses a `println` statement instead of the `LOGGER.info` tag it's supposed to:
- https://github.com/mikepenz/AboutLibraries/blob/bebaf725623879ab8e2afa36f46fea63c67bdbce/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/PomLoader.kt#L42

Would that solve the need? (E.g. have `INFO` log level for that item)

**Comment by mikepenz** [comment]
(Also to answer the pure question, there is no setting or option to fully turn off logs at this time)

**Comment by stkent** [comment]
Ah, yes, I suspect that using the logger and marking this output as informational would be perfect; I'm pretty sure we only log statements that are warnings or more severe!

**Comment by stkent** [comment]
Thank you for the quick response!
