### ISSUE TITLE
Legacy module not compatible with Gradle 8.0

### ISSUE THREAD

**Issue by fourofspades** [mikepenz/AboutLibraries#881]
## About this issue
Legacy module not compatible with Gradle 8.0

```
Missing class com.mikepenz.aboutlibraries.util.AndroidExtensionsKt (referenced from: androidx.lifecycle.ViewModelProvider$Factory com.mikepenz.aboutlibraries.ui.LibsSupportFragment$viewModel$2.invoke())
```

- Briefly describe the issue
create a java Android app and use the legacy plugin method. and create a release.  R8 strips out things that are needed, runtime app crashes.

## Details
- [10.6.3] Used library version
- [8.0] Used support library version
- [8.0] Used gradle build tools version
- [2022.2.1 Patch 1 Flamingo ] Used tooling / Android Studio version

# Checklist

- [Y ] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [Y - however it's a Kotlin app] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [Y] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [Y] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [Y] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The crash occurs simply by upgrading gradle without any other changes?

**Comment by fourofspades** [comment]
Yes, never had a problem until I upgraded to Gradle 8.0.   All the versions I tried (including the latest 10.6.3) are perfectly happy on Gradle 7.4

**Comment by mikepenz** [comment]
Tested this with the sample app which uses Gradle 8.1.1. And it does not run in any problems. (With `minifyEnabled` enabled) 

Any special r8 rule you use? 


Also make sure your jetpack dependencies are up2date. 

----

Can you please provide a sample app to reproduce this problem?

**Comment by fourofspades** [comment]
Sample java app that has the issue.
(will work in development, but a release build will crash at runtime when the FaB is selected.

[MyApplication.zip](https://github.com/mikepenz/AboutLibraries/files/11522106/MyApplication.zip)

**Comment by mikepenz** [comment]
It looks for whatever reason gradle decides to pull in the `jvm` variant of the `core` module instead of the `android` variant. 

You can overrule this by doing:
```groovy
    implementation("com.mikepenz:aboutlibraries-core-android:10.7.0")
    implementation("com.mikepenz:aboutlibraries:10.7.0") {
        exclude group: 'com.mikepenz', module: 'aboutlibraries-core'
    }
```

**Comment by fourofspades** [comment]
Can confirm this workaround is working.

**Comment by DDihanov** [comment]
FYI I had this issue but after upgrading to 10.8.3 the crash no longer happens:

`implementation("com.mikepenz:aboutlibraries-core:10.8.3")
 implementation("com.mikepenz:aboutlibraries-compose:10.8.3")
`

**Comment by mikepenz** [comment]
Thank you @DDihanov . glad this looks to be resolved with the new release.

**Comment by sucicf1** [comment]
@DDihanov we are talking about legacy UI but you mentioned compose. The workaround from @mikepenz 
implementation("com.mikepenz:aboutlibraries-core-android:10.7.0")
    implementation("com.mikepenz:aboutlibraries:10.7.0") {
        exclude group: 'com.mikepenz', module: 'aboutlibraries-core'
    }
works by me.
