### ISSUE TITLE
Eager creation of prepareLibraryDefinitions and exportLibraryDefinitions

### ISSUE THREAD

**Issue by CharlieTap** [mikepenz/AboutLibraries#887]
## About this issue

- Briefly describe the issue

Both of these tasks are created with project.tasks.create rather than register, potentially it's intentional with prepareLibraryDefinitions as I can see you're using the task returned (though it should still be possible) but exportLibraryDefinitions looks like a quick win.

- How can the issue be reproduced / sample code

Run ./gradlew help --scan on any project using the library and you'll see these tasks are created at config time.

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you very much for raising this ticket
