### ISSUE TITLE
LibsActivity memory leak

### ISSUE THREAD

**Issue by shayousefi** [mikepenz/AboutLibraries#89]
I recently added [LeakCanary](https://github.com/square/leakcanary) to my app and it reports a leak in LibsActivity.

Here's the leak trace:
```Java
* com.mikepenz.aboutlibraries.ui.LibsActivity has leaked:
* GC ROOT static android.os.UserManager.sInstance
* references android.os.UserManager.mContext
* references android.app.ContextImpl.mOuterContext
* leaks com.mikepenz.aboutlibraries.ui.LibsActivity instance
```

This is how I'm calling it from my MainActivity:
```Java
new Libs.Builder()
        .withFields(R.string.class.getFields())
        .withLicenseShown(true)
        .withVersionShown(false)
        .withActivityTitle(getString(R.string.title_about))
        .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
        .start(this)
```

I can provide the heap dump as well if it's needed.

**Comment by mikepenz** [comment]
@shayousefi thank you. I will try to take a deeper look and solve it. Thanks for the report

**Comment by mikepenz** [comment]
@shayousefi seems to be an Android specific Memory leak. no variables or anything which could leak the context.

**Comment by mikepenz** [comment]
@shayousefi if someone has a more specific info it would be great. but as far as i can say from the code side it looks fine.

**Comment by shayousefi** [comment]
@mikepenz Indeed it is a platform bug, so it can be ignored:
https://code.google.com/p/android/issues/detail?id=173789

**Comment by mikepenz** [comment]
@shayousefi thank you ;)
