### ISSUE TITLE
10.8.1 gradle plugin failed to generate json

### ISSUE THREAD

**Issue by asuka-mio** [mikepenz/AboutLibraries#902]
See https://github.com/Ehviewer-Overhauled/Ehviewer/pull/1232
Feel like https://github.com/mikepenz/AboutLibraries/pull/899 is causing that.

**Comment by mikepenz** [comment]
Can you please retry with the `10.8.2-b01` plugin version?

**Comment by asuka-mio** [comment]
It works, thanks!
