### ISSUE TITLE
Missing v10.8.2 artifacts on Maven Central

### ISSUE THREAD

**Issue by arkon** [mikepenz/AboutLibraries#905]
## About this issue

Renovate opened an automatic PR to bump the dependency, but the artifacts weren't found from Maven Central: https://github.com/tachiyomiorg/tachiyomi/pull/9689

I can verify that 10.8.2 does not appear in https://repo1.maven.org/maven2/com/mikepenz/aboutlibraries-compose/

## Details
- Used library version: 10.8.2

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
  - Similar issue in the past: https://github.com/mikepenz/AboutLibraries/issues/809
- [ ] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [ ] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you. The release of the staged artifacts on nexus is sadly a manual step, had no time yesterday to complete this. 

Just clicked "release", will take around 30-60 minutes to be synced to maven central.
