### ISSUE TITLE
Apache-2.0 License in generated JSON file may have invalid "url"

### ISSUE THREAD

**Issue by rocka** [mikepenz/AboutLibraries#907]
## About this issue

In the generated JSON file, `"Apache-2.0"` license may have an invalid `"url"` field, which value is `"apache_2_0"`, rather than `"https://spdx.org/licenses/Apache-2.0.html"` or `"https://spdx.org/licenses/Apache-2.0.txt"`.

This affects the sample application as well, if you download **AboutLibraries-v10.8.2-c100820-release.apk** in https://github.com/mikepenz/AboutLibraries/releases/tag/v10.8.2 , extract `res/iz.json` file, jump to line 2338, you can see the "url":

![image](https://github.com/mikepenz/AboutLibraries/assets/13914967/918e8c9a-de1f-4b82-987e-09264d82f40f)

We are using the core module only, and consume the JSON file by

```kotlin
Libs.Builder()
    .withJson(jsonString)
    .build()
```

then open `license.url` in browser, such url could cause an exception and crash the App.

## Details
- Used library version: v10.8.2
- Used support library version: androidx.appcompat:appcompat:1.6.1
- Used gradle build tools version: Gradle 8.1 / AGP 8.0.2
- Used tooling / Android Studio version: Android Studio 2022.1 Patch 2
- Other used libraries, potential conflicting libraries: N/A

**Comment by mikepenz** [comment]
Thank you very much for the report. 

There will be a fixed plugin version released soon.
