### ISSUE TITLE
Duplicate "AboutLibraries Library" listed

### ISSUE THREAD

**Issue by RyeGordo** [mikepenz/AboutLibraries#949]
## Duplicate "AboutLibraries Library" 

The AboutLibraries lib is listed twice.

Implemented via Compose
```
LibrariesContainer(Modifier.fillMaxSize())
```
added `com.mikepenz:aboutlibraries-compose-m3`
added `com.mikepenz.aboutlibraries.plugin`

## Details
- [x] Used library version 10.10.0
- [ ] Used support library version
- [x] Used gradle build tools version 34
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by RyeGordo** [comment]
Thanks for your quick response.

To clarify, I'm not using the core module, only the compose-m3.

**Comment by mikepenz** [comment]
Which depends on the `core` module: https://github.com/mikepenz/AboutLibraries/blob/develop/aboutlibraries-compose-m3/build.gradle.kts#L111

**Comment by RyeGordo** [comment]
Thanks for the clarification.

And allow me to take this opportunity to commend you on a wonderful
library.  The UI is very nice. Well done.

**Comment by mikepenz** [comment]
Thank you very much!

The next release will now also have different names for the individual modules for more clarity.
