### ISSUE TITLE
License dialog text is not shown correctly

### ISSUE THREAD

**Issue by LethalMaus** [mikepenz/AboutLibraries#953]
## About this issue

The dialog text is cut off for me. I am utilizing the legacy UI fragment on Android.

```
        val fragment = LibsBuilder()
            .withVersionShown(true)
            .withLicenseShown(true)
            .withLicenseDialog(true)
            .supportFragment()

        supportFragmentManager.beginTransaction().apply {
            replace(R.id.fragment_container, fragment)
        }.commit()
```

The provided screenshots show the start of the text (cannot scroll upwards) and that scrolling downwards is possible, but no text is shown.

![Screenshot_20240209_143237](https://github.com/mikepenz/AboutLibraries/assets/29340043/acb79487-9e61-479f-b7a3-33950a7fad62)
![Screenshot_20240209_143248](https://github.com/mikepenz/AboutLibraries/assets/29340043/ee2c4ad8-9d21-44ea-adf5-b4c2e4a6e297)

## Details
- [x] Used library version - 10.10.0
- [ ] Used support library version
- [ ] Used gradle build tools version - 8.3.0-rc01
- [x] Used tooling / Android Studio version - Android Studio Iguana | 2023.2.1 RC 1
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@LethalMaus thank you for the report. 

Can you reproduce this in the sample app? I just tried to see if the same happens in the FragmentActivity, and it doesn't appear to be the case. 

I also notice the dialog has a different corner radius than the sample 🤔 Could it be a m2 vs m3 issue perhaps?

**Comment by LethalMaus** [comment]
No worries, thanks for the great library. I haven't had the time to build a mini sample app. It could be that it's M2 as we have not yet migrated.

**Comment by mikepenz** [comment]
Appreciated @LethalMaus 

You can use the sample app in this repo perhaps: https://github.com/mikepenz/AboutLibraries/tree/develop/app

Having it reproduced in this context would really help!

**Comment by LethalMaus** [comment]
Alright, as soon as I get the chance I'll do so. The app is not compiling straight off the bat on my mac, will try it on my Windows PC later on this week and let you know.

**Comment by mikepenz** [comment]
I am building this project on a Mac, any details on what is not compiling for you?

**Comment by LethalMaus** [comment]
```
A problem occurred configuring root project 'AboutLibraries'.
> Could not determine the dependencies of task ':plugin-build:plugin:compileKotlin'.
   > No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.
```
I didnt spend long looking into it. I presume its because I'm on Java 17

**Comment by mikepenz** [comment]
Ah yes. It's searching for a java 11 on your system. And can't find any

**Comment by LethalMaus** [comment]
Found the issue

**Comment by mikepenz** [comment]
Thank you for reporting back! greatly appreciated 👍
