### ISSUE TITLE
Copyright text isn't embedded to aboutlibraries.json starting from 11.1.1

### ISSUE THREAD

**Issue by DennisBauer** [mikepenz/AboutLibraries#970]
## About this issue

- With the update from 11.1.0 to 11.1.1 the plugin doesn't add the copyright text of spdx ID dependencies to the `aboutlibraries.json` generated.
- That makes the Compose Material 3 UI open the website instead of the copyright text embedded with the app as in the previous version.

## Details
- Used library version: 11.1.1
- [ ] Used support library version
- Used gradle build tools version: 8.3.1
- Used tooling / Android Studio version: Android Studio Iguana | 2023.2.1 Patch 1
- [ ] Other used libraries, potential conflicting libraries

Having the following plugin configuration
```
aboutLibraries {
    offlineMode = false
    includePlatform = true
    prettyPrint = true
    duplicationMode = com.mikepenz.aboutlibraries.plugin.DuplicateMode.LINK
    allowedLicenses = arrayOf(
        "ASDKL",
        "Apache-2.0",
        "BSD-2-Clause",
        "BSD-3-Clause",
        "MIT",
    )
    strictMode = StrictMode.FAIL
}
```

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you for the report. Lowering the version directly solves it again for you?

Looked through the diff, there doesn't appear something that would describe such behavior.

**Comment by mikepenz** [comment]
could you please send the `aboutlibraries.json` from `11.1.0` and `11.1.1`, having trouble to reproduce what you note. 
Trying to see if it is actually the export (e.g. the plugin) -> which wasn't modified (beside the gradle update) - or parsing the output maybe. 

Using the sample app still works as intended as far as I can tell.

**Comment by mikepenz** [comment]
Thank you so much for having a look!

<img width="1453" alt="Screenshot 2024-04-03 at 17 17 43" src="https://github.com/mikepenz/AboutLibraries/assets/1476232/1dbd1e3f-f142-46f2-8997-4deb3085382c">

that's extremely interesting. the only change was gradle 🤔 

If you update only the plugin but not the ui, or inverse. would it make a difference? 
Wondering if some gradle cache is causing this

**Comment by mikepenz** [comment]
@DennisBauer thank you so much for the feedback. And no, don't worry. That's awesome feedback. I need to double check what log level errors are for such cases. Because maybe the plugin didn't report visible enough that the request wasn't going through.

**Comment by mikepenz** [comment]
Ok checked. There should have been error/warning logs. But I suppose the log around the GitHub rate limit might have been the major one, not indicating the request couldn't be done at all:
https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/api/GitHubApi.kt#L39

Btw. if you would prefer the plugin to act offline without doing requests, you can do so. And you can supply the license content via the config folder. 

For example as done in the sample: https://github.com/mikepenz/AboutLibraries/tree/develop/config/licenses
