### ISSUE TITLE
Build licenses json only for specific target in multiplatform module

### ISSUE THREAD

**Issue by syt0r** [mikepenz/AboutLibraries#991]
## About this issue

I have a multiplatform module (app written with compose) with android and jvm targets. I want to use gradle command to generate json specifically for desktop target while using automatic task for android. The issue is that it looks like android dependencies appear in the output of this manually launched task and I can't find any configuration except for build variant, but it doesn't allow to specify target platform, right? Is it not possible at the moment to generate json only for one specific platform?

**Comment by Tanwiwat** [comment]
L

**Comment by mikepenz** [comment]
Good day. 

Please have a look at the `exportVariant` property which you can pass to the CLI

```

# Filter exported definition by variant by passing `-PaboutLibraries.exportVariant==<VARIANT>`
./gradlew :app-wasm:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/ -PaboutLibraries.exportVariant=wasmJs
./gradlew :app-wasm:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/ -PaboutLibraries.exportVariant=jvm
```

**Comment by syt0r** [comment]
Thanks for the answer, it works!
