### ISSUE TITLE
Code embedded in the content of BSD license

### ISSUE THREAD

**Issue by przanBrainly** [mikepenz/AboutLibraries#995]
Thank you for the library, I really appreciate its flexibility!

## About this issue

For some libraries, the BSD license is presented with some code (`<<var;name=copyright`) instead of simple placeholders or proper values; please check the attached image. 

Example libraries:
https://mvnrepository.com/artifact/com.facebook.shimmer/shimmer/0.5.0
https://mvnrepository.com/artifact/com.esotericsoftware/kryo

<img width="295" alt="Screenshot 2024-06-06 at 07 48 05" src="https://github.com/mikepenz/AboutLibraries/assets/108520654/9dc782aa-9eb8-4359-b533-e5bd11dcdeb1">

## Details
- [x] Used library version - 11.1.4

**Comment by mikepenz** [comment]
Thank you very much for the report. Will look into this report

**Comment by mikepenz** [comment]
The values you see are the result of the license including these placeholders when retrieving from SPDX, as you can see here: https://spdx.org/licenses/BSD-3-Clause.txt

Which is same as the BSD-3 license text as linked here:
- https://repo1.maven.org/maven2/com/esotericsoftware/kryo-parent/5.6.0/kryo-parent-5.6.0.pom
- https://opensource.org/license/BSD-3-Clause

The plugin won't insert placeholders, as that's challenging to get correct. 

For this case I fear it is working as intended.
