### ISSUE TITLE
Generated Json file contains unreadable library names

### ISSUE THREAD

**Issue by ductavius** [mikepenz/AboutLibraries#998]
## About this issue
I use the `AboutLibrary` for multiplatforms [Android/iOS]. From the generated `aboutlibraries.json`, I have seen that some of the library names are unreadable.

```
            "uniqueId": "com.ibm.icu:icu4j",
            "name": "${proj-title} (${project.artifactId})",
            "website": "https://icu.unicode.org/",
            "licenses": [
                "8e76e04435ff54c8e0e7444ba2faa856"
            ],
            "organization": {
                "url": "https://icu.unicode.org/",
                "name": "Unicode, Inc."
            }
```
and 
```
           "uniqueId": "javax.annotation:javax.annotation-api"
           "scm": {
                "connection": "scm:git:https://github.com/javaee/javax.annotation.git",
                "url": "https://github.com/javaee/javax.annotation",
                "developerConnection": "scm:git:git@github.com:javaee/javax.annotation.git"
            },
            "name": "${extension.name} API",
            "website": "http://jcp.org/en/jsr/detail?id=250",
            "licenses": [
                "9be0c4d7964ad9a68deb2e9706266b8c"
            ],
```
I think it was resolved in the old version [issue](https://github.com/mikepenz/AboutLibraries/issues/564).

## Details
- [x] Used library version 11.1.4

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues/564) 
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
for `com.ibm.icu` it is unfortunately a bug in the `pom.xml` from the library. You can either patch it manually by providing the correct details, or raise it to the authors of the library to fix this in their pom.

https://repo1.maven.org/maven2/com/ibm/icu/icu4j-root/75.1/icu4j-root-75.1.pom

<img width="786" alt="Screenshot 2024-06-26 at 17 25 57" src="https://github.com/mikepenz/AboutLibraries/assets/1476232/1e6cf6e2-4297-4a84-ba4b-e7afac694b29">


Also the same applies to `javax.annotation:javax.annotation-api`

https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.pom

<img width="891" alt="Screenshot 2024-06-26 at 17 27 37" src="https://github.com/mikepenz/AboutLibraries/assets/1476232/29621d1b-76ba-46b6-8f93-44c606113d3a">

**Comment by ductavius** [comment]
Thank you very much for the reply. Then, I would patch it manually for now
